#! /bin/csh -f

# If HOST_NAME isn't defined yet, do it here...
if (! $?HOST_NAME ) then
  if (-e whereami) then
    set HOST_NAME=`./whereami|tail -1`
  else
    set HOST_NAME="UNKNOWN"
  endif

  if ( $HOST_NAME == "*UNKNOWN*" ) then
    set HOST_NAME=default
  endif
  echo "Using HOST_NAME = $HOST_NAME"
endif

# List of default compilers per HOST_NAME
switch ($HOST_NAME)
case "ASIPP":
case "GA":
case "IFERC":
case "IN-DA":
case "IPP":
case "IPP-HGW":
case "IPR":
case "ITER":
case "ITM":
case "KEIO":
case "SWIP":
  echo ifort64
  breaksw
case "CCFE":
case "ENEA":
case "JET":
case "ORNL":
case "PPPL":
  echo pgf90
  breaksw
case "FZJ":
case "LEUVEN":
case "WM":
  echo gfortran
  breaksw
default:
  echo ifort64
endsw
