#! /bin/csh -f
set hostname=`hostname`
set fullhost=`nslookup $hostname |& awk '/Name:/{print $2}' | tr 'A-Z' 'a-z'`
switch ($fullhost)
case "*.iter.org":
  echo ITER
  breaksw
case "*.itm.rzg.mpg.de":
case "*.efda-itm.eu":
  echo ITM
  breaksw
case "*.ipp-garching.mpg.de":
case "*.ipp.mpg.de":
case "*.ipp-hgw.mpg.de":
case "*.rzg.mpg.de":
  echo IPP
  breaksw
case "*.pppl.gov":
  echo PPPL
  breaksw
case "*.gov":
case "*.edu":
  echo USA_UNKNOWN
  breaksw
case "*.de":
case "*.uk":
  echo EU_UNKNOWN
  breaksw
default:
  echo UNKNOWN
endsw
