#! /bin/csh -f
set hostname=`hostname`
set fullhost=`nslookup $hostname |& awk '/Name:/{print $2}' | tr 'A-Z' 'a-z'`
switch ($fullhost)
case "*.iter.org":
  echo ITER
  breaksw
case "*.iferc-csc.org":
  echo IFERC
  breaksw
case "*.itm.rzg.mpg.de":
case "*.efda-itm.eu":
  echo ITM
  breaksw
case "*.ipp-garching.mpg.de":
case "*.ipp.mpg.de":
case "*.rzg.mpg.de":
  echo IPP
  breaksw
case "*.ipp-hgw.mpg.de":
  echo IPP-HGW
  breaksw
case "*.fz-juelich.de":
case "*.ipp.kfa-juelich.de":
  echo FZJ
  breaksw
case "*.ccfe.ac.uk":
  echo CCFE
  breaksw
case "*.jet.uk":
  echo JET
  breaksw
case "*.mech.kuleuven.be":
  echo LEUVEN
  breaksw
case "*.pppl.gov":
  echo PPPL
  breaksw
case "*.fusion.gat.com":
  echo GA
  breaksw
case "*.wm.edu":
  echo WM
  breaksw
case "*.nersc.gov":
  echo NERSC
  breaksw
case "*.ornl.gov":
  echo ORNL
  breaksw
case "*.ipp.cas.cn":
  echo ASIPP
  breaksw
case "*.ipr.res.in":
  echo IPR
  breaksw
case "*.iter-india.org":
  echo IN-DA
  breaksw
case "*.gov":
case "*.edu":
case "*.us":
  echo USA_UNKNOWN
  breaksw
case "*.de":
case "*.uk":
case "*.it":
case "*.fr":
case "*.fi":
case "*.be":
case "*.eu":
  echo EU_UNKNOWN
  breaksw
case "*.cn":
  echo CN_UNKNOWN
  breaksw
case "*.in":
  echo IN_UNKNOWN
  breaksw
case "*.jp":
  echo JP_UNKNOWN
  breaksw
case "*.kr":
  echo KR_UNKNOWN
  breaksw
case "*.ru":
  echi RU_UNKNOWN
  breaksw
default:
  echo UNKNOWN
endsw
