#! /bin/tcsh

#BSUB -e SOLPS.e%J.%I
#BSUB -o SOLPS.o%J.%I
#BSUB -J SOLPS
#BSUB -W 36:00

setenv PATH ${PATH}:/afs/ipp-garching.mpg.de/@sys/bin

if (-e SOLPSTOP) then
  pushd `cat SOLPSTOP`
else
  pushd `echo $PWD | sed 's:/runs/.*::'`
endif
source setup.csh
echo Using SOLPSTOP = $SOLPSTOP
popd

update_solps_run_status "Started on `hostname` at `date`"

time b2run >! run.log 

QSUB.postprocess

update_solps_run_status "Finished on `hostname` at `date`"
