      subroutine uinbndxp
       use b2mod_layer
     , , only: ntrack, nalloys
       use eirmod_extrab25
     , , only: msrfclsx, mgwtiesx
c
c  version : 24.03.99 23:20
c
c======================================================================
c*** Fill in the data for explicitly specified zones
c=======================================================================
#include "uinpcom.inc"
      logical ex
c=======================================================================
      return
c=======================================================================
      end
