C******* -FUNCTION DIST- **********************************************
C----
C---- THIS FUNCTION CALCULATES THE DISTANCE BETWEEN THE POINTS X AND Y
C----

      FUNCTION DIST(X1,X2,Y1,Y2)
      IMPLICIT NONE

C---- INPUT VARIABLES
C---- X1,X2  : X- AND Y- COORDINATE OF POINT X
C---- Y1,Y2  : X- AND Y- COORDINATE OF POINT Y
      DOUBLE PRECISION X1,X2,Y1,Y2

C---- OUTPUT VARIABLES
C---- DIST  : DISTANCE BETWEEN POINT X AND POINT Y
      DOUBLE PRECISION DIST

      DIST = SQRT((Y1-X1)**2 + (Y2-X2)**2)

      END
