/* Generates fallback resource table from a resource file

   Syntax: res2fbr varName <infile.res >outfile.fbr

   varName      Name of char** variable to hold fallback resources
   input.res    Resource file
   output.fbr   Output file

   ----------------------------------------------------------------

   Changes:

     970403 'relcheck_ignore_line' comment used for valid printf()s
     970313 If the NO_FBR envvar is set, generates empty fallback resources

*/

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
  int bSlash=0,c;

  if (argc!=2) {
    fprintf(stderr,"Syntax: res2fbr varName <infile.res >outfile.fbr\n");
    exit(1);
  }

  printf("/* File generated by res2fbr */\n\n"  /* relcheck_ignore_line */
    "#include <stddef.h>\n\nchar* %s[]={\n  \"",argv[1]);

  if (getenv("NO_FBR")!=NULL) {
    fprintf(stderr,"res2fbr: NO_FBR condition, no fallback resources\n");
    printf("\"\"");                     /* relcheck_ignore_line */
  }
  else while ((c=getchar())!=EOF) {
    if (bSlash) switch(c) {
      case '\n':
	printf("\"\n  \"");             /* relcheck_ignore_line */
	bSlash=0;
	break;
      default:
	printf("\\\\%c",c);             /* relcheck_ignore_line */
	bSlash=0;
	break;
    } else switch(c) {
      case '\\':
	bSlash=1;
	break;
      case '\"':
	printf("\\\"");                 /* relcheck_ignore_line */
	break;
      case '\n':
	printf("\\n\",\n  \"");         /* relcheck_ignore_line */
	break;
      default:
	putchar(c);
	break;
    }
  }
  printf("\",\n  NULL\n};\n");          /* relcheck_ignore_line */
  return 0;
}

