#! /bin/csh -f
if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif
if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif
set x=$1
shift
set source=b2mn.exe.dir/b2time.nc
if (! -e $source) set source=b2time.nc
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif

set args="$argv"
set nargs=$#argv

which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1

cp /dev/null ${tmpdir}gnuplot.data.tmp
if ($no_nc2text == 1) then
  ncdump $source -f f -v $x | \
  awk 'BEGIN {ORS="";} /data:/{found1=1;next;} /$x/{if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}} END {print "\n";}' | \
  sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
else
  echo `nc2text -n 9999999 $source $x` >> ${tmpdir}gnuplot.data.tmp
endif
start:
  if ($no_nc2text == 1) then
    ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
    sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
  else
    echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
  endif
  shift
  if ("X$1X" != "XX") goto start

awk.transpose < ${tmpdir}gnuplot.data.tmp | awk 'NR==1{saveNF=NF}NF==saveNF{print $0}' | plot ${lx}x${ly}yplot$nargs $args $x '' $PWD
rm ${tmpdir}gnuplot.data.tmp
