#! /bin/csh -f
if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif
if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif
set x=$1
shift
set source=b2mn.exe.dir/b2time.nc
if (! -e $source) set source=b2time.nc
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif

set args="$argv"
set nargs=$#argv

cp /dev/null ${tmpdir}gnuplot.data.tmp
echo `nc2text -n 9999999 $source $x` >> ${tmpdir}gnuplot.data.tmp
start:
  echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
  shift
  if ("X$1X" != "XX") goto start

awk.transpose < ${tmpdir}gnuplot.data.tmp | awk 'NR==1{saveNF=NF}NF==saveNF{print $0}' | plot ${lx}x${ly}yplot$nargs $args $x '' $PWD
rm ${tmpdir}gnuplot.data.tmp
