#! /bin/csh -f

if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif

if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif

if ( $#argv < 2 ) then
    echo "Error: You must provide at least two arguments (2nd, 3rd, etc. arguments will be plotted vs. the 1st one)."
    exit 1
endif

set x=$1
shift
set source=b2mn.exe.dir/b2time.nc
if (! -s $source) set source=b2time.nc
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif

set args="$argv"
set nargs=$#argv

which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
if (-e b2mn.exe.dir/.netcdf4) then
  ln -sf $source ${tmpdir}b2time.nc.tmp
  set source=${tmpdir}b2time.nc.tmp
  gtfl $source
  set netcdf4=1
else
  set netcdf4=0
endif

cp /dev/null ${tmpdir}gnuplot.data.tmp
if ($no_nc2text == 1) then
  if ("$x" =~ *[0-9]) then
      # Multi-species quantities, called as $x = $name$is (e.g. $x = 'nasepm1')
      echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
      exit 1
  else
      # Time, called as $x = 'timesa', or single species quantities, called as $x = $name (e.g. $x = 'nesepm')
      ncdump $source -f f -v $x | \
      awk 'BEGIN {ORS="";} /data:/{found1=1;next;} /$x/{if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}} END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
  endif
else
  if ("$x" =~ *[0-9]) then 
      # Multi-species quantities, called as $x = $name$is (e.g. $x = 'nasepm1')
      set is = `echo "$x" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
      set name = `echo "$x" | sed -E 's/([0-9]+)$//'`
      @ is_plus_1 = $is + 1
      echo `nc2text -n 9999999 $source "$name(:,$is_plus_1)"` >> ${tmpdir}gnuplot.data.tmp
  else
      # Time, called as $x = 'timesa', or single species quantities, called as $x = $name (e.g. $x = 'nesepm')
      echo `nc2text -n 9999999 $source $x` >> ${tmpdir}gnuplot.data.tmp
  endif
endif

set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-s $solps_fluids) then
  setenv SOLPS_FLUIDS `cat $solps_fluids`
else
  setenv SOLPS_FLUIDS "`get_solps_fluids`"
endif
set species_names = ( $SOLPS_FLUIDS )
set neutral_species_names = ()
foreach name ($species_names)
  set last_char = `echo "$name" | awk '{print substr($0,length($0),1)}'`
  set second_last_char = `echo "$name" | awk '{print substr($0,length($0)-1,1)}'`
  if ("$last_char" == "0" && "$second_last_char" !~ [0-9]) then
    set neutral_species_names = ($neutral_species_names $name)
  endif
end

start:
  if ($no_nc2text == 1) then
    if ("$1" =~ *[0-9]) then
      # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
      echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
      exit 1
    else
      # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
      ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
    endif
  else
    if ("$1" =~ *[0-9]) then
      # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
      set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
      set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
      @ is_plus_1 = $is + 1
      echo `nc2text -n 9999999 $source "$name(:,$is_plus_1)"` >> ${tmpdir}gnuplot.data.tmp
    else
      # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
      echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
    endif
  endif
  shift
  if ("X$1X" != "XX") goto start

# Find species names, in case of multi-species array
set args_plot=""
set field_names = ( $args )
foreach i ($field_names)
  if ("$i" =~ *[0-9]) then
    # Multi-species quantities, called as $i = $name$is (e.g. $i = 'nasepm1')
    set is = `echo "$i" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
    set name = `echo "$i" | sed -E 's/([0-9]+)$//'`
    @ is_plus_1 = $is + 1
    if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
      setenv species_name $neutral_species_names[$is_plus_1]
    else
      setenv species_name $species_names[$is_plus_1]
    endif
    set args_plot="$args_plot $name($species_name)"
  else
    set args_plot="$args_plot $i"
  endif
end

awk.transpose < ${tmpdir}gnuplot.data.tmp | awk 'NR==1{saveNF=NF}NF==saveNF{print $0}' | plot ${lx}x${ly}yplot$nargs $args_plot $x '' $PWD
rm ${tmpdir}gnuplot.data.tmp

if ($netcdf4 == 1) then
  rm $source
endif
