#! /bin/tcsh -f
set NUM=10
if ("X$1X" != "XX") set NUM=$1
@ NUM = 1 - $NUM
echo $NUM
set nreg=`climb_and_look_for NREG`
if (-s $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
set usual=""
if (-s dsl) then
  set usual=`echo ${usual}" fn3dl fe3dl fi3dl fc3dl fl3dl fo3dl ft3dl ne3dl te3dl ti3dl po3dl an3dl tp3dl"`
  if (-s fort.1) then
    set usual=`echo ${usual}" mn3dl"`
  endif
endif
if (-s dsi) then
  set usual=`echo ${usual}" ne3di te3di ti3di po3di an3di dn3di dp3di ke3di ki3di vx3di vy3di vs3di"`
  if (-s fort.1) then
    set usual=`echo ${usual}" mn3di"`
  endif
endif
if (-s dsa) then
  set usual=`echo ${usual}" ne3da te3da ti3da po3da an3da dn3da dp3da ke3da ki3da vx3da vy3da vs3da"`
  if (-s fort.1) then
    set usual=`echo ${usual}" mn3da"`
  endif
endif
if (-s dsr) then
  set usual=`echo ${usual}" ne3dr te3dr ti3dr po3dr an3dr fn3dr fe3dr fi3dr fc3dr fl3dr fo3dr ft3dr tp3dr"`
  if (-s fort.1) then
    set usual=`echo ${usual}" mn3dr"`
  endif
endif
set extra=""
if ($?NREG) then
  if ($NREG == 8 || $NREG == 7) then
    set extra="fn3dtl fe3dtl fi3dtl fc3dtl fl3dtl fo3dtl ft3dtl ne3dtl te3dtl ti3dtl po3dtl an3dtl ne3dtr te3dtr ti3dtr po3dtr an3dtr fn3dtr fe3dtr fi3dtr fc3dtr fl3dtr fo3dtr ft3dtr tp3dtl tp3dtr"
    if (-s fort.1) then
      set extra=`echo ${extra}" mn3dtl mn3dtr"`
    endif
  endif
endif

set source=b2mn.exe.dir/b2time.nc
if (! -s $source) set source=b2time.nc

which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
if (-e b2mn.exe.dir/.netcdf4) then
  ln -sf $source ${tmpdir}b2time.nc.tmp
  set source=${tmpdir}b2time.nc.tmp
  gtfl $source
  set netcdf4=1
else
  set netcdf4=0
endif

if ($no_nc2text == 1) then
  # get array size and set indices
  set ny = `ncdump $source -f f -v fn3dl | sed -n 's/.*ny[ \t]*=[ \t]*\([0-9]\{1,\}\).*/\1/p'`
  set nt = `ncdump $source -f f -v fn3dl | sed -n 'x;$p' | awk -F '[,)]' '{print $2;}'`
#  echo "ny $ny"
#  echo "nt $nt"
  @ jstart = $nt + $NUM
  if ($jstart < 1) then
    set jstart = 1
  endif
  @ jend = $nt
#  echo $jstart $jend
else
  set nt = `nc2text $source "ntstep" | awk '{printf "%d", $1}'`
#  echo "nt $nt"
  @ jstart = $nt + $NUM
  if ($jstart < 0) then
    @ NUM = -$nt + 1
  endif
#  echo $NUM
endif

foreach i ($usual $extra)
  set prefix=`echo $i | cut -c1`
  set pr2fix=`echo $i | cut -c2`
  set suffix=`echo $i | cut -c5-`
  set SUFFIX=`echo $suffix | tr 'a-z' 'A-Z'`
  set SUFFIXP=`echo $suffix | tr 'a-z' 'A-Z'`P
  set dsfile=b2mn.exe.dir/ds$suffix
  if (! -s $dsfile) set dsfile=ds$suffix
  set dsFILE=b2mn.exe.dir/ds$SUFFIX
  if (! -s $dsFILE) set dsFILE=ds$SUFFIX
  set dsFILEP=b2mn.exe.dir/ds$SUFFIXP
  if (! -s $dsFILEP) set dsFILEP=ds$SUFFIXP
#  echo $i $prefix $pr2fix $suffix $SUFFIX $SUFFIXP $dsfile $dsFILE $dsFILEP
  if ($no_nc2text == 1) then
    if ($prefix == "f" && -s $dsFILE) then
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \    
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILE | awk '{print $1,$2/$3}' >! $i.last10
    else if ($prefix == "t" && $pr2fix != "p") then
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' | paste $dsfile - >! $i.last10
    else if ($prefix == "t" && $pr2fix == "p") then
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \    
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! $i.last10
    else
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \    
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! $i.last10
    endif
    if ($prefix == "f" && -s $dsFILEP) then
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \    
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILEP | awk '{print $1,$2/$3}' >! $i'P'.last10
    endif
  else
    if ($prefix == "f" && -s $dsFILE) then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILE | awk '{print $1,$2/$3}' >! $i.last10
    else if ($prefix == "t" && $pr2fix != "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' | paste $dsfile - >! $i.last10
    else if ($prefix == "t" && $pr2fix == "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! $i.last10
    else
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! $i.last10
    endif
    if ($prefix == "f" && -s $dsFILEP) then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILEP | awk '{print $1,$2/$3}' >! $i'P'.last10
    endif
  endif
end

if ($netcdf4 == 1) then
  rm $source
endif
