#! /bin/tcsh -f
set NUM=10
if ("X$1X" != "XX") set NUM=$1
set END=-0
if ("X$2X" != "XX") set END=$2
@ NUM = 1 + $END - $NUM
echo $NUM $END
set nreg=`climb_and_look_for NREG`
if (-s $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
set usual="fn3dl fe3dl fi3dl fc3dl fl3dl fo3dl ft3dl ne3dl te3dl ti3dl po3dl an3dl mn3dl ne3di te3di ti3di po3di an3di mn3di ne3da te3da ti3da po3da an3da mn3da ne3dr te3dr ti3dr po3dr an3dr mn3dr fn3dr fe3dr fi3dr fc3dr fl3dr fo3dr ft3dr dn3di dn3da dp3di dp3da ke3di ke3da ki3di ki3da vx3di vx3da vy3di vy3da vs3di vs3da tp3dl tp3dr"
set extra=""
if ($?NREG) then
  if ($NREG == 8) then
    set extra="fn3dtl fe3dtl fi3dtl fc3dtl fl3dtl fo3dtl ft3dtl ne3dtl te3dtl ti3dtl po3dtl an3dtl mn3dtl ne3dtr te3dtr ti3dtr po3dtr an3dtr mn3dtr fn3dtr fe3dtr fi3dtr fc3dtr fl3dtr fo3dtr ft3dtr tp3dtl tp3dtr"
  endif
  if ($NREG == 7) then
    set extra="fn3dtl fe3dtl fi3dtl fc3dtl fl3dtl fo3dtl ft3dtl ne3dtl te3dtl ti3dtl po3dtl an3dtl mn3dtl ne3dtr te3dtr ti3dtr po3dtr an3dtr mn3dtr fn3dtr fe3dtr fi3dtr fc3dtr fl3dtr fo3dtr ft3dtr tp3dtl tp3dtr"
  endif
endif

if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif
set source=b2mn.exe.dir/b2time.nc
if (! -s $source) set source=b2time.nc

which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
if (-e b2mn.exe.dir/.netcdf4) then
  ln -sf $source ${tmpdir}b2time.nc.tmp
  set source=${tmpdir}b2time.nc.tmp
  gtfl $source
  set netcdf4=1
else
  set netcdf4=0
endif

if ($no_nc2text == 1) then
  # get array size and set indices
  set ny = `ncdump $source -f f -v fn3dl | sed -n 's/.*ny[ \t]*=[ \t]*\([0-9]\{1,\}\).*/\1/p'`
  set nt = `ncdump $source -f f -v fn3dl | sed -n 'x;$p' | awk -F '[,)]' '{print $2;}'`
#  echo "ny $ny"
#  echo "nt $nt"
  @ jstart = $nt + $NUM
  if ($jstart < 1) then
    set jstart = 1
  endif
  @ jend = $nt + $END
  if ($jend > $nt) then
    set jend = $nt
  endif
#  echo $jstart $jend
else
  set nt = `nc2text $source "ntstep" | awk '{printf "%d", $1}'`
#  echo "nt $nt"
  @ jstart = $nt + $NUM
  if ($jstart < 0) then
    @ NUM = -$nt + 1
  endif
  @ jend = $nt + $END
  if ($jend > $nt) then
   set END = -0
  endif
#  echo $NUM $END
endif

foreach i ($usual $extra)
  set prefix=`echo $i | cut -c1`
  set pr2fix=`echo $i | cut -c2`
  set suffix=`echo $i | cut -c5-`
  set SUFFIX=`echo $suffix | tr 'a-z' 'A-Z'`
  set SUFFIXP=`echo $suffix | tr 'a-z' 'A-Z'`P
  set dsfile=b2mn.exe.dir/ds$suffix
  if (! -s $dsfile) set dsfile=ds$suffix
  set dsFILE=b2mn.exe.dir/ds$SUFFIX
  if (! -s $dsFILE) set dsFILE=ds$SUFFIX
  set dsFILEP=b2mn.exe.dir/ds$SUFFIXP
  if (! -s $dsFILEP) set dsFILEP=ds$SUFFIXP
#  echo $i $prefix $pr2fix $suffix $SUFFIX $SUFFIXP $dsfile $dsFILE $dsFILEP
  if ($no_nc2text == 1) then
    if ($prefix == "f" && -s $dsFILE) then
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILE | awk '{print $1,$2/$3}' >! ${tmpdir}$i.last10
    else if ($prefix == "t" && $pr2fix != "p") then
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' | paste $dsfile - >! ${tmpdir}$i.last10
    else if ($prefix == "t" && $pr2fix == "p") then
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! ${tmpdir}$i.last10
    else
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! ${tmpdir}$i.last10
    endif
    if ($prefix == "f" && -s $dsFILEP) then
      ncdump $source -f f -v "$i" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      awk -v nyy="$ny" -v j1=$jstart -v j2=$jend 'BEGIN{ORS=" "} {for (j=j1;j<=j2;j++) {for (i=1;i<=nyy;i++) {k=i+(j-1)*nyy; print $k};print "\n";}}' | head -n -1 | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILEP | awk '{print $1,$2/$3}' >! ${tmpdir}$i'P'.last10
    endif
  else
    if ($prefix == "f" && -s $dsFILE) then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILE | awk '{print $1,$2/$3}' >! ${tmpdir}$i.last10
    else if ($prefix == "t" && $pr2fix != "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' | paste $dsfile - >! ${tmpdir}$i.last10
    else if ($prefix == "t" && $pr2fix == "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! ${tmpdir}$i.last10
    else
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - >! ${tmpdir}$i.last10
    endif
    if ($prefix == "f" && -s $dsFILEP) then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste $dsfile - $dsFILEP | awk '{print $1,$2/$3}' >! ${tmpdir}$i'P'.last10
    endif
  endif
end

if ($netcdf4 == 1) then
  rm $source
endif
