#! /bin/tcsh -f
set NUM=10
if ("X$1X" != "XX") set NUM=$1
@ NUM = 1 - $NUM
echo $NUM
set nreg=`climb_and_look_for NREG`
if (-e $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
endif
set usual="fn3dl fe3dl fi3dl fc3dl fl3dl fo3dl ft3dl ne3dl te3dl ti3dl po3dl an3dl mn3dl ne3di te3di ti3di po3di an3di mn3di ne3da te3da ti3da po3da an3da mn3da ne3dr te3dr ti3dr po3dr an3dr mn3dr fn3dr fe3dr fi3dr fc3dr fl3dr fo3dr ft3dr dn3di dn3da dp3di dp3da ke3di ke3da ki3di ki3da vx3di vx3da vy3di vy3da vs3di vs3da tp3dl tp3dr"
set extra=""
if ($?NREG) then
  if ($NREG == 8) then
    set extra="fn3dtl fe3dtl fi3dtl fc3dtl fl3dtl fo3dtl ft3dtl ne3dtl te3dtl ti3dtl po3dtl an3dtl mn3dtl ne3dtr te3dtr ti3dtr po3dtr an3dtr mn3dtr fn3dtr fe3dtr fi3dtr fc3dtr fl3dtr fo3dtr ft3dtr tp3dtl tp3dtr"
  endif
endif
which nc2text && set no_nc2text=0 || set no_nc2text=1
foreach i ($usual $extra)
  set source=b2mn.exe.dir/b2time.nc
  if (! -e $source) set source=b2time.nc
  set prefix=`echo $i | cut -c1`
  set pr2fix=`echo $i | cut -c2`
  set suffix=`echo $i | cut -c5-`
  set SUFFIX=`echo $suffix | tr 'a-z' 'A-Z'`
  set SUFFIXP=`echo $suffix | tr 'a-z' 'A-Z'`P
#  echo $i $prefix $pr2fix $suffix $SUFFIX $SUFFIXP
  if ($no_nc2text == 1) then
    if ($prefix == "f" && -e ds$SUFFIX) then
      ncdump $source -f f -v "$i(:,${NUM}:-0)" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $i; else {print $3;found2=1;}}}  END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - ds$SUFFIX | awk '{print $1,$2/$3}' >! $i.last10
    else if ($prefix == "t" && $pr2fix != "p") then
      ncdump $source -f f -v "$i(:,${NUM}:-0)" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $i; else {print $3;found2=1;}}}  END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176565e-19}' | paste ds$suffix - >! $i.last10
    else if ($prefix == "t" && $pr2fix == "p") then
      ncdump $source -f f -v "$i(:,${NUM}:-0)" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $i; else {print $3;found2=1;}}}  END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - >! $i.last10
    else
      ncdump $source -f f -v "$i(:,${NUM}:-0)" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $i; else {print $3;found2=1;}}}  END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - >! $i.last10
    endif
    if ($prefix == "f" && -e ds$SUFFIXP) then
      ncdump $source -f f -v "$i(:,${NUM}:-0)" | awk -v string="$i" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $i; else {print $3;found2=1;}}}  END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' | \
      ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - ds$SUFFIXP | awk '{print $1,$2/$3}' >! $i'P'.last10
    endif
  else
    if ($prefix == "f" && -e ds$SUFFIX) then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - ds$SUFFIX | awk '{print $1,$2/$3}' >! $i.last10
    else if ($prefix == "t" && $pr2fix != "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176565e-19}' | paste ds$suffix - >! $i.last10
    else if ($prefix == "t" && $pr2fix == "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - >! $i.last10
    else
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - >! $i.last10
    endif
    if ($prefix == "f" && -e ds$SUFFIXP) then
      nc2text -n 9999999 $source "$i(:,${NUM}:-0)" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ds$suffix - ds$SUFFIXP | awk '{print $1,$2/$3}' >! $i'P'.last10
    endif
  endif
end
