#! /bin/tcsh -f

if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif
setenv GNUPLOT_BATCH yes
setenv GNUPLOT_POSTSCRIPT_OPTIONS 'color solid noenhanced'
setenv PRINT_PLOT b2time2d.ps
rm -f ${tmpdir}GNUPLOT_COUNT ${tmpdir}gnuplot.cmd
echo 0 > ${tmpdir}GNUPLOT_COUNT

set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif

2dt nesepm
2dt tesepm tisepm
2dt nesepi nemxip nesepa nemxap
2dt tesepi temxip tesepa temxap
2dt tisepi timxip tisepa timxap
2dt fnixip fnixap
2dt feexip feexap
2dt feixip feixap
switch ($NREG)
  case "8":
    2dt fniyip fniyap
    2dt feeyip feeyap
    2dt feiyip feiyap
  breaksw
  case "7":
    2dt fniyip fniyap
    2dt feeyip feeyap
    2dt feiyip feiyap
  breaksw
  case "5":
    2dt fniyip fniyap
    2dt feeyip feeyap
    2dt feiyip feiyap
  breaksw
  case "4":
    2dt fniyip fniyap
    2dt feeyip feeyap
    2dt feiyip feiyap
  breaksw
  case "2":
    2dt fniyip
    2dt feeyip
    2dt feiyip
  breaksw   
  case "1":
    2dt fniyip
    2dt feeyip
    2dt feiyip
  breaksw   
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
2dt pwmxip pwmxap
2dt tmne
2dt tmte tmti

gnuplot ${tmpdir}gnuplot.cmd
rm ${tmpdir}GNUPLOT_COUNT ${tmpdir}gnuplot.*data ${tmpdir}gnuplot.cmd
