#! /bin/csh -f
set source=b2mn.exe.dir/b2time.nc
if (! -s $source) set source=b2time.nc
if ("X$1" == "X-s") then
  set source=$2
  shift
  shift
endif

set args=""
set nargs=0

if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif

which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1

/bin/cp /dev/null ${tmpdir}gnuplot.data.tmp
start:
  set count=`echo "$1" | sed -e 's:[^()]::g' | wc -c`
  if ($count == "1") then
    if ($no_nc2text == 1) then
      set check=`ncdump $source -v $1 | sed -n 'x;$p' | sed 's/;//g'`
    else
      set check=`nc2text -s -n 999999 $source "$1(1)"`
    endif
  else
    set check="1"
  endif
  if ($#check == 1) then
    if ($no_nc2text == 1) then
      ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
      sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
    else
      echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
    endif
    set args="$args $1"
  else
    if ($no_nc2text == 1) then
      ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
      awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}' | sed 's/;//g' | \
      awk.transpose >> ${tmpdir}gnuplot.data.tmp
    else
      nc2text -n 9999999 $source $1 | awk.transpose >> ${tmpdir}gnuplot.data.tmp
    endif
    set args="$args `count -p $1. 1 $#check`"
  endif
  shift
  if ("X$1X" != "XX") goto start

echo "# $args"
awk.transpose < ${tmpdir}gnuplot.data.tmp
