#! /bin/csh -f

set source=b2mn.exe.dir/b2time.nc
if (! -s $source) set source=b2time.nc
if ("X$1" == "X-s") then
  set source=$2
  shift
  shift
endif

set args=""
set nargs=0

if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif

which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
if (-e b2mn.exe.dir/.netcdf4) then
  ln -sf $source ${tmpdir}b2time.nc.tmp
  set source=${tmpdir}b2time.nc.tmp
  gtfl $source
  set netcdf4=1
else
  set netcdf4=0
endif

set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-s $solps_fluids) then
  setenv SOLPS_FLUIDS `cat $solps_fluids`
else
  setenv SOLPS_FLUIDS "`get_solps_fluids`"
endif
set species_names = ( $SOLPS_FLUIDS )
set neutral_species_names = ()
foreach name ($species_names)
  set last_char = `echo "$name" | awk '{print substr($0,length($0),1)}'`
  set second_last_char = `echo "$name" | awk '{print substr($0,length($0)-1,1)}'`
  if ("$last_char" == "0" && "$second_last_char" !~ [0-9]) then
    set neutral_species_names = ($neutral_species_names $name)
  endif
end

/bin/cp /dev/null ${tmpdir}gnuplot.data.tmp
set nc=`ncdump -h $source | grep "nc = " | cut -d "=" -f 2 | cut -d ";" -f 1`
start:
  set count=`echo "$1" | sed -e 's:[^()]::g' | wc -c`
  if ($count == "1") then
    if ($no_nc2text == 1) then
      if ("$1" =~ *[0-9]) then
        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
        echo "Error: Printing multi-species arrays from b2time.nc not yet implemented without nc2text."
        exit 1
      else
        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
        set check=`ncdump $source -v $1 | sed -n 'x;$p' | sed 's/;//g'`
      endif
    else
      if ("$1" =~ *[0-9]) then
        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
        set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
        set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
        @ is_plus_1 = $is + 1
        if ("$name" =~ namx* || "$name" =~ *bsep* || "$name" =~ nasep* ) then
          set check=`nc2text -n 999999 $source "$name($is_plus_1,:,1)"`
        else
          set check=`nc2text -n 999999 $source "$name($is_plus_1,1)"`
        endif
      else
        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
        set check=`nc2text -n 999999 $source "$1(1)"`
      endif
    endif
  else
    set check="1"
  endif
  if ($#check == 1) then
    if ($no_nc2text == 1) then
      if ("$1" =~ *[0-9]) then
        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
        echo "Error: Printing multi-species arrays from b2time.nc not yet implemented without nc2text."
        exit 1
      else
        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
        ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
        sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
        set args="$args $1"
      endif
    else
      if ("$1" =~ *[0-9]) then
        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
        set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
        set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
        @ is_plus_1 = $is + 1
        if ("$name" =~ namx* || "$name" =~ *bsep* || "$name" =~ nasep*) then
          nc2text -n 9999999 $source "$name($is_plus_1,1,:)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
          if ($nc = "2") then
            nc2text -n 9999999 $source "$name($is_plus_1,2,:)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
          endif
        else
          nc2text -n 9999999 $source "$name($is_plus_1,:)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
        endif
        if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
          setenv species_name $neutral_species_names[$is_plus_1]
        else
          setenv species_name $species_names[$is_plus_1]
        endif
        set args="$args $name($species_name)"
      else
        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
        if ("$1" =~ tm* && !("$1" =~ tmb*)) then
          nc2text -n 9999999 $source $1 >> ${tmpdir}gnuplot.data.tmp
        else
          nc2text -n 9999999 $source $1 | awk.transpose >> ${tmpdir}gnuplot.data.tmp
        endif
        set args="$args $1"
      endif
    endif
  else
    if ($no_nc2text == 1) then
      if ("$1" =~ *[0-9]) then
        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
        echo "Error: Printing multi-species arrays from b2time.nc not yet implemented without nc2text."
        exit 1
      else
        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
        ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
        awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' | \
        awk.transpose >> ${tmpdir}gnuplot.data.tmp
        set args="$args `count -p $1. 1 $#check`"
      endif
    else
      if ("$1" =~ *[0-9]) then
        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
        set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
        set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
        @ is_plus_1 = $is + 1
        if ("$name" =~ namx* || "$name" =~ *bsep* || "$name" =~ nasep*) then
          nc2text -n 9999999 $source "$name($is_plus_1,1,:)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
          if ($nc = "2") then
            nc2text -n 9999999 $source "$name($is_plus_1,2,:)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
          endif
        else
          nc2text -n 9999999 $source "$name($is_plus_1,:)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
        endif
        if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
          setenv species_name $neutral_species_names[$is_plus_1]
        else
          setenv species_name $species_names[$is_plus_1]
        endif
        set args="$args `count -p '$name($species_name)'. 1 $#check`"
      else
        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
        if ("$1" =~ tm* && !("$1" =~ tmb*)) then
          nc2text -n 9999999 $source $1 >> ${tmpdir}gnuplot.data.tmp
        else
          nc2text -n 9999999 $source $1 | awk.transpose >> ${tmpdir}gnuplot.data.tmp
        endif
        set args="$args `count -p $1. 1 $#check`"
      endif
    endif
  endif
  shift
  if ("X$1X" != "XX") goto start

echo "# $args"
awk.transpose < ${tmpdir}gnuplot.data.tmp
rm ${tmpdir}gnuplot.data.tmp

if ($netcdf4 == 1) then
  rm $source
endif
