#! /bin/csh -f

nc2text -n 9999999 b2time.nc "dsl" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! dsfile

set x=$1
if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif

if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif

if ( $#argv < 1 ) then
    echo "Error: You must provide at least one argument (1st, 2nd, etc. arguments will be plotted vs. ds*)."
    exit 1
endif

set source=b2mn.exe.dir/b2time.nc
if (! -s $source) set source=b2time.nc

set args = ( $argv )
set nargs=$#argv

set last = $argv[$nargs]
@ second_last_index = $nargs - 1
set second_last = $argv[$second_last_index]

set test_last = `echo $last | grep '^[0-9]*$'`
set test_second_last = `echo $second_last | grep '^[0-9]*$'`

set NUM=10
if ((($test_last) || ($test_last == 0)) && !(($test_second_last) || ($test_second_last == 0)) ) then
    set NUM=$last
    @ n = $#args - 1
    set args = ( $args[1-$n] )
    set nargs=$#args
endif
set END=-0
if ((($test_last) || ($test_last == 0)) && (($test_second_last) || ($test_second_last == 0)) ) then
    set NUM=$second_last
    set END=$last
    @ n = $#args - 2
    set args = ( $args[1-$n] )
    set nargs=$#args
endif
@ NUM = 1 + $END - $NUM

if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif

which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
if (-e b2mn.exe.dir/.netcdf4) then
  ln -sf $source ${tmpdir}b2time.nc.tmp
  set source=${tmpdir}b2time.nc.tmp
  gtfl $source
  set netcdf4=1
else
  set netcdf4=0
endif

set nt = `nc2text $source "ntstep" | awk '{printf "%d", $1}'`
set ns = `ncdump -h $source | grep -w "ns =" | sed -E 's/.*= *([0-9]+) *;.*/\1/'`
@ jstart = $nt + $NUM
if ($jstart < 0) then
  @ NUM = -$nt + 1
endif
@ jend = $nt + $END
if ($jend > $nt) then
 set END = -0
endif

set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-s $solps_fluids) then
  setenv SOLPS_FLUIDS `cat $solps_fluids`
else
  setenv SOLPS_FLUIDS "`get_solps_fluids`"
endif
set species_names = ( $SOLPS_FLUIDS )
set neutral_species_names = ()
foreach name ($species_names)
  set last_char = `echo "$name" | awk '{print substr($0,length($0),1)}'`
  set second_last_char = `echo "$name" | awk '{print substr($0,length($0)-1,1)}'`
    if ("$last_char" == "0" && "$second_last_char" !~ [0-9]) then
        set neutral_species_names = ($neutral_species_names $name)
    endif
end

set is_first = 1

set labels=""

set neutral_species_index = -1

foreach i ($args)

if ($is_first) then

  if ("$i" !~ *[0-9]) then

    set prefix=`echo $i | cut -c1`
    set pr2fix=`echo $i | cut -c2`
    set suffix=`echo $i | cut -c5-`
    set SUFFIX=`echo $suffix | tr 'a-z' 'A-Z'`
    set SUFFIXP=`echo $suffix | tr 'a-z' 'A-Z'`P
    set dsfile=b2mn.exe.dir/ds$suffix
    if (! -s $dsfile) set dsfile=ds$suffix
    set dsFILE=b2mn.exe.dir/ds$SUFFIX
    if (! -s $dsFILE) set dsFILE=ds$SUFFIX
    set dsFILEP=b2mn.exe.dir/ds$SUFFIXP
    if (! -s $dsFILEP) set dsFILEP=ds$SUFFIXP
    nc2text -n 9999999 $source "ds${suffix}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsfile
    if ("$suffix" != "a" && "$suffix" != "i") then
      nc2text -n 9999999 $source "ds${SUFFIX}T" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILET
      nc2text -n 9999999 $source "ds${SUFFIXP}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILEP
    endif

    set labels="$labels $i"

    if ($prefix == "f" && -s $dsFILE) then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILET | awk '{print $1,$2/$3}' >! ${tmpdir}gnuplot.data.tmp
    else if ($prefix == "t" && $pr2fix != "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' | paste ${tmpdir}dsfile - >! ${tmpdir}gnuplot.data.tmp
    else if ($prefix == "t" && $pr2fix == "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - >! ${tmpdir}gnuplot.data.tmp
    else
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - >! ${tmpdir}gnuplot.data.tmp
    endif
    if ($prefix == "f" && -s $dsFILEP) then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILEP | awk '{print $1,$2/$3}' >! ${tmpdir}gnuplot.data.tmp
    endif

  else

    set is = `echo "$i" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
    set name = `echo "$i" | sed -E 's/([0-9]+)$//'`
    @ is_plus_1 = $is + 1

    if ("$i" =~ dab* || "$i" =~ dmb* || "$i" =~ tab* || "$i" =~ tmb*) then
      set prefix=`echo $name | cut -c2`
      set pr2fix=`echo $name | cut -c3`
      set suffix=`echo $name | cut -c6-`
    else
      set prefix=`echo $name | cut -c1`
      set pr2fix=`echo $name | cut -c2`
      set suffix=`echo $name | cut -c5-`
    endif
    set SUFFIX=`echo $suffix | tr 'a-z' 'A-Z'`
    set SUFFIXP=`echo $suffix | tr 'a-z' 'A-Z'`P
    set dsfile=b2mn.exe.dir/ds$suffix
    if (! -s $dsfile) set dsfile=ds$suffix
    set dsFILE=b2mn.exe.dir/ds$SUFFIX
    if (! -s $dsFILE) set dsFILE=ds$SUFFIX
    set dsFILEP=b2mn.exe.dir/ds$SUFFIXP
    if (! -s $dsFILEP) set dsFILEP=ds$SUFFIXP
    nc2text -n 9999999 $source "ds${suffix}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsfile
    if ("$suffix" != "a" && "$suffix" != "i") then
      nc2text -n 9999999 $source "ds${SUFFIX}T" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILET
      nc2text -n 9999999 $source "ds${SUFFIXP}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILEP
    endif

    if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
      setenv species_name $neutral_species_names[$is_plus_1]
    else
      setenv species_name $species_names[$is_plus_1]
    endif
    set labels="$labels $name($species_name)"

    if ($prefix == "f" && -s $dsFILE) then
        nc2text -n 9999999 $source "$name(:,$is_plus_1,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILET | awk '{print $1,$2/$3}' >! ${tmpdir}gnuplot.data.tmp
    else
        nc2text -n 9999999 $source "$name(:,$is_plus_1,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - >! ${tmpdir}gnuplot.data.tmp
    endif
    if ($prefix == "f" && -s $dsFILEP) then
        nc2text -n 9999999 $source "$name(:,$is_plus_1,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILEP | awk '{print $1,$2/$3}' >! ${tmpdir}gnuplot.data.tmp
    endif

  endif

set is_first = 0

else

  if ("$i" !~ *[0-9]) then

    set prefix=`echo $i | cut -c1`
    set pr2fix=`echo $i | cut -c2`
    set suffix=`echo $i | cut -c5-`
    set SUFFIX=`echo $suffix | tr 'a-z' 'A-Z'`
    set SUFFIXP=`echo $suffix | tr 'a-z' 'A-Z'`P
    set dsfile=b2mn.exe.dir/ds$suffix
    if (! -s $dsfile) set dsfile=ds$suffix
    set dsFILE=b2mn.exe.dir/ds$SUFFIX
    if (! -s $dsFILE) set dsFILE=ds$SUFFIX
    set dsFILEP=b2mn.exe.dir/ds$SUFFIXP
    if (! -s $dsFILEP) set dsFILEP=ds$SUFFIXP
    nc2text -n 9999999 $source "ds${suffix}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsfile
    if ("$suffix" != "a" && "$suffix" != "i") then
      nc2text -n 9999999 $source "ds${SUFFIX}T" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILET
      nc2text -n 9999999 $source "ds${SUFFIXP}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILEP
    endif

    set labels="$labels $i"

    if ($prefix == "f" && -s $dsFILE) then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILET | awk '{print $2/$3}' >! ${tmpdir}gnuplot.data.tmp.tmp
    else if ($prefix == "t" && $pr2fix != "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' | paste ${tmpdir}dsfile - | awk '{print $2}' >! ${tmpdir}gnuplot.data.tmp.tmp
    else if ($prefix == "t" && $pr2fix == "p") then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - | awk '{print $2}' >! ${tmpdir}gnuplot.data.tmp.tmp
    else
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - | awk '{print $2}' >! ${tmpdir}gnuplot.data.tmp.tmp
    endif
    if ($prefix == "f" && -s $dsFILEP) then
      nc2text -n 9999999 $source "$i(:,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILEP | awk '{print $2/$3}' >! ${tmpdir}gnuplot.data.tmp.tmp
    endif

  else

    set is = `echo "$i" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
    set name = `echo "$i" | sed -E 's/([0-9]+)$//'`
    @ is_plus_1 = $is + 1

    if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
      set prefix=`echo $name | cut -c2`
      set pr2fix=`echo $name | cut -c3`
      set suffix=`echo $name | cut -c6-`
    else
      set prefix=`echo $name | cut -c1`
      set pr2fix=`echo $name | cut -c2`
      set suffix=`echo $name | cut -c5-`
    endif
    set SUFFIX=`echo $suffix | tr 'a-z' 'A-Z'`
    set SUFFIXP=`echo $suffix | tr 'a-z' 'A-Z'`P
    set dsfile=b2mn.exe.dir/ds$suffix
    if (! -s $dsfile) set dsfile=ds$suffix
    set dsFILE=b2mn.exe.dir/ds$SUFFIX
    if (! -s $dsFILE) set dsFILE=ds$SUFFIX
    set dsFILEP=b2mn.exe.dir/ds$SUFFIXP
    if (! -s $dsFILEP) set dsFILEP=ds$SUFFIXP
    nc2text -n 9999999 $source "ds${suffix}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsfile
    if ("$suffix" != "a" && "$suffix" != "i") then
      nc2text -n 9999999 $source "ds${SUFFIX}T" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILET
      nc2text -n 9999999 $source "ds${SUFFIXP}" | ave.awk | tr ' ' '\n' | awk 'NF>0 { printf("  % .16E\n", $1) }' >! ${tmpdir}dsFILEP
    endif

    if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
      setenv species_name $neutral_species_names[$is_plus_1]
    else
      setenv species_name $species_names[$is_plus_1]
    endif
    set labels="$labels $name($species_name)"

    if ($prefix == "f" && -s $dsFILE) then
        nc2text -n 9999999 $source "$name(:,$is_plus_1,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILET | awk '{print $2/$3}' >! ${tmpdir}gnuplot.data.tmp.tmp
    else
        nc2text -n 9999999 $source "$name(:,$is_plus_1,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - | awk '{print $2}' >! ${tmpdir}gnuplot.data.tmp.tmp
    endif
    if ($prefix == "f" && -s $dsFILEP) then
        nc2text -n 9999999 $source "$name(:,$is_plus_1,${NUM}:${END})" | ave.awk | tr ' ' '\n' | awk 'NF>0{print $1}' | paste ${tmpdir}dsfile - ${tmpdir}dsFILEP | awk '{print $2/$3}' >! ${tmpdir}gnuplot.data.tmp.tmp
    endif

  endif

  paste ${tmpdir}gnuplot.data.tmp ${tmpdir}gnuplot.data.tmp.tmp >! ${tmpdir}gnuplot.data.tmp.tmp.tmp
  mv ${tmpdir}gnuplot.data.tmp.tmp.tmp ${tmpdir}gnuplot.data.tmp
  rm ${tmpdir}gnuplot.data.tmp.tmp

endif

end

awk 'NR==1{saveNF=NF} NF==saveNF{print $0}' ${tmpdir}gnuplot.data.tmp | plot ${lx}x${ly}yplot$nargs $labels $dsfile '' `chop_pwd 60`
rm ${tmpdir}gnuplot.data.tmp
[ -f "${tmpdir}dsfile" ] && rm "${tmpdir}dsfile"
[ -f "${tmpdir}dsFILET" ] && rm "${tmpdir}dsFILET"
[ -f "${tmpdir}dsFILEP" ] && rm "${tmpdir}dsFILEP"
