#! /bin/tcsh -f

set solpstop=`climb_and_look_for SOLPSTOP`
if (-e $solpstop) then
  setenv SOLPSTOP "`cat $solpstop`"
  set RUNS=$SOLPSTOP/runs
else
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
  set RUNS=$PWD
endif

loop:
  if(-e $RUNS/Makefile.plot) goto endloop
  echo $RUNS
  if ("$RUNS" == "/") then
    echo Makefile.plot not found
    exit
  endif
  set RUNS=`dirname $RUNS`
  goto loop

endloop:
  set debug=""
  set TIME=time

argloop:
  if ("X${1}X" == "X-hX") then
    shift
    echo 'Usage: b2plot [OPTIONS] > [log file]'
    echo 'Launches the b2plot graphical post-processor'
    echo ' '
    echo 'Optional arguments:'
    echo ' -d <debugger>: launch run with debugger <debugger>.'
    echo ' -h: Prints this message.'
    echo ' -n: dry run. Will show the sequence of commands requested by b2plot.'
    echo ' -s: request a stand-alone run (without Eirene).'
    echo ' '
    exit
  endif
  if ("X${1}X" == "X-nX") then
    set debug="-n"
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
    goto argloop
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if (! $?SOLPS_DEBUG) then
      source $SOLPSTOP/SETUP/debug
      set DEBUG_SET=yes
    endif
    if ($1 == "") then
      set TIME="$DBX"
    else
      set TIME="$1"
      shift
    endif
    goto argloop
  endif
  if ("X${argv}X" == "XX") set argv="b2pl"
  set CMD=`echo $argv" " | sed -e 's: :.prt :g'`
  gmake $debug TIME="$TIME" -f $RUNS/Makefile.plot $CMD
  unsetenv STAND_ALONE
  if ($?DEBUG_SET) source $SOLPSTOP/SETUP/nodebug
