#! /bin/ksh

#  VERSION : 18.11.2003 00:48

# Particle sources, densities, and flows for 1D approach

# Universal script for b2plot.
# Multiple boxes can be specified in box.b2p - if the first line there starts with #

DATE=20001129
LK=bpp

PS=$1
NAME=${0##*/}
[ -n "$PS" ] && echo "$NAME: producing PostScript files ..." || echo "$NAME: producing gmeta files ..."

STEM=${NAME}_PS

[ -n "$PS" ] && {
  [ -d "${STEM}" ] && {
    [ -d "${STEM}.$DATE" ] && {
      rm -rf ${STEM}/* >/dev/null 2>&1; true
    } || {
      mv "${STEM}" "${STEM}.$DATE"; false
    }
  } || mkdir ${STEM}
  [ -d ${STEM}/mono ] || mkdir ${STEM}/mono
  [ -d ${STEM}/color ] || mkdir ${STEM}/color
}

# First, determine the basic variables

unset swbox
[ -s box.${LK} ] && {
  [ -a box.b2p ] && {
    [ -a box.b2p.$$ ] && {
      print -u2 -- "Cannot switch box.b2p: box.b2p.$$ exists"
      exit 4
    }
    mv box.b2p box.b2p.$$
  }
  mv box.${LK} box.b2p && swbox=y
}
. get_parm.bpl
((ip=NXC_I+1))
((op=NXC_O-1))
[ -n "$swbox" ] && {
  mv box.b2p box.${LK} && [ -a box.b2p.$$ ] && mv box.b2p.$$ box.b2p
  unset swbox
}

B="'$LL' extl"
BBB="comp"
ST="lbof sep clvl vesl phys 1.2 lbsz"

unset i_D i_He
i=0; until [ $i -eq "$NSPEC" ]; do {
  [ "${SPEC[i]}" = He ] && {
    i_He=$i
  }
  [ "${SPEC[i]}" = D_ ] && {
    i_D=$i
  }
  ((i=i+1))
}; done

rm -f gmeta color.${LK} mono.${LK} ${LK}_${L}[cm].ps.legend ${LK}.log b2plot.ps 2>/dev/null
ic=0
im=0
ib=0
echo "$ST $BB" > color.${LK}.h
echo "$ST $BB writ" > mono.${LK}.h

unset ss sf kw
[ -n "${BB[1]}" ] && ss=_b

# Loop over frames specified in box.b2p - or the default one

for bb in " ${BB[@]}"; do {

# Check whether this frame should be plotted in this mode (empty kw means yes)

  [ -n "$ss" ] && {
    let 'ib=ib+1'
    sf="_${SB[$ib]:-${ib}}"
    kw=${KW[$ib]}
    [ -n "$kw" ] && {
      [ -n "$PS" ] && {
        [ "${kw#P}" = "$kw" ] || kw=
        true
      } || [ "${kw#g}" = "$kw" ] || kw=
    }
#    [ -z "$kw" ] && {
#      print -- "$bb" >> color.${LK}
#      print -- "$bb" >> mono.${LK}
#    }
  }

#  [ -z "$kw" ] && {
#
## Prepare the 2D plots depending on the frame (samples are below)
# 
#
#    ii=0; until { let "ii=ii+1"; [ "$ii" -gt "$NSPEC" ]; }; do {
#      let "i=ii-1"
#      ff=${SPEC[i]}
#
#      let "ic=ic+1"
#      echo "$B na ${SUMZ_1[i]} ${SUMZ_N[i]} sumz
#        1.e15 3.e15 1.e16 3.e16 1.e17 3.e17 1.e18 3.e18 1.e19 3.e19 1.e20 3.e20 1.e21
#        13 clvs surf drop" >> color.${LK}
#      echo "ni_${ff}_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend
#
#      let "ic=ic+1"
#      echo "$B b2ra ${SUMZ_1[i]} ${SUMZ_N[i]} sumz pvol abs
#        1.e4 2.e4 5.e4 1.e5 2.e5 5.e5 1.e6 2.e6 5.e6 1.e7 2.e7 5.e7 1.e8
#        13 clvs surf drop" >> color.${LK}
#      echo "rad_${ff}_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend
#
#      let "ic=ic+1"
#      echo "$B brna ${SUMZ_1[i]} ${SUMZ_1[i]} sumz pvol
#        0.0 1.e18 3.e18 1.e19 3.e19 1.e20 3.e20 1.e21 3.e21 1.e22 3.e22
#        11 clvs surf drop" >> color.${LK}
#      echo "src_${ff}_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend
#
#      let "ic=ic+1"
#      echo "'$LL: V pol ${SPEC[i]}' extl  
#        fnax ${SUMZ_1[i]} ${SUMZ_N[i]} sumz psx pit m* 
#        ni ${SUMZ_1[i]} ${SUMZ_N[i]} sumz 1.0 1.e-6 rm+
#        m/
#         -1000. -300. -100. -30. -10. 0. 10. 30. 100. 300. 1000.
#        11 clvs surf drop" >> color.${LK}
#      echo "vi_${ff}_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend
#
#    }; done
#
#  }
}; done

# Plots invariant with respect to the bounding box (sample is below)

((im=im+1))
echo "phys '$LL : fly D CEI' extl
    fnay 1 zsel 
    1 nreg m* psy 1 f.x drop" >> mono.${LK}
echo "fly_D_CEI_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : fly D sep' extl
    fnay 1 zsel 
    2 nreg m* psy jsep 1 i+ f.x drop" >> mono.${LK}
echo "fly_D_sep_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : nD CEI' extl
    na 1 zsel 
    1 nreg m* 1 f.x drop" >> mono.${LK}
echo "nD_CEI_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : nD sep' extl
    na 1 zsel 
    2 nreg m* jsep 1 i+ f.x drop" >> mono.${LK}
echo "nD_sep_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : ne CEI' extl
    ne 
    1 nreg m* 1 f.x drop" >> mono.${LK}
echo "ne_CEI_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : ne sep' extl
    ne 
    2 nreg m* jsep 1 i+ f.x drop" >> mono.${LK}
echo "ne_sep_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : core depth' extl
    hy1  
    1 nreg m* sumy jsep f.x drop" >> mono.${LK}
echo "core_depth_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : ne 1D' extl
    sy
    1 nreg 2 nreg m+ m*
    dup
    ne 
    m* sumx
    swap sumx m/
    jxa f.y drop" >> mono.${LK}
echo "ne_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

[ -n "$i_D" ] && {
  ((im=im+1))
  echo "phys '$LL : nD 1D' extl
      sy 
      1 nreg 2 nreg m+ m*
      dup
      na ${SUMZ_1[i_D]} ${SUMZ_N[i_D]} sumz 
      m* sumx
      swap sumx m/
      jxa f.y drop" >> mono.${LK}
  echo "nD_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective parallel sink of D ions
  ((im=im+1))
  echo "phys '$LL : D sink 1D' extl
      jsep iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
      fnax ${SUMZ_1[i_D]} ${SUMZ_N[i_D]} sumz m* sumx
      1 nreg 2 nreg m+ vol m* sumx m/
      jxa f.y drop" >> mono.${LK}
  echo "SD_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective tau parallel for D ions
  ((im=im+1))
  echo "phys '$LL : D nu par 1D' extl
      jsep iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
      fnax ${SUMZ_1[i_D]} ${SUMZ_N[i_D]} sumz m* sumx
      na ${SUMZ_1[i_D]} ${SUMZ_N[i_D]} sumz vol m*
      1 nreg 2 nreg m+ m* sumx m/
      jxa f.y drop" >> mono.${LK}
  echo "tp_D_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend
}

[ -n "$i_He" ] && {
  ((im=im+1))
  echo "phys '$LL : nHe 1D' extl
      sy 
      1 nreg 2 nreg m+ m*
      dup
      na ${SUMZ_1[i_He]} ${SUMZ_N[i_He]} sumz 
      m* sumx
      swap sumx m/
      jxa f.y drop" >> mono.${LK}
  echo "nHe_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective parallel sink of He ions
  ((im=im+1))
  echo "phys '$LL : He sink 1D' extl
      jsep iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
      fnax ${SUMZ_1[i_He]} ${SUMZ_N[i_He]} sumz m* sumx
      1 nreg 2 nreg m+ vol m* sumx m/
      jxa f.y drop" >> mono.${LK}
  echo "SHe_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective tau parallel for He ions
  ((im=im+1))
  echo "phys '$LL : He nu par 1D' extl
      jsep iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
      fnax ${SUMZ_1[i_He]} ${SUMZ_N[i_He]} sumz m* sumx
      na ${SUMZ_1[i_He]} ${SUMZ_N[i_He]} sumz vol m*
      1 nreg 2 nreg m+ m* sumx m/
      jxa f.y drop" >> mono.${LK}
  echo "tp_He_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend
}

((im=im+1))
echo "phys '$LL : Te 1D' extl
    sy
    1 nreg 2 nreg m+ m*
    ne m*
    dup
    Te 
    m* sumx
    swap sumx m/
    jxa f.y drop" >> mono.${LK}
echo "Te_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective parallel sink of electron energy
((im=im+1))
echo "phys '$LL : Ee sink 1D' extl
    jxsp iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
    fhex m* sumx
    1 nreg 2 nreg m+ vol m* sumx m/
    jxa f.y drop" >> mono.${LK}
echo "SEe_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective tau parallel for electron energy
((im=im+1))
echo "phys '$LL : Ee nu par 1D' extl
    jsep iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
    fhix m* sumx
    ne Te m* ev rm* 1.5 rm* vol m*
    1 nreg 2 nreg m+ m* sumx m/
    jxa f.y drop" >> mono.${LK}
echo "tp_Ee_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : Ti 1D' extl
    sy
    1 nreg 2 nreg m+ m*
    na 0 0 sumz m*
    dup
    Ti 
    m* sumx
    swap sumx m/
    jxa f.y drop" >> mono.${LK}
echo "Ti_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective parallel sink of ion energy
((im=im+1))
echo "phys '$LL : Ei sink 1D' extl
    jsep iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
    fhix m* sumx
    1 nreg 2 nreg m+ vol m* sumx m/
    jxa f.y drop" >> mono.${LK}
echo "SEi_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Effective tau parallel for ion energy
((im=im+1))
echo "phys '$LL : Ei nu par 1D' extl
    jsep iygt $NXC_I ixeq $ip ixeq m+ -1. rm* $NXC_O ixeq $op ixeq m+ m+ 0.5 rm* m*
    fhix m* sumx
    na 0 0 sumz Ti m* ev rm* 1.5 rm* vol m*
    1 nreg 2 nreg m+ m* sumx m/
    jxa f.y drop" >> mono.${LK}
echo "tp_Ei_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : src D 1D' extl
    b2nn 1 zsel
    1 nreg 2 nreg m+ m* sumx
    vol
    1 nreg 2 nreg m+ m* sumx
    m/
    jxa f.y drop" >> mono.${LK}
echo "src_D_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : fly D 1D' extl
    fnay 1 zsel 
    1 nreg 2 nreg m+ m*
    sumx
    jxa f.y drop" >> mono.${LK}
echo "fly_D_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

((im=im+1))
echo "phys '$LL : fly e 1D' extl
    fnay za m* 0 0 sumz 
    1 nreg 2 nreg m+ m*
    sumx
    jxa f.y drop" >> mono.${LK}
echo "fly_e_1D_${L}\t$im" >> ${LK}_${L}m.ps.legend

# Produce the plots from the prepared control files

S=mono
for C in m c; do {
  [ -s ${S}.${LK} ] && {
    cat ${S}.${LK} >> ${S}.${LK}.h
    mv ${S}.${LK}.h ${S}.${LK}
    b2plot < ${S}.${LK} >> ${LK}.log 2>&1
    [ -n "$PS" ] && {
      [ -s gmeta ] && {
        ctrans -d ps.$S -outfile ${STEM}/${S}/${LK}_${L}${C}.ps gmeta
        mv ${LK}_${L}${C}.ps.legend ${STEM}/${S}
        [ -s b2plot.write ] && mv b2plot.write ${STEM}/${S}
        ln -s $PWD/VarID ${STEM}/${S}
        (cd ${STEM}/${S}
          ps_GV ${LK}_${L}${C}.ps && mv ${LK}_${L}${C}_GV.ps ${LK}_${L}${C}.ps && ps_mac ${LK}_${L}${C}.ps
        )
        rm gmeta
      }
    }
    [ -s gmeta ] && mv gmeta gmeta.${LK}.${S}
    true
  } || {
    rm ${S}.${LK}.h 2>/dev/null
  }
  [ -a b2plot.write ] && [ ! -s b2plot.write ] && rm b2plot.write
  S=color
}; done

[ -s gmeta.${LK}.color ] && ln -s gmeta.${LK}.color gmeta
true
