#! /bin/tcsh -f

## -h                         print help
## -n                         dry run
## -s                         run B2.5 applications in stand-alone mode (no Eirene coupling)
## -m <mpi-launcher + args>   run mpi-version (example: b2run -m \"mpiexec -np 2\" b2mn)
## -d <debugger>              use debugger <debugger>

# if we are running at JET then do not rely on the automatic feature of searching in ../baserun, instead setup links
# XPB: not sure this is still needed
# if (${HOST_NAME} == "JET" && `basename $PWD` != "baserun") then
#   echo Special action is being taken since we are running at JET
#   foreach i (b2mn.dat b2fgmtry b2fpardf b2fstati b2frates)
#     if (! -s $i) then
#       echo Setting up a link to ../baserun/$i
#       ln -s ../baserun/$i
#     endif
#   end
# endif
# end

set solpstop=`climb_and_look_for SOLPSTOP`
if (-s $solpstop) then
  setenv SOLPSTOP "`cat $solpstop`"
  set RUNS=$SOLPSTOP/runs
else if ($SOLPSTOP != "") then
  set RUNS=$SOLPSTOP/runs
else
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
  set RUNS=$PWD
endif
echo Using SOLPSTOP = $SOLPSTOP

loop:
  if(-s $RUNS/Makefile) goto endloop
  if ("$RUNS" == "/") then
    echo Makefile not found
    exit
  endif
  set RUNS=`dirname $RUNS`
  goto loop

endloop:
  set debug=""
  set TIME=time

argloop:
  if ("X${1}X" == "X-hX") then
    shift
    echo 'Usage: b2run [OPTIONS] [executable] < [Eirene input file] > [log file]'
    echo 'Launches a SOLPS run'
    echo ' '
    echo 'Optional arguments:'
    echo ' -d <debugger>: launch run with debugger <debugger>.'
    echo ' -h: Prints this message.'
    echo ' -m <mpi-launcher + args>: run mpi-version (example: b2run -m \"mpiexec -np 2\" b2mn)'
    echo ' -n: dry run. Will show the sequences of commands requested by b2run.'
    echo ' -s: request a B2.5 stand-alone run. No Eirene input file required then.'
    echo ' '
    echo 'Executable: One of the following'
    echo ' b2ag: Build the geometry files b2fgmtry and fort.30'
    echo ' b2ah: Build the run parameters file b2fpardf'
    echo ' b2ai: Build the initial state file b2fstati'
    echo ' b2ar: Build the atomic rates file b2frates'
    echo ' b2co: Recover from a plasmastate.xxxx file'
    echo ' b2fu: Convert from b2fplasmf to b2fplasma'
    echo ' b2md: Archive a run into MDSPLUS'
    echo ' b2mn: Main SOLPS-ITER run program'
    echo ' b2pl: Run the b2plot graphical post-processor'
    echo ' b2rd: Read an MDSPLUS archived run'
    echo ' b2ts: Generic post-processing program'
    echo ' b2uf: Convert from b2fplasma to b2fplasmf'
    echo ' b2xd: Convert to a SOLPS4.0 run'
    echo ' b2yg: Plot the geometry'
    echo ' b2yh: Plot the run parameters'
    echo ' b2yi: Plot the initial state'
    echo ' b2yi_gnuplot: Plot the initial state (using gnuplot)'
    echo ' b2ym: Produces movie output'
    echo ' b2yn: Plot the progress of inner iterations'
    echo ' b2yp: Plots the plasma state'
    echo ' b2yq: Plots the time evolution data'
    echo ' b2yr: Plot the atomic physics rates'
    echo ' b2yt: Convert a run to a different grid size or species list'
    echo ' '
    exit
  endif
  if ("X${1}X" == "X-nX") then
    shift
    set debug="-n"
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
    goto argloop
  endif
  if ("X${1}X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set TIME=`echo $argv | sed -e 's:^"::' -e 's:" .*::'`
    set nargs=`echo $TIME | awk '{print split($0,args," ")}'`
    mpiloop:
      if ($nargs > 0) then
        shift
        @ nargs = $nargs - 1
      else
        goto mpiloopend
      endif
      goto mpiloop
    mpiloopend:
    goto argloop
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if (! $?SOLPS_DEBUG) then
      source $SOLPSTOP/SETUP/debug
      set DEBUG_SET=yes
    endif
    if ($1 == "") then 
      set TIME="$DBX"
    else  
      set TIME="$1"
      shift
    endif
    goto argloop 
  endif
  if ("X${argv}X" == "XX") set argv="b2mn"
  echo "argument= " $argv
  set CMD=`echo $argv" " | sed -e 's: :.prt :g'`
  echo $CMD
  make $debug TIME="$TIME" -f $RUNS/Makefile $CMD
  unsetenv STAND_ALONE
  if ($?MPI_SET)   source $SOLPSTOP/SETUP/nompi
  if ($?DEBUG_SET) source $SOLPSTOP/SETUP/nodebug
  
