#! /bin/tcsh -f

## -n                         dry run
## -s                         run B2.5 applications in stand-alone mode (no Eirene coupling)
## -m <mpi-launcher + args>   run mpi-version (example: b2run -m "mpiexec -np 2" b2mn)
## -d <debugger>              use debugger <debugger>

# if we are running at JET then do not rely on the automatic feature of searching in ../baserun, instead setup links
if (${HOST_NAME} == "JET") then
  echo Special action is being taken since we are running at JET
  foreach i (b2mn.dat b2fgmtry b2fpardf b2fstati b2frates)
    if (! -e $i) then
      echo Setting up a link to ../baserun/$i
      ln -s ../baserun/$i
    endif
  end
endif
# end

set solpstop=`climb_and_look_for SOLPSTOP`
if (-e $solpstop) then
  setenv SOLPSTOP "`cat $solpstop`"
  set RUNS=$SOLPSTOP/runs
else
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
  set RUNS=$PWD
endif
echo Using SOLPSTOP = $SOLPSTOP

loop:
  if(-e $RUNS/Makefile) goto endloop
  if ("$RUNS" == "/") then
    echo Makefile not found
    exit
  endif
  set RUNS=`dirname $RUNS`
  goto loop

endloop:
  set debug=""
  set TIME=time
  if ("X${1}X" == "X-nX") then
    shift
    set debug="-n"
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
  endif
  if ("X${1}X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set TIME=`echo $argv | sed -e 's:^"::' -e 's:" .*::'`
    set nargs=`echo $TIME | awk '{print split($0,args," ")}'`
    argloop:
      if ($nargs > 0) then
        shift
        @ nargs = $nargs - 1
      else
        goto argloopend
      endif
      goto argloop
    argloopend:
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if (! $?SOLPS_DEBUG) then
      source $SOLPSTOP/SETUP/debug
      set DEBUG_SET=yes
    endif
    if ($1 == "") then 
      set TIME="$DBX"
    else  
      set TIME="$1"
      shift
    endif 
  endif
  if ("X${argv}X" == "XX") set argv="b2mn"
  set CMD=`echo $argv" " | sed -e 's: :.prt :g'`
  make $debug TIME="$TIME" -f $RUNS/Makefile $CMD
  unsetenv STAND_ALONE
  if ($?MPI_SET)   source $SOLPSTOP/SETUP/nompi
  if ($?DEBUG_SET) source $SOLPSTOP/SETUP/nodebug
  
