#! /usr/bin/env tcsh

setenv SOLPSTOP "`determine_SOLPSTOP`"
if ($SOLPSTOP != "") then
  set RUNS=$SOLPSTOP/runs
else
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
  set RUNS=$PWD
endif
echo Using SOLPSTOP = $SOLPSTOP

loop:
  if(-s $RUNS/Makefile.b2sxdr) goto endloop
  echo $RUNS
  if ("$RUNS" == "/") then
    echo Makefile.b2sxdr not found
    exit
  endif
  set RUNS=`dirname $RUNS`
  goto loop

endloop:
  set debug=""
  set TIME=time
  set RUN_OPTIONS=""

argloop:
  if ("X${1}X" == "X-hX") then
    shift
    echo 'Usage: b2sxdr [OPTIONS] > [log file]'
    echo 'Launches a SOLPS run'
    echo ' '
    echo 'Optional arguments:'
    echo ' -d <debugger>: launch run with debugger <debugger>.'
    echo ' -h: Prints this message.'
    echo ' -n: dry run. Will show the sequence of commands requested by b2sxdr.'
    echo ' -s: request a stand-alone run (without Eirene).'
    echo ' '
    exit
  endif
  if ("X${1}X" == "X-nX") then
    shift
    set debug="-n"
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
    goto argloop
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if (! $?SOLPS_DEBUG) then
      source $SOLPSTOP/SETUP/debug
      set DEBUG_SET=yes
    endif
    if ($1 == "") then
      set TIME="$DBX"
    else
      set next=$1
      set begin_next=`printf '%s' $next | cut -c1`
      if ("X${begin_next}X" == "X-X") then
        set TIME="$DBX"
      else
        set TIME="$1"
        shift
      endif
    endif
    goto argloop
  endif
  if ("X${1}X" == "X-oX") then
    shift
    set RUN_OPTIONS="$RUN_OPTIONS $1"
    shift
    goto argloop
  endif
  if ("X${argv}X" == "XX") set argv="b2sxdr"
  set CMD=`echo $argv" " | sed -e 's: :.prt :g'`
  ${MAKE} $debug TIME="$TIME" RUN_OPTIONS="$RUN_OPTIONS" -f $RUNS/Makefile.b2sxdr $CMD
  unsetenv STAND_ALONE
  if ($?DEBUG_SET) source $SOLPSTOP/SETUP/nodebug
