#! /bin/csh -f
pipe_run.log | \
  egrep -a 'fna.reg|nnreg' | \
  awk 'BEGIN{iss=2;ise=8} \
       /nnreg/{nxreg=$3+1;nyreg=$4+1} \
       /fnaxreg/{E=0;W=0;for (i=iss;i<=ise;i++) {E+=-$(2+nxreg*i+1);W+=$(5+nxreg*i+1)}} \
       /fnayreg/{core=0;pflxl=0;pflxr=0;N=0; \
                 for (i=iss;i<=ise;i++) \
                   {core+=-($(3+nyreg*i+1));pflxl+=-($(2+nyreg*i+1));pflxr+=-($(4+nyreg*i+1)); \
                    N+=($(6+nyreg*i+1)+$(7+nyreg*i+1)+$(8+nyreg*i+1))}; \
                 cnt++;print cnt,E,W,core,pflxl,pflxr,N}' | \
  plot x$1yplot6 -E W -core -pflxl -pflxr N iteration sum.C `noquote_pwd 3`
