#! /bin/tcsh -f
set jsep=`grep -A1 topcut ../baserun/b2fgmtry | paste - - | awk '{print $NF-1}'`
set nx=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '{print $2}' | sort -n | tail -1`
set ny=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '{print $3}' | sort -n | tail -1`
set l1=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2==-1{print $4}' | head -1`
set l2=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2==-1{print $4}' | tail -1`
set r1=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='$nx'{print $4}' | head -1`
set r2=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='$nx'{print $4}' | tail -1`
set t1=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$3=='$ny'{print $4}' | head -1`
set t2=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$3=='$ny'{print $4}' | tail -1`
set b1=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$3==-1{print $4}' | head -1`
set b2=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$3==-1{print $4}' | tail -1`

set mcw_outer=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='$nx'-1&&$3=='$ny'{print $4}'`
set outer_sep=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='$nx'&&$3=='$jsep'+1{print $4}'`
set pfx_outer=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='$nx'&&$3=='0'{print $4}'`
set pfx_inner=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='0'&&$3=='-1'{print $4}'`
set inner_sep=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='-1'&&$3=='$jsep'{print $4}'`
set mcw_inner=`grep -i XYMAP b2.wall_save.parameters | tr '(),=' '    ' | awk '$2=='-1'&&$3=='$ny'-1{print $4}'`
echo $mcw_outer $outer_sep $pfx_outer $pfx_inner $inner_sep $mcw_inner

nc2text -n1 b2wall.nc "plate_area" | awk '{sum+=$1;print sum}' | awk 'NR=='$mcw_outer'||NR=='$outer_sep'||NR=='$pfx_outer'||NR=='$pfx_inner'||NR=='$inner_sep'||NR=='$mcw_inner'{print $1,0}' >! AREA_BOUNDARIES.tmp

