#! /usr/bin/env ksh

#  VERSION : 20.07.2000 14:15

script=`basename $0`
stty erase ^H

Usage="
This is a script to call the \"carre\" grid generator.
It makes standard links to the necessary files, calls \"carre\", calls the grid convertor
\"traduit\", and moves the resulting grid to the standard place with a new name.

Usage:

$script  { <stem> | - }

The input files are:

<stem>.inp      the configuration file for carre
<stem>.vrq      the equilibrium data in \"TdeV\" format
<stem>.str      the \"structures\" file
<stem>.fld      the product of R*Btor

If \"-\" is specified, then the input files are assumed to exist or to be created
via fcrr from dg output.

The script prints the output filename after successful grid conversion to B2 format.
The directories for the input files and for the grids can be specified in the
environmental variables CARRE_INPUTDIR and CARRE_GRIDDIR (default is the current directory).
If the variable CARRE_STOREDIR is set, then all the input data (i.e., the control file, the
equilibrium file, and the structures file) are saved in a directory
\$CARRE_STOREDIR/\$DEVICE/<grid number>. If this directory does not exist, it is created.

Error messages and tracing data from carre (\"Grid\") and traduit (\"Convert\") can be found in
the files carre.log and traduit.log, respectively.
"
if [ "$(uname)" = "Darwin" ]; then
  [ -z "$1" ] && { printf '%s\n' "$Usage"; exit 4; }
else
  [ -z "$1" ] && { /bin/echo -e "$Usage"; exit 4; }
fi

SOLPSTOP=`determine_SOLPSTOP`
[ "$SOLPS_DEBUG" = '' ] || {
  export EXT_DEBUG=".debug"
}
CARRE_PATH=$SOLPSTOP/modules/Carre/builds/$HOST_NAME.$COMPILER$EXT_DEBUG
if [ "$(uname)" = "Darwin" ]; then
  printf 'CARRE_PATH : %s\n' "$CARRE_PATH"
else
  /bin/echo -e "CARRE_PATH : $CARRE_PATH"
fi

[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
}

[ "$SOLPS_CENTRAL" = 'yes' ] && DEVICE=$DEVICE/$USER

# griddir=${CARRE_GRIDDIR-$SOLPSTOP/src/Sonnet/output/ascii/${Model_Class-iter}}
# griddir=${CARRE_GRIDDIR-$SOLPSTOP/src/Sonnet/output/ascii/${DEVICE-iter}}
export CARRE_TOPDIR=$SOLPSTOP/modules/Carre
dgdir=${CARRE_GRIDDIR-$DG/device/${DEVICE-iter}}
griddir=${CARRE_GRIDDIR-$SOLPSTOP/modules/Carre/meshes/${DEVICE-iter}}
class=$DEVICE
indir=${CARRE_STOREDIR-.}
stordir=$griddir
[ -n "$CARRE_STOREDIR" ] && stordir="$CARRE_STOREDIR/${DEVICE-iter}"
grid_stem=$class.carre
endings="dgo equ str trg"
if [ "$(uname)" = "Darwin" ]; then
  printf 'Store directory: %s\n' "$stordir"
  printf 'Grid directory: %s\n' "$griddir"
  printf 'Input directory: %s\n' "$indir"
else
  /bin/echo -e "Store directory: $stordir"
  /bin/echo -e "Grid directory: $griddir"
  /bin/echo -e "Input directory: $indir\n"
fi

[ "$1" = '-' ] && {
    [ -r $indir/dg.str ] && {
      if [ "$(uname)" = "Darwin" ]; then
        printf 'Standard linking - the input files are assumed to exist in "%s" as symbolic links\n' "$indir"
      else
        /bin/echo -e "Standard linking - the input files are assumed to exist in \"$indir\" as symbolic links"
      fi
      q=p
      qqs=c
      grid_stem=`ls -ls $indir/dg.str | awk '{print $NF}' | xargs basename | sed 's:\.str$::'`
      for ext in $endings; do
        [ -e $indir/dg.$ext ] && {
          filename=`lln $indir/dg.$ext`
          [ "$filename" != '' ] || {
            if [ "$(uname)" = "Darwin" ]; then
              printf 'File dg.%s is not a symbolic link!\n' "$ext"
            else
              /bin/echo -e "File dg.$ext is not a symbolic link!"
            fi
            q=q
          }
        } || {
            if [ "$(uname)" = "Darwin" ]; then
              printf 'File dg.%s is missing!\n' "$ext"
            else
              /bin/echo -e "File dg.$ext is missing!"
            fi
           q=q
           qqs=q
        }
      done
      [ "$q" = 'q' ] && {
          [ "$qqs" = 'q' ] && {
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Run the lns script first.\n'
            else
              /bin/echo -e "Run the lns script first."
            fi
          } || {
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Case storage step will fail.\n'
              printf 'Run the lns script first to assign a stem name to this case.\n'
            else
              /bin/echo -e "Case storage step will fail."
              /bin/echo -e "Run the lns script first to assign a stem name to this case"
            fi
          }
      } ; break;
    } || {
      if [ "$(uname)" = "Darwin" ]; then
        printf 'Linking error - the input files were not found in "%s"\n' "$indir"
        printf 'Use (I)nput command to provide correct input directory\n'
      else
        /bin/echo -e "Linking error - the input files were not found in \"$indir\""
        /bin/echo -e "Use (I)nput command to provide correct input directory"
      fi
      q=i
      qqs=c
    }
} || { \
    u="$indir/$1"
    [ -r $u.vrq ] && [ -r $u.str ] && [ -r $u.fld ] & { \
        ln -sf $u.vrq rzpsi.dat
        ln -sf $u.str structure.dat
        ln -sf $u.fld btor.dat
        ln -sf $u.inp carre.dat
        q=g
        qqs=s
    } || {
        if [ "$(uname)" = "Darwin" ]; then
          printf 'Files %s.vrq, %s.str, and %s.fld must be present!\n' "$u" "$u" "$u"
        else
          /bin/echo -e "Files $u.vrq, $u.str, and $u.fld must be present!"
        fi
        exit 8
    }
}
while true
do {
  if [ "$(uname)" = "Darwin" ]; then
    printf 'Help, Prepare, Grid, Save, Convert, sTore, Next, Remove, Input, Output, Quit ? (%s)\c' "$q"
  else
    /bin/echo -e "Help, Prepare, Grid, Save, Convert, sTore, Next, Remove, Input, Output, Quit ? ($q)\c"
  fi
  while true; do {
    read u
    { case "${u:-$q}" in
    ( h|H )                                               # help:
            /bin/echo -e "
  Prepare (p)   apply fcrr to create Carre input files from DG output
  Grid    (g)   apply Carre to create a grid
  Save    (s)   save Carre output as the configuration file (carre.dat)
  Convert (c)   convert the Carre grid to the format suitable for B2 and DG
  Store   (t)   store the B2 grid in the storage directory.
                If CARRE_STOREDIR is set, the carre input files are also stored.
  Next    (n)   specify a new stem for the input files.
                If \"-\" is specified, then the Carre input files from the input directory
                are used. Otherwise, <stem>.vrq, <stem>.str, <stem>.fld, and <stem>.inp
                are used as the equilibrium, structures, toroidal field, and configuration
                files for Carre.
                This must be specified each time when you change the input directory.
  Remove  (r)   remove the specified B2 grid(s) from the storage directory.
                The list consists of the grid numbers (with leading zeros) separated by
                a white space.
                The stored input data (if any) for the specified grids are also removed.
  Input   (i)   specify a new directory for the input files (input directory).
                If the specified directory does not exist and the CARRE_STOREDIR is set,
                then the input directory is looked for in \$CARRE_STOREDIR/\$DEVICE
                and \$CARRE_STOREDIR
  Output  (o)   specify a new storage directory for the grids
  Quit    (q)   quit $script
"; break;;
    ( p|P )                                               # prepare input from DG output:
            [ "$DEVICE" = '' ] && { [ -L $indir/dg.trg ] && { \
                class=`lln $indir/dg.trg`
                class=${class%/*}
                class=${class##*/}
            } }
            [ "$class" = 'baserun' ] && {
                print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
                read u
                export DEVICE=$u
                class=$DEVICE
            }
            griddir=${CARRE_GRIDDIR-$SOLPSTOP/modules/Carre/meshes/${DEVICE-iter}}
            [ -n "$CARRE_STOREDIR" ] && stordir="$CARRE_STOREDIR/$class"

            if [ "$(uname)" = "Darwin" ]; then
              printf 'class = %s\ngriddir = %s\nindir = %s\ngrid_stem = %s\n' "$class" "$griddir" "$indir" "$grid_stem"
            else
              /bin/echo -e "class = $class\ngriddir = $griddir\nindir = $indir\ngrid_stem = $grid_stem"
            fi
            [ -n $class ] && {
              [ -r $class.aux ] && ln -sf $class.aux dg.aux
            }
            rm -f selptx.inf carre.dat structure.dat rzpsi.dat btor.dat 2>/dev/null
            $CARRE_PATH/fcrr.exe; q=g; break;;
    ( g|G )                                               # create the grid:
#            carre.exe; q=s; break;;
            $CARRE_PATH/carre.exe 2>carre.log
            [ -s carre.out ] && {
              q=$qqs
            } || {
              if [ "$(uname)" = "Darwin" ]; then
                printf 'Carre output was not produced. Check the carre.log file\n'
              else
                /bin/echo -e "Carre output was not produced. Check the carre.log file"
              fi
              q=q
            }
            break;;
    ( s|S )                                               # save the control data:
            cp carre.out carre.dat;
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Saved grid settings in carre.dat file\n'
            else
              /bin/echo -e "Saved grid settings in carre.dat file"
            fi
            q=c; break;;
    ( c|C )                                               # convert:
            if [ "$(uname)" = "Darwin" ]; then
              printf 'carre.out\n4\n' | $CARRE_PATH/traduit.exe 2>traduit.log; mv traduit.out traduit.sno ;
              printf 'carre.out\n2\n' | $CARRE_PATH/traduit.exe 2>traduit.log;
            else
              /bin/echo -e "carre.out\n4" | $CARRE_PATH/traduit.exe 2>traduit.log; mv traduit.out traduit.sno ;
              /bin/echo -e "carre.out\n2" | $CARRE_PATH/traduit.exe 2>traduit.log;
            fi
            q=t; break;;
    ( t|T )                                               # store the grid:
            [ -r traduit.out ] && {
                [ -d "$griddir" ] || {
                    if [ "$(uname)" = "Darwin" ]; then
                      printf 'The directory "%s" does not exist. Create it (y/n)? \c' "$griddir"
                    else
                      /bin/echo -e "The directory \"$griddir\" does not exist. Create it (y/n)? \c"
                    fi
                    read u; case "$u" in
                      ( y|Y )   /bin/echo -e mkdir "$griddir"
                      mkdir -p "$griddir" || break;;
                      (  *  )   /bin/echo -e break
                      break;;
                    esac
                }
                if [ "$(uname)" = "Darwin" ]; then
                  printf 'dir OK\n'
                else
                  /bin/echo -e dir OK
                fi
                typeset -i n
                n=1
                set -- $griddir/$grid_stem.v[0-9][0-9][0-9].geo
                [ -f $1 ] && {
                    m=`ls $griddir/$grid_stem.v[0-9][0-9][0-9].geo | tail -1`
#		    m=`echo $griddir/$grid_stem.v[0-9][0-9][0-9].geo | awk '{print $NF}'`
                    m=${m#*/$grid_stem.v}
                    m=${m%.geo}
                    if [ "$(uname)" = "Darwin" ]; then
                      printf 'Last grid number found is : %d\n' "$m"
                    else
                      /bin/echo -e "Last grid number found is : $m"
                    fi
                    n=`echo $m | sed -r -e 's:^0{1,}::'`
                    n=n+1
                    m=$n
                } || {
                    m=1
                }
                [ ${#m} -lt 2 ] && m=00$m || {
                    [ ${#m} -lt 3 ] && m=0$m
                }
                touch CARRE.HISTORY
		echo $user `date +%Y-%m-%d_%H:%M:%S` >> CARRE.HISTORY
		ls -ls dg.??? | awk '{for (i=6;i<=NF;i++) printf " %s",$i;printf "\n"}' >> CARRE.HISTORY
                cp traduit.sno $dgdir/$grid_stem.v$m.sno && \
                  if [ "$(uname)" = "Darwin" ]; then
                    printf 'The grid in DG format is stored as %s/%s.v%d.sno\n' "$dgdir" "$grid_stem" "$m" && \
                    printf 'The grid in DG format is stored as %s/%s.v%d.sno\n' "$dgdir" "$grid_stem" "$m" >> CARRE.HISTORY
                  else
                    /bin/echo -e "The grid in DG format is stored as $dgdir/$grid_stem.v$m.sno" && \
                    /bin/echo -e "The grid in DG format is stored as $dgdir/$grid_stem.v$m.sno" >> CARRE.HISTORY
                  fi
                mv -f traduit.sno $grid_stem.v$m.sno
                for ext in $endings; do
                  filename=`lln dg.$ext`
                  cp $filename $dgdir/`basename $filename`
                  if [ "$(uname)" = "Darwin" ]; then
                    printf '%s copied to %s\n' "$filename" "$dgdir" && \
                    printf '%s copied to %s\n' "$filename" "$dgdir" >> CARRE.HISTORY
                  else
                    /bin/echo -e "`basename $filename` copied to $dgdir" && \
                    /bin/echo -e "`basename $filename` copied to $dgdir" >> CARRE.HISTORY
                  fi
                done
                if [ "$(uname)" = "Darwin" ]; then
                  modelname=$(echo $filename | sed -e 's#trg\\dg##' )
                else
                  modelname=`echo $filename | sed -e 's\trg\dg\' `
                fi
                cp $modelname $dgdir/`basename $modelname`
                if [ "$(uname)" = "Darwin" ]; then
                  printf 'DG model %s copied to %s\n' "$modelname" "$dgdir" && \
                  printf 'DG model %s copied to %s\n' "$modelname" "$dgdir" >> CARRE.HISTORY
                else
                  /bin/echo -e "DG model `basename $modelname` copied to $dgdir" && \
                  /bin/echo -e "DG model `basename $modelname` copied to $dgdir" >> CARRE.HISTORY
                fi
                cp traduit.out $griddir/$grid_stem.v$m.geo && \
                  if [ "$(uname)" = "Darwin" ]; then
                    printf 'The grid in B2.5 format is stored as %s/%s.v%d.geo\n' "$griddir" "$grid_stem" "$m" && \
                    printf 'The grid in B2.5 format is stored as %s/%s.v%d.geo\n' "$griddir" "$grid_stem" "$m" >> CARRE.HISTORY
                  else
                    /bin/echo -e "The grid in B2.5 format is stored as $griddir/$grid_stem.v$m.geo" && \
                    /bin/echo -e "The grid in B2.5 format is stored as $griddir/$grid_stem.v$m.geo" >> CARRE.HISTORY
                  fi
                mv -f traduit.out $grid_stem.v$m.geo
                [ -x ctrans ] && {
                  ctrans -d ps.mono gmeta > $griddir/$grid_stem.v$m.ps && \
                  if [ "$(uname)" = "Darwin" ]; then
                    printf 'You can view the grid in PostScript format as %s/%s.v%d.ps\n' "$griddir" "$grid_stem" "$m" && \
                    printf 'You can view the grid in PostScript format as %s/%s.v%d.ps\n' "$griddir" "$grid_stem" "$m" >> CARRE.HISTORY
                  else
                    /bin/echo -e "You can view the grid in PostScript format as $griddir/$grid_stem.v$m.ps" && \
                    /bin/echo -e "You can view the grid in PostScript format as $griddir/$grid_stem.v$m.ps" >> CARRE.HISTORY
                  fi
                }
                [ -n "$stordir" ] && {
                  [ -d "$stordir" ] || {
                    [ -a "$stordir" ] && {
                      if [ "$(uname)" = "Darwin" ]; then
                        printf 'Name collision: there is already a file named %s\n' "$stordir"
                        printf '  ==> the directory cannot be created\n'
                      else
                        /bin/echo -e "Name collision: there is already a file named $stordir"
                        /bin/echo -e "  ==> the directory cannot be created"
                      fi
                    } || {
                      if [ "$(uname)" = "Darwin" ]; then
                        printf 'The directory "%s" does not exist. Create it (y/n)? \c' "$stordir"
                      else
                        /bin/echo -e "The directory \"$stordir\" does not exist. Create it (y/n)? \c"
                      fi
                      read u; case "$u" in
                        ( y|Y )   /bin/echo -e mkdir "$stordir"
                                  mkdir -p "$stordir";;
                        (  *  )   ;;
                      esac
                    }
                  }
                  [ -d "$stordir" ] && {
                    s="$stordir/$grid_stem.v$m"
                    u=y
                    [ -d "$s" ] && {
                      if [ "$(uname)" = "Darwin" ]; then
                        printf 'The directory "%s" already exists. Use it (y/n)? \c' "$s"
                      else
                        /bin/echo -e "The directory \"$s\" already exists. Use it (y/n)? \c"
                      fi
                      read u; case "$u" in
                        ( y|Y )   ;;
                        (  *  )   u=;;
                      esac
                     }
                    [ -n "$u" ] && {
                      [ -d "$s" ] || mkdir -p "$s"
                      cp carre.dat structure.dat rzpsi.dat btor.dat "$s" && \
                              if [ "$(uname)" = "Darwin" ]; then
                                printf 'carre.dat, structure.dat, rzpsi.dat, and btor.dat copied to %s\n' "$s" && \
                                printf 'carre.dat, structure.dat, rzpsi.dat, and btor.dat copied to %s\n' "$s" >> CARRE.HISTORY
                              else
                                /bin/echo -e "carre.dat, structure.dat, rzpsi.dat, and btor.dat copied to $s" && \
                                /bin/echo -e "carre.dat, structure.dat, rzpsi.dat, and btor.dat copied to $s" >> CARRE.HISTORY
                              fi
                    }
                  }
                }
                q=q; true
            } || { /bin/echo -e "No traduit.out. Convert the grid first."; q=c; }
                echo "=======================================================================================" >> CARRE.HISTORY
            break;;
    ( n|N )                                               # next job:
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Input the new stem: \c'; read u
            else
              /bin/echo -e "Input the new stem: \c"; read u
            fi
            [ -n "$u" ] && {
              [ "$u" = '-' ] && {
                [ -r $indir/rzpsi.dat ] && [ -r $indir/structure.dat ] && [ -r $indir/btor.dat ] && {
                  ln -sf $indir/rzpsi.dat $indir/structure.dat $indir/btor.dat . && q=g
                  [ -r $indir/carre.dat ] && {
                    ln -sf $indir/carre.dat .
                    true
                  } || {
                    rm -f carre.dat 2>/dev/null
                    true
                  }
                } || {
                  print -- "If you specify \"-\" as the stem, the following files must be present in the input directory:"
                  print -- "    rzpsi.dat   structure.dat   btor.dat"
                }
              } || {
                u="$indir/$u"
                [ -r $u.vrq ] && [ -r $u.str ] && [ -r $u.fld ] & {
                  ln -sf $u.vrq rzpsi.dat
                  ln -sf $u.str structure.dat
                  ln -sf $u.fld btor.dat
                  ln -sf $u.inp carre.dat
                  q=g
                  true
                } || {
                  if [ "$(uname)" = "Darwin" ]; then
                    printf 'Files %s.vrq, %s.str, and %s.fld must be present in the input directory\n' "$u" "$u" "$u" 
                  else
                    /bin/echo -e "Files $u.vrq, $u.str, and $u.fld must be present in the input directory"
                  fi
                }
              }
            }; break;;
    ( r|R )                                               # remove the grid(s):
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Input the list of grid numbers to be REMOVED:\n'; read u
            else
              /bin/echo -e "Input the list of grid numbers to be REMOVED:"; read u
            fi
            [ -n "$u" ] && {
                uu=
                vv=
                ww=
                for n in $u; do
                  m=$n
                  [ ${#m} -lt 2 ] && m=00$m || {
                    [ ${#m} -lt 3 ] && m=0$m
                  }
                  uu="$uu $griddir/$grid_stem.v$m.geo"
                  vv="$vv $griddir/$grid_stem.v$m.ps"
                  ww="$ww $dgdir/$grid_stem.v$m.sno"
                done
                ls -l $uu $vv $ww
                if [ "$(uname)" = "Darwin" ]; then
                  printf 'Do you wish to remove this grid(s)? (y/n): \c'; read u
                else
                  /bin/echo -e "Do you wish to remove this grid(s)? (y/n): \c"; read u
                fi
                case "$u" in
                  ( y|Y ) rm -f $uu $vv $ww
                          for f in $uu; do {
                            n=${f#$griddir/$grid_stem.v}
                            n=${n%.geo}
                            [ -d "$stordir/$grid_stem.v$n" ] && rm -r "$stordir/$grid_stem.v$n"
                          }; done ;;
                  (  *  ) ;;
                esac
            }; break;;
    ( i|I )                                               # input files:
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Specify the new input directory: \c'; read u
            else
              /bin/echo -e "Specify the new input directory: \c"; read u
            fi
            [ -n "$u" ] && {
              indir="$u"; /bin/echo -e "$indir"
              [ -d $u ] && {
                indir="$u"
              } || {
                [ -n "$stordir" ] && {
                  indir="$stordir/$u"
                  [ -d "$indir" ] || {
                    indir="$CARRE_STOREDIR/$u"
                    [ -d "$indir" ] || indir=
                  }
                }
              }
              [ -n "$indir" ] && {
                /bin/echo -e "The input directory is now `(cd $indir && pwd)`"; q=n; true
                [ -r $u/dg.str ] && {
                  grid_stem=`ls -ls $u/dg.str | awk '{print $NF}' | xargs basename | sed 's:\.str$::'`
                  q=p
                } || {
                  if [ "$(uname)" = "Darwin" ]; then
                    printf 'Cannot find dg.str file in %s\n' "$u"
                  else
                    /bin/echo -e "Cannot find dg.str file in $u"
                  fi
                  q=i
                }
              } || {
                if [ "$(uname)" = "Darwin" ]; then
                  printf 'Cannot find directory: %s' "$u"; q=i
                else
                  /bin/echo -e "Cannot find directory: $u"; q=i
                fi
              }
            }; break;;
    ( o|O )                                               # output directory:
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Specify the new grid storage directory: \c'; read u
            else
              /bin/echo -e "Specify the new grid storage directory: \c"; read u
            fi
            [ -n "$u" ] && {
              [ -d $u ] && {
                griddir="$u"; /bin/echo -e "The grid storage directory is now $griddir"; q=t
              } || {
                /bin/echo -e "No such directory: $u\nCreate it? (y/n) \c"; read uu
                case "$uu" in
                  ( y|Y ) s=$u; ss=$u
                          while true; do
                            case "$s" in
                              ( */* ) w="${s%/*}"
                                      [ -z "$w" ] && {
                                        if [ "$(uname)" = "Darwin" ]; then
                                          printf 'Wrong directory specification: no %s\n' "$s"
                                        else
                                          /bin/echo -e "Wrong directory specification: no $s"
                                        fi
                                        q=o; break 2
                                      }; s="$w"
                                      [ -d "$s" ] && break
                                      ss="$s $ss";;
                              (  *  ) break;;
                            esac
                          done
                          if [ "$(uname)" = "Darwin" ]; then
                            printf 'Creating %s\n' "$ss"
                          else
                            /bin/echo -e "Creating $ss"
                          fi
                          mkdir -p $ss && {
                            griddir="$u"; q=t
                            if [ "$(uname)" = "Darwin" ]; then
                              printf 'The grid storage directory is now %s\n' "$griddir"
                            else
                              /bin/echo -e "The grid storage directory is now $griddir"
                            fi
                          } || {
                            if [ "$(uname)" = "Darwin" ]; then
                              printf 'Unable to create %s\n' "$u"; q=o
                              printf 'The grid storage directory is still %s\n' "$griddir"
                            else
                              /bin/echo -e "Unable to create $u"; q=o
                              /bin/echo -e "The grid storage directory is still $griddir"
                            fi
                          };;
                  (  *  ) ;;
                esac
              }
            }; break;;
    ( q|Q )                                               # quit:
            break 2;;
    (  *  )
            if [ "$(uname)" = "Darwin" ]; then
              printf 'Illegal response.\n'
              printf 'Please use letters capitalized in the list or press ENTER for default\n'
            else
              /bin/echo -e 'Illegal response.'
              /bin/echo -e 'Please use letters capitalized in the list or press ENTER for default'
            fi
            continue;;
    esac;}
  }; done
}; done
stty sane

