#! /usr/bin/env ksh

# VERSION 15.05.2023
# based on Carre script VERSION : 20.07.2000 14:15

script=`basename $0`
stty erase ^H

Usage="
This is a script to call the \"carre2\" grid generator.
It makes standard links to the necessary files, calls \"carre2\", calls the grid convertor
\"traduit\", and moves the resulting grid to the standard place with a new name.

Usage:

$script  { <stem> | - }

The input files are:

<stem>.inp      the configuration file for carre2
<stem>.vrq      the equilibrium data in \"TdeV\" format
<stem>.str      the \"structures\" file
<stem>.fld      the product of R*Btor

If \"-\" is specified, then the input files are assumed to exist or to be created
via fcrr from dg output.

The script prints the output filename after successful grid conversion to B2.5 format.
The directories for the input files and for the grids can be specified in the
environmental variables CARRE2_INPUTDIR and CARRE2_GRIDDIR (default is the current directory).
If the variable CARRE2_STOREDIR is set, then all the input data (i.e., the control file, the
equilibrium file, and the structures file) are saved in a directory
\$CARRE2_STOREDIR/\$DEVICE/<grid number>. If this directory does not exist, it is created.

Error messages and tracing data from carre2 (\"Grid\") and traduit (\"Convert\") can be found in
the files carre.log and traduit.log, respectively.
"
[ -z "$1" ] && { /bin/echo -e "$Usage"; exit 4; }

SOLPSTOP=`determine_SOLPSTOP`
[ "$SOLPS_DEBUG" = '' ] || {
  export EXT_DEBUG=".debug"
}
CARRE2_PATH=$SOLPSTOP/modules/Carre2/builds/$HOST_NAME.$COMPILER$EXT_DEBUG
/bin/echo -e "CARRE2_PATH : $CARRE2_PATH"

[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
}

[ "$SOLPS_CENTRAL" = 'yes' ] && DEVICE=$DEVICE/$USER

# griddir=${CARRE2_GRIDDIR-$SOLPSTOP/src/Sonnet/output/ascii/${Model_Class-iter}}
# griddir=${CARRE2_GRIDDIR-$SOLPSTOP/src/Sonnet/output/ascii/${DEVICE-iter}}
export CARRE2_TOPDIR=$SOLPSTOP/modules/Carre2
dgdir=${CARRE2_GRIDDIR-$DG/device/${DEVICE-iter}}
griddir=${CARRE2_GRIDDIR-$SOLPSTOP/modules/Carre2/meshes/${DEVICE-iter}}
class=$DEVICE
indir=${CARRE2_STOREDIR-.}
stordir=$griddir
[ -n "$CARRE2_STOREDIR" ] && stordir="$CARRE2_STOREDIR/${DEVICE-iter}"
grid_stem=$class.carre
endings="dgo equ str trg"
/bin/echo -e "Store directory: $stordir"
/bin/echo -e "Grid directory: $griddir"
/bin/echo -e "Input directory: $indir\n"

[ "$1" = '-' ] && {
  [ -r $indir/dg.str ] && {
    /bin/echo -e "Standard linking - the input files are assumed to exist in \"$indir\""
    q=p
    qqs=c
    grid_stem=`ls -ls $indir/dg.str | awk '{print $NF}' | xargs basename | sed 's:\.str$::'`
    for ext in $endings; do
      [ -e $indir/dg.$ext ] && {
        filename=`lln $indir/dg.$ext`
        [ "$filename" != '' ] || {
          /bin/echo -e "File dg.$ext is not a symbolic link!"
          q=q
        }
      } || {
        /bin/echo -e "File dg.$ext is missing!"
        q=q
        qqs=q
      }
    done
    [ "$q" != 'q' ] || {
      [ "$qqs" = 'q' ] && {
        /bin/echo -e "Run the lns script first."
      } || {
        /bin/echo -e "Case storage step will fail."
        /bin/echo -e "Run the lns script first to assign a stem name to this case"
      }
    }
  } || {
    /bin/echo -e "Linking error - the input files were not found in \"$indir\""
    /bin/echo -e "Use (I)nput command to provide correct input directory"
    q=i
    qqs=c
  }
} || {
  u="$indir/$1"
  [ -r $u.vrq ] && [ -r $u.str ] && [ -r $u.fld ] & {
    ln -sf $u.vrq rzpsi.dat
    ln -sf $u.str structure.dat
    ln -sf $u.fld btor.dat
    ln -sf $u.inp carre.dat
    q=g
    qqs=s
  } || {
    /bin/echo -e "Files $u.vrq, $u.str, and $u.fld must be present!"
    exit 8
  }
}
while true
do {
  /bin/echo -e "Help, Prepare, Grid, Save, Convert, sTore, Next, Remove, Input, Output, Quit ? ($q)\c"
  while true; do {
    read u
    { case "${u:-$q}" in
    ( h|H )                                               # help:
            /bin/echo -e "
  Prepare (p)   apply fcrr to create Carre2 input files from DG output
  Grid    (g)   apply Carre2 to create a grid
  Save    (s)   save Carre2 output as the configuration file (carre.dat)
  Convert (c)   convert the Carre grid to the format suitable for B2 and DG
  Store   (t)   store the B2 grid in the storage directory.
                If CARRE2_STOREDIR is set, the Carre2 input files are also stored.
  Next    (n)   specify a new stem for the input files.
                If \"-\" is specified, then the Carre2 input files from the input directory
                are used. Otherwise, <stem>.vrq, <stem>.str, <stem>.fld, and <stem>.inp
                are used as the equilibrium, structures, toroidal field, and configuration
                files for Carre2.
                This must be specified each time when you change the input directory.
  Remove  (r)   remove the specified B2 grid(s) from the storage directory.
                The list consists of the grid numbers (with leading zeros) separated by
                a white space.
                The stored input data (if any) for the specified grids are also removed.
  Input   (i)   specify a new directory for the input files (input directory).
                If the specified directory does not exist and the CARRE2_STOREDIR is set,
                then the input directory is looked for in \$CARRE2_STOREDIR/\$DEVICE
                and \$CARRE2_STOREDIR
  Output  (o)   specify a new storage directory for the grids
  Quit    (q)   quit $script
"; break;;
    ( p|P )                                               # prepare input from DG output:
            [ "$DEVICE" = '' ] && { [ -L $indir/dg.trg ] && { \
                class=`lln $indir/dg.trg`
                class=${class%/*}
                class=${class##*/}
            } }
            [ "$class" = 'baserun' ] && {
                print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
                read u
                export DEVICE=$u
                class=$DEVICE
            }
            griddir=${CARRE2_GRIDDIR-$SOLPSTOP/modules/Carre2/meshes/${DEVICE-iter}}
            [ -n "$CARRE2_STOREDIR" ] && stordir="$CARRE2_STOREDIR/$class"

            /bin/echo -e "class = $class\ngriddir = $griddir\nindir = $indir\ngrid_stem = $grid_stem"
            [ -n $class ] && {
              [ -r $class.aux ] && ln -sf $class.aux dg.aux
            }
            rm -f selptx.inf carre.dat structure.dat rzpsi.dat btor.dat 2>/dev/null
            $CARRE2_PATH/fcrr.exe
            [ -s carre.dat ] && {
              q=g
            } || {
              printf 'Carre input was not produced. Check the DG model\n'
              q=q
            }
            break;;
    ( g|G )                                               # create the grid:
#            carre.exe; q=s; break;;
            $CARRE2_PATH/carre.exe 2>carre.log
            [ -s carre.out ] && {
              q=$qqs
            } || {
              /bin/echo -e "Carre output was not produced. Check the carre.log file"
              q=q
            }
            break;;
    ( s|S )                                               # save the control data:
            cp carre.out carre.dat;
            /bin/echo -e "Saved grid settings in carre.dat file"
            q=c; break;;
    ( c|C )                                               # convert:
            /bin/echo -e "carre.out\n4" | $CARRE2_PATH/traduit.exe 2>traduit.log; mv traduit.out traduit.sno ;
            /bin/echo -e "carre.out\n2" | $CARRE2_PATH/traduit.exe 2>traduit.log;
            q=t; break;;
    ( t|T )                                               # store the grid:
            [ -r traduit.out ] && {
                [ -d "$griddir" ] || {
                    /bin/echo -e "The directory \"$griddir\" does not exist. Create it (y/n)? \c"
                    read u; case "$u" in
                      ( y|Y )   /bin/echo -e mkdir "$griddir"
                      mkdir -p "$griddir" || break;;
                      (  *  )   /bin/echo -e break
                      break;;
                    esac
                }
                /bin/echo -e dir OK
                typeset -i n
                n=1
                set -- $griddir/$grid_stem.v[0-9][0-9][0-9].geo
                [ -f $1 ] && {
                    m=`ls $griddir/$grid_stem.v[0-9][0-9][0-9].geo | tail -1`
#                    m=`echo $griddir/$grid_stem.v[0-9][0-9][0-9].geo | awk '{print $NF}'`
                    m=${m#*/$grid_stem.v}
                    m=${m%.geo}
                    /bin/echo -e "Last grid number found is : $m"
                    n=`echo $m | sed -r -e 's:^0{1,}::'`
                    n=n+1
                    m=$n
                } || {
                    m=1
                }
                [ ${#m} -lt 2 ] && m=00$m || {
                    [ ${#m} -lt 3 ] && m=0$m
                }
                touch CARRE.HISTORY
                echo $user `date +%Y-%m-%d_%H:%M:%S` >> CARRE.HISTORY
                ls -ls dg.??? | cut -d ' ' -f 9- >> CARRE.HISTORY
                [ -d "$dgdir" ] || {
                    /bin/echo -e "The directory \"$dgdir\" does not exist. Create it (y/n)? \c"
                    read u; case "$u" in
                      ( y|Y )   /bin/echo -e mkdir "$dgdir"
                      mkdir -p "$dgdir" || break;;
                      (  *  )   /bin/echo -e break
                      break;;
                    esac
                }
                /bin/echo -e dir OK
                cp traduit.sno $dgdir/$grid_stem.v$m.sno && \
                  /bin/echo -e "The grid in DG format is stored as $dgdir/$grid_stem.v$m.sno" && \
                  /bin/echo -e "The grid in DG format is stored as $dgdir/$grid_stem.v$m.sno" >> CARRE.HISTORY
                mv -f traduit.sno $grid_stem.v$m.sno
                for ext in $endings; do
                  filename=`lln dg.$ext`
                  cp $filename $dgdir/`basename $filename`
                  /bin/echo -e "`basename $filename` copied to $dgdir" && \
                  /bin/echo -e "`basename $filename` copied to $dgdir" >> CARRE.HISTORY
                done
                modelname=`echo $filename | sed -e 's\trg\dg\' `
                cp $modelname $dgdir/`basename $modelname`
                /bin/echo -e "DG model `basename $modelname` copied to $dgdir" && \
                /bin/echo -e "DG model `basename $modelname` copied to $dgdir" >> CARRE.HISTORY
                cp traduit.out $griddir/$grid_stem.v$m.geo && \
                  /bin/echo -e "The grid in B2.5 format is stored as $griddir/$grid_stem.v$m.geo" && \
                  /bin/echo -e "The grid in B2.5 format is stored as $griddir/$grid_stem.v$m.geo" >> CARRE.HISTORY
                mv -f traduit.out $grid_stem.v$m.geo
                [ -x ctrans ] && {
                  ctrans -d ps.mono gmeta > $griddir/$grid_stem.v$m.ps && \
                  /bin/echo -e "You can view the grid in PostScript format as $griddir/$grid_stem.v$m.ps" && \
                  /bin/echo -e "You can view the grid in PostScript format as $griddir/$grid_stem.v$m.ps" >> CARRE.HISTORY
                }
                [ -n "$stordir" ] && {
                  [ -d "$stordir" ] || {
                    [ -a "$stordir" ] && {
                      /bin/echo -e "Name collision: there is already a file named $stordir"
                      /bin/echo -e "  ==> the directory cannot be created"
                    } || {
                      /bin/echo -e "The directory \"$stordir\" does not exist. Create it (y/n)? \c"
                      read u; case "$u" in
                        ( y|Y )   /bin/echo -e mkdir "$stordir"
                                  mkdir -p "$stordir";;
                        (  *  )   ;;
                      esac
                    }
                  }
                  [ -d "$stordir" ] && {
                    s="$stordir/$grid_stem.v$m"
                    u=y
                    [ -d "$s" ] && {
                      /bin/echo -e "The directory \"$s\" already exists. Use it (y/n)? \c"
                      read u; case "$u" in
                        ( y|Y )   ;;
                        (  *  )   u=;;
                      esac
                     }
                    [ -n "$u" ] && {
                      [ -d "$s" ] || mkdir -p "$s"
                      cp carre.dat structure.dat rzpsi.dat btor.dat carre.out "$s" && \
                              /bin/echo -e "carre.dat, structure.dat, rzpsi.dat, btor.dat, and carre.out copied to $s" && \
                              /bin/echo -e "carre.dat, structure.dat, rzpsi.dat, btor.dat, and carre.out copied to $s" >> CARRE.HISTORY
                    }
                  }
                }
                q=q; true
            } || { /bin/echo -e "No traduit.out. Convert the grid first."; q=c; }
                echo "=======================================================================================" >> CARRE.HISTORY
            break;;
    ( n|N )                                               # next job:
            /bin/echo -e "Input the new stem: \c"; read u
            [ -n "$u" ] && {
              [ "$u" = '-' ] && {
                [ -r $indir/rzpsi.dat ] && [ -r $indir/structure.dat ] && [ -r $indir/btor.dat ] && {
                  ln -sf $indir/rzpsi.dat $indir/structure.dat $indir/btor.dat . && q=g
                  [ -r $indir/carre.dat ] && {
                    ln -sf $indir/carre.dat .
                    true
                  } || {
                    rm -f carre.dat 2>/dev/null
                    true
                  }
                } || {
                  print -- "If you specify \"-\" as the stem, the following files must be present in the input directory:"
                  print -- "    rzpsi.dat   structure.dat   btor.dat"
                }
              } || {
                u="$indir/$u"
                [ -r $u.vrq ] && [ -r $u.str ] && [ -r $u.fld ] & {
                  ln -sf $u.vrq rzpsi.dat
                  ln -sf $u.str structure.dat
                  ln -sf $u.fld btor.dat
                  ln -sf $u.inp carre.dat
                  q=g
                  true
                } || {
                  /bin/echo -e "Files $u.vrq, $u.str, and $u.fld must be present in the input directory"
                }
              }
            }; break;;
    ( r|R )                                               # remove the grid(s):
            /bin/echo -e "Input the list of grid numbers to be REMOVED:"; read u
            [ -n "$u" ] && {
                uu=
                vv=
                ww=
                for n in $u; do
                  m=$n
                  [ ${#m} -lt 2 ] && m=00$m || {
                    [ ${#m} -lt 3 ] && m=0$m
                  }
                  uu="$uu $griddir/$grid_stem.v$m.geo"
                  vv="$vv $griddir/$grid_stem.v$m.ps"
                  ww="$ww $dgdir/$grid_stem.v$m.sno"
                done
                ls -l $uu $vv $ww
                /bin/echo -e "Do you wish to remove this grid(s)? (y/n): \c"; read u
                case "$u" in
                  ( y|Y ) rm -f $uu $vv $ww
                          for f in $uu; do {
                            n=${f#$griddir/$grid_stem.v}
                            n=${n%.geo}
                            [ -d "$stordir/$grid_stem.v$n" ] && rm -r "$stordir/$grid_stem.v$n"
                          }; done ;;
                  (  *  ) ;;
                esac
            }; break;;
    ( i|I )                                               # input files:
            /bin/echo -e "Specify the new input directory: \c"; read u
            [ -n "$u" ] && {
              indir="$u"; /bin/echo -e "$indir"
              [ -d $u ] && {
                indir="$u"
              } || {
                [ -n "$stordir" ] && {
                  indir="$stordir/$u"
                  [ -d "$indir" ] || {
                    indir="$CARRE2_STOREDIR/$u"
                    [ -d "$indir" ] || indir=
                  }
                }
              }
              [ -n "$indir" ] && {
                /bin/echo -e "The input directory is now `(cd $indir && pwd)`"; q=n; true
                [ -r $u/dg.str ] && {
                  grid_stem=`ls -ls $u/dg.str | awk '{print $NF}' | xargs basename | sed 's:\.str$::'`
                  q=p
                } || {
                  /bin/echo -e "Cannot find dg.str file in $u"
                  q=i
                }
              } || {
                /bin/echo -e "Cannot find directory: $u"; q=i
              }
            }; break;;
    ( o|O )                                               # output directory:
            /bin/echo -e "Specify the new grid storage directory: \c"; read u
            [ -n "$u" ] && {
              [ -d $u ] && {
                griddir="$u"; /bin/echo -e "The grid storage directory is now $griddir"; q=t
              } || {
                /bin/echo -e "No such directory: $u\nCreate it? (y/n) \c"; read uu
                case "$uu" in
                  ( y|Y ) s=$u; ss=$u
                          while true; do
                            case "$s" in
                              ( */* ) w="${s%/*}"
                                      [ -z "$w" ] && {
                                        /bin/echo -e "Wrong directory specification: no $s"
                                        q=o; break 2
                                      }; s="$w"
                                      [ -d "$s" ] && break
                                      ss="$s $ss";;
                              (  *  ) break;;
                            esac
                          done
                          /bin/echo -e "Creating $ss"
                          mkdir -p $ss && {
                            griddir="$u"; q=t
                            /bin/echo -e "The grid storage directory is now $griddir"
                          } || {
                            /bin/echo -e "Unable to create $u"; q=o
                            /bin/echo -e "The grid storage directory is still $griddir"
                          };;
                  (  *  ) ;;
                esac
              }
            }; break;;
    ( q|Q )                                               # quit:
            break 2;;
    (  *  )
            /bin/echo -e 'Illegal response.'
            /bin/echo -e 'Please use letters capitalized in the list or press ENTER for default'
            continue;;
    esac;}
  }; done
}; done
stty sane

