#! /bin/tcsh -f
set REG=0
if ("X$1" != "X") set REG=$1
echo "Region,srcb(atomic physics+d/dt),b2she+b2shi,srca(b2sihs),b2she0+b2shi0,b2she+b2shi+b2she0+b2shi0,srca+srcb-(b2she+b2shi+b2she0+b2shi0)"
tail -10000 run.log | \
awk 'BEGIN{F=2+'$REG'}\
     /Start tallies/{srca=0;srcb=0}\
     /nreg/{nrv=$2;nrx=$3;nry=$4}\
     /b2divue/{srca+=$F}\
     /b2divua/{srca+=$F}\
     /b2visa/{srca+=$F}\
     /b2joule/{srca+=$F}\
     /b2fraa/{srca+=$F}\
     /b2she /{b2she=$F}\
     /b2shi /{b2shi=$F}\
     /b2she0/{b2she0=$F}\
     /b2shi0/{b2shi0=$F}\
     /rqahereg/{for (i=F;i<=NF;i+=nrv+1) srcb+=-$i}\
     /rsahireg/{for (i=F;i<=NF;i+=nrv+1) srcb+=+$i}\
     /rrahireg/{for (i=F;i<=NF;i+=nrv+1) srcb+=+$i}\
     /rcxhireg/{for (i=F;i<=NF;i+=nrv+1) srcb+=+$i}\
     /End tallies/{print F-2,srcb,b2she+b2shi,srca,b2she0+b2shi0,b2she+b2shi+b2she0+b2shi0,srca+srcb-(b2she+b2shi+b2she0+b2shi0)}' | tail | ave.awk
