#! /bin/csh -f
# arg1: start column
# arg2: end column
# arg3: number of time steps to average
# arg4: scaling factor
# arg5: file containing additional plotmtv commands
if($3 == "") then
  set AVE=1
else
  set AVE=$3
endif
if($4 == "") then
  set SCALE=1
else
  set SCALE=$4
endif
sed -e 's/\(E+[0-9][0-9]\)-/\1 -/g' -e '$d' b2.diagnostics | \
  awk '\
    BEGIN{print "$ DATA=CONTOUR";\
          print "% nx =",'$2'-'$1'+1," xgrid=True"}\
    $1=="#_TIMEPOS"{START=NR;COUNT=0;TIME=0;NY=0;\
                    for (j='$1';j<='$2';j++) {print $j}}\
    NR>START&&/^[^#]/{TIME=TIME+$1;COUNT=COUNT+1}\
    COUNT=='$AVE'{NY=NY+1;TIMEVAL[NY]=TIME/COUNT;COUNT=0;TIME=0}\
    END{print "% ny =",NY," ygrid=True";\
        for (j=1;j<=NY;j++) {print TIMEVAL[j]};\
        print "% contfill = T  equalscale = F"}'
if($5 != "") then
  if( -f $5) cat $5
endif
sed -e 's/\(E+[0-9][0-9]\)-/\1 -/g' -e '$d' b2.diagnostics | \
  awk '\
    $1!~"#"{for (j='$1';j<='$2';j++) {VAL[j]=VAL[j]+$j*'$SCALE'};COUNT=COUNT+1}\
    $1!~"#"&&COUNT=='$AVE'{for (j='$1';j<='$2';j++) {printf "%s ",VAL[j]/COUNT;VAL[j]=0};printf "\n";COUNT=0}\
    END{print "$ END"}'
#cmin = 0.01  cmax = 20  
