#! /bin/csh -f
# arg1 is start column in b2.diagnostics
# arg2 is end column in b2.diagnostics
# if arg4 doesn't exist or it equals 0, 
# then
#   arg3 specifies the number of time-slices over which to average
# else
#   arg3 specifies a start time and arg4 an end time, and the data
#   between these two times is then averaged
# endif
# arg5, if it exists, specifies a scaling factor for the data
if($5 == "") then
  set SCALE=1
else
  set SCALE=$5
endif
if($4 == "" || $4 == "0") then
  if($3 == "") then
    set AVE=1
  else
    set AVE=$3
  endif
  sed -e 's/\(E+[0-9][0-9]\)-/\1 -/g' -e '$d' b2.diagnostics | \
    awk '\
      $1=="#_TIMEPOS"{for (j=2;j<=NF;j++) {POS[j]=$j;VAL[j]=0};COUNT=0;TIME=0}\
      $1!~"#"{for (j='$1';j<='$2';j++) {VAL[j]=VAL[j]+$j};TIME=TIME+$1;COUNT=COUNT+1}\
      COUNT=='$AVE'{for (j='$1';j<='$2';j++) {print TIME/COUNT,POS[j],VAL[j]/COUNT*'$SCALE';VAL[j]=0};printf "\n";COUNT=0;TIME=0}'
else
  set START_TIME=$3
  set END_TIME=$4
  sed '$d' b2.diagnostics | \
    awk '\
      $1=="#_TIMEPOS"{for (j=2;j<=NF;j++) {POS[j]=$j;VAL[j]=0};COUNT=0;TIME=0}\
      $1!~"#"&&$1>='$START_TIME'&&$1<='$END_TIME'{for (j='$1';j<='$2';j++) {VAL[j]=VAL[j]+$j};TIME=TIME+$1;COUNT=COUNT+1}\
      END{for (j='$1';j<='$2';j++) {print POS[j],VAL[j]/COUNT*'$SCALE';VAL[j]=0};printf "\n";COUNT=0;TIME=0}'
endif


#    $1!~"#"{for (j='$1';j<='$2';j++) {print $1,POS[j],$j};printf "\n"}'
