#! /usr/bin/env csh
###eval '(exit $?0)' && eval 'exec tcsh $0 ${1+"$@"}' && eval 'exec tcsh $0 $argv:q'
###! /bin/tcsh

if ("X$1X" == "X-rX") then
  set REL_FLAG=1
  shift
else
  set REL_FLAG=0
endif

set DIR=$PWD
set REL=""
set target=$1

loop:
  if(-e $DIR/$target) goto endloop
  if ("$DIR" == "/") then
    goto endloop
  endif
  set DIR=`dirname $DIR`
  set REL="../"$REL
  goto loop

endloop:
  if($REL_FLAG == 0) then
    echo $DIR/$target
  else
    echo $REL$target
  endif
