#! /usr/bin/env ksh

#  VERSION : 05.02.2005 17:55

. triang.conf

set -A f -- $TRIATRI

coord=${f[0]}
elem=${f[1]}

NAME=${0##*/}
Usage="$NAME :  conversion of TRIA mesh into DG template.   Usage:

  $NAME <stem>

Here <stem> is the common part of the TRIA mesh files (the mesh name).
The result is put in the file <stem>.tria in the directory where the DG templates
reside for the set value of the DEVICE variable, unless the CNVTRIOUT variable
is set, pointing to the desired directory
"

[ "$1" = -h ] && { print -- "$Usage"; exit; }

[ "$SOLPS_MPI" = ' ' ] && {
  toolchain=${HOST_NAME}.${COMPILER}.mpi
} || {
  toolchain=${HOST_NAME}.${COMPILER}
}  
[ "$SOLPS_DEBUG" = '' ] || {
  toolchain=$toolchain.debug
}

[ -z "$CNVTRIOUT" ] && { 
  CNVTRIOUT=$SOLPSTOP/modules/DivGeo/device/$DEVICE
}

[ -d $CNVTRIOUT/templates ] && CNVTRIOUT=$CNVTRIOUT/templates

[ -d "$CNVTRIOUT" ] || {
  print -- "The output directory not found: $CNVTRIOUT"
  print -- "$Usage"
  exit 2
}

[ -z "$CNVTRIEXE" ] && CNVTRIEXE=$SOLPSTOP/modules/DivGeo/convert/builds/$toolchain/cnvtria.exe

[ -x "$CNVTRIEXE" ] || {
  print -- "The executable not found: $CNVTRIEXE"
  print -- "$Usage"
  exit 2
}


stem=$1

[ -z "$stem" ] && {

  print -- "No TRIA mesh specified"
  print -- "$Usage"
  exit 4
}

[ -s "$stem.$coord" ] && [ -s "$stem.$elem" ] || {
  set -A f -- $B2USEXT
  coord=${f[0]}
  elem=${f[1]}
}

[ -s "$stem.$coord" ] && [ -s "$stem.$elem" ] || {
  print -- "No non-empty TRIA files found"
  print -- "$Usage"
  exit 8
}

cat "$stem.$coord" "$stem.$elem" | "$CNVTRIEXE" >  "$CNVTRIOUT"/"$stem.tria"
