#! /bin/tcsh -f
[ -e stra.dat ] || ln -s $SOLPSTOP/modules/B2.5/Database/stra.dat .
[ -e weis.dat ] || ln -s $SOLPSTOP/modules/B2.5/Database/weis.dat .
touch b2ag.prt b2fgmtry fort.30
sleep 1
touch b2ah.prt b2fpardf
sleep 1
touch b2ai.prt b2fstati
sleep 1
touch b2ar.prt b2frates
sleep 1
[ -e b2fstate ] && touch b2fstate || cp b2fstati b2fstate
