#! /bin/tcsh -f
[ -s stra.dat ] || ln -s $SOLPSTOP/modules/B2.5/Database/stra.dat .
[ -s weis.dat ] || ln -s $SOLPSTOP/modules/B2.5/Database/weis.dat .
[ -e b2ag.prt ] && touch b2ag.prt || ( [ -e ../baserun/b2ag.prt ] && touch ../baserun/b2ag.prt || touch b2ag.prt )
[ -s b2fgmtry ] && touch b2fgmtry || ( [ -s ../baserun/b2fgmtry ] && touch ../baserun/b2fgmtry || echo "No valid b2fgmtry file found" )
[ -s fort.30 ] && touch fort.30 || ( [ -s ../baserun/fort.30 ] && touch ../baserun/fort.30 || echo "No valid fort.30 file found" )
sleep 1
[ -e b2ah.prt ] && touch b2ah.prt || ( [ -e ../baserun/b2ah.prt ] && touch ../baserun/b2ah.prt || touch b2ah.prt )
[ -s b2fpardf ] && touch b2fpardf || ( [ -s ../baserun/b2fpardf ] && touch ../baserun/b2fpardf || echo "No valid b2fpardf file found" )
sleep 1
[ -e b2ai.prt ] && touch b2ai.prt || ( [ -e ../baserun/b2ai.prt ] && touch ../baserun/b2ai.prt || touch b2ai.prt )
[ -s b2fstati ] && touch b2fstati || ( [ -s ../baserun/b2fstati ] && touch ../baserun/b2fstati || echo "No valid b2fstati file found" )
sleep 1
[ -e b2ar.prt ] && touch b2ar.prt || ( [ -e ../baserun/b2ar.prt ] && touch ../baserun/b2ar.prt || touch b2ar.prt )
[ -s b2frates ] && touch b2frates || ( [ -s ../baserun/b2frates ] && touch ../baserun/b2frates || echo "No valid b2frates file found" )
sleep 1
[ -s b2fstate ] && touch b2fstate || ( [ -s b2fstati ] && cp b2fstati b2fstate || ( [ -s ../baserun/b2fstati ] || cp ../baserun/b2fstati b2fstate || echo "No valid b2fstati file found" ) )
