#! /bin/csh -f
set prefix=""
set suffix=""
set digits=1
restart:
if ("$1" == "-h") then
  echo 'The basic version counts from $1 to $2 in increments of $3.'
  echo 'The defaults are:'
  echo '  $1: 1'
  echo '  $2: 10'
  echo '  $3: 1'
  echo 'Additional options are:'
  echo ' -h      this help'
  echo ' -p STR  prefix the output with STR'
  echo ' -s STR  suffix the output with STR'
  echo ' -d INT  use at least INT digits to write the number, zero-filling'
  echo ' -n INT  same as -d option'
  echo 'A special case is when 4 arguments are supplied -- then $4 will be written instead of the usual output'
  exit
endif
if ("$1" == "-p") then
  set prefix=$2
  shift ; shift
  goto restart
endif
if ("$1" == "-s") then
  set suffix=$2
  shift ; shift
  goto restart
endif
if ("$1" == "-d" || "$1" == "-n") then
  set digits=$2
  shift ; shift
  goto restart
endif
if ($1 == "") then
  set start=1
else
  set start="$1"
endif
if ($2 == "") then
  set end=10
else
  set end=$2
endif
if ($3 == "") then
  set inc=1
else
  set inc=$3
endif
set i=$start
if ($inc > 0) then
  while ($i <= $end)
    if ($4 == "") then
      echo $prefix`printf "%0${digits}i\n" $i`$suffix
    else
      echo $4
    endif
    @ i=$i + $inc
  end
else if ($inc < 0) then
   while ($i >= $end)
    if ($4 == "") then
      echo $prefix`printf "%0${digits}i\n" $i`$suffix
    else
      echo $4
    endif
    @ i=$i + $inc
   end
else
  echo Increment factor = 0
endif
