#! /bin/csh -f
pipe_run.log | \
  egrep -a 'fnareg|nnreg' | \
  awk '/nnreg/{nfreg=$3} \
       /fnareg/{E=-($3);W=($6);core=-($10);pflxl=-($9); \
                pflxr=-($11);N=($13+$14+$15); \
                cnt++;print cnt,E,W,core,pflxl,pflxr,N}' | \
  plot x$1yplot6 -E W -core -pflxl -pflxr N iteration D0 `noquote_pwd 3`
