#! /bin/csh -f
pipe_run.log | \
  egrep -a 'fna.reg|nnreg' | \
  awk '/nnreg/{nxreg=$3;nyreg=$4} \
       /fnaxreg/{E=-($3);W=($6)} \
       /fnayreg/{core=-($4);pflxl=-($3); \
                 pflxr=-($5);N=($7+$8+$9); \
                 cnt++;print cnt,E,W,core,pflxl,pflxr,N}' | \
  plot x$1yplot6 -E W -core -pflxl -pflxr N iteration D0 `noquote_pwd 3`
