#! /bin/ksh
Name=`basename $0`
Usage="$Name: DG equilibrium refinement
Usage: $Name DG-old-file DG-new-file [Field-file]
       where DG-old-file and Field-file the input filenames,
       and DG-new-file is the output filename.
       If the Field-file is not specified, the default field.snn is used.

       The Field-file is only needed, when the DG-file is in old format!
"

[ $# -lt 2 ] && { echo "$Usage"; exit; }
F='field.snn'; [ -n "$3" ] && F=$3
[ -r $1 ] || { echo "File $1 is absent"; echo "$Usage"; exit; }
[ $# -eq 3 ] && { [ -r $F ] || { echo "File $F is absent"; echo "$Usage"; exit; } }
[ -e fort.2 ] && rm -f fort.2
[ -e $2 ] && { echo "The output file $2 exists. Overwrite it (y/n)?"
               read u; [ `echo "$u" | cut -c1 | tr Y y` != y ] && exit;
               ln -sf $2 fort.2
}
ln -sf $1 fort.1
[ $# -eq 3 ] && ln -sf $F fort.3

[ $# -eq 3 ] && { dg2dg $1 $2 $3 && { [ -L fort.2 ] && { rm -f fort.2; true; } || mv fort.2 $2 rm -f fort.[13]; } } || { dg2dg $1 $2 && { [ -L fort.2 ] && { rm -f fort.2; true; } || mv fort.2 $2 rm -f fort.1; } }
