#! /usr/bin/env ksh

#  VERSION : 16.01.96 18:34

Name=`basename $0`
Usage="$Name: DG-to-EFIT format conversion
Usage: $Name DG-file EFIT-file [Field-file]
       where DG-file and Field-file are the input filenames,
       and EFIT-file is the output filename.
       If the Field-file is not specified, the default field.snn is used.
       The Field-file is only needed, when the DG-file is in old format!
"

[ $# -lt 2 ] && { echo "$Usage"; exit; }
F='field.snn'; [ -n "$3" ] && F=$3

[ -r $1 ] || { echo "File $1 is absent"; echo "$Usage"; exit; }

[ -r $F ] && dg2ef $1 $2 $F || dg2ef $1 $2
