#! /bin/ksh

#  VERSION : 02.09.99 14:45

Name=`basename $0`
Usage="$Name: DG-to-EFIT format conversion
Usage: $Name DG-file EFIT-file [Field-file]
       where DG-file and Field-file are the input filenames,
       and EFIT-file is the output filename.
       If the Field-file is not specified, the default field.snn is used.

       The Field-file is only needed, when the DG-file is in old format!
"

[ $# -lt 2 ] && { echo "$Usage"; exit; }
F='field.snn'; [ -n "$3" ] && F=$3
[ $# -eq 3 ] && { [ -r $F ] || { echo "File $F is absent"; echo "$Usage"; exit; } }
[ -r $1 ] || { echo "File $1 is absent"; echo "$Usage"; exit; }
[ -e fort.2 ] && rm -f fort.2
[ -e $2 ] && { echo "The output file $2 exists. Overwrite it (y/n)?"
               read u; [ `echo "$u" | cut -c1 | tr Y y` != y ] && exit;
               ln -sf $2 fort.2
}
ln -sf $1 fort.1
ln -sf $F fort.3
$SOLPSTOP/src/DivGeo/dg/equtrn/$OBJECTCODE/dg2ef && { [ -L fort.2 ] && { rm -f fort.2; true; } || mv fort.2 $2
rm -f fort.[13]; }
