#! /bin/ksh

#  VERSION : 18.01.96 15:18

Name=`basename $0`
Usage="$Name: DG-to-CARRE format conversion
Usage: $Name DG-file CARRE-file \[Field-file\]
       where DG-file and Field-file are the input filenames,
       and CARRE-file is the output filename.
       If the Field-file is not specified, the default field.snn is used.

       The Field-file is only needed, when the DG-file is in old format!
"

echo `dirname $0`
[ $# -lt 2 ] && { echo "$Usage"; exit; }
F='field.snn'; [ -n "$3" ] && F=$3
[ -r $1 ] || { echo "File $1 is absent\n"; echo "$Usage"; exit; }
# [ -a fort.2 ] || rm -f fort.2
# ln -sf $1 fort.1
[ -r $F ] || { dg2vr $1 $2 } && { dg2vr $1 $2 $F }
#        && { [ -L fort.2 ] && { rm -f fort.2; true; } || mv fort.2 $2 ; rm -f fort.1; }
