#! /bin/ksh

#  VERSION : 02.09.99 14:44

Name=`basename $0`
Usage="$Name: DG-to-CARRE format conversion
Usage: $Name DG-file CARRE-file \[Field-file\]
       where DG-file and Field-file are the input filenames,
       and CARRE-file is the output filename.

"

[ $# -lt 2 ] && { echo "$Usage"; exit; }
[ -r $1 ] || { echo "File $1 is absent\n"; echo "$Usage"; exit; }
[ -a fort.2 ] || rm -f fort.2
ln -sf $1 fort.1
$SOLPSTOP/src/DivGeo/dg/equtrn/$OBJECTCODE/dg2vr && { [ -L fort.2 ] && { rm -f fort.2; true; } || mv fort.2 $2
rm -f fort.1; }
