#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "4":
    pipe_run.log | \
      egrep -a 'fna.reg|b2stbr_sna_reg|nnreg|Total profile-source na|tallies' | \
      awk 'BEGIN{ext=0} \
           /nnreg/{nvreg=$2;nxreg=$3;nyreg=$4} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnaxreg/{dev+=-(+$3+$(3+nxreg+1))+($6+$(6+nxreg+1))}\
           /fnayreg/{dev+=-(+$3+$(3+nyreg+1))-(+$4+$(4+nyreg+1))-(+$5+$(5+nyreg+1))+($7+$(7+nyreg+1))+($8+$(8+nyreg+1))+($9+$(9+nyreg+1))}\
           /b2stbr_sna_reg/{recyc=$2+$(2+nvreg+1)}\
           /End tallies by region/{cnt++;print cnt,dev,ext,recyc,dev-ext-recyc;dev=0}' | \
      plot x$1yplot4 N-S+E-W EXT RECYC ERR
    breaksw
  case "7":
    pipe_run.log | \
      egrep -a 'fna.reg|b2stbr_sna_reg|nnreg|Total profile-source na|tallies' | \
      awk 'BEGIN{ext=0} \
           /nnreg/{nvreg=$2;nxreg=$3;nyreg=$4} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnaxreg/{dev+=-(+$3+$(3+nxreg+1))+($6+$(6+nxreg+1))-($7+$(7+nxreg+1))+($10+$(10+nxreg+1))}\
           /fnayreg/{dev+=-(+$3+$(3+nyreg+1))-(+$4+$(4+nyreg+1))-(+$5+$(5+nyreg+1))+($7+$(7+nyreg+1))+($8+$(8+nyreg+1))+($9+$(9+nyreg+1))-($10+$(10+nyreg+1)+$11+$(11+nyreg+1)+$12+$(12+nyreg+1))+($13+$(13+nyreg+1)+$14+$(14+nyreg+1)+$15+$(15+nyreg+1))}\
           /b2stbr_sna_reg/{recyc=$2+$(2+nvreg+1)}\
           /End tallies by region/{cnt++;print cnt,dev,ext,recyc,dev-ext-recyc;dev=0}' | \
      plot x$1yplot4 N-S+E-W EXT RECYC ERR
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a 'fna.reg|b2stbr_sna_reg|nnreg|Total profile-source na|tallies' | \
      awk 'BEGIN{ext=0} \
           /nnreg/{nvreg=$2;nxreg=$3;nyreg=$4} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnaxreg/{dev+=-(+$3+$(3+nxreg+1))+($6+$(6+nxreg+1))-($7+$(7+nxreg+1))+($10+$(10+nxreg+1))}\
           /fnayreg/{dev+=-(+$3+$(3+nyreg+1))-(+$4+$(4+nyreg+1))-(+$5+$(5+nyreg+1))+($7+$(7+nyreg+1))+($8+$(8+nyreg+1))+($9+$(9+nyreg+1))-($10+$(10+nyreg+1)+$11+$(11+nyreg+1)+$12+$(12+nyreg+1))+($14+$(14+nyreg+1)+$15+$(15+nyreg+1)+$16+$(16+nyreg+1))}\
           /b2stbr_sna_reg/{recyc=$2+$(2+nvreg+1)}\
           /End tallies by region/{cnt++;print cnt,dev,ext,recyc,dev-ext-recyc;dev=0}' | \
      plot x$1yplot4 N-S+E-W EXT RECYC ERR
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
