#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep ^nnreg | head -1`
if (-e $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "4":
    pipe_run.log | \
      egrep -a 'fna.reg|b2stbr_sna_reg|nnreg|Total profile-source na|tallies' | \
      awk 'BEGIN{ext=0} \
           /nnreg/{nvreg=$2;nxreg=$3;nyreg=$4} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnayreg/{dev=-(+$4+$(4+nyreg+1))+($6+$(6+nyreg+1))}\
           /b2stbr_sna_reg/{recyc=$3+$(3+nvreg+1)}\
           /End tallies by region/{cnt++;print cnt,dev,ext,recyc,dev-ext-recyc}' | \
      plot x$1yplot4 N-S EXT RECYC ERR
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a 'fna.reg|b2stbr_sna_reg|nnreg|Total profile-source na|tallies' | \
      awk 'BEGIN{ext=0} \
           /nnreg/{nvreg=$2;nxreg=$3;nyreg=$4} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnayreg/{dev=-(+$4+$(4+nyreg+1))+($6+$(6+nyreg+1))-(+$11+$(11+nyreg+1))+($13+$(13+nyreg+1))}\
           /b2stbr_sna_reg/{recyc=$3+$(3+nvreg+1)+$7+$(7+nvreg+1)}\
           /End tallies by region/{cnt++;print cnt,dev,ext,recyc,dev-ext-recyc}' | \
      plot x$1yplot4 N-S EXT RECYC ERR
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
