#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "1":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na|Total first-flight-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /Total first-flight-source na: *0 /{ffl=$5} \
           /Total first-flight-source na: *1 /{ffl+=$5} \
           /fnareg/{dev=-($3+$(3+nfreg+1))+($4+$(4+nfreg+1))-($5+$(5+nfreg+1))+($6+$(6+nfreg+1));\
                 cnt++;print cnt,dev,ffl+0,ext+0}' | \
      plot x$1yplot3 N-S+E-W FF EXT
    breaksw
  case "2":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na|Total first-flight-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /Total first-flight-source na: *0 /{ffl=$5} \
           /Total first-flight-source na: *1 /{ffl+=$5} \
           /fnareg/{dev=-($3+$(3+nfreg+1))+($4+$(4+nfreg+1))-($6+$(6+nfreg+1))+($8+$(8+nfreg+1));\
                 cnt++;print cnt,dev,ffl+0,ext+0}' | \
      plot x$1yplot3 N-S+E-W FF EXT
    breaksw
  case "4":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na|Total first-flight-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /Total first-flight-source na: *0 /{ffl=$5} \
           /Total first-flight-source na: *1 /{ffl+=$5} \
           /fnareg/{dev=-($3+$(3+nfreg+1))+($6+$(6+nfreg+1))-($9+$(9+nfreg+1)+$10+$(10+nfreg+1)+$11+$(11+nfreg+1))+($13+$(13+nfreg+1)+$14+$(14+nfreg+1)+$15+$(15+nfreg+1));\
                 cnt++;print cnt,dev,ffl+0,ext+0}' | \
      plot x$1yplot3 N-S+E-W FF EXT
    breaksw
  case "5":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na|Total first-flight-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /Total first-flight-source na: *0 /{ffl=$5} \
           /Total first-flight-source na: *1 /{ffl+=$5} \
           /fnareg/{dev=-($3+$(3+nfreg+1))+($6+$(6+nfreg+1))-($10+$(10+nfreg+1)+$11+$(11+nfreg+1)+$12+$(12+nfreg+1))+$15+$(15+nfreg+1));\
                 cnt++;print cnt,dev,ffl+0,ext+0}' | \
      plot x$1yplot3 N-S+E-W FF EXT
    breaksw
  case "7":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na|Total first-flight-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /Total first-flight-source na: *0 /{ffl=$5} \
           /Total first-flight-source na: *1 /{ffl+=$5} \
           /fnareg/{dev=-($3+$(3+nfreg+1))+($6+$(6+nfreg+1))-($7+$(7+nfreg+1))+($10+$(10+nfreg+1))-($16+$(16+nfreg+1)+$17+$(17+nfreg+1)+$18+$(18+nfreg+1))+($20+$(20+nfreg+1)+$21+$(21+nfreg+1)+$22+$(22+nfreg+1))-($23+$(23+nfreg+1)+$24+$(24+nfreg+1)+$25+$(25+nfreg+1))+($26+$(26+nfreg+1)+$27+$(27+nfreg+1)+$28+$(28+nfreg+1));\
                 cnt++;print cnt,dev,ffl+0,ext+0}' | \
      plot x$1yplot3 N-S+E-W FF EXT
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na|Total first-flight-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /Total first-flight-source na: *0 /{ffl=$5} \
           /Total first-flight-source na: *1 /{ffl+=$5} \
           /fnareg/{dev=-($3+$(3+nfreg+1))+($6+$(6+nfreg+1))-($7+$(7+nfreg+1))+($10+$(10+nfreg+1))-($(nfreg-11)+$(nfreg-11+nfreg+1)+$(nfreg-10)+$(nfreg-10+nfreg+1)+$(nfreg-9)+$(nfreg-9+nfreg+1))+($(nfreg-7)+$(nfreg-7+nfreg+1)+$(nfreg-6)+$(nfreg-6+nfreg+1)+$(nfreg-5)+$(nfreg-5+nfreg+1))-($(nfreg-4)+$(nfreg-4+nfreg+1)+$(nfreg-3)+$(nfreg-3+nfreg+1)+$(nfreg-2)+$(nfreg-2+nfreg+1))+($nfreg+$(nfreg+nfreg+1)+$(nfreg+1)+$(nfreg+1+nfreg+1)+$(nfreg+2)+$(nfreg+2+nfreg+1));\
                 cnt++;print cnt,dev,ffl+0,ext+0}' | \
      plot x$1yplot3 N-S+E-W FF EXT
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
