#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | head -100000 | grep -a nreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "1":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnareg/{dev=-(+$5+$(5+nfreg+1))+($6+$(6+nfreg+1));\
                 print NR/2,dev,ext+0}' | \
      x$1yplot2 N-S EXT
    breaksw
  case "2":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnareg/{dev=-(+$6+$(6+nfreg+1))+($7+$(7+nfreg+1));\
                 print NR/2,dev,ext+0}' | \
      x$1yplot2 N-S EXT
    breaksw
  case "4":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnareg/{dev=-(+$10+$(10+nfreg+1))+($12+$(12+nfreg+1));\
                 print NR/2,dev,ext+0}' | \
      x$1yplot2 N-S EXT
    breaksw
  case "5":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnareg/{dev=-(+$11+$(11+nfreg+1))+($13+$(13+nfreg+1));\
                 print NR/2,dev,ext+0}' | \
      x$1yplot2 N-S EXT
    breaksw
  case "7":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnareg/{dev=-(+$17+$(17+nfreg+1))+($19+$(19+nfreg+1));\
                 print NR/2,dev,ext+0}' | \
      x$1yplot2 N-S EXT
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a 'fnareg|nnreg|Total profile-source na' | \
      awk '/nnreg/{nfreg=$3} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnareg/{dev=-(+$(nfreg-10)+$(nfreg-10+nfreg+1))+($(nfreg-8)+$(nfreg-8+nfreg+1))-(+$(nfreg-3)+$(nfreg-3+nfreg+1))+($(nfreg-1)+$(nfreg-1+nfreg+1));\
                 print NR/2,dev,ext+0}' | \
      x$1yplot2 N-S EXT
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
