#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | head -100000 | grep -a nreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "4":
    pipe_run.log | \
      egrep -a 'fna.reg|nnreg' | \
      awk 'BEGIN{iss=0;ise=1;nxreg=4+1;nyreg=7+1} \
           /nnreg/{nxreg=$3+1;nyreg=$4+1} \
           /fnaxreg/{E=0;W=0;for (i=iss;i<=ise;i++) {E+=-$(2+nxreg*i+1);W+=$(5+nxreg*i+1)}} \
           /fnayreg/{core=0;pflxl=0;pflxr=0;N=0; \
                 for (i=iss;i<=ise;i++) \
                   {core+=-($(3+nyreg*i+1));pflxl+=-($(2+nyreg*i+1));pflxr+=-($(4+nyreg*i+1)); \
                    N+=($(6+nyreg*i+1)+$(7+nyreg*i+1)+$(8+nyreg*i+1))}; \
                 cnt++;print cnt,E,W,core,pflxl,pflxr,N}' | \
      plot x$1yplot6 -E W -core -pflxl -pflxr N iteration D0+D1+ `noquote_pwd 3`
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a 'fna.reg|nnreg' | \
      awk 'BEGIN{iss=0;ise=1;nxreg=4+1;nyreg=7+1} \
           /nnreg/{nxreg=$3+1;nyreg=$4+1} \
           /fnaxreg/{E1=0;W1=0;E2=0;W2=0;for (i=iss;i<=ise;i++) {E1+=-$(2+nxreg*i+1);W1+=$(5+nxreg*i+1);E2+=-$(6+nxreg*i+1);W1+=$(9+nxreg*i+1)}} \
           /fnayreg/{core=0;pflx=0;N=0; \
                 for (i=iss;i<=ise;i++) \
                   {core+=-($(3+nyreg*i+1))-($(10+nyreg*i+1));pflx+=-($(2+nyreg*i+1))-($(4+nyreg*i+1))-($(9+nyreg*i+1))-($(11+nyreg*i+1)); \
                    N+=($(6+nyreg*i+1)+$(7+nyreg*i+1)+$(8+nyreg*i+1))+($(13+nyreg*i+1)+$(14+nyreg*i+1)+$(15+nyreg*i+1))}; \
                 cnt++;print cnt,E1,W1,E2,W2,core,pflx,N}' | \
      plot x$1yplot7 -E1 W2 -E2 W2 -core -pflx N iteration D0+D1+ `noquote_pwd 3`
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
