#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG=4
@ NREGP = $NREG + 1
set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-s $solps_fluids) then
  setenv SOLPS_FLUIDS `cat $solps_fluids`
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on $solps_fluids)"
else
  setenv SOLPS_FLUIDS "`get_solps_fluids`"
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on log file)"
endif
set nplts=`echo $SOLPS_FLUIDS | wc -w`
pipe_run.log | \
  egrep -a '^nareg '\|'^volreg ' | \
  awk '/nareg/{j=0;for (i=2;i<=NF;i+='$NREGP') {j++;na[j]=$i}}\
       /volreg/{for (i=1;i<=j;i++) printf "%s ",na[i]/$2;printf "\n"}' | \
  nl | \
  plot x"$1"yplot$nplts $SOLPS_FLUIDS iter "density" $PWD
