#! /bin/tcsh -f
# author: David Coster (2015-06-25)
# modified by Xavier Bonnin (2021-10-07)
#
# return a value of SOLPSTOP by taking the first of
#  1. returning the value of the environment variable $SOLPSTOP_FORCE (if it points to a valid directory)
#  2. climbing the tree looking for SOLPSTOP and returning the contents
#  3. returning the value of the environment variable $SOLPSTOP
#  4. attempting to strip off the elements from $PWD
#

setenv S ""
set solpstop=`climb_and_look_for SOLPSTOP`

if ($?SOLPSTOP_FORCE) then
  [ -d $SOLPSTOP_FORCE ] && setenv S $SOLPSTOP_FORCE
endif
if ("X${S}X" == "XX") then
  [ -s $solpstop ] && setenv S `cat $solpstop`
endif
if ("X${S}X" == "XX") then
   if ($?SOLPSTOP) then
     [ -d $SOLPSTOP ] && setenv S $SOLPSTOP
   endif
endif
if ("X${S}X" == "XX") then
   setenv S `echo $PWD | sed 's:/runs/.*::'`
endif

echo $S

unsetenv S
