#! /usr/bin/ksh
#  VERSION : 03.02.99 21:02

c=`basename \`pwd\``
[ "$c" = divgeo ] && { class=${DEVICE:-iter}; cd class/$class; } || class=$c

export DGSONNETMASK="$SonnetTopDirectory/output/ascii/$class/*"
export DG_MESH_MASK="$SonnetTopDirectory/output/ascii/$class/*"
export DG_EXPORT_MESH_MASK="$DG_MESH_MASK"

[ "$OBJECTCODE" = linux.Fujitsu ] && export LD_LIBRARY_PATH='/usr/lib/:/usr/local/lib:/usr/X11R6/lib'

[ -d templates ] && {
  export DG_EXPORT_TEMPLATE_MASK="$PWD/templates/*.itp"
  export DG_TEMPLATE_MASK="$PWD/templates/*"
}

[ -d equilibria ] && export DG_EQUIL_MASK="$PWD/equilibria/*.equ"

[ -d "${SOLPSTOP}/src/DivGeo/topologies" ] && export DG_IMPORT_TOPOLOGY_MASK="${SOLPSTOP}/src/DivGeo/topologies/*" 

unset vers cfg
[ -s ~/.dg_version ] && vers=`cat ~/.dg_version`
[ -s "${SOLPSTOP}/.dg_version" ] && vers=`cat "${SOLPSTOP}/.dg_version"`
[ -s ./.dg_version ] && vers=`cat ./.dg_version`
while true; do {
  { case $1 in
    ( -- ) shift; break;;
    ( -v ) vers="$2"; shift 2;;
    (  * ) break;; 
  esac; }
}; done
[ -n "$vers" ] && {
  print -u2 "dg version: $vers"
  vers=".$vers"
  [ -s "${SOLPSTOP}/src/DivGeo/dg.dgc${vers}" ] && {
    cfg="-cfg ${SOLPSTOP}/src/DivGeo/dg.dgc${vers}"
  } || {
    print -u2 "No configuration file available for this version"
    cfg="-nocfg"
  } 
}

$SOLPSTOP/bin/$OBJECTCODE/dg${vers} $cfg $* &
