#! /usr/bin/env ksh
#  VERSION : 03.02.99 21:02

[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
}
[ "$SOLPS_CENTRAL" = 'yes' ] && DEVICE=$DEVICE/$USER

export DGSONNETMASK="$DG/device/$DEVICE/*.sno"
export DG_MESH_MASK="$DG/device/$DEVICE/*.sno"
export DG_EXPORT_MESH_MASK="$DG_MESH_MASK"

[ "$OBJECTCODE" = linux.Fujitsu ] && export LD_LIBRARY_PATH='/usr/lib/:/usr/local/lib:/usr/X11R6/lib'

[ -d templates ] && {
  export DG_EXPORT_TEMPLATE_MASK="$PWD/templates/*.itp"
  export DG_TEMPLATE_MASK="$PWD/templates/*"
}

[ -d equilibria ] && export DG_EQUIL_MASK="$PWD/*.equ"

[ -d "${SOLPSTOP}/modules/DivGeo/topologies" ] && export DG_IMPORT_TOPOLOGY_MASK="${SOLPSTOP}/modules/DivGeo/topologies/*" 

unset vers cfg
[ -s ~/.dg_version ] && vers=`cat ~/.dg_version`
[ -s "${SOLPSTOP}/.dg_version" ] && vers=`cat "${SOLPSTOP}/.dg_version"`
[ -s ./.dg_version ] && vers=`cat ./.dg_version`
while true; do {
  { case $1 in
    ( -- ) shift; break;;
    ( -v ) vers="$2"; shift 2;;
    (  * ) break;; 
  esac; }
}; done
[ -n "$vers" ] && {
  print -u2 "dg version: $vers"
  vers=".$vers"
  [ -s "${SOLPSTOP}/modules/DivGeo/dg.dgc${vers}" ] && {
    cfg="-cfg ${SOLPSTOP}/modules/DivGeo/dg.dgc${vers}"
  } || {
    print -u2 "No configuration file available for this version"
    cfg="-nocfg"
  } 
}

# Copy links to help files/config files to dir. where dg is called
[ $PWD != "$DG" ] && {
ln -sf $DG/dg.dgh ./dg.dgh
ln -sf $DG/dg.dgc ./dg.dgc
}

# Execute the program
dg.exe${vers} $cfg $* &
wait

# Remove links again (if not in DG directory)
[ $PWD != $DG ] && {
rm -f dg.dgh dg.dgc
}
