#! /bin/ksh

#  VERSION : 02.09.99 14:44

Name=`basename $0`
Usage="$Name: EFIT-to-DG format conversion
Usage: $Name EFIT-file DG-file
       where DG-file is the output filename,
       and EFIT-file is the input filename.
"

[ $# -lt 2 ] && { echo "$Usage"; exit; }
[ -r $1 ] || { echo "File $1 is absent\n"; echo "$Usage"; exit; }
ef2dg $1 $2 $3
