#! /bin/csh -f
if ($?LAST10) then
  set FILE=b2.log.last10
else
  set FILE=b2.log
endif
if (-x $SOLPSTOP/bin/$OBJECTCODE/zcat) then
    set ZCAT=$SOLPSTOP/bin/$OBJECTCODE/zcat
else if (-x $SOLPSMASTER/@sys/bin/zcat) then
    set ZCAT=$SOLPSMASTER/@sys/bin/zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT -f $FILE | \
  egrep -A1 'ITER.*TIME|TOTALS, EI,EE,NI' | \
  egrep 'E\+|TIME' | \
  awk 'NF==5{EI=$3;EE=$4;NI=$5}/TIME/{print $4,EI,EE}' | \
  xyplot2 EI EE TIME "(W)" $PWD
