#! /bin/ksh

# version : 19.08.2004 17:14


# Check whether a special version of b2eirene is required

E=${0##*/}
eirobj="$SOLPSTOP/src/Eirene/$OBJECTCODE/$E"
[ -s B2E.version ] && {
  set -A u -- `cat B2E.version`
  eirobj="${SOLPSTOP%/*}/$u/src/Eirene/$OBJECTCODE/$E"
}

trail=
[ -s "$1" ] && { 
  ln -sf "$1" fort.1
  trail="< $1"
  shift
}
print $eirobj $* $trail
eval "$eirobj $* $trail"
