#! /bin/csh
if ( "$1" == "") then
  set file=""
else if (-e $1 || -e $1.gz) then
  set file=$1
else if (-e $SOLPSTOP/src/Sonnet/output/ascii/$DEVICE/$1 || -e $SOLPSTOP/src/Sonnet/output/ascii/$DEVICE/$1.gz) then
  set file=$SOLPSTOP/src/Sonnet/output/ascii/$DEVICE/$1
else
  echo Cannot find $1
  exit
endif

zcat -f $file | \
  sed -e '1,/====/d' -e '/-----/d' | \
  paste - - - | \
  tr '(),:' '    ' | \
  awk '{printf "%s %s\n%s %s\n\n%s %s\n%s %s\n\n%s %s\n%s %s\n\n%s %s\n%s %s\n\n",$6,$7,$8,$9,$6,$7,$16,$17,$8,$9,$18,$19,$16,$17,$18,$19}'
