#! /bin/tcsh -f
set nreg=`climb_and_look_for NREG`
if (-e $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
endif
if (! $?NREG) set NREG = 4
set nnreg=`pipe_run.log | head -10000 | grep -a nreg | head -1`
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG
    exit
  endif
endif
switch ($NREG)
  case "4":
    pipe_run.log | \
      egrep -a '^fht[xy]reg |tallies|nnreg' | \
      awk '/Start tallies by region/{W=0;w=0;e=0;E=0;core=0;sep=0;mcw=0;pfw=0}/fhtxreg/{W+=-$3;w+=-$4;e+=$5;E+=$6}/fhtyreg/{core+=$4;sep+=$6;mcw+=$8;pfw+=-$3-$5+$7+$9}/End tallies by region/{print W,w,e,E,core,sep,mcw,pfw}' | \
      nl | \
      plot x"$1"yplot8 -W -w e E core sep mcw pfw iterations W $PWD
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a '^fht[xy]reg |tallies|nnreg'| \
      awk '/Start tallies by region/{LI=0;li=0;ui=0;UI=0;UO=0;uo=0;lo=0;LO=0;coreI=0;coreO=0;sepI=0;sepO=0;mcwI=0;mcwO=0;pfwL=0;pfwU=0}/fhtxreg/{LI+=-$3;li+=-$4;ui+=$5;UI+=$6;UO+=-$7;uo+=-$8;lo+=$9;LO+=$10}/fhtyreg/{coreI+=$4;coreO+=$11;sepI+=$6;sepO+=$13;mcwI+=$8;mcwO+=$15;pfwL+=-$3-$12+$7+$16;pfwU+=-$5-$10+$9+$14}/End tallies by region/{print LI,li,ui,UI,UO,uo,lo,LO,coreI,coreO,coreI+coreO,sepI,sepO,sepI+sepO,mcwI,mcwO,mcwI+mcwO,pfwL,pfwU,pfwL+pfwU}' | \
      nl | \
      plot x"$1"yplot20 -LI -li ui UI -UO -uo lo LO coreI coreO core sepI sepO sep mcwI mcwO mcw pfwL pfwU pfw iterations W__UNTESTED $PWD
    breaksw
  case "5":
    pipe_run.log | \
      egrep -a '^fht[xy]reg |tallies|nnreg'| \
      awk '/Start tallies by region/{W=0;w=0;e=0;E=0;core=0;sep=0;island=0;centre=0;pfw=0}/fhtxreg/{W+=-$3;w+=-$4;e+=$5;E+=$6}/fhtyreg/{core+=$4;sep+=$6;island+=$10;centre+=$8;pfw+=-$3-$5+$7+$9}/End tallies by region/{print W,w,e,E,core,sep,island,centre,pfw}' | \
      nl | \
      plot x"$1"yplot9 -W -w e E core sep island center pfw iterations W__UNTESTED $PWD
    breaksw
  case "2":
    pipe_run.log | \
      egrep -a '^fht[xy]reg |tallies|nnreg'| \
      awk '/Start tallies by region/{W=0;w=0;e=0;E=0;core=0;sep=0;mcw=0;pfw=0}/fhtxreg/{W+=-$3;E+=$4}/fhtyreg/{core+=$3;sep+=$4;mcw+=$5}/End tallies by region/{print W,E,core,sep,mcw}' | \
      nl | \
      plot x"$1"yplot5 -W E core sep mcw iterations W__UNTESTED $PWD
    breaksw
  case "1":
    pipe_run.log | \
      egrep -a '^fht[xy]reg |nnreg'| \
      paste - - - | \
      awk '{print NR,$7,$8,$11,$12}' | \
      plot x"$1"yplot4 W E S N iterations W__UNTESTED $PWD
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
