#! /bin/csh -f
pipe_run.log | \
  egrep -a 'r..[hn].reg|fh..reg|^pot|nnreg|End tallies|Total profile-source Power' | \
  awk '/nnreg/{nreg=$2+1;nxreg=$3+1;nyreg=$4+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.6021766028e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=3;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=3;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=3;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=3;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=3;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=3;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhiyreg/{S=-$4;N=$6} \
       /fheyreg/{S+=-$4;N+=$6} \
       /fhpyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+2);N+=$(i+4)}} \
       /fhmyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+2);N+=$(i+4)}} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,N,S,N+S+rsa+rra+rqa+rcx-rsap+rrap,ext+0} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap N S N+S N+S+rsa+rra+rqa+rcx-rsap+rrap EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap N S N+S+rsa+rra+rqa+rcx-rsap+rrap EXT"}' | \
  plot x$1yplot10 rsa rra rqa rcx rsap rrap N S N+S+rsa+rra+rqa+rcx-rsap+rrap EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
