#! /bin/csh -f
set x=$1
if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif
if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | head -100000 | grep -a nreg | head -1`
if (-e $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "4":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh.reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nfreg=$3+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhireg/{W=-$3;E=$6;S=-$9-$10-$11;N=$13+$14+$15} \
       /fhereg/{W+=-$3;E+=$6;S+=-$9-$10-$11;N+=$13+$14+$15} \
       /fhpreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+4);S+=-$(i+7)-$(i+8)-$(i+9);N+=$(i+11)+$(i+12)+$(i+13)}} \
       /fhmreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+4);S+=-$(i+7)-$(i+8)-$(i+9);N+=$(i+11)+$(i+12)+$(i+13)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,E,N,W,S,srcr,srcm,srce,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "8":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh.reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nfreg=$3+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhireg/{LI=-$3;UI=$6;UO=-$7;LO=$10;coreI=-$(nfreg-12);coreO=-$(nfreg-5);NI=$(nfreg-9)+$(nfreg-8)+$(nfreg-7);NO=$(nfreg-2)+$(nfreg-1)+$nfreg;pfrL=-$(nfreg-13)-$(nfreg-4);pfrU=-$(nfreg-11)-$(nfreg-6)} \
       /fhereg/{LI+=-$3;UI+=$6;UO+=-$7;LO+=$10;coreI+=-$(nfreg-12);coreO+=-$(nfreg-5);NI+=$(nfreg-9)+$(nfreg-8)+$(nfreg-7);NO+=$(nfreg-2)+$(nfreg-1)+$nfreg;pfrL+=-$(nfreg-13)-$(nfreg-4);pfrU+=-$(nfreg-11)-$(nfreg-6)} \
       /fhpreg/{for (i=2;i<=NF;i+=nfreg) {LI+=-$(i+1);UI+=$(i+4);UO+=-$(i+5);LO+=-$(i+8);coreI+=-$(i+nfreg-14);coreO+=-$(i+nfreg-7);NI+=$(i+nfreg-11)+$(i+nfreg-10)+$(i+nfreg-9);NO+=$(i+nfreg-4)+$(i+nfreg-3)+$(i+nfreg-2);pfrL+=-$(i+nfreg-15)-$(i+nfreg-6);pfrU+=-$(i+nfreg-13)-$(i+nfreg-8)}} \
       /fhmreg/{for (i=2;i<=NF;i+=nfreg) {LI+=-$(i+1);UI+=$(i+4);UO+=-$(i+5);LO+=-$(i+8);coreI+=-$(i+nfreg-14);coreO+=-$(i+nfreg-7);NI+=$(i+nfreg-11)+$(i+nfreg-10)+$(i+nfreg-9);NO+=$(i+nfreg-4)+$(i+nfreg-3)+$(i+nfreg-2);pfrL+=-$(i+nfreg-15)-$(i+nfreg-6);pfrU+=-$(i+nfreg-13)-$(i+nfreg-8)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap LI NI UI pfrU UO NO LO pfrL srcr srcm srce LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap LI NI UI pfrU UO NO LO pfrL srcr srcm srce LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,LI,NI,UI,pfrU,UO,NO,LO,pfrL,srcr,srcm,srce,LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot19 rsa rra rqa rcx rsap rrap LI NI UI pfrU UO NO LO pfrL srcr srcm srce LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "7":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh.reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nfreg=$3+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhireg/{W=-$3;E1=$6;E2=-$7;E3=$10;core=-$17;N=$20+$21+$22+$26+$27+$28;pfr=-$16-$18-$23-$24-$25} \
       /fhereg/{w+=-$3;E1+=$6;E2+=-$7;E3+=$10;core+=-$17;N+=$20+$21+$22+$26+$27+$28;pfr+=-$16-$18-$23-$24-$25} \
       /fhpreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E1+=$(i+4);E2+=-$(i+5);E3+=-$(i+8);core+=-$(i+15);N+=$(i+18)+$(i+19)+$(i+20)+$(i+24)+$(i+25)+$(i+26);pfr+=-$(i+14)-$(i+16)-$(i+21)-$(i+22)-$(i+23)}} \
       /fhmreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E1+=$(i+4);E2+=-$(i+5);E3+=-$(i+8);core+=-$(i+15);N+=$(i+18)+$(i+19)+$(i+20)+$(i+24)+$(i+25)+$(i+26);pfr+=-$(i+14)-$(i+16)-$(i+21)-$(i+22)-$(i+23)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap W N E1 E2 E3 pfr srcr srcm srce W+N+E1+E2+E3+pfr+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap W N E1 E2 E3 pfr srcr srcm srce W+N+E1+E2+E3+pfr+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,W,N,E1,E2,E3,pfr,srcr,srcm,srce,W+N+E1+E2+E3+pfr+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot17 rsa rra rqa rcx rsap rrap W N E1 E2 E3 pfr srcr srcm srce W+N+E1+E2+E3+pfr+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "5":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh.reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nfreg=$3+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhireg/{W=-$3;E=$6;S=-$10-$11-$12;N=$15} \
       /fhereg/{W+=-$3;E+=$6;S+=-$10-$11-$12;N+=$15} \
       /fhpreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+4);S+=-$(i+8)-$(i+9)-$(i+10);N+=$(i+13)}} \
       /fhmreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+4);S+=-$(i+8)-$(i+9)-$(i+10);N+=$(i+13)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,srcr,srcm,srce,E,N,W,S,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap srcr srcm srce E N W S E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "2":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh.reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nfreg=$3+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhireg/{W=-$3;E=$4;S=-$6;N=$8} \
       /fhereg/{W+=-$3;E+=$4;S+=-$6;N+=$8} \
       /fhpreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+2);S+=-$(i+4);N+=$(i+6)}} \
       /fhmreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+2);S+=-$(i+4);N+=$(i+6)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,E,N,W,S,srcr,srcm,srce,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "1":
    pipe_run.log | \
     egrep -a 'r..[hn].reg|fh.reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
     awk '/nnreg/{nreg=$2+1;nfreg=$3+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhireg/{W=-$3;E=$4;S=-$5;N=$6} \
       /fhereg/{W+=-$3;E+=$4;S+=-$5;N+=$6} \
       /fhpreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+2);S+=-$(i+3);N+=$(i+4)}} \
       /fhmreg/{for (i=2;i<=NF;i+=nfreg) {W+=-$(i+1);E+=$(i+2);S+=-$(i+3);N+=$(i+4)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,E,N,W,S,srcr,srcm,srce,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
