#! /bin/csh -f
set x=$1
if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif
if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | head -100000 | grep -a nreg | head -1`
if (-e $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "4":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh..reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nxreg=$3+1;nyreg=$4+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhixreg/{W=-$3;E=$6} \
       /fhiyreg/{S=-$3-$4-$5;N=$7+$8+$9} \
       /fhexreg/{W+=-$3;E+=$6} \
       /fheyreg/{S+=-$3-$4-$5;N+=$7+$8+$9} \
       /fhpxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+4)}} \
       /fhpyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1)-$(i+2)-$(i+3);N+=$(i+5)+$(i+6)+$(i+7)}} \
       /fhmxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+4)}} \
       /fhmyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1)-$(i+2)-$(i+3);N+=$(i+5)+$(i+6)+$(i+7)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,E,N,W,S,srcr,srcm,srce,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "8":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh..reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nxreg=$3+1;nyreg=$4+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhixreg/{LI=-$3;UI=$6;UO=-$7;LO=$10} \
       /fhiyreg/{coreI=-$4;coreO=-$11;NI=$7+$8+$9;NO=$14+$15+$16;pfrL=-$3-$12;pfrU=-$5-$10} \
       /fhexreg/{LI+=-$3;UI+=$6;UO+=-$7;LO+=$10} \
       /fheyreg/{coreI+=-$4;coreO+=-$11;NI+=$7+$8+$9;NO+=$14+$15+$16;pfrL+=-$3-$12;pfrU+=-$5-$10} \
       /fhpxreg/{for (i=2;i<=NF;i+=nxreg) {LI+=-$(i+1);UI+=$(i+4);UO+=-$(i+5);LO+=-$(i+8)}} \
       /fhpyreg/{for (i=2;i<=NF;i+=nyreg) {coreI+=-$(i+2);coreO+=-$(i+9);NI+=$(i+5)+$(i+6)+$(i+7);NO+=$(i+12)+$(i+13)+$(i+14);pfrL+=-$(i+1)-$(i+10);pfrU+=-$(i+3)-$(i+8)}} \
       /fhmxreg/{for (i=2;i<=NF;i+=nxreg) {LI+=-$(i+1);UI+=$(i+4);UO+=-$(i+5);LO+=-$(i+8)}} \
       /fhmyreg/{for (i=2;i<=NF;i+=nyreg) {coreI+=-$(i+2);coreO+=-$(i+9);NI+=$(i+5)+$(i+6)+$(i+7);NO+=$(i+12)+$(i+13)+$(i+14);pfrL+=-$(i+1)-$(i+10);pfrU+=-$(i+3)-$(i+8)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap LI NI UI pfrU UO NO LO pfrL srcr srcm srce LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap LI NI UI pfrU UO NO LO pfrL srcr srcm srce LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,LI,NI,UI,pfrU,UO,NO,LO,pfrL,srcr,srcm,srce,LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot19 rsa rra rqa rcx rsap rrap LI NI UI pfrU UO NO LO pfrL srcr srcm srce LI+NI+UI+pfrU+UO+NO+LO+pfrL+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "5":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh..reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nxreg=$3+1;nyreg=$4+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhixreg/{W=-$3;E=$6} \
       /fhiyreg/{S=-$3-$4-$5;N=$7+$10+$9} \
       /fhexreg/{W+=-$3;E+=$6} \
       /fheyreg/{S+=-$3-$4-$5;N+=$7+$10+$9} \
       /fhpxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+4)}} \
       /fhpyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1)-$(i+2)-$(i+3);N+=$(i+5)+$(i+8)+$(i+7)}} \
       /fhmxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+4)}} \
       /fhmyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1)-$(i+2)-$(i+3);N+=$(i+5)+$(i+8)+$(i+7)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,srcr,srcm,srce,E,N,W,S,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap srcr srcm srce E N W S E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "2":
   pipe_run.log | \
    egrep -a 'r..[hn].reg|fh..reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
    awk '/nnreg/{nreg=$2+1;nxreg=$3+1;nyreg=$4+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhixreg/{W=-$3;E=$4} \
       /fhiyreg/{S=-$3;N=$5} \
       /fhexreg/{W+=-$3;E+=$4} \
       /fheyreg/{S+=-$3;N+=$5} \
       /fhpxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+2)}} \
       /fhpyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1);N+=$(i+3)}} \
       /fhmxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+2)}} \
       /fhmyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1);N+=$(i+3)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,E,N,W,S,srcr,srcm,srce,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  case "1":
    pipe_run.log | \
     egrep -a 'r..[hn].reg|fh..reg|b2s..._s.._reg|^pot|nnreg|End tallies|Total profile-source Power' | \
     awk '/nnreg/{nreg=$2+1;nxreg=$3+1;nyreg=$4+1} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /Total profile-source Power/{ext=$4} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nreg) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nreg) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nreg) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nreg) rcx+=$i} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nreg) rsap+=$i*pot[int(i/nreg)+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nreg) rrap+=$i*pot[int(i/nreg)+1]} \
       /fhixreg/{W=-$3;E=$4} \
       /fhiyreg/{S=-$3;N=$4} \
       /fhexreg/{W+=-$3;E+=$4} \
       /fheyreg/{S+=-$3;N+=$4} \
       /fhpxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+2)}} \
       /fhpyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1);N+=$(i+2)}} \
       /fhmxreg/{for (i=2;i<=NF;i+=nxreg) {W+=-$(i+1);E+=$(i+2)}} \
       /fhmyreg/{for (i=2;i<=NF;i+=nyreg) {S+=-$(i+1);N+=$(i+2)}} \
       /b2stbr_she_reg/{srcr=0;for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_shi_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i} \
       /b2stbr_sna_reg/{for (i=2;i<=NF;i+=nreg) srcr+=$i*pot[int(i/nreg)+2]} \
       /b2stbm_she_reg/{srcm=0;for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_shi_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i} \
       /b2stbm_sna_reg/{for (i=2;i<=NF;i+=nreg) srcm+=$i*pot[int(i/nreg)+2]} \
       /b2sext_shi_reg/{srce=0;for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_shi_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i} \
       /b2sext_sna_reg/{for (i=2;i<=NF;i+=nreg) srce+=$i*pot[int(i/nreg)+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       END{print "#cnt rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT"} \
       /End tallies/{cnt++;print cnt,rsa,rra,rqa,rcx,rsap,rrap,E,N,W,S,srcr,srcm,srce,E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce,ext+0}' | \
    plot ${lx}x${ly}yplot15 rsa rra rqa rcx rsap rrap E N W S srcr srcm srce E+N+W+S+rsa+rra+rqa+rcx-rsap+rrap+srcr+srcm+srce EXT iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
