#! /bin/tcsh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | head -100000 | grep -a nreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "4old":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg '| \
      paste - - | \
      ave.awk 2 | \
      awk "$2"'{print NR,-2*$3,-2*$4,2*$5,2*$6,2*$10,2*$12,2*$14,2*(-$9-$11+$13+$15)}' | \
      plot x"$1"yplot8 -W -w e E core sep mcw pfw iterations W $PWD
    breaksw
  case "4":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg |tallies'| \
      awk '/Start tallies by region/{W=0;w=0;e=0;E=0;core=0;sep=0;mcw=0;pfw=0}/fh[ei]xreg/{W+=-$3;w+=-$4;e+=$5;E+=$6}/fh[ei]yreg/{core+=$4;sep+=$6;mcw+=$8;pfw+=-$3-$5+$7+$9}/End tallies by region/{print W,w,e,E,core,sep,mcw,pfw}' | \
      nl | \
      plot x"$1"yplot8 -W -w e E core sep mcw pfw iterations W $PWD
    breaksw
  case "8old":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg '| \
      paste - - | \
      ave.awk 2 | \
      awk "$2"'{print NR,-2*$3,-2*$4,2*$5,2*$6,-2*$7,-2*$8,2*$9,2*$10,2*$14,2*$21,2*($14+$21),2*$16,2*$23,2*($16+$23),2*$18,2*$25,2*($18+$25),2*(-$13+$17-$22+$26),2*(-$15+$19-$20+$24),2*(-$13+$17-$22+$26-$15+$19-$20+$24)}' | \
      plot x"$1"yplot20 -LI -li ui UI -UO -uo lo LO coreI coreO core sepI sepO sep mcwI mcwO mcw pfwL pfwU pfw iterations W $PWD
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg |tallies'| \
      awk '/Start tallies by region/{LI=0;li=0;ui=0;UI=0;UO=0;uo=0;lo=0;LO=0;coreI=0;coreO=0;sepI=0;sepO=0;mcwI=0;mcwO=0;pfwL=0;pfwU=0}/fh[ei]xreg/{LI+=-$3;li+=-$4;ui+=$5;UI+=$6;UO+=-$7;uo+=-$8;lo+=$9;LO+=$10}/fh[ei]yreg/{coreI+=$4;coreO+=$11;sepI+=$6;sepO+=$13;mcwI+=$8;mcwO+=$15;pfwL+=-$3-$12+$7+$16;pfwU+=-$5-$10+$9+$14}/End tallies by region/{print LI,li,ui,UI,UO,uo,lo,LO,coreI,coreO,coreI+coreO,sepI,sepO,sepI+sepO,mcwI,mcwO,mcwI+mcwO,pfwL,pfwU,pfwL+pfwU}' | \
      nl | \
      plot x"$1"yplot20 -LI -li ui UI -UO -uo lo LO coreI coreO core sepI sepO sep mcwI mcwO mcw pfwL pfwU pfw iterations W $PWD
    breaksw
  case "7":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg |tallies'| \
      awk '/Start tallies by region/{W=0;w=0;e=0;E1=0;E2=0;e2=0;e3=0;E3=0;core=0;sep=0;mcw=0;pfw=0}/fh[ei]xreg/{W+=-$3;w+=-$4;e+=$5;E1+=$6;E2+=-$7;e2+=-$9;e3+=$8;E3+=$10}/fh[ei]yreg/{coreI+=$4;sep+=$6;mcw+=$7+$8+$9+$13+$14+$15;pfw+=-$3-$5-$10-$11-$12}/End tallies by region/{print W,w,e,E1,E2,e2,e3,E3,core,sep,mcw,pfw}' | \
      nl | \
      plot x"$1"yplot20 -W -w e E1 -E2 -e2 e3 E3 core sep mcw iterations W $PWD
    breaksw
  case "5old":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg '| \
      paste - - | \
      ave.awk 2 | \
      awk '{print NR,-2*$3,-2*$4,2*$5,2*$6,2*$10,2*$12,2*$16,2*$14,2*(-$9-$11)}' | \
      plot x"$1"yplot9 -W -w e E core sep island center pfw iterations W $PWD
    breaksw
  case "5":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg |tallies'| \
      awk '/Start tallies by region/{W=0;w=0;e=0;E=0;core=0;sep=0;island=0;centre=0;pfw=0}/fh[ei]xreg/{W+=-$3;w+=-$4;e+=$5;E+=$6}/fh[ei]yreg/{core+=$4;sep+=$6;island+=$10;centre+=$8;pfw+=-$3-$5+$7+$9}/End tallies by region/{print W,w,e,E,core,sep,island,centre,pfw}' | \
      nl | \
      plot x"$1"yplot9 -W -w e E core sep island center pfw iterations W $PWD
    breaksw
  case "2old":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg '| \
      paste - - | \
      ave.awk 2 | \
      awk "$2"'{print NR,-2*$3,2*$4,2*$7,2*$8,2*$9}' | \
      plot x"$1"yplot5 -W E core sep mcw iterations W $PWD
    breaksw
  case "2":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg |tallies'| \
      awk '/Start tallies by region/{W=0;w=0;e=0;E=0;core=0;sep=0;mcw=0;pfw=0}/fh[ei]xreg/{W+=-$3;E+=$4}/fh[ei]yreg/{core+=$3;sep+=$4;mcw+=$5}/End tallies by region/{print W,E,core,sep,mcw}' | \
      nl | \
      plot x"$1"yplot5 -W E core sep mcw iterations W $PWD
    breaksw
  case "1":
    pipe_run.log | \
      egrep -a '^fh[ei][xy]reg '| \
      paste - - | \
      ave.awk 2 | \
      awk "$2"'{print NR,2*$3,2*$4,2*$7,2*$8}' | \
      plot x"$1"yplot4 W E S N iterations W $PWD
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
