#! /bin/csh -f
set text=`basename $0`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set freg=$nnreg[3]
if ("" == $vreg) set vreg=4
if ("" == $freg) set freg=13
pipe_run.log | \
  egrep -a "^$text |^nnreg" | \
  regxy_sum_over_species | \
  awk '/^'$text' /{for (i=3;i<=6;i++) printf "%s ",$i; for (i=9;i<=15;i++) printf "%s ",$i; printf "\n"}' | \
  nl | \
  plot x"$1"yplot11 W w e E sw core se sep nw mcw ne iter $text $PWD
