#! /bin/csh -f
set text=`basename $0`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set xreg=$nnreg[3]
set yreg=$nnreg[4]
if ("" == $vreg) set vreg=4
if ("" == $xreg) set xreg=6
if ("" == $yreg) set yreg=7
pipe_run.log | \
  egrep -a "^$text |^nnreg" | \
  regxy_sum_over_species | \
  awk '/^'$text' /{for (i=3;i<=NF;i++) printf "%s ",$i; printf "\n"}' | \
  nl | \
  plot x"$1"yplot7 sw core se sep nw mcw ne iter $text $PWD
