#! /usr/bin/env ksh
OLD_PWD=$PWD
filename=setup.csh.${HOST_NAME}.${COMPILER}
echo Looking if ${filename} file is present...
cd $SOLPSTOP/SETUP
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  cp setup.csh.default.default ${filename}
  echo "Created ${filename} from setup.csh.default.default in $PWD: please modify if needed"
}
filename=config.${HOST_NAME}.${COMPILER}
echo Looking for ${filename} files...
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  cp config.default.default ${filename}
  echo "Created ${filename} from config.default.default in $PWD: please modify if needed"
}
cd $SOLPSTOP/modules/B2.5/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    cp config.default.default ${filename}
    echo "Created ${filename} from config.default.default in $PWD: please modify if needed"
  }
}
cd $SOLPSTOP/modules/Eirene/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $SOLPSTOP/modules/Carre2/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $SOLPSTOP/modules/DivGeo/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $SOLPSTOP/modules/DivGeo/convert/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $SOLPSTOP/modules/DivGeo/equtrn/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $SOLPSTOP/modules/Uinp/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $SOLPSTOP/modules/Triang/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $SOLPSTOP/modules/solps4-5/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    cp config.default.default ${filename}
    echo "Created ${filename} from config.default.default in $PWD: please modify if needed"
  }
}
cd $SOLPSTOP/modules/amds/config
[ -s ${filename} ] && {
  echo "Non-empty ${filename} already present in $PWD: nothing done"
} || {
  [ -s config.default.$COMPILER ] && {
    cp config.default.$COMPILER ${filename}
    echo "Created ${filename} from config.default.$COMPILER in $PWD: please modify if needed"
  } || {
    echo "No config.default.$COMPILER file available in $PWD: nothing done"
  }
}
cd $OLD_PWD
[ -d $SOLPSTOP/lib/${HOST_NAME}.${COMPILER} ] || mkdir $SOLPSTOP/lib/${HOST_NAME}.${COMPILER}
