#! /bin/tcsh -f
if (! -e .next_run_no) then
#  echo "No .next_run_no"
  echo ARCHIVE/run* | tr ' ' '\n' | grep -v -i invalid | tail -1 | sed 's:ARCHIVE/run::' | awk '{print $1,length($1)}' > .next_run_no
#  echo ".next_run_no: `cat .next_run_no`"
  if (-z .next_run_no) then
#    echo "Zero length .next_run_no"
    echo 0 4 > .next_run_no
#  echo ".next_run_no: `cat .next_run_no`"
  endif
endif
# echo ".next_run_no: `cat .next_run_no`"
mv .next_run_no .next_run_no.old
cat .next_run_no.old | awk '{print $1+1,$2}' >! .next_run_no
rm .next_run_no.old
echo `cat .next_run_no | awk '{printf "run%0"$2"i\n",$1}'`
# echo ".next_run_no: `cat .next_run_no`"
