#! /bin/tcsh -f
set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-s $solps_fluids) then
  echo `cat $solps_fluids`
else
  pipe_run.log |& grep -a -m 1 '^species' | awk '{for (j=3;j<=NF;j++) {printf $j; print "\t"}}' | awk.transpose
endif
