#! /usr/bin/ksh

#  VERSION : 24.12.2004 19:14

[ -L grep.lis ] && O=grep.lis || { 
  [ -L grp.lis ] && O=grp.lis || {
    [ -f grep.lis ] && O=grep.lis || {
      [ -f grp.lis ] && O=grp.lis || O=grep.lis
    }
  }
}

{ case "$1" in
  ( -- )  shift;;
  ( -o )  shift
          [ -n "$1" ] && {
            [ -d "$1" ] && O="$1/$O" || O="$1"
            shift
          };;
  ( * )   ;;
esac; }

{ case `pwd` in
  ( */include               ) I="[a-zA-Z0-9_]*.H";;
  ( */src/Eirene/current/common ) I="../../../../include/[a-zA-Z0-9_]*.[FH]";;
  ( */src/Eirene/current    ) I="../../../include/[a-zA-Z0-9_]*.[FH]";;
  ( */src/Eirene            ) I="current/*/*.[FH] ../../include/[a-zA-Z0-9_]*.[FH]";;
  ( */src/b2/current        ) I="../../../include/[a-zA-Z0-9_]*.[FH] common/*.h common/*.inc common/emissivity.* common/COUPLE/*.F";;
  ( */src/b2                ) I="../../include/[a-zA-Z0-9_]*.[FH] src.local/*.h src/*/*.F src/common/*.h src/common/*.inc src/common/emissivity.* src/common/COUPLE/*.F";;
  ( */base/b2               ) I="../../../include/[a-zA-Z0-9_]*.[FH] ../src.local/*.[Fh] ../src/*/*.F ../src/common/*.h ../src/common/*.inc ../src/common/emissivity.* ../src/common/COUPLE/*.F";;
  ( */src/DivGeo/uinp/src   ) I="[A-Z]* [a-zA-Z0-9_]*.inc ../../../Eirene/src/common/[A-Z]*.F ../../../include/[a-zA-Z0-9_]*.[FH]";;
  (          *              ) I=;;
esac; }

for i in "$@"; do {
  echo \\n ==== $i \\n >> $O
  i=`echo $i | sed -e 's/\./\\\./g' -e 's/\*/\\\*/g' `
  grep -i -n -s -e "[^a-zA-Z0-9_]$i[^a-zA-Z0-9_]" -e "[^a-zA-Z0-9_]$i$" [a-zA-Z0-9_]*.[Ff] $I */[a-zA-Z0-9_]*.F >> $O
}; done
