#! /usr/bin/env ksh

#  VERSION : 24.12.2004 19:14

[ -L grep.lis ] && O=grep.lis || { 
  [ -L grp.lis ] && O=grp.lis || {
    [ -f grep.lis ] && O=grep.lis || {
      [ -f grp.lis ] && O=grp.lis || O=grep.lis
    }
  }
}

{ case "$1" in
  ( -- )  shift;;
  ( -o )  shift
          [ -n "$1" ] && {
            [ -d "$1" ] && O="$1/$O" || O="$1"
            shift
          };;
  ( * )   ;;
esac; }

{ case `pwd` in
  ( */modules/Eirene/src    ) I="*/*/*.[fFHh] */*/.[fF]90 ../../B2.5/src/include/[a-zA-Z0-9_]*.[FHh]";;
  ( */modules/Eirene        ) I="src/*/*.[fFHh] src/*/*.[fF]90 src/*/*/*.[fFHh] src/*/*/*.[fF]90 ../B2.5/src/include/[a-zA-Z0-9_]*.[FHh]";;
  ( */modules/B2.5/src      ) I="include/[a-zA-Z0-9_]*.[FHh] common/*.h common/*.inc common/emissivity.* common/COUPLE/*.F";;
  ( */modules/B2.5          ) I="src/include/[a-zA-Z0-9_]*.[FHh] src.local/*.h src/*/*.F src/*/*.F90 src/common/*.h src/common/*.inc src/common/emissivity.* src/common/COUPLE/*.F";;
  ( */modules/Uinp/src      ) I="[a-zA-Z0-9_]*.inc [a-zA-Z0-9_]*.h ../../B2.5/src/include/[a-zA-Z0-9_]*.[FHh]";;
  ( */modules/Uinp          ) I="src/[a-zA-Z0-9_]*.inc src/[a-zA-Z0-9_]*.h ../B2.5/src/include/[a-zA-Z0-9_]*.[FHh]";;
  ( */modules/Carre2/src90  ) I="include/[a-zA-Z0-9_]*.inc include/[a-zA-Z0-9_]*.h ../../B2.5/src/include/[a-zA-Z0-9_]*.[FHh]";;
  ( */modules/Carre2        ) I="src90/include/[a-zA-Z0-9_]*.inc src90/include/[a-zA-Z0-9_]*.h ../B2.5/src/include/[a-zA-Z0-9_]*.[FHh]";;
  (          *              ) I=;;
esac; }

for i in "$@"; do {
  echo \\n ==== $i \\n >> $O
  i=`echo $i | sed -e 's/\./\\\./g' -e 's/\*/\\\*/g' `
  grep -i -n -s -e "[^a-zA-Z0-9_]$i[^a-zA-Z0-9_]" -e "[^a-zA-Z0-9_]$i$" [a-zA-Z0-9_]*.[Ff] [a-zA-Z0-9_]*.[Ff]90 $I */[a-zA-Z0-9_]*.[Ff] */[a-zA-Z0-9_]*.[Ff]90 >> $O
}; done
