#! /bin/csh -f
pipe_run.log | \
  egrep -a 'fna.reg|nnreg|Total profile-source na' | \
  awk '/nnreg/{nxreg=$3;nyreg=$4} \
       /Total profile-source na: *0 /{ext=$5} \
       /Total profile-source na: *1 /{ext+=$5} \
       /fnaxreg/{dev=-($3+$(3+nxreg+1))+($6+$(6+nxreg+1))} \
       /fnayreg/{dev=dev-($3+$(3+nyreg+1)+$4+$(4+nyreg+1)+$5+$(5+nyreg+1))+($7+$(7+nyreg+1)+$8+$(8+nyreg+1)+$9+$(9+nyreg+1));\
                 cnt++;print cnt,dev,ext+0}' | \
  plot x$1yplot2 N-S+E-W EXT
