#! /bin/csh -f
pipe_run.log | \
  egrep -a 'fnareg|nnreg|Total profile-source na' | \
  awk '/nnreg/{nfreg=$3} \
       /Total profile-source na: *0 /{ext=$5} \
       /Total profile-source na: *1 /{ext+=$5} \
       /fnareg/{dev=-($3+$(3+nfreg+1))+($6+$(6+nfreg+1))-($9+$(9+nfreg+1)+$10+$(10+nfreg+1)+$11+$(11+nfreg+1))+($13+$(13+nfreg+1)+$14+$(14+nfreg+1)+$15+$(15+nfreg+1));\
                 cnt++;print cnt,dev,ext+0}' | \
  plot x$1yplot2 N-S+E-W EXT
