#! /bin/csh -f
pipe_run.log | \
  egrep -a 'fnareg|nnreg' | \
  awk 'BEGIN{iss=9;ise=11} \
       /nnreg/{nfreg=$3+1} \
       /fnareg/{E=0;W=0;core=0;pflxl=0;pflxr=0;N=0;for (i=iss;i<=ise;i++) {E+=-$(2+nfreg*i+1);W+=$(5+nfreg*i+1);core+=-($(9+nfreg*i+1));pflxl+=-($(8+nfreg*i+1));pflxr+=-($(10+nfreg*i+1));N+=($(12+nfreg*i+1)+$(13+nfreg*i+1)+$(14+nfreg*i+1))}; \
                 cnt++;print cnt,E,W,core,pflxl,pflxr,N}' | \
  plot x$1yplot6 -E W -core -pflxl -pflxr N iteration sum.He `noquote_pwd 3`
