#! /bin/ksh

#  VERSION : 22.08.96 17:12

#syntax for call: hlp_blnn [ -v -n -k -c [ -i # ] ]

name=`basename $0`

case "$OBJECTCODE" in
    IBMaix  )   ;;
    *       )   echo "$name: Improper platform $OBJECTCODE"; exit 4;;
esac

view=; verb=; keep=; keepcmd=; iterations=
while true; do
    case "$1" in
        -c  )   keepcmd=$1;;
        -k  )   keep=$1;;
        -n  )   view=$1;;
        -v  )   verb=$1;;
        -i  )   shift; iterations=$1;;
        -*  )   echo "Non-supported option $1";;
        *   )   break;;
    esac; shift
done

# Check whether the script is called from trc ...

freestanding=
[ -z "$GNUPLOT_BATCH" ] && freestanding=yes
if [ -n "$freestanding" ]; then

# do the following only if run free-standing, i.e. not from trc

   export GNUPLOT_BATCH=yes
   export GNUPLOT_DELAY=0
# clean up the directory
   rm -f GNUPLOT_COUNT gnuplot.cmd $name.ps gnuplot.[1-9]*.data >/dev/null 2>&1
   echo 0 > GNUPLOT_COUNT
   echo set term postscript landscape color > gnuplot.cmd
   echo set output \'$name.ps\' >> gnuplot.cmd
fi


filename=tracing/blnn.trc
[ -r "$filename" ] || { echo "$name: filename=$filename does not exist!!!" >&2; exit 33; }

#get rid of leading tab if before 960727

filedate=`head -1 $filename | awk '{print $2}'`
if [ $filedate -lt 960727 ]; then
  notab=tracing/notab
  rm -f $temp0  >/dev/null 2>&1
  cat $filename | tr '\011' '@' | sed s/^@//g | tr '@' '\011' > $notab
  filename=$notab
fi


# copy files to local directory tempdir and shorten them to iterations,
# output files: in $tempdir/$header headerfile, 1 column per line
# in $tempdir/$data, all data for $iterations,  1 line per timestep

[ -z "$iterations" ] && iterations=`wc -l < $filename | awk '{print $1}'`

dir=`hlp_src_cp $iterations $filename`
[ $? -gt 0 ] && { echo "$name: file copy to local directory did not work" >&2; exit 33; }

header=$dir/header
data=$dir/data


specieslist=`hlp_species $filename flux_tot_`

[ -n "$verb" ] && echo "%% hlp_blnn: species = $specieslist"

arglist=""
for f in $specieslist; do
  arglist="$arglist flux_ttr_$f"
done

# hlp_src blnr lin $header $data time $arglist
hlp_src time_scales lin $header $data time $arglist

arglist=""
for f in $specieslist; do
  arglist="$arglist bln_blnr_$f"
done

#hlp_src blnr lin $header $data time $arglist
hlp_src B2_particle_balance lin $header $data time $arglist

arglist=""
for f in $specieslist; do
  arglist="$arglist flux_blr_$f"
done

hlp_src flux_balance lin $header $data time $arglist

for f in $specieslist; do
#  hlp_src flux_$f lin $header $data time flux_tot_$f ion_core_$f ntr_core_$f ion_targ_$f ntr_targ_$f ion_wall_$f ntr_wall_$f ntr_puff_$f flx_d/dt_$f flux_bln_$f
  hlp_src fluxes_$f lin $header $data time flux_tot_$f ion_core_$f ntr_core_$f ion_targ_$f ntr_targ_$f ion_wall_$f ntr_wall_$f ntr_puff_$f
done

for f in $specieslist; do
  hlp_src particles_$f lin $header $data time ions_tot_$f
done

if [ -n "$freestanding" ]; then
#  Replace the labels

[ -r VarID ] && { [ -n "$verb" ] && echo "%%%% editing gnuplot.cmd ..."
    v=`cat VarID | tr _/ '  '`; echo "1,\$g/^set title/s/\".*\"/\"$v\"/
w
q" | ed -s gnuplot.cmd > /dev/null; }

gnuplot gnuplot.cmd
  [ -z "$keep" ] && rm GNUPLOT_COUNT gnuplot.*data

  if [ -z "$view" ] ; then
    ghostview $GV_OPT $name.ps &
    setnice 0 $!
  fi

fi

rm -rf plots_$name >/dev/null 2>&1
mv $dir/plots plots_$name
rm -rf $dir >/dev/null 2>&1
rm -rf $notab >/dev/null 2>&1
