#! /bin/ksh

# syntax for call: hlp_scr_cp iterations filename
# output is name of temporary local directory
# usage e.g. tempdir=`hlp_src_cp 300 tracing/sources.trc`
# output files: in $tempdir/$header headerfile, 1 column per line
# in $tempdir/$data, all data for $iterations,  1 line per timestep

#  VERSION : 16.02.98 13:14

name=`basename $0`


iterations=$1
[ -z "$iterations" ] && { echo "$name: iterations not specified" >&2; exit 33; }
[ $iterations -gt 1 ] || { echo "$name: number of iterations=$iterations;  not > 1 !!!" >&2; exit 32; }
shift

filename=$1
shift

[ ! -r "$filename" ] && { echo "$name: filename=$filename does not exist!!!" >&2; exit 33; }

# copy file to local directory to speed it up
# check to see if line length the same for last file

hh=`hostname`

#dir0=`echo $PWD`
#dir0=`basename $dir0`
#dir1=`dirname $dir0`
#dir1=`dirname $dir1`
#dir1=`dirname $dir1`
#dir1=`dirname $dir1`
#dir1=`basename $dir1`

dir0=${PWD##*/}
dir1="$USER"
dirs=${SOLPSTOP##*/}
dirr=${PWD%${dirs}*}/tmp
[ -d "$dirr" ] || mkdir "$dirr"
if [ -d "$dirr" ]; then
  dir="$dirr"/${hh}_${dir1}_${dir0}
else
  if [ -d /u/tmp/ -a -w /u/tmp/ ]; then
    dir=/u/tmp/${user}_${dir1}_${dir0}
  else
    dir=${hh}_${dir1}_${dir0}
  fi
fi

[ -d $dir ] && rm -rf $dir >/dev/null 2>&1
mkdir $dir
filenew=`basename $filename`
filenew=$dir/$filenew

cp $filename $filenew
filename=$filenew

#get number of headerline (last line with hash mark
#headerline=`cat $filename | grep "^#" | wc -l | awk '{print $1}'`
headerline=`cut -c1 $filename | grep "^#" | wc -l | awk '{print $1}'`

[ -z "$headerline" ] && { echo "$name: headerline not specified" >&2; exit 33; }
[ $headerline -gt 0 ] || { echo "$name: headerline=$headerline; not correct" >&2; exit 33; }

lines=`wc -l $filename | awk '{ print $1}'`

temp0=$dir/temp0
temp1=$dir/temp1
temp2=$dir/temp2
temp3=$dir/temp3


cat $filename | head -$headerline | tail -1 | tr '\011' '\012' | sed s/^#//g | sed s/" "//g > $temp0
filebasename=`basename $filename`

let "datalines = lines - headerline"

tail -2 $filename > $temp1
head -1 $temp1 > $temp2
tail -1 $temp1 > $temp3

ncol2ndlast=`wc -w < $temp2 | awk '{print $1}'`
ncollast=`wc -w < $temp3 | awk '{print $1}'`

lasterror=
if [ $ncollast -lt $ncol2ndlast ]; then
  lasterror=1
  let "iterations = iterations + 1"
fi
if [ $iterations -gt $datalines ]; then
  echo "$name: only $datalines datalines in $filebasename; iterations reduced from $iterations to $datalines" >&2
  iterations=$datalines
fi

cat  $filename | tail -$datalines | nl | tail -$iterations > $temp2

if [ -n "$lasterror" ]; then
  let "iterations = iterations - 1"
  cat  $temp2 | head -$iterations > $temp1
else
  mv $temp2 $temp1
fi


mv $temp0 $dir/header
mv $temp1 $dir/data


rm -f $filename $temp2 $temp3 >&2

echo $dir
