#! /bin/ksh

#syntax for call: hlp_src_run title iterations filename lin_log x_column_header y_col_headers
# lin_log will give linear plot if not equal to "log", log plot if "log"
# x_column_header is either 0 (if x axis are iterations)
# or name of column (e.g. "time" in case of blnn.trc). This permits plots versus time
# or x-y plots (various quantitities against one other quantity)
# y_col_headers are n arguments yielding n lines on plot
# e.g. hlp_src_run title 20 tracing/sources.trc lin 0 srces01r srces01c srces01i



# do the following only if run free-standing, i.e. not from trc

name=`basename $0`


case "$OBJECTCODE" in
    IBMaix  )   ;;
    *       )   echo "$name: Improper platform $OBJECTCODE"; exit 4;;
esac

title=$1
shift

iterations=$1
shift

filename=$1
shift

log=$1
shift

view=
keep=
freestanding=
[ -z "$GNUPLOT_BATCH" ] && freestanding=yes
if [ -n "$freestanding" ]; then 
   export GNUPLOT_BATCH=yes
   export GNUPLOT_DELAY=0
# clean up the directory
   rm -f GNUPLOT_COUNT gnuplot.cmd $name.ps gnuplot.[1-9]*.data >/dev/null 2>&1
   echo 0 > GNUPLOT_COUNT
   echo set term postscript landscape color > gnuplot.cmd
   echo set output \'$name.ps\' >> gnuplot.cmd
fi


[ ! -r "$filename" ] && { echo "$name: filename=$filename does not exist!!!" >&2; exit 33; }

# copy files to local directory tempdir and shorten them to iterations, 
# output files: in $tempdir/$header headerfile, 1 column per line
# in $tempdir/$data, all data for $iterations,  1 line per timestep

dir=`hlp_src_cp $iterations $filename`

[ $? -gt 0 ] && { echo "$name: file copy to local directory did not work" >&2; exit 33; }

header=$dir/header
data=$dir/data


hlp_src $title $log $header $data $*


if [ -n "$freestanding" ]; then 
#  Replace the labels

[ -r VarID ] && { [ -n "$verb" ] && echo "%%%% editing gnuplot.cmd ..."
    v=`cat VarID | tr _/ '  '`; echo "1,\$g/^set title/s/\".*\"/\"$v\"/
w
q" | ed -s gnuplot.cmd > /dev/null; }

gnuplot gnuplot.cmd
  [ -z "$keep" ] && rm GNUPLOT_COUNT gnuplot.*data

  if [ -z "$view" ] ; then
    ghostview $GV_OPT $name.ps &
    setnice 0 $!
  fi

fi


#rm -rf $dir >/dev/null 2>&1
