#! /bin/ksh

[ ${COMPILER} == "HP" ] && {
  filestem="ftn"
} || {
  filestem="fort."
}
rundir="`pwd`"
[ -s ../convert/b2yt.files ] && {
  echo "First copying the files modified by b2yt"
  files="`cat ../convert/b2yt.files | sed -e 's:../::' | awk.transpose`"
  for fn in $files
  do
    origin=$fn
    destination=`echo $origin | sed -e 's:b2fstatt:b2fstati:' -e 's:\.2$::'`
    cp -iv ../convert/$origin $destination
  done
  echo "Now copying unmodified files"
  [ -s ../convert/b2fgmtry.old ] && {
    [ -s ../convert/b2ag.dat.2 ] && {
        cp -v --no-preserve=timestamps ../convert/b2ag.dat.2 ../baserun/b2ag.dat
    } || {
        [ -s ../convert/b2ag.dat ] && cp -v --no-preserve=timestamps ../convert/b2ag.dat ../baserun
    }
    [ -s ../convert/b2fgmtry ] && cp -v --no-preserve=timestamps ../convert/b2fgmtry ../baserun
    [ -s ../convert/"$filestem"30 ] && cp -v --no-preserve=timestamps ../convert/"$filestem"30 .
    [ -s ../convert/"$filestem"33 ] && cp -uv ../convert/"$filestem"33 .
    [ -s ../convert/"$filestem"34 ] && cp -uv ../convert/"$filestem"34 .
    [ -s ../convert/"$filestem"35 ] && cp -uv ../convert/"$filestem"35 .
  }
  [ -s ../baserun/b2fgmtry ] || {
     [ -s ../convert/b2ag.dat.2 ] || {
       [ -s ../convert/b2ag.dat ] && cp -v --no-preserve=timestamps ../convert/b2ag.dat ../baserun
       [ -s ../convert/b2fgmtry ] && cp -v --no-preserve=timestamps ../convert/b2fgmtry ../baserun
       [ -s ../convert/"$filestem"30 ] && cp -v --no-preserve=timestamps ../convert/"$filestem"30 .
       [ -s ../convert/"$filestem"33 ] && cp -uv ../convert/"$filestem"33 .
       [ -s ../convert/"$filestem"34 ] && cp -uv ../convert/"$filestem"34 .
       [ -s ../convert/"$filestem"35 ] && cp -uv ../convert/"$filestem"35 .
     }
  }
  [ -s ../convert/b2ag.dat.2 ] && rm b2ag.dat
  [ -s ../convert/b2fgmtry.2 ] && rm b2fgmtry
  [ -s ../convert/input.dat.2 ] && {
    cp -v ../convert/input.dat.2 ../baserun/input.dat
  } || {
    [ -s ../convert/input.dat ] && cp -uv ../convert/input.dat ../baserun
  }
  [ -s ../baserun/"$filestem"30 ] || cp -v --no-preserve=timestamps ../convert/"$filestem"30 ../baserun
  [ -s ../baserun/"$filestem"33 ] || cp -uv ../convert/"$filestem"33 ../baserun
  [ -s ../baserun/"$filestem"34 ] || cp -uv ../convert/"$filestem"34 ../baserun
  [ -s ../baserun/"$filestem"35 ] || cp -uv ../convert/"$filestem"35 ../baserun
  [ -s ../convert/b2ah.dat.2 ] && cp -v --no-preserve=timestamps ../convert/b2ah.dat.2 ../baserun/b2ah.dat
  [ -s ../convert/b2fpardf ] && cp -v --no-preserve=timestamps ../convert/b2fpardf .
  [ -s ../convert/b2ah.dat.2 ] && rm b2ah.dat
  [ -s ../convert/b2ai.dat.2 ] && cp -v --no-preserve=timestamps ../convert/b2ai.dat.2 ../baserun/b2ai.dat
  [ -s ../convert/b2ai.dat.2 ] && rm b2ai.dat
  [ -s ../convert/b2ar.dat.2 ] && {
    cp -v --no-preserve=timestamps ../convert/b2ar.dat.2 ../baserun/b2ar.dat
  } || {
    [ -s ../convert/b2ar.dat ] && cp -v --no-preserve=timestamps ../convert/b2ar.dat ../baserun
  }
  [ -s ../convert/b2frates ] && cp -v --no-preserve=timestamps ../convert/b2frates ../baserun
  [ -s ../convert/b2ar.dat.2 ] && rm b2ar.dat
  [ -s ../convert/b2.*.parameters ] && cp -uv ../convert/b2.*.parameters .
  [ -s ../convert/b2.transport.inputfile ] && cp -uv ../convert/b2.transport.inputfile .
  [ -s ../convert/b2.sources.profile ] && cp -uv ../convert/b2.sources.profile .
  [ -s ../convert/"$filestem"46.2 ] || {
    [ -s ../convert/"$filestem"46 ] && cp -uv ../convert/"$filestem"46 .
  }
  [ -s ../convert/"$filestem"44.2 ] || {
    [ -s ../convert/"$filestem"44 ] && cp -uv ../convert/"$filestem"44 .
  }
  [ -s ../convert/"$filestem"31 ] && cp -uv ../convert/"$filestem"31 .
  [ -s ../convert/"$filestem"15 ] && cp -uv ../convert/"$filestem"15 .
  [ -s ../convert/"$filestem"14 ] && cp -uv ../convert/"$filestem"14 .
  [ -s ../convert/"$filestem"13 ] && cp -uv ../convert/"$filestem"13 .
  [ -s ../convert/"$filestem"12 ] && cp -uv ../convert/"$filestem"12 .
  [ -s ../convert/"$filestem"11 ] && cp -uv ../convert/"$filestem"11 .
  [ -s ../convert/"$filestem"10 ] && cp -uv ../convert/"$filestem"10 .
  [ -s ../baserun/mesh.extra ] || {
    [ -s ../convert/mesh.extra ] && cp -uv ../convert/mesh.extra ../baserun
  }
  [ -s ../convert/ratadas.filelist ] && cp -uv ../convert/ratadas.filelist .
  cd ../baserun
  b2run b2ah b2ai b2ar
  cd ..
  correct_baserun_timestamps
  cd $rundir
  touch b2fstati
  setup_baserun_eirene_links
} || {
  echo 'Did not find b2yt.files list. Exiting ...'
}
