#! /bin/tcsh -f
set x=$1
if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif
if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG=4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
pipe_run.log | \
  awk 'BEGIN{nrv='$NREG'} \
       /nreg/{nrv=$2;nrf=$3} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /rsahireg/{rsa=0;for (i=3;i<=NF;i+=nrv+1) rsa+=$i} \
       /rrahireg/{rra=0;for (i=3;i<=NF;i+=nrv+1) rra+=$i} \
       /rqahereg/{rqa=0;for (i=3;i<=NF;i+=nrv+1) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=3;i<=NF;i+=nrv+1) rcx+=$i} \
       /b2divue/{b2divue=$3} \
       /b2divua/{b2divua=$3} \
       /b2exbe/{b2exbe=$3} \
       /b2exba/{b2exba=$3} \
       /b2visa/{b2visa=$3} \
       /b2joule/{b2joule=$3} \
       /b2fraa/{b2fraa=$3} \
       /b2wrong1/{b2wrong1=$3} \
       /b2wrong2/{b2wrong2=$3} \
       /b2wrong3/{b2wrong3=$3} \
       /b2stbr_she_reg/{b2brhe=$3} \
       /b2stbr_shi_reg/{b2brhi=$3} \
       /fhireg/&&nrv==2{S=-$4;N=$5} \
       /fhereg/&&nrv==2{S+=-$4;N+=$5} \
       /fhireg/&&nrv==4{S=-$10;N=$12} \
       /fhereg/&&nrv==4{S+=-$10;N+=$12} \
       /fhireg/&&nrv==5{S=-$11;N=$13} \
       /fhereg/&&nrv==5{S+=-$11;N+=$13} \
       /fhireg/&&nrv==7{S=-$17;N=$19} \
       /fhereg/&&nrv==7{S+=-$17;N+=$19} \
       /fhireg/&&nrv==8&&nrf==26{S=-$16-$23;N=$18+$25} \
       /fhereg/&&nrv==8&&nrf==26{S+=-$16-$23;N+=$18+$25} \
       /fhireg/&&nrv==8&&nrf==27{S=-$17-$24;N=$19+$26} \
       /fhereg/&&nrv==8&&nrf==27{S+=-$17-$24;N+=$19+$26} \
       /rsanareg/{rsap=0;for (i=3;i<=NF;i+=nrv+1) rsap+=$i*pot[int(i/(nrv+1))+2]} \
       /rranareg/{rrap=0;for (i=3;i<=NF;i+=nrv+1) rrap+=$i*pot[int(i/(nrv+1))+1]} \
       /b2stbr_sna_reg/{b2brnp=0; for (i=3;i<=NF;i+=nrv+1) b2brnp+=$i*pot[int(i/(nrv+1))+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx b2divue b2divua b2exbe b2exba b2visa b2joule b2fraa b2wrong1 b2wrong2 b2wrong3 b2brhe b2brhi rsap rrap b2brnp N S N+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp"} \
       END{print "#cnt rsa rra rqa rcx b2divue b2divua b2exbe b2exba b2visa b2joule b2fraa b2wrong1 b2wrong2 b2wrong3 b2brhe b2brhi rsap rrap b2brnp N S N+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp"} \
       /End tallies by region/{cnt++;print cnt,rsa,rra,rqa,rcx,b2divue,b2divua,b2exbe,b2exba,b2visa,b2joule,b2fraa,b2wrong1,b2wrong2,b2wrong3,b2brhe,b2brhi,rsap,rrap,b2brnp,N,S,N+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp}' | \
  plot ${lx}x${ly}yplot22 rsa rra rqa rcx b2divue b2divua b2exbe b2exba b2visa b2joule b2fraa b2wrong1 b2wrong2 b2wrong3 b2brhe b2brhi rsap rrap b2brnp N S N+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
