#! /bin/tcsh -f

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
set JOB_NAME="SOLPS-ITER"
set PROCS=1
set THREADS=1
set hours=24
set mem=4GB
echo Your email is $EMAIL

set compress=""
set MPIOPTS=""
set standalone="no"
set LOOP_OPTS=""

setenv SOLPSTOP "`determine_SOLPSTOP`"
if ($SOLPSTOP == "") then
 setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
endif

argloop:
  if ("X${1}X" == "X-hX") then
    cat <<EOF

Help for $0

This script is used to submit SOLPS-ITER jobs to the SLURM batch system on the TOK cluster.

Usage:

  `basename $0` {options} {<<SCRIPT>>}

where the optional <<SCRIPT>> is the SLURM submission file to be used

Available options are:
  -j <<JOB NAME>>    set the job name (default $JOB_NAME)
  -z                 compress run.log using gzip
  -s                 specify a standalone B2.5 run
  -m <<MPI OPTIONS>> use the MPI options specified (default serial version)
  -t <<THREADS>>     use OpenMP parallelization with <<THREADS>> threads (default $THREADS)
  -T <<HOURS>>       number of elapsed hours requested (default $hours)
  -M <<MEM_SIZE>>    memory size (default $mem)

EOF
    exit
  endif
  if ("X${1}X" == "X-jX") then
    shift
    set JOB_NAME="$1"
    echo Job name is ${JOB_NAME}
    shift
    set HELP_STRING=\"${JOB_NAME}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-j ${HELP_STRING} ${LOOP_OPTS}" 
    goto argloop
  endif
  if ("X${1}X" == "X-zX") then
    set compress="-gz"
    echo run.log will be compressed
    shift
    set LOOP_OPTS="-gz ${LOOP_OPTS}" 
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    set standalone="yes"
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5"
    echo Asking for a B2.5 standalone run
    shift
    set LOOP_OPTS="-s ${LOOP_OPTS}" 
    goto argloop
  endif
  if ("X${1}X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set MPIOPTS="$1"
    echo Using MPI options: $MPIOPTS
    set PROCS=`echo $MPIOPTS | awk.transpose | grep -A 1 "\-np" | tail -n 1`
    echo Asking for $PROCS processors
    shift
    set HELP_STRING=`echo \"$MPIOPTS\"`
#    echo $HELP_STRING
    set LOOP_OPTS="-m ${HELP_STRING} ${LOOP_OPTS}" 
    goto argloop
  endif
  if ("X${1}X" == "X-tX") then
    shift
    if (! $?SOLPS_OPENMP) then
      source $SOLPSTOP/SETUP/openmp
      set OPENMP_SET=yes
    endif
    set THREADS="$1"
    echo Asking for OpenMP run with $THREADS threads
    shift
    set HELP_STRING=\"${THREADS}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-t ${HELP_STRING} ${LOOP_OPTS}" 
    goto argloop
  endif
  if ("X${1}X" == "X-TX") then
    shift
    set hours="$1"
    echo Requested time is ${hours} hours
    shift
    set HELP_STRING=\"${hours}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-T ${HELP_STRING} ${LOOP_OPTS}" 
    goto argloop
  endif
  if ("X${1}X" == "X-MX") then
    shift
    set mem="$1"
    echo Requested memory is ${mem}
    shift
    set HELP_STRING=\"${mem}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-M ${HELP_STRING} ${LOOP_OPTS}" 
    goto argloop
  endif

if ($1 == "") then
  if (-s input.dat && $standalone == "no") then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for SLURM.ipp_coupled$compress
    set QSUB=`climb_and_look_for SLURM.ipp_coupled$compress`
    if ($QSUB == "//SLURM.ipp_coupled$compress") then
      if (-s $SOLPSTOP/runs/SLURM.ipp_coupled$compress) then
        set QSUB="$SOLPSTOP/runs/SLURM.ipp_coupled$compress"
      else
        set QSUB=""
      endif
    endif
  else
    if ($standalone == "no") echo No input.dat file found: reverting to a standalone run
    echo No argument is specified. Looking for SLURM.ipp$compress
    set QSUB=`climb_and_look_for SLURM.ipp$compress`
    if ($QSUB == "//SLURM.ipp$compress") then
      if (-s $SOLPSTOP/runs/SLURM.ipp$compress) then
        set QSUB="$SOLPSTOP/runs/SLURM.ipp$compress"
      else
        set QSUB=""
      endif
    endif
  endif
else if (-s $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1 
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    if (-s $SOLPSTOP/runs/$1) then
      set QSUB="$SOLPSTOP/runs/$1"
      echo Submission file $QSUB is found
    else
      set QSUB=""
    endif
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No ITM submission file $1 found. Exiting.
  exit
endif
echo Using submission file template $QSUB
echo For loop resubmission following options will be used: $LOOP_OPTS

# logic to determine the partition and qos on the IPP TOK cluster
if ($PROCS == 1) then
  set part=s.tok
  if ($hours > 36 ) then
    set qos=s.tok.long
  else if ($hours > 4) then
    set qos=s.tok.standard
  else
    set qos=s.tok.short
  endif
else
  set part=p.tok.openmp
  if ($hours > 24) then
    set qos=p.tok.openmp.48h
  else if ($hours > 2) then
    set qos=p.tok.openmp.24h
  else
    set qos=p.tok.openmp.2h
  endif
endif

sed \
  -e 's:#PWD#:'$PWD':g' \
  -e 's:#SOLPSTOP#:'$SOLPSTOP':g' \
  -e 's:#EMAIL#:'$EMAIL':g' \
  -e "s:#MPIOPTS#:'$MPIOPTS':g" \
  -e 's:#PROCS#:'$PROCS':g' \
  -e 's:#THREADS#:'$THREADS':g' \
  -e 's:#MEM#:'$mem':g' \
  -e 's:#HOURS#:'$hours':g' \
  -e 's:#PART#:'$part':g' \
  -e 's:#QOS#:'$qos':g' \
  -e 's:#JOBNAME#:'$JOB_NAME':g' \
  -e 's:#USER#:'$USER':g' \
  -e 's:#LOOPOPTS#:'"$LOOP_OPTS"':g' \
  < $QSUB > $NAME

set msg="Submitted at `date`"
update_solps_run_status -n ${msg}
if ($?SOLPS_GUI_IP) then
  echo ${USER} ${PWD} ${msg} | netcat -u -v -w 1 ${SOLPS_GUI_IP} ${SOLPS_GUI_PORT}
endif
sbatch $NAME
