#! /usr/bin/env tcsh

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set NAMP=/tmp/.zut.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
set PROCS=1
echo Your email is $EMAIL

set compress=""
set MPIOPTS=""
set standalone="no"

argloop:
  if ("X${1}X" == "X-zX") then
    set compress="-gz"
    echo run.log will be compressed
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    set standalone="yes"
    echo Asking for a standalone run
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-mX") then
    shift
    set MPIOPTS="$1"
    echo Using MPI options: $MPIOPTS
    set PROCS=`echo $MPIOPTS | awk.transpose | grep -A 1 "\-np" | tail -n 1`
    echo Asking for $PROCS processors
    shift
    goto argloop
  endif

set solpstop=`climb_and_look_for SOLPSTOP`
if (-e $solpstop) then
 setenv SOLPSTOP "`cat $solpstop`"
else
 setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
endif

if ($1 == "") then
  if (-e input.dat && $standalone == "no") then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for QSUB.itm_coupled$compress
    set QSUB=`climb_and_look_for QSUB.itm_coupled$compress`
    if ($QSUB == "//QSUB.itm_coupled$compress") then
      if (-e $SOLPSTOP/runs/QSUB.itm_coupled$compress) then
        set QSUB="$SOLPSTOP/runs/QSUB.itm_coupled$compress"
      else
        set QSUB=""
      endif
    endif
  else
    if ($standalone == "no") echo Assuming standalone run
    echo No argument is specified. Looking for QSUB.itm$compress
    set QSUB=`climb_and_look_for QSUB.itm$compress`
    if ($QSUB == "//QSUB.itm$compress") then
      if (-e $SOLPSTOP/runs/QSUB.itm$compress) then
        set QSUB="$SOLPSTOP/runs/QSUB.itm$compress"
      else
        set QSUB=""
      endif
    endif
  endif
else if (-e $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1 
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    if (-e $SOLPSTOP/runs/$1) then
      set QSUB="$SOLPSTOP/runs/$1"
    else
      set QSUB=""
    endif
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No ITM submission file $1 found. Exiting.
  exit
endif
echo Using submission file template $QSUB

if ($PROCS != 1) then
  head -n 2 $QSUB > $NAMP
  echo "#$ -pe impi_hydra #PROCS#" >> $NAMP
  set lines = `wc $QSUB | awk '{printf "%s",$1-2;printf "\n"}'`
  tail --lines=$lines $QSUB >> $NAMP
else
  set NAMP=$QSUB
endif

sed -e 's:#PWD#:'$PWD':g' -e 's:#SOLPSTOP#:'$SOLPSTOP':g' -e 's:#EMAIL#:'$EMAIL':g' -e "s:#MPIOPTS#:'$MPIOPTS':g" -e 's:#PROCS#:'$PROCS':g' < $NAMP > $NAME

set msg="Submitted at `date`"
update_solps_run_status -n ${msg}
if ($?SOLPS_GUI_IP) then
  echo ${USER} ${PWD} ${msg} | nc -u -v -w 0 ${SOLPS_GUI_IP} ${SOLPS_GUI_PORT}
endif
qsub -V -S /usr/bin/tcsh $NAME
