#! /usr/bin/env tcsh

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
set JOB_NAME="SOLPS-ITER"
set PROCS=1
set hours=36
set mem=4G
echo Your email is $EMAIL

set compress=""
set MPIOPTS=""
set standalone="no"

set solpstop=`climb_and_look_for SOLPSTOP`
if (-s $solpstop) then
 setenv SOLPSTOP "`cat $solpstop`"
else if ($SOLPSTOP == "") then
 setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
endif

argloop:
  if ("X${1}X" == "X-hX") then
    cat <<EOF

Help for $0

This script is used to submit SOLPS-ITER jobs to the QSUB batch system at JET.

Usage:

  `basename $0` {options} {<<SCRIPT>>}

where the optional <<SCRIPT>> is the QSUB submission file to be used

Available options are:
  -j <<JOB NAME>>    set the job name (default $JOB_NAME)
  -z                 compress run.log using gzip
  -s                 specify a standalone B2.5 run
  -m <<MPI OPTIONS>> use the MPI options specified (default serial version)
  -T <<HOURS>>       number of elapsed hours requested (default $hours)
  -M <<MEM_SIZE>>    memory size (default $mem)

EOF
    exit
  endif
  if ("X${1}X" == "X-jX") then
    shift
    set JOB_NAME="$1"
    echo Job name is ${JOB_NAME}
    shift
    goto argloop
  endif
  if ("X$1X" == "X-zX") then
    set compress="-gz"
    echo run.log will be compressed
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    set standalone="yes"
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5"
    echo Asking for a B2.5 standalone run
    shift
    goto argloop
  endif
  if ("X$1X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set MPIOPTS="$1"
    echo Using MPI options: $MPIOPTS
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-TX") then
    shift
    set hours="$1"
    echo Requested time is ${hours} hours
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-MX") then
    shift
    set mem="$1"
    echo Requested memory is ${mem}
    shift
    goto argloop
  endif

if ($1 == "") then
  if (-s input.dat && $standalone == "no") then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for QSUB.jet_coupled$compress
    set QSUB=`climb_and_look_for QSUB.jet_coupled$compress`
    if ($QSUB == "//QSUB.jet_coupled$compress") then
      if (-s $SOLPSTOP/runs/QSUB.jet_coupled$compress) then
        set QSUB="$SOLPSTOP/runs/QSUB.jet_coupled$compress"
      else
        set QSUB=""
      endif
    endif
  else
    if ($standalone == "no") echo Assuming standalone run
    echo No argument is specified. Looking for QSUB.jet$compress
    set QSUB=`climb_and_look_for QSUB.jet$compress`
    if ($QSUB == "//QSUB.jet$compress") then
      if (-s $SOLPSTOP/runs/QSUB.jet$compress) then
        set QSUB="$SOLPSTOP/runs/QSUB.jet$compress"
      else
        set QSUB=""
      endif
    endif
  endif
else if (-s $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1 
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    if (-s $SOLPSTOP/runs/$1) then
      set QSUB="$SOLPSTOP/runs/$1"
    else
      set QSUB=""
    endif
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No JET submission file $1 found. Exiting.
  exit
endif
echo Using submission file template $QSUB

sed \
  -e 's:#PWD#:'$PWD':g' \
  -e 's:#SOLPSTOP#:'$SOLPSTOP':g' \
  -e 's:#EMAIL#:'$EMAIL':g' \
  -e "s:#MPIOPTS#:'$MPIOPTS':g" \
  -e "s:#PROCS#:'$PROCS':g" \
  -e 's:#MEM#:'$mem':g' \
  -e 's:#HOURS#:'$hours':g' \
  -e 's:#USER#:'$USER':g' \
  -e "s:#JOBNAME#:'$JOB_NAME':g" \
  < $QSUB > $NAME

set msg="Submitted at `date`"
update_solps_run_status -n ${msg}
if ($?SOLPS_GUI_IP) then
  echo ${USER} ${PWD} ${msg} | nc -u -v -w 0 ${SOLPS_GUI_IP} ${SOLPS_GUI_PORT}
endif
qsub -V -S /bin/tcsh $NAME
