#! /usr/bin/env tcsh

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
set JOB_NAME="SOLPS-ITER"
set PROCS=1
set THREADS=1
set cpus=1
set hours=24
set mem=4GB
set part="S-M"
set job_prefix="SLURM"
set chain="unset"
echo Your email is $EMAIL

set compress=""
set MPIOPTS=""
set standalone="no"
set LOOP_OPTS=""

setenv SOLPSTOP "`determine_SOLPSTOP`"
if ($SOLPSTOP == "") then
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
endif

argloop:
  if ("X${1}X" == "X-hX") then
    cat <<EOF

Help for $0

This script is used to submit SOLPS-ITER jobs to the SLURM batch system on the JFRS IFERC cluster.

Usage:

  `basename $0` {options} {<<SCRIPT>>}

where the optional <<SCRIPT>> is the SLURM submission file to be used

Available options are:
  -j <<JOB NAME>>    set the job name (default $JOB_NAME)
  -z                 compress run.log using gzip
  -s                 specify a standalone B2.5 run
  -c <<JOB_ID>>      job ID of the previous job in a chain submission
  -m <<MPI OPTIONS>> use the MPI options specified (default serial version)
  -t <<THREADS>>     use OpenMP parallelization with <<THREADS>> threads (default $THREADS)
  -T <<HOURS>>       number of elapsed hours requested (default $hours)
  -M <<MEM_SIZE>>    memory size (default $mem)
  -N <<NODES>>       number of nodes requested (default $NODES)
  -Q <<PARTITION>>   partition on which to submit the job (default is S-M)

EOF
    exit
  endif
  if ("X${1}X" == "X-jX") then
    shift
    set JOB_NAME="$1"
    echo Job name is ${JOB_NAME}
    shift
    set HELP_STRING=\"${JOB_NAME}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-j ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-zX") then
    set compress="-gz"
    echo run.log will be compressed
    shift
    set LOOP_OPTS="-z ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    set standalone="yes"
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5"
    echo Asking for a B2.5 standalone run
    shift
    set LOOP_OPTS="-s ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
    endif
    set MPIOPTS="$1"
    echo Using MPI options: $MPIOPTS
    set PROCS=`echo $MPIOPTS | cut -d n -f 2 | awk '{printf $1}'`
    echo Asking for MPI run with a total of $PROCS processors
    shift
    set HELP_STRING="${MPIOPTS}"
#    echo $HELP_STRING
    set LOOP_OPTS="-m '${HELP_STRING}' ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-tX") then
    shift
    if (! $?SOLPS_OPENMP) then
      source $SOLPSTOP/SETUP/openmp
    endif
    set THREADS="$1"
    @ cpus = ( 2 * $THREADS )
    echo Asking for OpenMP run with $THREADS threads
    shift
    set HELP_STRING="${THREADS}"
#    echo $HELP_STRING
    set LOOP_OPTS="-t ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-TX") then
    shift
    set hours="$1"
    if ( $hours == 1) then
      echo Requested time is ${hours} hour
    else
      echo Requested time is ${hours} hours
    endif
    shift
    set HELP_STRING="${hours}"
#    echo $HELP_STRING
    set LOOP_OPTS="-T ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-MX") then
    shift
    set mem="$1"
    echo Requested memory is ${mem}
    shift
    set HELP_STRING="${mem}"
#    echo $HELP_STRING
    set LOOP_OPTS="-M ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-QX") then
    shift
    set part="$1"
    echo Requested partition is ${part}
    shift
    set HELP_STRING="${part}"
#    echo $HELP_STRING
    set LOOP_OPTS="-Q ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-cX") then
    shift
    set chain="$1"
    echo Chain submission following job number ${chain}
    shift
    goto argloop
  endif

if ($1 == "") then
  if (-s fort.1 && $standalone == "no") then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for $job_prefix.jfrs_coupled$compress
    set QSUB=`climb_and_look_for $job_prefix.jfrs_coupled$compress`
    if ($QSUB == "//$job_prefix.jfrs_coupled$compress") then
      if (-s $SOLPSTOP/runs/$job_prefix.jfrs_coupled$compress) then
        set QSUB="$SOLPSTOP/runs/$job_prefix.jfrs_coupled$compress"
      else
        set QSUB=""
      endif
    endif
  else
    if ($standalone == "no") echo No fort.1 file found: reverting to a standalone run
    echo No argument is specified. Looking for $job_prefix.jfrs$compress
    set QSUB=`climb_and_look_for $job_prefix.jfrs$compress`
    if ($QSUB == "//$job_prefix.jfrs$compress") then
      if (-s $SOLPSTOP/runs/$job_prefix.jfrs$compress) then
        set QSUB="$SOLPSTOP/runs/$job_prefix.jfrs$compress"
      else
        set QSUB=""
      endif
    endif
  endif
else if (-s $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    if (-s $SOLPSTOP/runs/$1) then
      set QSUB="$SOLPSTOP/runs/$1"
      echo Submission file $QSUB is found
    else
      set QSUB=""
    endif
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No JFRS submission file $1 found. Exiting.
  exit 1
endif

echo Using submission file template $QSUB
if ($chain == "unset") then
  echo For loop resubmission following options will be used: $LOOP_OPTS
endif

sed \
  -e 's:#PWD#:'$PWD':g' \
  -e 's:#SOLPSTOP#:'$SOLPSTOP':g' \
  -e 's:#EMAIL#:'$EMAIL':g' \
  -e "s:#MPIOPTS#:'$MPIOPTS':g" \
  -e "s:#PROCS#:'$PROCS':g" \
  -e "s:#THREADS#:'$THREADS':g" \
  -e 's:#MEM#:'$mem':g' \
  -e 's:#HOURS#:'$hours':g' \
  -e 's:#PART#:'$part':g' \
  -e 's:#CPUS#:'$cpus':g' \
  -e "s:#JOBNAME#:'$JOB_NAME':g" \
  -e 's:#USER#:'$USER':g' \
  -e 's:#LOOPOPTS#:'"$LOOP_OPTS"':g' \
  < $QSUB > $NAME

if ($chain != "unset") then
  set b2run_line=`grep -n "b2run" $NAME | cut -d ':' -f 1`
  @ before_line = $b2run_line - 1
  head -n ${before_line} $NAME > $job_prefix.jfrs.after_$chain
  echo "mv run.log.gz run.log.$chain.gz" >> $job_prefix.jfrs.after_$chain
  echo "mv b2mn.prt b2mn.prt.$chain" >> $job_prefix.jfrs.after_$chain
  echo "mv b2fstate b2fstati" >> $job_prefix.jfrs.after_$chain
  echo "if (-e b2favere) mv b2favere b2faveri" >> $job_prefix.jfrs.after_$chain
  set all_lines=`cat $NAME | wc -l`
  @ tail_lines = $all_lines - $before_line
  tail -n $tail_lines $NAME >> $job_prefix.jfrs.after_$chain
  set NAME=$job_prefix.jfrs.after_$chain
endif

update_solps_run_status -n "Submitted at `date`"

if ($chain == "unset") then
  sbatch $NAME
else
  sbatch --dependency=afterok:${chain} $NAME
endif
