#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG=4
@ NREGP = $NREG + 1
pipe_run.log | \
  egrep -a '^b2joule' | \
  awk '/b2joule/{for (i=2;i<=NF;i++) printf "%s ",$i;printf "\n"}' | \
  nl | \
  plot x"$1"yplot$NREGP `count 0 $NREG` iter "Joule heating (W)" $PWD
