#! /bin/tcsh -f
if (-e run.log) then
  tail -100000 run.log >! tmp.run.log
else
  if (-X zcat) then
    set ZCAT=zcat
  else
    set ZCAT="gzip --decompress --force --stdout"
  endif
  $ZCAT -f run.log.gz | tail -100000 >! tmp.run.log
endif
set steps=`grep -n 'b2-step-cpu' tmp.run.log | wc | awk '{print $1}'`
if ($steps == 0) then
  set count=0
else
  set count=`grep -n 'b2-step-cpu' tmp.run.log | tail -11 | head -1 | awk -F: '{print $1}'`
endif
tail --lines=+$count tmp.run.log >! run.log.last10
rm tmp.run.log
