#! /bin/ksh

# changed "ls -l" to "ls -ld"  DPC 2002.05.07

#  VERSION : 02.12.96 18:27

##   Modification by A.S.Kukushkin
##   Purpose: to keep local links local,
##   and to avoid getting lost in symbolically linked directories

# lndr - create shadow link tree
#
# Used to create a copy of a directory tree that has links for all
# non- directories (except those named CVS, RCS or SCCS).  If you are
# building the distribution on more than one machine, you should use
# this script.
#
# If your master sources are located in /usr/local/src/X and you would like
# your link tree to be in /usr/local/src/new-X, do the following:
#
#  %  mkdir /usr/local/src/new-X  |    |   %  mkdir /usr/local/src/new-X
#  %  cd /usr/local/src/new-X     | or |   %  lndr ../X /usr/local/src/new-X
#  %  lndr ../X                   |    |


USAGE="
Usage  : `basename $0` [-a] [-c] [-f] [-F file] [-r path] fromdir [todir]

Options: -a       include all sub-directories (CVS, RCS, SCCS) in the shadow tree
         -c       mind the special filenames in the directories to control execution
         -f       follow the symbolic links
         -F file  use the specified file to control execution
         -r path  use path as the root directory for the tree

    The presence of a special filename in a directory tells lndr how to treat the
    directory if -c option is used. These names are:
        .lndr_skip  to skip the directory;
        .lndr_real  to make a real shadow of the symbolically linked directory;
        .lndr_link  to create a symbolic link instead of the real shadow.

    The control file (-F option) can be specified with both absolute or relative
    pathname. In the second case, it is related to the root of the original tree.
    Each line in this file consists of a pathname starting from the first position,
    and one of the (space-separated) words 'skip', 'real', or 'link' which specify
    the action.
"
NEGLECT=' CVS RCS SCCS '

while true; do
    case "$1" in
        -a  )   LNDR_ALL=y; export LNDR_ALL;;
        -c  )   LNDR_CNTR=y; export LNDR_CNTR;;
        -f  )   FolSymLin=y; export FolSymLin;;
        -F  )   LNDR_CNTF=$2; cntf=m; shift;;
        -r  )   pwd=`pwd`; DRFRLN=$2
                cd $DRFRLN && { DRFRLN=`pwd`; cd $pwd; true; } || { \
                    echo "`basename $0`: $DRFRLN must be a pathname of a DIRECTORY"
                    echo "$USAGE"; exit 2;
                }; export DRFRLN; shift;;
        *   )   break;;
    esac; shift
done

[ $# -lt 1 -o $# -gt 2 ] && { echo "$USAGE"; exit 2; }

[ -n "$LNDR_ALL" ] && NEGLECT=

pwd=`pwd`; DIRFROM=$1
cd $DIRFROM && { DIRFROM=`pwd`; cd $pwd; true; } || { \
    echo "`basename $0`: $DIRFROM must be a pathname of a DIRECTORY"
    echo "$USAGE"; exit 2;
}

[ $# -eq 2 ] && DIRTO=$2 || DIRTO=.

[ ! -d $DIRTO ] && { echo "`basename $0`: $DIRTO is not a directory"; echo "$USAGE"; exit 2; }

cd $DIRTO

[ ! -d $DIRFROM ] && { echo "`basename $0`: $DIRFROM must be a pathname of a DIRECTORY"
                       echo "$USAGE"; exit 2; }

pwd=`pwd`

[ "$DRFRLN" = '' ] && DRFRLN=`(cd $DIRFROM; pwd)`

[ -n "$LNDR_CNTF" -a -n "$cntf" ] && { \
    case $LNDR_CNTF in
        /*          )   ;;
        ./* | ../*  )   echo "`basename $0`: error in the specification of a control file"
                        echo "$USAGE"; exit 2;;
        *           )   LNDR_CNTF=$DRFRLN/$LNDR_CNTF;;
    esac; [ -f "$LNDR_CNTF" ] || { echo "`basename $0`: the control file $LNDR_CNTF does not exist"; exit 2; }
    export LNDR_CNTF; unset cntf
}

[ "$DRTOLN" = '' ] && DRTOLN="$pwd"
export DRFRLN DRTOLN

case "$DRTOLN" in
     "$DRFRLN"/* | "$DRFRLN" ) echo `basename $0`":  Cannot create a shadow tree inside the original!!!"
                               exit 2 ;;
     * )  ;;
esac

[ `(cd $DIRFROM; pwd)` = $pwd ] && { echo "$pwd: FROM and TO are identical!"; exit 1; }

act=n

echo $DIRFROM > .lndr_master
for file in `ls -af $DIRFROM`
do
    [ ! -d $DIRFROM/$file ] && { act=f; true; } || {
        [ $file = . -o $file = .. ] && act=n || { act=d
            [ -n "$NEGLECT" ] && { set $NEGLECT
                while true; do
                    [ -z "$1" ] && break
                    [ $file = $1 ] && { act=n; break; }
                    shift
                done
            }
            [ "$act" = d ] && { \
                [ -n "$LNDR_CNTR" -a -f $DIRFROM/$file/.lndr_skip ] && act=n && echo Skipping $file
                [ -n "$LNDR_CNTR" -a -f $DIRFROM/$file/.lndr_link ] && act=f && echo Setting up a link for $DIRFROM/$file
                [ -n "$LNDR_CNTF" ] && { \
                    lis1=`grep "^$DIRFROM/$file " $LNDR_CNTF | cut -f2-99 -d' '`
                    lis2=`sed -e "s,^,$DRFRLN/," < $LNDR_CNTF | grep "^$DIRFROM/$file " | cut -f2-99 -d' '`
                    lis="$lis1 $lis2"
                    set a $lis; shift
                    while true; do
                        [ -z "$1" ] && break
                        case $1 in
                            skip    )   act=n;;
                            link    )   act=f;;
                            real    )   act=r;;
                            *       )   ;;
                        esac; shift
                    done
                }
                [ -L $DIRFROM/$file -a "$act" = d ] && { \
                    [ -z "$FolSymLin" ] && act=f;
                    [ -n "$LNDR_CNTR" ] && { \
# Moved up                        [ -f $DIRFROM/$file/.lndr_link ] && act=f && echo Setting up a link for $DIRFROM/$file
                        [ -f $DIRFROM/$file/.lndr_real ] && act=d
                    }
                }
            }
        }
    }; [ "$act" = r ] && act=d

    if [ $act = f ]
    then
        lnk=`ls -ld $DIRFROM/$file | grep \>` && {
             set `echo $lnk | cut -f2 -d\>`; lnk=$1
             case $lnk in
                  "$DRFRLN"/* ) ln -s "$DRTOLN"/`echo $lnk | sed "s;$DRFRLN/;;"` $file ;;
                  /*          ) ln -s $DIRFROM/$file . ;;
                  ../*        ) cd $DIRFROM; cd `dirname $lnk`; tpwd=`pwd`; cd $pwd
                                case $tpwd in
                                    "$DRFRLN"/* | "$DRFRLN" ) ln -s $lnk $file ;;
                                    *           ) ln -s $DIRFROM/$file . ;;
                                esac;;
                  *           ) ln -s $lnk $file ;;
             esac; true
        } || ln -s $DIRFROM/$file .
    else
            if [ "$act" = d ]
            then
                    echo $file:
                    mkdir $file
                    (cd $file
                     pwd=`pwd`
                     case "$DIRFROM" in
                             /*) ;;
                             *)  DIRFROM=../$DIRFROM ;;
                     esac
                     if [ `(cd $DIRFROM/$file; pwd)` = $pwd ]
                     then
                            echo "$pwd: FROM and TO are identical!"
                            exit 1
                     fi
                     $0 $DIRFROM/$file
                    )
            fi
    fi
done
