#! /usr/bin/env ksh

#  VERSION : 05.03.98 19:38

[ "$1" = '' ] && { \
    echo "Usage: lns <Varid>"
    echo "        This will link the files to the DGSONNETMASK directory:"
    echo "                <Varid>.str --> struct.snn"
    echo "                <Varid>.trg --> targets.snn"
    echo "           equilibrium file --> equilibr.snn"
    echo "        to the Carre directory:"
    echo "                <Varid>.str --> dg.str"
    echo "                <Varid>.trg --> dg.trg"
    echo "                <Varid>.dgo --> dg.dgo"
    echo "           equilibrium file --> dg.equ"
    echo "        to the uinp directory:"
    echo "                <Varid>.dgo --> uinput.dg"
    echo "                <Varid>.trg --> uinput.trg"
    echo "        and to the baserun directory:"
    echo "                <Varid>.dgo --> param.dg"
    exit 4
}


[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
}
[ "$SOLPS_CENTRAL" = 'yes' ] && DEVICE=$DEVICE/$USER

# the directory where the DivGeo files will be stored
[ -z "$DGSONNETMASK" ] && DGSONNETMASK=${DG}/device/$DEVICE

[ -d "$DGSONNETMASK" ] || {
  print -u2 -n -- "The directory $DGSONNETMASK does not exist. Create it? (y/n) "
  while true; do {
    read u
    { case $u in
       (y|Y) mkdir -p "$DGSONNETMASK" || {
             print -u2 -- "Unable to create the directory. Check the permissions in ${DGSONNETMASK}%/*"
             break 2
             }; break;;
       (n|N) break 2;;
       ( * ) print -u2 -n -- "Please answer with either y or n: ";;
      esac; }
    }; done
  }

cp "$1".dgo "$1".str "$1".trg ${DGSONNETMASK}
ln -sf `pwd`/"$1".str ${DGSONNETMASK}/struct.snn
ln -sf `pwd`/"$1".trg ${DGSONNETMASK}/targets.snn
ln -sf `pwd`/"$1".dgo uinput.dg
ln -sf `pwd`/"$1".trg uinput.trg
ln -sf `pwd`/"$1".str dg.str
ln -sf `pwd`/"$1".trg dg.trg
ln -sf `pwd`/"$1".dgo dg.dgo
ln -sf `pwd`/"$1".dgo param.dg

e=`cat $1.trg | grep '# equil' | cut -f3 -d' '`

# check in case we are doing a limiter configuration
# and must fetch the real equilibrium from the .dgo file
typeset -i z
NAME=/tmp/lns.$USER.`date +%Y%m%d%H%M%S`
cat $1.dgo | grep 'lm_equ' | wc -l > $NAME
z=`cat $NAME`
[ $z -gt 0 ] && {
  l=`cat $1.dgo | grep 'lm_equ' | cut -f4 -d' '`
  [ -s $l ] && {
    echo Linking to limiter equilibrium $l
    e=$l
  } || {
    [ "X${l}X" -eq 'X-X' ] && {
      echo Default limiter equilibrium name provided: assuming a linear device case!
    } || {
      echo Limiter equilibrium file $l not found!
    }
  }
}
rm $NAME

case $e in
  ( ''   ) echo "$1.trg is in old format - no information on the equilibrium there"
           [ -r default.equ ] && { \
               ln -sf `pwd`/default.equ ${DGSONNETMASK}/equilibr.snn
               ln -sf `pwd`/default.equ dg.equ
                    echo '-- the default equilibrium file is used';
           } || echo '*** No default equilibrium file found (!!!)';;
  ( /*   ) ln -sf $e ${DGSONNETMASK}/equilibr.snn
           cp $e ${DGSONNETMASK}
           ln -sf $e dg.equ;;
  ( ../* ) (d=`dirname $e`; f=`basename $e`; cd $d;
           ln -sf `pwd`/$f ${DGSONNETMASK}/equilibr.snn
           cp $f ${DGSONNETMASK}
           ln -sf `pwd`/$f dg.equ);;
  ( ./*  ) (d=`dirname $e`; f=`basename $e`; cd $d;
           ln -sf `pwd`/$f ${DGSONNETMASK}/equilibr.snn
           cp $f ${DGSONNETMASK}
           ln -sf `pwd`/$f dg.equ);;
  (   *  ) ln -sf `pwd`/$e ${DGSONNETMASK}/equilibr.snn
           cp $e ${DGSONNETMASK}
           ln -sf `pwd`/$e dg.equ;;
esac
