#! /usr/bin/env ksh

#  VERSION : 05.03.98 19:38

[ "$1" = '' ] && { \
    echo "Usage: lns <Varid>"
    echo "        This will link the files to the Sonnet directory:"
    echo "                <Varid>.str --> struct.snn"
    echo "                <Varid>.trg --> targets.snn"
    echo "           equilibrium file --> equilibr.snn"
    echo "        to the Carre directory:"
    echo "                <Varid>.str --> dg.str"
    echo "                <Varid>.trg --> dg.trg"
    echo "                <Varid>.dgo --> dg.dgo"
    echo "           equilibrium file --> dg.equ"
    echo "        and to the uinp directory:"
    echo "                <Varid>.dgo --> uinput.dg"
    echo "                <Varid>.trg --> uinput.trg"
    exit 4
}


[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
}

CLASSDIR=${DG}/device/$DEVICE
[ -d "$CLASSDIR" ] || {
  print -u2 -n -- "The directory $CLASSDIR does not exist. Create it? (y/n) "
  while true; do {
    read u
    { case $u in
       (y|Y) mkdir -p "$CLASSDIR" || {
             print -u2 -- "Unable to create the directory. Check the permissions in ${CLASSDIR}%/*"
             break 2
             }; break;;
       (n|N) break 2;;
       ( * ) print -u2 -n -- "Please answer with either y or n: ";;
      esac; }
    }; done
  }

ln -sf `pwd`/"$1".str ${DG}/device/$DEVICE/struct.snn
ln -sf `pwd`/"$1".trg ${DG}/device/$DEVICE/targets.snn
ln -sf `pwd`/"$1".dgo uinput.dg
ln -sf `pwd`/"$1".trg uinput.trg
ln -sf `pwd`/"$1".str dg.str
ln -sf `pwd`/"$1".trg dg.trg
ln -sf `pwd`/"$1".dgo dg.dgo

e=`cat $1.trg | grep '# equil' | cut -f3 -d' '`
case $e in
  ( ''   ) echo "$1.trg is in old format - no information on the equilibrium there"
           [ -r default.equ ] && { \
               ln -sf `pwd`/default.equ ${DG}/device/$DEVICE/equilibr.snn
               ln -sf `pwd`/default.equ dg.equ
                    echo '-- the default equilibrium file is used';
           } || echo '*** No default equilibrium file found (!!!)';;
  ( /*   ) ln -sf $e ${DG}/device/$DEVICE/equilibr.snn
           ln -sf $e dg.equ;;
  ( ../* ) (d=`dirname $e`; f=`basename $e`; cd $d;
           ln -sf `pwd`/$f ${DG}/device/$DEVICE/equilibr.snn
           ln -sf `pwd`/$f dg.equ);;
  ( ./*  ) (d=`dirname $e`; f=`basename $e`; cd $d;
           ln -sf `pwd`/$f ${DG}/device/$DEVICE/equilibr.snn
           ln -sf `pwd`/$f dg.equ);;
  (   *  ) ln -sf `pwd`/$e ${DG}/device/$DEVICE/equilibr.snn
           ln -sf `pwd`/$e dg.equ;;
esac
