#! /usr/bin/env tcsh
set standalone="no"
set compress="no"

argloop:
  if ("X${1}X" == "X-zX") then
    set compress="-gz"
    echo run.log will be compressed
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    set standalone="yes"
    echo Asking for a B2.5 standalone run
    shift
    goto argloop
  endif

# Please note that some atd do not support SHELL environment
# and always use /bin/sh.

<< __EOF__  batch |& sed '/warning: commands will be executed using \/bin\/sh/d'
#!/bin/sh
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH

update_solps_run_status "Started on `hostname` at `date`"

if [ -s fort.1 -a ${standalone} = "no" ]; then
  if [ ${compress} = "-gz" ]; then
    time b2run ${argv} b2mn < fort.1 | gzip -9 > run.log.gz
  else
    time b2run ${argv} b2mn < fort.1 > run.log
  fi
else
  if [ ${compress} = "-gz" ]; then
    time b2run ${argv} -s b2mn | gzip -9 > run.log.gz
  else
    time b2run ${argv} -s b2mn > run.log
  fi
fi

update_solps_run_status "Finished on `hostname` at `date`"
__EOF__
