#! /bin/csh -f
if ($?LAST10) then
  set FILE=b2.log.last10
else
  set FILE=b2.log
endif
if (-x $SOLPSTOP/bin/$OBJECTCODE/zcat) then
    set ZCAT=$SOLPSTOP/bin/$OBJECTCODE/zcat
else if (-x $SOLPSMASTER/@sys/bin/zcat) then
    set ZCAT=$SOLPSMASTER/@sys/bin/zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT -f $FILE |\
  egrep 'B2BREM,B2RAD,B2QIE,B2VDP|ITER.*TIME' | \
  awk '/B2BREM,B2RAD,B2QIE,B2VDP/{b2brem=$2;b2rad=$3;b2qie=$4;b2vdp=$5}\
       /ITER.*TIME/{print $4,b2brem,b2rad,b2qie,b2vdp}' | \
  xyplot2 B2BREM B2RAD "Time" "" $PWD
