#! /bin/csh -f
if ($?SOLPSMDSSERVER) then
  echo MDSSERVER:$SOLPSMDSSERVER
else
  echo MDSSERVER:"solps-mdsplus.ipp.mpg.de:8002"
endif
echo date:`date`
echo dir:`cd .. ; pwd`
echo user:`whoami`
set hostname=`hostname`
set qualified_hostname=`nslookup $hostname |& awk '/^Name:/{print $2}'`
if ($qualified_hostname == '') set qualified_hostname=$hostname
echo hostname:$qualified_hostname
echo solpstop:$SOLPSTOP
if ($?OBJECTCODE) then
  echo objectcode:$OBJECTCODE
else
  echo objectcode:`which b2md.exe | sed -e 's:/[^/]*$::' | sed 's:^.*/::'`
endif
echo b2fstatiid:`md5sum b2fstati`
echo b2fstateid:`md5sum b2fstate`
echo b2fplasmaid:`md5sum ../b2fplasma`
echo b2fgmtryid:`md5sum b2fgmtry`
echo b2fratesid:`md5sum b2frates`
if (-s ../run.log) then
  echo jxijxajsep:`head -100000 ../run.log | grep jxi | head -1 | sed 's;.*:;;'`
else if (-s ../run.log.gz) then
  echo jxijxajsep:`zcat ../run.log.gz | head -100 | grep jxi | sed 's;.*:;;'`
else
  echo jxijxajsep:`echo jxi, jxa, jsep :  -2 -2 -2 | sed 's;.*:;;'`
endif
if (! -d $SOLPSTOP/.svn ) then
  set svn_version="Revision: -2"
else
  set svn_version=`cd $SOLPSTOP ; svn info | grep Revision:`
  if ("$svn_version" == '') set svn_version="Revision: -1"
endif
echo $svn_version
if (! -d $SOLPSTOP/.git ) then
  set git_version="git:None"
else
  set git_version="git:`cd $SOLPSTOP ; git describe --tags --always --dirty --abbrev`"
  if ("$git_version" == '') set git_version="git:None"
endif
echo $git_version
