#! /bin/csh -f
if ($?SOLPSMDSSERVER) then
  echo MDSSERVER:$SOLPSMDSSERVER
else
  echo MDSSERVER:"solps-mdsplus.aug.ipp.mpg.de:8002"
endif
echo date:`date`
echo dir:`cd .. ; pwd`
echo user:`whoami`
set hostname=`hostname`
set qualified_hostname=`nslookup $hostname |& awk '/^Name:/{print $2}'`
if ($qualified_hostname == '') set qualified_hostname=$hostname
echo hostname:$qualified_hostname
echo solpstop:$SOLPSTOP
echo objectcode:$OBJECTCODE
echo b2fstatiid:`md5sum b2fstati`
echo b2fstateid:`md5sum b2fstate`
echo b2fplasmaid:`md5sum ../b2fplasma`
echo b2fgmtryid:`md5sum b2fgmtry`
echo b2fratesid:`md5sum b2frates`
if (-e ../run.log) then
  echo jxijxajsep:`head -100 ../run.log | grep jxi | sed 's;.*:;;'`
else if (-e ../run.log.gz) then
  echo jxijxajsep:`zcat ../run.log.gz | head -100 | grep jxi | sed 's;.*:;;'`
else
  echo jxijxajsep:`echo jxi, jxa, jsep :  -2 -2 -2 | sed 's;.*:;;'`
endif
if (! -d $SOLPSTOP/.svn ) then
  set svn_version="Revision: -2"
else
  set svn_version=`cd $SOLPSTOP ; svn info | grep Revision:`
  if ("$svn_version" == '') set svn_version="Revision: -1"
endif
echo $svn_version
