#! /usr/bin/env tcsh

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
set JOB_NAME="SOLPS-ITER"
set PROCS=1
set THREADS=1
set hours=24
set mem=4GB
set chain="unset"
set job_count=0
echo Your email is $EMAIL

set compress=""
set MPIOPTS=""
set standalone="no"
set exclusive=""

setenv SOLPSTOP "`determine_SOLPSTOP`"
if ($SOLPSTOP == "") then
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
endif

argloop:
  if ("X${1}X" == "X-hX") then
    cat <<EOF

Help for $0

This script is used to submit SOLPS-ITER jobs to the SLURM batch system on the MEPHI cluster.

Usage:

  `basename $0` {options} {<<SCRIPT>>}

where the optional <<SCRIPT>> is the SLURM submission file to be used

Available options are:
  -j <<JOB NAME>>    set the job name (default $JOB_NAME)
  -z                 compress run.log using gzip
  -s                 specify a standalone B2.5 run
  -x                 requests an exclusive job allocation
  -c <<JOB_ID>>      job ID of the previous job in a chain submission
  -m <<MPI OPTIONS>> use the MPI options specified (default serial version)
  -t <<THREADS>>     use OpenMP parallelization with <<THREADS>> threads (default $THREADS)
  -T <<HOURS>>       number of elapsed hours requested (default $hours)
  -M <<MEM_SIZE>>    memory size (default $mem)

EOF
    exit
  endif
  if ("X${1}X" == "X-jX") then
    shift
    set JOB_NAME="$1"
    echo Job name is ${JOB_NAME}
    shift
    goto argloop
  endif
  if ("X$1X" == "X-zX") then
    set compress="-gz"
    echo run.log will be compressed
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    set standalone="yes"
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5"
    echo Asking for a B2.5 standalone run
    shift
    goto argloop
  endif
  if ("X$1X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set MPIOPTS="$1"
    echo Using MPI options: $MPIOPTS
    set PROCS=`echo $MPIOPTS | awk.transpose | grep -A 1 "\-np" | tail -n 1`
    echo Asking for MPI run with a total of $PROCS processors
    shift
    goto argloop
  endif
  if ("X$1X" == "X-tX") then
    shift
    if (! $?SOLPS_OPENMP) then
      source $SOLPSTOP/SETUP/openmp
      set OPENMP_SET=yes
    endif
    set THREADS="$1"
    echo Asking for OpenMP run with $THREADS threads
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-TX") then
    shift
    set hours="$1"
    if ( $hours == 1) then
      echo Requested time is ${hours} hour
    else
      echo Requested time is ${hours} hours
    endif
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-MX") then
    shift
    set mem="$1"
    echo Requested memory is ${mem}
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-cX") then
    shift
    if ($chain == "unset") then
      set chain="$1"
    else
      set chain="$chain,$1"
    endif
    @ job_count= ( $job_count + 1 )
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-xX") then
    shift
    set exclusive="--exclusive"
    echo Requesting an exclusive job allocation
    goto argloop
  endif

if ($1 == "") then
  if (-s fort.1 && $standalone == "no") then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for SBATCH.mephi_coupled$compress
    set QSUB=`climb_and_look_for SBATCH.mephi_coupled$compress`
    if ($QSUB == "//SBATCH.mephi_coupled$compress") then
      if (-s $SOLPSTOP/runs/SBATCH.mephi_coupled$compress) then
        set QSUB="$SOLPSTOP/runs/SBATCH.mephi_coupled$compress"
      else
        set QSUB=""
      endif
    endif
  else
    if ($standalone == "no") echo No fort.1 file found: reverting to a standalone run
    echo No argument is specified. Looking for SBATCH.mephi$compress
    set QSUB=`climb_and_look_for SBATCH.mephi$compress`
    if ($QSUB == "//SBATCH.mephi$compress") then
      if (-s $SOLPSTOP/runs/SBATCH.mephi$compress) then
        set QSUB="$SOLPSTOP/runs/SBATCH.mephi$compress"
      else
        set QSUB=""
      endif
    endif
  endif
else if (-s $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    if (-s $SOLPSTOP/runs/$1) then
      set QSUB="$SOLPSTOP/runs/$1"
      echo Submission file $QSUB is found
    else
      set QSUB=""
    endif
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No MEPHI submission file $1 found. Exiting.
  exit 1
endif

echo Using submission file template $QSUB
if ($chain == "unset") then
  echo For loop resubmission following options will be used: $LOOP_OPTS
else if ($job_count == 1) then
  echo Chain submission following job number ${chain}
else if ($job_count > 1) then
  echo Chain submission following job numbers ${chain}
endif

sed \
  -e 's:#PWD#:'$PWD':g' \
  -e 's:#SOLPSTOP#:'$SOLPSTOP':g' \
  -e 's:#EMAIL#:'$EMAIL':g' \
  -e "s:#MPIOPTS#:'$MPIOPTS':g" \
  -e "s:#PROCS#:'$PROCS':g" \
  -e "s:#THREADS#:'$THREADS':g" \
  -e 's:#MEM#:'$mem':g' \
  -e 's:#HOURS#:'$hours':g' \
  -e "s:#JOBNAME#:'$JOB_NAME':g" \
  -e 's:#USER#:'$USER':g' \
  < $QSUB > $NAME

if ($chain != "unset") then
  set b2run_line=`grep -n "b2run" $NAME | cut -d ':' -f 1`
  @ before_line = $b2run_line - 1
  head -n ${before_line} $NAME > SBATCH.mephi.after_$chain
  echo "mv run.log.gz run.log.$chain.gz" >> SBATCH.mephi.after_$chain
  echo "mv b2mn.prt b2mn.prt.$chain" >> SBATCH.mephi.after_$chain
  echo "mv b2fstate b2fstati" >> SBATCH.mephi.after_$chain
  echo "if (-e b2favere) mv b2favere b2faveri" >> SBATCH.mephi.after_$chain
  set all_lines=`cat $NAME | wc -l`
  @ tail_lines = $all_lines - $before_line
  tail -n $tail_lines $NAME >> SBATCH.mephi.after_$chain
  set NAME=SBATCH.mephi.after_$chain
endif

update_solps_run_status -n "Submitted at `date`"

echo sbatch $NAME
echo $NAME
if ($chain == "unset") then
  sbatch ${exclusive} $NAME
else
  sbatch ${exclusive} --dependency=afterok:${chain} $NAME
endif

rm -f $NAME

