#! /usr/bin/env tcsh

cd ../b2mn.exe.dir
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:b2.*_save.parameters:'`)
set recoverfile=`echo $i:t:r`
if ($recoverfile != 'b2.dummy_save.parameters') mv -v `basename $i` ../$recoverfile
end
if (${COMPILER} == "HP") then
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:ftn13:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:ftn15:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:ftn44:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:ftn46:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
else
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:fort.13:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:fort.15:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:fort.44:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:fort.46:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
endif
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:b2time.nc:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:b2wall.nc:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:b2movies.nc:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:b2tallies.nc:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:run_av/run_av:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../b2favere || echo > /dev/null
end
cd ../b2co.exe.dir
