#! /usr/bin/env tcsh

foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:b2.*_save.parameters:'`)
set recoverfile=`echo $i:t:r`
if ($recoverfile != 'b2.dummy_save.parameters') mv -v `basename $i` ../$recoverfile
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:fort.44:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../$recoverfile || echo > /dev/null
end
foreach i (`echo $PLASMASTATE:t | sed -e 's:plasmastate:run_av/run_av:'`)
set recoverfile=`echo $i:t:r`
[ -e $recoverfile ] && mv -v `basename $i` ../b2favere || echo > /dev/null
end

