#! /bin/tcsh -f
# plots the flux of (arg)3dl and (arg)3dr
# -l ==> log
set file=b2mn.exe.dir/b2time.nc
if (! -e $file) set file=b2time.nc
if( "$1" == "-l" ) then
  set log="T"
  shift
else
  set log="F"
endif
if( "$1" == "" ) then
  set field="tp"
else
  set field=$1
endif
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif
set tfilename=${tmpdir}tmp.mtv
set tfilenam1=${tmpdir}tmp.mtv.01
set tfilenam2=${tmpdir}tmp.mtv.02
set pfilename=${tmpdir}tmp.ps
setenv MTV_WRB_COLORMAP ON
if (-e $SOLPSTOP/data.local/palettes/plotmtv_white.map) then
  setenv COLORMAP $SOLPSTOP/data.local/palettes/plotmtv_white.map
else
  setenv COLORMAP $SOLPSTOP/data/palettes/plotmtv_white.map
endif
echo '$' DATA=CONTOUR >! $tfilename
echo '%' nx = `cat dsl dsr | wc -l` xgrid=True xlabel=x-xsep>> $tfilename
cat dsl | awk.reverse | awk '{print -0.1-$1}' >> $tfilename
cat dsr | awk '{print 0.1+$1}' >> $tfilename
echo '%' ny = `nc2text $file timesa | wc -w`  ygrid=True ylabel=time>> $tfilename
nc2text $file timesa >> $tfilename
if ($log == "T") then
  echo '%' contfill = T  equalscale = F logsteps=10 toplabel=$field >> $tfilename
else
  echo '%' contfill = T  equalscale = F nsteps=20 toplabel=$field >> $tfilename
endif
( nc2text -n 999999 $file ${field}3dl ) | awk.reverse.columns >! $tfilenam1
( nc2text -n 999999 $file ${field}3dr ) >! $tfilenam2
switch ($field)
case t[ei]:
  paste $tfilenam1 $tfilenam2 | awk '{for (i=1;i<=NF;i++) printf "%s ",$i/1.602176565e-19; printf "\n"}' >> $tfilename
  breaksw
default:
  paste $tfilenam1 $tfilenam2 >> $tfilename
endsw
echo '$' END >> $tfilename
echo n | plotmtv -colorps -noxplot -o $pfilename $tfilename
