#! /bin/tcsh -f
# plots the value of (arg)3dl and (arg)3dr
# -l ==> log
set file=b2mn.exe.dir/b2time.nc
if (! -e $file) set file=b2time.nc
if( "$1" == "-l" ) then
  set log="T"
  shift
else
  set log="F"
endif
if( "$1" == "" ) then
  set field="te"
else
  set field=$1
endif
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif
set tfilename=${tmpdir}tmp.mtv
set tfilenam1=${tmpdir}tmp.mtv.01
set tfilenam2=${tmpdir}tmp.mtv.02
set pfilename=${tmpdir}tmp.ps
setenv MTV_WRB_COLORMAP ON
if (-s $SOLPSTOP/data.local/palettes/plotmtv_white.map) then
  setenv COLORMAP $SOLPSTOP/data.local/palettes/plotmtv_white.map
else
  setenv COLORMAP $SOLPSTOP/scripts/palettes/plotmtv_white.map
endif
which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
if (-e b2mn.exe.dir/.netcdf4) then
  ln -sf $file ${tmpdir}b2time.nc.tmp
  set file=${tmpdir}b2time.nc.tmp
  gtfl $file
  set netcdf4=1
else
  set netcdf4=0
endif
echo '$' DATA=CONTOUR >! $tfilename
set dsleft=b2mn.exe.dir/dsl
if (! -s $dsleft) set dsleft=dsl
set dsLEFT=b2mn.exe.dir/dsL
if (! -s $dsLEFT) set dsLEFT=dsL
set dsright=b2mn.exe.dir/dsr
if (! -s $dsright) set dsright=dsr
set dsRIGHT=b2mn.exe.dir/dsR
if (! -s $dsRIGHT) set dsRIGHT=dsR
echo '%' nx = `cat $dsleft $dsright | wc -l` xgrid=True xlabel=x-xsep>> $tfilename
cat $dsleft | awk.reverse | awk '{print -0.1-$1}' >> $tfilename
cat $dsright | awk '{print 0.1+$1}' >> $tfilename
if ($no_nc2text == 1) then
  echo '%' ny = `ncdump $file -f f -v timesa | awk 'BEGIN {ORS="";} /data:/{found1=1;next;} /timesa/{if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}} END {print "\n";}' | sed 's/,/ /g' | sed 's/;//g' | wc -w` ygrid=True ylabel=time >> $tfilename
  ncdump $file -f f -v timesa | awk 'BEGIN {ORS="";} /data:/{found1=1;next;} /timesa/{if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}} END {print "\n";}' | sed 's/,/ /g' | sed 's/;//g' | awk.transpose >> $tfilename
else
  echo '%' ny = `nc2text $file timesa | wc -w` ygrid=True ylabel=time >> $tfilename
  nc2text $file timesa | awk.transpose >> $tfilename
endif
if ($log == "T") then
  echo '%' contfill = T equalscale = F logsteps=10 toplabel=$field >> $tfilename
else
  echo '%' contfill = T equalscale = F nsteps=20 toplabel=$field >> $tfilename
endif
if ($no_nc2text == 1) then
  ( cat $dsLEFT | tr '\n' ' ' ; echo " " ; ncdump $file -f f -v ${field}3dl | awk -v string="${field}3dl" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print ${field}3dl; else {print $3;found2=1;}}}' | awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' ) >! $tfilenam1
  ( cat $dsRIGHT | tr '\n' ' ' ; echo " " ; ncdump $file -f f -v ${field}3dl | awk -v string="${field}3dl" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print ${field}3dl; else {print $3;found2=1;}}}' | awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' ) >! $tfilenam2
else
  ( cat $dsLEFT | tr '\n' ' ' ; echo " " ; nc2text -n 999999 $file ${field}3dl ) >! $tfilenam1
  ( cat $dsRIGHT | tr '\n' ' ' ; echo " " ; nc2text -n 999999 $file ${field}3dr ) >! $tfilenam2
endif
paste $tfilenam1 $tfilenam2 >> $tfilename
echo '$' END >> $tfilename
echo n | plotmtv -colorps -noxplot -o $pfilename $tfilename

if ($netcdf4 == 1) then
  rm $file
endif
