#! /bin/tcsh -f
set file=b2mn.exe.dir/b2time.nc
if (! -e $file) set file=b2time.nc
if( "$1" == "-l" ) then
  set log="T"
  shift
else
  set log="F"
endif
if( "$1" == "" ) then
  set field="ne3da"
else
  set field=$1
endif
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif
set tfilename=${tmpdir}tmp.mtv
set pfilename=${tmpdir}tmp.ps
set prefix=`echo $field | sed 's:^\(.\).*:\1:'`
set pr2fix=`echo $field | cut -c2`
set suffix=`echo $field | sed 's:^.*\(.\):\1:'`
echo '$' DATA=CONTOUR >! $tfilename
echo '%' nx = `wc -l < ds$suffix` xgrid=True xlabel=x-xsep>> $tfilename
cat ds$suffix >> $tfilename
echo '%' ny = `nc2text $file timesa | wc -w`  ygrid=True ylabel=time>> $tfilename
nc2text $file timesa >> $tfilename
if ($log == "T") then
  echo '%' contfill = T  equalscale = F logsteps=10 toplabel=$field >> $tfilename
else
  echo '%' contfill = T  equalscale = F nsteps=20 toplabel=$field >> $tfilename
endif
if ($prefix == "t" && $pr2fix != "p") then
  nc2text $file $field | tr ' ' '\n' | awk 'NF>0{print $1/1.602176565e-19}' >> $tfilename
else if ($prefix == "f") then
  if ($suffix == "r") then
    ( cat ds`echo $suffix | tr 'a-z' 'A-Z'` | tr '\n' ' ' ; echo " " ; nc2text -n 999999 $file $field ) | awk 'NR==1{for (i=1;i<=NF;i++) dsR[i]=$i}NR>1{for (i=1;i<=NF;i++) printf "%s ",$i/dsR[i];printf "\n"}' >> $tfilename
  else
    ( cat ds`echo $suffix | tr 'a-z' 'A-Z'` | tr '\n' ' ' ; echo " " ; nc2text -n 999999 $file $field ) | awk 'NR==1{for (i=1;i<=NF;i++) dsR[i]=$i}NR>1{for (i=1;i<=NF;i++) printf "%s ",-$i/dsR[i];printf "\n"}' >> $tfilename
  endif
else
  nc2text $file $field >> $tfilename
endif
echo '$' END >> $tfilename
echo n | plotmtv -colorps -noxplot -o $pfilename $tfilename
