#! /bin/tcsh -f
set file=b2mn.exe.dir/b2time.nc
if (! -s $file) set file=b2time.nc
if( "$1" == "-l" ) then
  set log="T"
  shift
else
  set log="F"
endif
if( "$1" == "" ) then
  set field="ne3da"
else
  set field=$1
endif
set f2eld=`echo $field | sed 's:P$::'`
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif
set tfilename=${tmpdir}tmp.mtv
set pfilename=${tmpdir}tmp.ps
set prefix=`echo $field | sed 's:^\(.\).*:\1:'`
set pr2fix=`echo $field | cut -c2`
set suffix=`echo $field | cut -c5-`
set suf2ix=`echo $field | cut -c5`
which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
if (-e b2mn.exe.dir/.netcdf4) then
  ln -sf $file ${tmpdir}b2time.nc.tmp
  set file=${tmpdir}b2time.nc.tmp
  gtfl $file
  set netcdf4=1
else
  set netcdf4=0
endif
echo '$' DATA=CONTOUR >! $tfilename
set dsf2le=b2mn.exe.dir/ds$suf2ix
if (! -s $dsf2le) set dsf2le=ds$suf2ix
echo '%' nx = `wc -l < $dsf2le` xgrid=True xlabel=x-xsep>> $tfilename
cat $dsf2le >> $tfilename
if ($no_nc2text == 1) then
  echo '%' ny = `ncdump $file -f f -v timesa | awk 'BEGIN {ORS="";} /data:/{found1=1;next;} /timesa/{if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}} END {print "\n";}' | sed 's/,/ /g' | sed 's/;//g' | wc -w` ygrid=True ylabel=time >> $tfilename
  ncdump $file -f f -v timesa | awk 'BEGIN {ORS="";} /data:/{found1=1;next;} /timesa/{if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}} END {print "\n";}' | sed 's/,/ /g' | sed 's/;//g' >> $tfilename
else
  echo '%' ny = `nc2text $file timesa | wc -w` ygrid=True ylabel=time >> $tfilename
  nc2text $file timesa >> $tfilename
endif
if ($log == "T") then
  echo '%' contfill = T equalscale = F logsteps=10 toplabel=$field >> $tfilename
else
  echo '%' contfill = T equalscale = F nsteps=20 toplabel=$field >> $tfilename
endif
set dsfile=b2mn.exe.dir/ds`echo $suffix | tr 'a-z' 'A-Z'`
if (! -s $dsfile) set dsfile=ds`echo $suffix | tr 'a-z' 'A-Z'`
if ($no_nc2text == 1) then
  if ($prefix == "t" && $pr2fix != "p") then
    ncdump $file -f f -v $f2eld | awk 'BEGIN {ORS="";} /data:/{found1=1;next;} /timesa/{if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}} END {print "\n";}' | sed 's/,/ /g' | sed 's/;//g' | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' >> $tfilename
  else if ($prefix == "f") then
    if ($suf2ix == "r") then
      ( cat $dsfile | tr '\n' ' ' ; echo " " ; ncdump $file -f f -v $f2eld | awk -v string="$field" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $field; else {print $3;found2=1;}}}' | awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' ) | awk 'NR==1{for (i=1;i<=NF;i++) dsR[i]=$i}NR>1{for (i=1;i<=NF;i++) printf "%s ",$i/dsR[i];printf "\n"}' >> $tfilename
    else
      ( cat $dsfile | tr '\n' ' ' ; echo " " ; ncdump $file -f f -v $f2eld | awk -v string="$field" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $field; else {print $3;found2=1;}}}' | awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' ) | awk 'NR==1{for (i=1;i<=NF;i++) dsR[i]=$i}NR>1{for (i=1;i<=NF;i++) printf "%s ",-$i/dsR[i];printf "\n"}' >> $tfilename
    endif
  else
    ncdump $file -f f -v $f2eld | awk -v string="$field" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $field; else {print $3;found2=1;}}}' | awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' >> $tfilename
  endif
else
  if ($prefix == "t" && $pr2fix != "p") then
    nc2text $file $f2eld | tr ' ' '\n' | awk 'NF>0{print $1/1.602176634e-19}' >> $tfilename
  else if ($prefix == "f") then
    if ($suf2ix == "r") then
      ( cat $dsfile | tr '\n' ' ' ; echo " " ; nc2text -n 999999 $file $f2eld ) | awk 'NR==1{for (i=1;i<=NF;i++) dsR[i]=$i}NR>1{for (i=1;i<=NF;i++) printf "%s ",$i/dsR[i];printf "\n"}' >> $tfilename
    else
      ( cat $dsfile | tr '\n' ' ' ; echo " " ; nc2text -n 999999 $file $f2eld ) | awk 'NR==1{for (i=1;i<=NF;i++) dsR[i]=$i}NR>1{for (i=1;i<=NF;i++) printf "%s ",-$i/dsR[i];printf "\n"}' >> $tfilename
    endif
  else
    nc2text $file $f2eld >> $tfilename
  endif
endif
echo '$' END >> $tfilename
echo n | plotmtv -colorps -noxplot -o $pfilename $tfilename

if ($netcdf4 == 1) then
  rm $file
endif
