#! /bin/tcsh -f
if (! -e .na_feedback) then
  grep na_feedback_rescale run.log | awk '{print $2}' | sort | uniq | wc -l > .na_feedback
endif
set NNA=`cat .na_feedback`

pipe_run.log | \
  grep "na_feedback_rescale   $1" | \
  awk '{print NR,$3,$4}' | xyplot2 curr targ
