#! /bin/tcsh -f
if ("X$1" == "Xl") then
  set log="l"
  shift
else
  set log=""
endif
if ("X$1" == "X") then
  set species=0
else
  set species=$1
endif
set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-s $solps_fluids) then
  setenv SOLPS_FLUIDS `cat $solps_fluids`
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on $solps_fluids)"
else
  setenv SOLPS_FLUIDS "`get_solps_fluids`"
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on log file)"
endif
set local_fluids=( $SOLPS_FLUIDS )
@ speciesp = $species + 1
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set freg=$nnreg[3]
if ("" == $vreg) set vreg=4
if ("" == $freg) set freg=13
@ vregP = $vreg + 1
pipe_run.log | \
  egrep -a ^nareg\|^volreg | \
  awk '/nareg/{ic=1;for (i=0;ic<NF;i++) for (j=0;j<='$vreg';j++) {ic++;na[i,j]=$ic}}\
       /volreg/{for (j=0;j<='$vreg';j++) {vol[j]=$(j+2);\
                  printf "%s ",na['$species',j]/vol[j]};printf "\n"}' | \
  nl | \
  plot x${log}yplot$vregP `count 0 $vreg` iteration $local_fluids[$speciesp]
