#! /bin/csh -f
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set freg=$nnreg[3]
if ("" == $vreg) set vreg=4
if ("" == $freg) set freg=13
@ vregP = $vreg + 1
pipe_run.log | \
  egrep -a '^nereg '\|'^volreg ' | \
  awk '/nereg/{for (i=2;i<=NF;i++) {ne[i]=$i}}\
       /volreg/{for (i=2;i<=NF;i++) printf "%s ",ne[i]/$i;printf "\n"}' | \
  nl | \
  plot x"$1"yplot$vregP `count 0 $vreg` iter "ave ne" $PWD
