#! /bin/csh -f
set dfilename=feedback.data
set pfilename=feedback.ps
setenv GNUPLOT_POSTSCRIPT_OPTIONS 'color solid noenhanced'
setenv GNUPLOT_DATA $dfilename
setenv PRINT_PLOT $pfilename
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG = 4
switch ($NREG)
  case "1":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10}' | sed '$d' | x{$1}yplot3 current target control Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "2":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10}' | sed '$d' | x{$1}yplot3 current target control Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "4":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10}' | sed '$d' | x{$1}yplot3 current target control Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "5":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10}' | sed '$d' | x{$1}yplot3 current target control Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "7":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10}' | sed '$d' | x{$1}yplot3 current target control Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "8":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,($10+$11)}' | sed '$d' | x{$1}yplot3 current target control Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw

