#! /bin/csh -f
set dfilename=feedback.data
set pfilename=feedback.ps
setenv GNUPLOT_POSTSCRIPT_OPTIONS 'color solid'
setenv GNUPLOT_DATA $dfilename
setenv PRINT_PLOT $pfilename
set nreg=`climb_and_look_for NREG`
if (-e $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
endif
if (! $?NREG) set NREG = 4
if (-e b2mn.dat) then
  set rescale = `egrep -i 'b2mndr_rescale_neutrals_sources' b2mn.dat | sed -e 's/b2mndr_rescale_neutrals_sources//' | sed -e "s/'//g" `
else
  set rescale = 1.0e-10
endif
switch ($NREG)
  case "1":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10/'$rescale'/1000}' | sed '$d' | x{$1}yplot3 current target control/1e3 Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "2":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10/'$rescale'/1000}' | sed '$d' | x{$1}yplot3 current target control/1e3 Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "4":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10/'$rescale'/1000}' | sed '$d' | x{$1}yplot3 current target control/1e3 Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "5":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,$10/'$rescale'/1000}' | sed '$d' | x{$1}yplot3 current target control/1e3 Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  case "8":
    pipe_run.log | grep -a nesepm_curr | awk '{print NR,$2,$5,($10+$11)/'$rescale'/1000}' | sed '$d' | x{$1}yplot3 current target control/1e3 Iteration_no density_or_flux `noquote_pwd 3`
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
