#! /bin/csh -f
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set xreg=$nnreg[3]
set yreg=$nnreg[4]
if ("" == $vreg) set vreg=4
if ("" == $xreg) set xreg=6
if ("" == $yreg) set yreg=7
@ vregP = $vreg + 1
pipe_run.log | \
  egrep -a '^nireg '\|'^volreg ' | \
  awk '/nireg/{for (i=2;i<=NF;i++) {ni[i]=$i}}\
       /volreg/{for (i=2;i<=NF;i++) printf "%s ",ni[i]/$i;printf "\n"}' | \
  nl | \
  plot x"$1"yplot$vregP `count 0 $vreg` iter "ave ni" $PWD
