#! /bin/csh -f
if ($1 == "") then
  echo `pwd`
else
  if($2 == "") then
    set join="/"
  else
    set join=$2
  endif
  set dir=`pwd`
  if($3 != "") then
    set cnt=$3
    while ($cnt > 0)
      set dir=`dirname $dir`
      @ cnt -= 1
    end
  endif   
  set res=`basename $dir`
  set cnt=$1
  @ cnt -= 1
  while ($cnt > 0)
    set dir=`dirname $dir`
    set res=`basename $dir`"$join"$res
    @ cnt -= 1
  end
  echo $res
endif
