#! /bin/ksh

#Braams-Eirene  fluxes  (Units Particles-s**-1) 1 species

filename=tracing/blnn.trc
dir=`dirname $filename`

[ ! -d $dir ] && { echo "$dir does not exist!!!"; exit 33; }
( cd $dir; rm -f particle_*  >/dev/null 2>&1 )
[ ! -r $filename ] && { echo "$filename does not exist!!!"; exit 33; }

 
# check to see if columns are right (optional)
cat  $filename \
  | head -2 | tail -1 \
  | awk '{ print $1, $41 , $34, $35, $36, $37, $38, $39, $40}' \
  > $dir/particle_header

titlex=`awk '{print $1}' $dir/particle_header`
title1=`awk '{print $2}' $dir/particle_header`
title2=`awk '{print $3}' $dir/particle_header`
title3=`awk '{print $4}' $dir/particle_header`
title4=`awk '{print $5}' $dir/particle_header`
title5=`awk '{print $6}' $dir/particle_header`
title6=`awk '{print $7}' $dir/particle_header`
title7=`awk '{print $8}' $dir/particle_header`
title8=`awk '{print $9}' $dir/particle_header`


cat  $filename \
  | tail -n +3 \
  | awk '{ print $1, $41 , $34, $35, $36, $37, $38, $39, $40}' \
  | plot xyplot8 $title1 $title2 $title3 $title4 $title5 $title6 $title7 $title8  $titlex '(part-s^-1)' $PWD

