#! /usr/bin/ksh
# plotsum_id
# Usage: plotsum_id xcolumn ycolumn
# e.g for ns_Zeff plot plotsum_id 19 11
# precede by plotsum_id to associate symbols with shot numbers
# plots symbols at a distance dxshot, dyshot from each point connected by arrow to point
# complete data for each shot from $in, where shotID is given in first column by ${symbol}_${shotnumber}
# to plot legend on same plot run plotsum_legend
# output are lines to be included in gnuplot .cmd file. These are placed in $out

#  VERSION : 29.08.2003 23:17

scriptname=`basename $0`
scriptdir=`dirname $0`

xcolumn=$1
ycolumn=$2
dyshot=${DDY_PLOTSUM:-0.04}
dxshot=${DDX_PLOTSUM:-0.004}
out=summary/shot_cmd
in=summary/shot_list
temp=summary/tempshot
rm -f $temp $out > /dev/null 2>&1

#(xxxto avoid misreading leading minus)
set -A shot xxx `cat $in | cut -f1`
set -A xpoint xxx `cat $in | cut -f${xcolumn}`
set -A ypoint xxx `cat $in | cut -f${ycolumn}`
set -A symbol xxx `cat $in | cut -c1`
xshot[1]=xxx 
yshot[1]=xxx 

shotlist=${shot[*]}

i=0
for ff in $shotlist; do {
  [ $i -gt 0 ] && {
    yshot[$i]=`echo "a=${ypoint[$i]} + $dyshot\na\nquit" | bc`
    xshot[$i]=`echo "a=${xpoint[$i]} + $dxshot\na\nquit" | bc`
  }
  let "i=i+1"
}; done

i=0
> $out
for ff in $shotlist; do {
  [ $i -gt 0 ] && {
    echo "set label \"${symbol[$i]}\" at ${xshot[$i]},${yshot[$i]} center" >> $out
    echo "set arrow from ${xpoint[$i]},${ypoint[$i]} to ${xshot[$i]},${yshot[$i]} nohead" >> $out
  }
  let "i=i+1"
}; done

