#! /usr/bin/ksh

# Produce the profiles along the targets

#  VERSION : 25.01.2005 22:50

ps4_map='3 2 4 5 6 7'
[ -s ld_tg_ou.dat ] && ps4_map="$ps4_map 8 9" 
OOFILE='targ_prf'
OFILE="$OOFILE".ps

unset sep noprint
case "$1" in
  -n ) noprint=y;;
  '' ) ;;
  *  ) print -u2 "Usage: ${0##*/} [-n]"
       print -u2 "   Plots the profiles (load, ne, Te) along the targets"
       print -u2 "   Does not send the file to the printer if called with -n"
       exit 2;;
esac

export PLOT_IT_STEM=plot_trg

#alias CPP='/usr/lib/cpp -P'

[ -s VarID ] && [ -r VarID ] && {
  L=`cat VarID | cut -f1 -d_ | cut -f2 -d#`
  LL=`cat VarID | tr _ ' '`
  [ -s time_dep/traces ] && [ time_dep/traces -nt Label ] && write_time_mark
  [ -r Label ] && LL="$LL `cat Label`"
  true
} || {
  L=000
  LL="${PWD#$SOLPSTOP}"
}

# Check whether the data files are in old format, and correct them if necessary

for s in ld fp; do {
  for i in i o; do {
    f=${s}_tg_$i.dat
    [ "`head -c1 $f`" = \# ] || {
      mv $f ${f}~
      (print '#\c'; cat ${f}~) > $f
    }
  }; done
}; done

#set -x
plot_set -f "$OFILE" -t "$LL" targets.prf
#set +x
#exit

#if [ -s $OFILE ]; then {
#  if [ -z "$noprint" ]; then {
#    ps4 $OFILE -n ${ps4_map}
#    [ -s ${OOFILE}4.ps ] && print_file -Pc ${OOFILE}4.ps &
#  }; fi
#}; fi
