#! /usr/bin/env ksh

#  VERSION : 08.07.2002 16:10

# Plot the data specified in a control file.

# This is a version with "functions" introduced instead of the recursive calls.
# It had appeared to be significantly slower (2 seconds instead of 1 on a simple file)!
# However, later on the timing has shown the opposite trend: functions are faster.

# Next things to be done:
#   - axis limits in a regular way
#   - using old cmd file if it exists and is newer than the control file

#========================================================================================
function get_header {
#!!!{
#          print -u2 -- "==>> get_header.  pattern :$1:"                #!!!
#          print -r "==>> get_header.  pattern :$1:"                    #!!!
#          echo `echo "$header"`                                        #!!!
#          print -r "header :$header:"                                  #!!!
#!!!}

# Input :
#   $1	   : pattern to search
#   header : file header with newline-separated fields
# Output:
#   match    : number of matching columns
#   columns  : list of their indices
#   suffixes : list of suffixes

# Check the pattern for the presense of wildcard

    match=0
    unset s1 s2 wldc left_field right_field
    for s in \% \@ \! \~ \= \+ \- \? \, \^ \& \# \$ \. \: \; \< \> \|; do {
      { case "$1" in
	( *${s}* ) ;;
	( *	 ) [ -z "$s1" ] && s1="$s" || {
		     s2="$s"
		     break
		   };;
      esac; }
    }; done

#    echo "s1 :$s1:   s2 :$s2:"                                          #!!!

    [ -n "$s2" ] && {
      redpat=`print -r "$1" | sed -e "s/\\\\\\\\\\\\\\\\/\\\\${s1}/g" -e "s/\\\\\\\\\\*/\\\\${s2}/g"`
#      print -r "redpat :$redpat:"                                       #!!!
      { case "$redpat" in
	( *\**\** ) print -u2 "$NAME: more than one '*' wildcard in a column name"
		    print -u2 "column :$redpat:,  line $il, section $is, page $ip, ID $pid"
		    print -u2 "Type '$NAME -h' for help"
		    ;;
	( *'*'*   ) wldc=y
		    left_field=`print "${redpat%\**}" | sed -e "s/\\\\${s1}/\\\\\\\\\\\\\\\\/g" -e "s/\\\\${s2}/\\\\\\\\\\*/g"`
		    right_field=`print "${redpat#*\*}" | sed -e "s/\\\\${s1}/\\\\\\\\\\\\\\\\/g" -e "s/\\\\${s2}/\\\\\\\\\\*/g"`
		    ;;
	( *	  ) wldc=n;;
      esac; }
      true
    } || {
      print -u2 "$NAME: too complicated search pattern for the column name"
      print -u2 "  column :$1:,  line $il, section $is, page $ip, ID $pid"
      print -u2 "  Try to reduce the number of non-alphabetic characters in the column names"
    }
    [ "$wldc" != y ] && [ "$wldc" != n ] && {
      print -u2 "$NAME: unexpected error. wldc must be either 'y' or 'n'"
      print -u2 "  column :$1:,  line $il, section $is, page $ip, ID $pid"
      wldc=
    }

#    echo "wldc :$wldc:   left :$left_field:   right :$right_field:"

    [ -n "$wldc" ] && {

# Look for the pattern in the header string

      redpat=`print -r "$redpat" | sed -e "s/\\\*/\\\.\\\*/" -e "s/\\\\${s1}/\\\\\\\\\\\\\\\\/g" -e "s/\\\\${s2}/\\\\\\\\\\*/g"`
#      echo "redpat for grep :$redpat:"                                   #!!!
      print "$header" | grep -n "^$redpat\$" > $tmpfile
#      echo "\nAfter grep:\n--------------------"                         #!!!
#      cat $tmpfile                                                       #!!!
#      echo "--------------------\n"                                      #!!!

      [ -s $tmpfile ] && {

# Set the output data

	match=`wc -l < $tmpfile`
	set -A columns '' `cut -f1 -d: $tmpfile`

	cut -f2 -d: $tmpfile |&
	  i=0; while true; do {
	    read -p s || break
	    let "i=$i+1"
	    [ -n "$left_field" ] && s=${s#$left_field}
	    [ -n "$right_field" ] && s=${s%$right_field}
	    suffixes[i]="$s"
	  }; done
#        echo "suffixes:${suffixes[*]}"                                   #!!!
	[ "$i" -ne "$match" ] && {
	  print -u2 "$NAME: unexpected error. i =/= match  ( :$i: =/= :$match: )"
	  print -u2 "  column :$1:,  line $il, section $is, page $ip, ID $:pid:"
	  match=0
	}
	true
      } || {
	print -u2 "$NAME: no match for the column name was found"
	print -u2 "column :$1:,  line $il, section $is, page $ip, ID :$pid:"
	print -u2 "Type '$NAME -h' for help"
      }
    }

#    echo "match :$match:"                                                #!!!
#    echo "columns :${columns[*]}:"                                       #!!!
#    echo "suffixes  :${suffixes[*]}:\n"                                  #!!!
#     print -u2 -- "<<== get_header."                    #!!!
}
#========================================================================================
function  set_up_page {

#    print -u2 -- "## set_up_page.  bad_page:$bad_page:   np:$np:   ip :$ip:"  #!!!

    [ "$ip" -gt 0 ] && {
      [ -z "$bad_page" ] && {
	[ "$np" -gt 0 ] && {

#	 echo "## set_up_page.   np :$np:   repeat :$repeat:    nr:${nr[0]}:"
#	 i=0; until { let "i=$i+1"; [ "$i" -gt "$np" ]; }; do {
#	   echo "  curve : $i,  file :${file[$i]}:;  x :${x[$i]}:,  y :${y[$i]}:,  nr :${nr[$i]}:,  label :${label[$i]}:"
#	   echo "  yy    :${yy[$i]}:"
#	   echo "  sy    :${sy[$i]}:"
#	 }; done

	  [ -z "$repeat" ] && {
#  A single page
#	     echo "Single page. SETQ[1] :${SETQ[1]}:" >&2
	    {
	      i=0; until { let i=$i+1; [ -z "${SETQ[$i]}" ]; }; do {
		print "${SETQ[$i]}"
	      }; done
	      [ -n "$title" ] && print "title=$title"
	      [ -n "$xlabel" ] && print "xlabel=$xlabel"
	      [ -n "$logx" ] && print "logx=y" || print "logx=n"
	      [ -n "$logy" ] && print "logy=y" || print "logy=n"
	      [ -n "$style" ] && print "dstyle=$style"
	      [ -n "$time" ] && print "time=$time"
	      i=0; until { let "i=$i+1"; [ "$i" -gt "$np" ]; }; do {
		unset yl sl
		[ -z "${file[$i]}" ] && {
		  print -u2 "$NAME: unexpected error in page set up - empty filename."
		  print -u2 "Curve $i, section $is, page $ip, ID :$pid:"
		  bad_page=y
		  break
		}
		print "file=${file[$i]}"
		[ -n "${style[$i]}" ] && print "dstyle=${style[$i]}"
		print "x=${x[$i]}"
		[ -z "${nr[$i]}" ] && n=1 || n="${nr[$i]}"
		[ -z "${y[$i]}" ] && {
		  eval "set -A yl '' ${yy[$i]}"
		  eval "set -A sl '' ${sy[$i]}"
		  true
		} || {
		  yl[1]="${y[$i]}"
		}
#		 echo "yl :${yl[*]}:" >&2
#		 echo "sl :${sl[*]}:" >&2
		j=0; until { let "j=$j+1"; [ "$j" -gt "$n" ]; }; do {
		  print "y=${yl[$j]}"
		  print "label=${label[$i]}${sl[$j]}"
		  [ "$j" -lt "$n" ] && print "next="
		}; done
		[ "$i" -lt "$np" ] && print "next="
	      }; done
	    } | plot_it -a
	    let "npage=$npage+1"
	    print "${pid}\t\t${npage}\t${ip}\t\t1" >> $logfile
	    true
	  } || {
	    [ -z "$nr" ] && n=1 || n="$nr"
#	     echo "Multiple page.  n=$n,  SETQ[1] :${SETQ[1]}:" >&2   #!!!
	    j=0; until { let "j=$j+1"; [ "$j" -gt "$n" ]; }; do {
	      {
		i=0; until { let i=$i+1; [ -z "${SETQ[$i]}" ]; }; do {
		  print "${SETQ[$i]}"
		}; done
		[ -n "$title" ] && print "title=$title"
		[ -n "$xlabel" ] && print "xlabel=$xlabel"
		[ -n "$logx" ] && print "logx=y" || print "logx=n"
		[ -n "$logy" ] && print "logy=y" || print "logy=n"
		[ -n "$style" ] && print "dstyle=$style"
		i=0; until { let "i=$i+1"; [ "$i" -gt "$np" ]; }; do {
		  [ -z "${file[$i]}" ] && {
		    print -u2 "$NAME: unexpected error in page set up - empty filename."
		    print -u2 "Curve $i, section $is, page $ip, ID :$pid:"
		    bad_page=y
		    break
		  }
		  print "file=${file[$i]}"
		  [ -n "${style[$i]}" ] && print "dstyle=${style[$i]}"
		  print "x=${x[$i]}"
		  unset yl sl
		  [ -z "${y[$i]}" ] && {
		    eval "set -A yl '' ${yy[$i]}"
		    eval "set -A sl '' ${sy[$i]}"
		    true
		  } || {
		    yl[$j]="${y[$i]}"
		  }
		  print "y=${yl[$j]}"
		  print "label=${label[$i]}${sl[$j]}"
		  [ "$i" -lt "$np" ] && print "next="
		}; done
	      } | plot_it -a
	      let "npage=$npage+1"
	      i=0; until { let "i=$i+1"; [ "$i" -gt "$np" ]; }; do {
		unset sl suff
		[ -z "${y[$i]}" ] && {
		  eval "set -A sl '' ${sy[$i]}"
		  suff=${sl[$j]}
		  break
		}
	      }; done
	      print "${pid}${suff}\t$npage\t$ip\t\t$j" >> $logfile
	    }; done
	  }
	  true
	} || {
	  print -u2 "$NAME: empty page (not plotted).  Section $is, page $ip"
	}
	true
      } || {
	print -u2 "$NAME: bad page (not plotted).  Section $is, page $ip"
      }
    }
    reset_page
#          print -u2 -- "<<== set_up_page. "                    #!!!
}
#========================================================================================
function  reset_page {

# Reset the page variables

    np=0
    unset pid time repeat bad_page $page_arrays isq SETQ
    style="$dstyle"
    title="$dtitle"
    xlabel="$dxlabel"
    logx="$dlogx"
    logy="$dlogy"
    time="$dtime"
    dselx="$ddselx"
    dsely="$ddsely"
    i=1; until [ -z "${DSETQ[$i]}" ]; do {
      isq=$i
      SETQ[$isq]="${DSETQ[$isq]}"
      let i=$i+1;
    }; done
#    echo "Reset page. isq=$isq,  DSETQ[1] :${DSETQ[1]}:  SETQ[1] :${SETQ[1]}:"
}
#========================================================================================
#          print -u2 -- "=== Starting plot_set"                    #!!!

{ case "$1" in
  ( -h ) {
# Print help on the control file format

    Help='
    The format of the control file:

    !! <filename> [ <options> ] [ <qoptions> ]
    // <pageID> [ %% ] [ <options> ] [ <qoptions> ]
    <file> <x> <y> "<label>" [ <style> ] [ selx=<n> ] [ sely=<n> ]
      ...
    <file> <x> <y> "<label>" [ <style> ] [ selx=<n> ] [ sely=<n> ]
    // <pageID> [ %% ] [ <options> ]
    <file> <x> <y> "<label>" [ <style> ] [ selx=<n> ] [ sely=<n> ]
      ...

    Lines starting with # and empty lines are comments and can be placed everywhere.
    The file may consist of several sections each specifying one output file.
    The first non-comment line must be a section header.
    It starts with !! and contains general information and defaults.
    Then go blocks describing each page of the output plot.
    First line of each block starts with // and contains information common to the page.
    The following lines describe the data to be plot on the page.

    <options>	: A combination of space-separated title="<page title>", xlabel=<xlabel>,
		  style=<style>, selx=<n>, sely=<n>, linx, liny, logx, logy, timestamp, and
		  notimestamp
    <qoptions>	: A combination of space-separated groups <name>=<value>.
		  These options are to be set in gnuplot
    <filename>	: Name of the output file
    <page title>: The title to appear on the plot
    <xlabel>	: The label of the x axis
    <style>	: Plot style defaulted to "lines").
		  Can be lines|points|linespoints|dots|... (see gnuplot manual)
    logx, logy	: Make the corresponding axis logarithmic
    linx, liny	: Make the corresponding axis linear (default)
    timestamp	: Print the timestamp on the plot border (default)
    notimestamp : Do not print the timestamp
    <pageID>	: Page identifier. Used for information on the errors and for the log
    %%		: Repeat the page for each column header matching <y>
    <file>	: The data file
    <x>, <y>	: Columns to be used for x and y.
		  Can be either column numbers or column headers
    <label>	: the label of the data to appear in legend on the plot
    <n> 	: in case of ambiguous column selection, use either <n>th match if <n>
		  is set or all of them otherwise (default)

    Column headers for <y> can contain a single wildcard *.
    In this case, either all the matching columns are plotted on the same page (default),
    or each matching column is plotted on a separate page (%% option). In the last case,
    if more than one data set is specified for the page, the number of the matching
    columns must be either the same for all wildcard-specified sets or equal to 1.
    Symbols "*" and "\" in the column names ARE NOT ALLOWED YET !!!
    The wildcard substitutions appear then in the data labels, appended after the
    trailing space.

    '
    print "$Help" | more
  } ;;
#========================================================================================
  ( * ) {
# Normal entry

#----------------------------------------------------------------------------------------
# Global defaults (set through the parameters):
#
#  pfile     : output filename. If set, overrides specifications in the section headers
#  ptitle    : prefix to the plot title printed on each page
#
# Input file attributes:
#
#  il	     : line number (used only for the error messages)
#
# Section attributes:
#
#  is	     : section number
#  open      : if null, open the new plotfile
#  ofile     : output filename
#  dtitle    : default plot title. Title specification in the page header overrides it.
#  dlog[xy]  : default flags for logarithmic axes.
#  dxlabel   : default label for X axis
#  dstyle    : default data style
#  dtime     : default timestamp flag
#  ddsel[xy] : default column selection flags.
#
# Page attributes:
#
#  ip	     : page number within a section
#  pid	     : page identifier
#  np	     : number of data sets on the page
#  repeat    : repetition flag. If set, repeat the page with different columns
#  nr	     : repetition counter.
#  title     : plot title.
#  log[xy]   : flags for logarithmic axes
#  xlabel    : label for X axis
#  style[0]  : default data style
#  time      : timestamp flag. Can be set to 'y' or 'n'.
#  dsel[xy]  : default column selection flags.
#  bad_page  : bad page flag. If set, do not plot the page
#
# Dataset attributes:
#
#  x[i]      : X index
#  y[i]      : Y index. If set, then the single column is to be plotted
#  label[i]  : data label
#  style[i]  : data style
#  yy[i]     : Y index for multiple columns
#  sy[i]     : suffixes to be added to the data labels for multiple columns
#  sel[xy]   : selection flag for multiple columns. If not set, then all matches
#
# Data file attributes:
#
#  files     : list of already checked data files
#  headers   : list of corresponding headers
#  file_OK   : list of file statuses (empty means OK)
#  fxn	     : the column name last used for the x axis
#  fxc	     : the corresponding index
#  nfl	     : number of entries in these lists
#
# Plot file attributes:
#
#  npage     : page number on the plot (used for the legend)
#----------------------------------------------------------------------------------------

    NAME=${0##*/}

    export PLOT_IT_STEM="${PLOT_IT_STEM:-,,$NODE.$$}"

    page_arrays="nr file x y label style yy sy"

    plot_section='plot_it -c $keep'
#    plot_section="echo '%% plot section' \$is"                       #!!!

    tmpfile=/tmp/plot_set.$$

    Usage="
Usage: $NAME [ -t <title> ] [ -f <filename> [ -s ] ] <control file>

The control file, unless specified with absolute path, is looked for as follows:

- if the variable 'PLOT_SET_PATH' is set, then in all the directories specified there;
- otherwise, in the current directory, in the parent directory, and so on until the root.

Options:
-t  <title> specifies the page title prefix to appear on the plots
-f  <filename> specifies the output file name.
    This option overrides the settings in the control file and
    all the output goes to one file.
-s  \"Smart\" mode. If the required command file for gnuplot (presumably, created by $NAME)
    exists and is newer than the <control file>, than is is used.
    This option only works together with -f option.
-k  keep the working files (starting with ',,').

A legend file is also created for each output file produced by $NAME. The name of this
file consists of the output filename with extension '.legend' appended to it.

Type $NAME -h to get information on the format of the control file.
"

# Parse the parameters and check the control file

#print -u2 -- "=== Parse the parameters"                    #!!!
    [ -z "$1" ] && { \
      print -u2 "$NAME: a script for plotting the data from multiple files."
      print -u2 "$Usage"
      exit
    }

    unset ptitle pfile smart keep

    while true; do {
      { case "$1" in
	( -t ) shift; ptitle="$1";;
	( -f ) shift; pfile="$1";;
	( -s ) smart="$1";;
	( -k ) keep="$1";;
	( *  ) break;;
      esac; }
      shift
    }; done

#    echo "ptitle :$ptitle:"                        #!!!
#    echo "pfile :$pfile:"                          #!!!

    [ -z "$1" ] && { \
      print -u2 "$NAME: the control file must be specified."
      print -u2 "$Usage"
      exit 2
    }

# Check the control file

#print -u2 -- "=== Check the control file"                    #!!!
    cfile="$1"
#   echo "cfile:$cfile:"                             #!!!
    CFILE=
#    echo "cfile:$cfile:"                             #!!!
    { case "$cfile" in
      ( /* | ./* | ../* ) CFILE="$cfile";;
      ( *		) {
#	 echo "PLOT_SET_PATH:$PLOT_SET_PATH:"         #!!!
	[ -z "$PLOT_SET_PATH" ] && {
	  dir=`pwd`
	  while true; do {
	    CFILE="$dir/$cfile"
	    [ -z "$dir" ] && break
	    [ -s "$CFILE" ] && break
	    dir=${dir%/*}
	  }; done
	  true
	} || {
	  set_path=`print "$PLOT_SET_PATH" | \
		    sed -e 's/^:/.:/' -e 's/::/:.:/g' -e 's/:$/:./' | tr : ' '`
#	   echo "$set_path"                                    #!!!
	  for d in $set_path; do {
#	     echo "dir:${d%/}:"                                #!!!
	    CFILE=${d%/}/"$cfile"
#	     echo "CFILE :$CFILE:"  >&2                           #!!!
	    [ -s "$CFILE" ] && break
	  }; done
	}
      };;
    esac; }
#    echo "CFILE:$CFILE:"                                          #!!!
    [ -s "$CFILE" ] || {
      print -u2 "$NAME: the control file not found - $CFILE"
      print -u2 "$Usage"
      exit 4
    }

# Check whether the required gnuplot command file exists and is newer than the control file

#sleep 5                                             #!!!
#print -u2 -- "=== Check gnuplot command file"       #!!!

    unset skipcntr
    [ -n "$pfile" ] && [ -n "$smart" ] && [ "$PLOT_IT_STEM.cmd" -nt "$CFILE" ] && skipcntr=y

    [ -z "$skipcntr" ] && {

#      print -u2 -- $CFILE                             #!!!
#      grep -v -e '^#' -e '^$' "$CFILE" 2> /dev/null | head -1l      #!!!
#      u='!! trc.ps title=" " xlabel="Time"'           #!!!

      u=`grep -v -e '^#' -e '^$' "$CFILE" 2> /dev/null | head -1`

#      sleep 5   #!!!
#      echo "u:$u:" >&2                                                  #!!!

      { case "$u" in
	( '!! '* ) ;;
	( *	 )
	    print -u2 "$NAME: Wrong format of the control file $CFILE";
	    print -u2 "The first non-comment line must be a section header starting with !!"
	    print -u2 "Type '$NAME -h' for help"
	    exit 6;;
      esac; }
#    echo "The control file: $CFILE"                                 #!!!

# Set the defaults and counters

#sleep 5 #!!!
#print -u2 -- "=== Set the defaults and counters"                    #!!!

      unset open files headers file_OK fxn fxc nfl il is

#    dtitle="$ptitle"
#    unset dlogx dlogy dxlabel ddstyle dselx dsely

# Read and interpret the control file

      exec 3< "$CFILE"
      while true; do {
	read -u3 u || break
	let "il=$il+1"
	{ case "$u" in
#----------------------------------------------------------------------------------------
	  ( \#* | '') continue;;
#----------------------------------------------------------------------------------------
	  ( '!! '*  ) {

#	   print -u2 -- "== New section. is :$is:, np :$np:"                #!!!

# New section. Here we do the following:
#  - set up the previous page if not empty;
#  - if this section is not the first, then
#    - if invoked with -f option, set the "open" flag
#    - else, create the plot file
#  - reset the counters.
#  - parse the line and store the section defaults
#  - if the "open" flag is not set, then
#	- open the plot file for the section
#	- open the log file for the section
#	- reset the page counter for the section log

#	    sleep 5   #!!!

            set_up_page
            
#            print -u2 -- "==== is:pfile:plot_section=$is:$pfile:$plot_section"  #!!!

	    [ "$is" -gt 0 ] && {
	      [ -n "$pfile" ] && open=n || {
#		set -x          #!!!
                eval "$plot_section"
#		set +x          #!!!
	      }
	    }

# Reset the section variables

#	   sleep 10  #!!!
#           print -u2 -- "==== Reset the section variables"                #!!!

	    ip=0
	    dtitle="$ptitle"
	    unset dlogx dlogy dxlabel dstyle ddselx ddsely dtime DSETQ isq

	    let "is=$is+1"

	    eval "set -- $u"
	    [ "$#" -lt 2 ] && {
	      print -u2 "$NAME: Wrong format of the section header in $CFILE"
	      print -u2 "Line $il, section $is, page $ip, ID $pid"
	      print -u2 "At least, the filename placeholder should be specified"
	      print -u2 "Type '$NAME -h' for help"
	      exit 6
	    }
	    ofile=${pfile:-$2}
#	     echo "ofile :$ofile"                                         #!!!
	    [ -z "$ofile" ] && {
	      print -u2 "$NAME: Wrong specification of the output file in $CFILE"
	      print -u2 "Line $il, section $is"
	      print -u2 "The filename must be specified in the control file of with -f option"
	      print -u2 "$Usage"
	      exit 8
	    }
	    shift

	    while true; do {
	      { case "$2" in
		( ''          ) break;;
		( title=*     ) dtitle="${ptitle}${2#*=}";;
		( xlabel=*    ) dxlabel="${2#*=}";;
		( style=*     ) dstyle="${2#*=}";;
		( selx=*      ) ddselx="${2#*=}";;
		( sely=*      ) ddsely="${2#*=}";;
		( logx		    ) dlogx=y;;
		( logy		    ) dlogy=y;;
		( timestamp   ) dtime=y;;
		( notimestamp ) dtime=;;
		( *=*		   ) let "isq=$isq+1"; DSETQ[$isq]="$2";;
		( *	      )
		    print -u2 "$NAME: Wrong format of the section header in $CFILE"
		    print -u2 "Line $il, section $is, page $ip, ID $pid"
		    print -u2 "Type '$NAME -h' for help"
		    exit 6;;
	      esac; }
	      shift
	    }; done

# Open a plot file if requested.
	    [ -z "$open" ] && {

#	     sleep 2                                    #!!!
#             print -u2 -- "## Open plot file $ofile"    #!!!

	      {
#		 echo "DSETQ[1] :${DSETQ[1]}:" >&2                             #!!!
		i=0; until { let "i=$i+1"; [ -z "${DSETQ[$i]}" ]; }; do {
		  print "${DSETQ[$i]}"
		}; done
		[ -n "$ofile" ] && print "ofile=$ofile"
		[ -n "$dtitle" ] && print "title=$dtitle"
		[ -n "$dxlabel" ] && print "xlabel=$dxlabel"
		[ -n "$dlogx" ] && print "logx=$dlogx"
		[ -n "$dlogy" ] && print "logy=$dlogy"
		[ -n "$dtime" ] && print "time=$dtime"
		[ -n "$dstyle" ] && print "dstyle=$dstyle"
	      } | plot_it -o
	      logfile="${ofile}.legend"
	      npage=0
	      print "# Plotfile: $ofile" > "$logfile"
	      print "# pageID\tpage#\tbase page#\tsubpage#" >> "$logfile"
	    }
#	     print -u2 -- "## done"                                   #!!!
	  };;
#----------------------------------------------------------------------------------------
	  ( '// '*  ) {

#	   print -u2 -- "== Next page. :is:ip:il: = :$is:$ip:$il:"                 #!!!

# New page. Here we do the following:
#  - check whether a section was opened
#  - set up the previous page if not empty;
#  - reset the counters and flags
#  - parse the line and store the page specifications

	    [ "$is" -eq 0 ] && {
	      print -u2 "$NAME: Wrong format of the control file $CFILE"
	      print -u2 "Line $il, section $is, page $ip, ID $pid"
	      print -u2 "First, open a section, and then start the page"
	      print -u2 "Type '$NAME -h' for help"
	      exit 6
	    }

	    set_up_page
#<<<
#          echo "Start of the page. isq=$isq,  DSETQ=${DSETQ[*]}"         #!!!
#          echo "isq=$isq, SETQ=${SETQ[*]}"                               #!!!
#>>>
	    eval "set -- $u"
	    pid="$2"
	    shift
	    let "ip=$ip+1"
	    while true; do {
#	     echo "Parsing :$2:"  #!!!
	      { case "$2" in
		( ''          ) break;;
		( title=*     ) title="${ptitle}${2#*=}";;
		( xlabel=*    ) xlabel="${2#*=}";;
		( style=*     ) style="${2#*=}";;
		( selx=*      ) dselx="${2#*=}";;
		( sely=*      ) dsely="${2#*=}";;
		( logx		    ) logx=;;
		( logy		    ) logy=y;;
		( linx		    ) logx=;;
		( liny		    ) logy=;;
		( timestamp   ) time=y;;
		( notimestamp ) time=n;;
		( %%		  ) repeat=y;;
		( *=*		   ) let "isq=$isq+1"; SETQ[$isq]="$2";;
		( *	      )
		    print -u2 "$NAME: Wrong format of the page header in $CFILE"
		    print -u2 "Line $il, section $is, page $ip, ID $pid"
		    print -u2 "Type '$NAME -h' for help"
		    bad_page=y
	      esac; }
	      shift
	    }; done
#!!!{
#          echo "Section $is,  page $ip : $pid"
#          echo "title :$title:"
#          echo "xlabel :$xlabel:"
#          echo "style :$style:   logx :$logx:   logy: $logy:   selx :$selx:   sely: $sely:"
#          echo "isq=$isq, SETQ=${SETQ[*]}"
#!!!}
	  };;
#----------------------------------------------------------------------------------------
	  ( *	    ) {

#	   print -u2 -- "== Next data set. :is:ip:il: = :$is:$ip:$il:"    #!!!

# Next data set. Here we do the following:
#  -  Check whether the page is opened
#  -  Parse the line
#  -  Check the unambiguity of the x-axis specification
#  -  Analyse the y-column specification:
#     - if multiple columns are specified, 'repeat' mode is on and repetition counter
#	is set, then check the suffixes for compatibility
#  -  If something is wrong, do not include this data set in the list

	    [ ${ip} -eq 0 ] && {
	      print -u2 "$NAME: Wrong format of the control file $CFILE"
	      print -u2 "Line $il, section $is, page $ip, ID $pid"
	      print -u2 "A page must be opened before the data specification."
	      print -u2 "Type '$NAME -h' for help"
	      true
	    } || {
	      eval "set -- $u"
	      [ $# -lt 4 ] && { \
		print -u2 "$NAME: Wrong format of the control file $CFILE"
		print -u2 "Line $il, section $is, page $ip, ID $pid"
		print -u2 "The first 4 positions in a data specification line are obligatory"
		print -u2 "Type '$NAME -h' for help"
		true
	      } || {
		selx=$dselx
		sely=$dsely
		let "np=$np+1"
		file[$np]="$1"
		x[$np]="$2"
		y[$np]="$3"
		label[np]="$4"
		shift 4
		for u in "$@"; do {
		  { case "$u" in
		    ( selx=* ) selx=${u#*=};;
		    ( sely=* ) sely=${u#*=};;
		    ( *      ) style[$np]="$u";;
		  esac; }
		}; done
#!!!{
#                echo "\nData set $np"
#                echo "file    :${file[$np]}:"
#                echo "x       :${x[$np]}:"
#                echo "y       :${y[$np]}:"
#                echo "label   :${label[$np]}:"
#                echo "style   :${style[$np]}:"
#                echo "sel[xy] :$selx:$sely:"
#!!!}
#  Check the specified data file
		file=${file[np]}
		{ case " ${files[*]} " in
		  ( *" $file "* ) oldfile=y;;
		  ( *		      ) oldfile=;;
		esac; }

#  Find the column headers (the last line starting with # before the first non-comment)

		[ -z "${oldfile}" ] && {

#   New file. Check the file and find its header

		  file_OK=
		  header=
		  [ -s "$file" ] && {
		    [ -r "$file" ] && {
		      exec 4<"$file"
		      while true; do {
			  read -u4 uu || {
			  file_OK=n
			  print -u2 "$NAME: no data in $file"
			  break
			  }
			  { case "$uu" in
			  ( \#*  ) header="${uu#\#}";;
			  ( ''   ) ;;
			  ( *	    ) break;;
			  esac; }
		      }; done
		      true
		    } || {
		      file_OK=n
		      print -u2 "$NAME: failed to read $file"
		    }
		    true
		  } || {
		    file_OK=n
		    print -u2 "$NAME: failed to find non-empty $file"
		  }
		  eval "set -- $header"
		  header="$1"
		  [ -n "$1" ] && shift
		  for f in "$@"; do {
		    header="$header\n$f"
		  }; done
		  let "nfl=$nfl+1"
		  file_OK[$nfl]=$file_OK
		  files[$nfl]="$file"
		  headers[$nfl]="$header"
		  kfl=$nfl
		  true
		} || {

#   The file has already been checked - just look for the stored data
		  unset i kfl; while { let "i=$i+1"; [ "$i" -le "$nfl" ]; }; do {
		    [ "${files[$i]}" = "$file" ] && { kfl=$i; break; }
		  }; done
		  [ -z "$kfl" ] && {
		    print -u2 "$NAME: unexpected error in file search :$i:$nfl:$file:"
		    print -u2 " ${files[*]} "
		    file_OK=n
		    header=
		  } || {
		    header="${headers[$kfl]}"
		    file_OK="${file_OK[$kfl]}"
		  }
		}

#		 echo "file :$file:"
#		 echo "file_OK :$file_OK:"
#		 echo "header :"`echo "$header"`

#  Check the column specifications. If non-numeric, then analyse the header

		[ -z "$file_OK" ] && {
		  x="${x[$np]}"
		  set -- `print "$x" | tr 0123456789 '          '`
		  [ -n "$1" ] && {
#		   echo "Comparing.  kfl=$kfl,  x :$x:  fxn :${fxn[$kfl]}:"
		    [ "${fxn[$kfl]}" = "$x" ] && {
		      x[$np]="${fxc[$kfl]}"
#			echo "Restoring.  kfl=$kfl,  x :${x[$np]}:  fxc :${fxc[$kfl]}:"
		    } || {
		      get_header "$x"
		      [ "$match" -ne 1 ] && [ -z "$selx" ] && {
			  print -u2 "$NAME: header for x-column must be unique"
			  print -u2 "Line $il, section $is, page $ip, ID:$pid"
			  file_OK=n
		      } || {
			  i=${selx:-1}
			  x[$np]=${columns[$i]}
			  fxc[$kfl]="${x[$np]}"
			  fxn[$kfl]="$x"
#			  echo "Storing.  kfl=$kfl,  fxc :${fxc[$kfl]}:  fxn :${fxn[$kfl]}:"
		      }
		    }
		  }
		}

#		 echo "x=${x[$np]}, file_OK :$file_OK:"

		[ -z "$file_OK" ] && {
		  y="${y[$np]}"
		  set -- `print "$y" | tr 0123456789 '          '`
		  [ -n "$1" ] && {
#		   echo "Before get_header(y)"
		    get_header "$y"
#		   echo "After get_header(y)"
		    [ "$match" -gt 0 ] && {
		      [ "$match" -eq 1 ] && y[$np]=${columns[1]} || {
			  [ -n "$sely" ] && y[$np]=${columns[$sely]} || {
			  y[$np]=
			  nr[$np]="$match"
			  yy[$np]=
			  sy[$np]=
			  i=0; until { let "i=$i+1"; [ "$i" -gt "$match" ]; }; do {
			    yy[$np]="${yy[$np]} '${columns[$i]}'"
			    sy[$np]="${sy[$np]} '${suffixes[$i]}'"
			  }; done
			  }
		      }

#			echo "Section $is, page $ip, set $np, ID:$pid"
#			echo "x column : ${x[$np]}"
#			echo "y columns: ${yy[$np]}"
#			echo "suffixes : ${sy[$np]}"

		      true
		    } || {
		      print -u2 "$NAME: failed to find y-column"
		      print -u2 "Line $il, section $is, page $ip, ID:$pid"
		      file_OK=n
		    }
		  }
		}

#		 echo "y=${y[$np]}, file_OK :$file_OK:"

		[ -z "$file_OK" ] && {
		  [ "$match" -gt 1 ] && {
		    [ -z "$repeat" ] || {
#    Multiple y columns in 'repeat' mode: check compatibility
		      [ -n "${nr[np]}" ] && {
			  [ -z "$nr" ] && {
#     First occurence on the page. Save the data
			  nr=${nr[np]}
			  sy="${sy[np]}"
			  } || {
#     Check the number of repetitions
			  [ "$nr" -eq "${nr[np]}" ] || {
			    print -u2 "$NAME: the number of column substitutions must be the same in 'repeat' mode"
			    print -u2 "Line $il, section $is, page $ip, ID:$pid"
			    print -u2 "For this line it is ${nr[np]}, whereas the common value is $nr"
			    file_OK=n
			  }
			  }
		      }
		    }
		  }
		}

#		 echo "nr :$nr:    file_OK :$file_OK:"

		[ -n "$file_OK" ] && {
		  for i in $page_arrays; do {
		    eval "$i[$np]="
		  }; done
		  let "np=np-1"
		}
#		 echo "line is done. np=$np    OK :$file_OK:"
	      }
	    }
	  };;
	esac; }
      }; done
      set_up_page
    }
#    echo "## Close the last section"
#    set -x    #!!!
    eval "$plot_section"
#    set +x    #!!!
    rm -f $tmpfile 2> /dev/null
  };;
esac; }
