#! /usr/bin/ksh
# plotsum_legend
# Usage: plotsum_legend
# (to print legend print $key)
# plots legend on same plot
# precede by plotsum_id to associate symbols with shot numbers
# plots legend starting (left-hand upper corner) at 
# at xlegend0, ylegend0 in plot units.
# Subsequent entries move down  by dylegend
# nlegend entries per column
# Subsequent columns move right down  by dxlegend
# complete data for each shot from $in, where shotID is given in first column by ${symbol}_${shotnumber}
# output are lines to be included in gnuplot .cmd file. These are placed in $out
# to plot symbols near points on same plot run plotsum_shot

#  version : 29.08.2003 23:20

scriptname=`basename $0`
scriptdir=`dirname $0`

dxlegend=${DXLEGEND_PLOTSUM:-0.016}
dylegend=${DYLEGEND_PLOTSUM:-0.035}
xlegend0=${XLEGEND0_PLOTSUM:-0.255}
ylegend0=${YLEGEND0_PLOTSUM:-1.3}
ylegend1=${YLEGEND1_PLOTSUM:-1.02}

n=`echo $ylegend0 $dylegend $ylegend1 | awk '{ print ($1-$3)/$2 }'`
nlegend=${n%.*}
[ "$n" = "$nlegend" ] && let 'nlegend=nlegend-1'
ylegend0=`echo $ylegend0 $dylegend | awk '{ print $1-$2 }'`

#echo "
#$scriptname: nlegend,ylegend0,dylegend = $nlegend $ylegend0 $dylegend
#      	     xlegend0,dxlegend = $xlegend0 $dxlegend"

in=summary/shot_list
out=summary/shot_legend
temp=summary/tempshot
rm -f $temp $out > /dev/null 2>&1

#(xxxto avoid misreading leading minus)
set -A shot xxx `cat $in | cut -f1`
xlegend[1]=xxx 
ylegend[1]=xxx 

shotlist=${shot[*]}
#echo "$shotlist"


yylegend=$ylegend0
xxlegend=$xlegend0
i=0
j=0
for ff in $shotlist; do {
  [ $i -gt 0 ] && {
    ylegend[$i]=$yylegend 
    yylegend=`echo "a=$yylegend - $dylegend\na\nquit" | bc`
    xlegend[$i]=$xxlegend 
    let "j=j+1"
    [ $j -ge $nlegend ] && {
      j=0
      yylegend=$ylegend0
      xxlegend=`echo "a=$xxlegend + $dxlegend\na\nquit" | bc`
    }
  }
  let "i=i+1"
}; done

i=0
> $out
for ff in $shotlist; do {
  [ $i -gt 0 ] && {
    echo "set label \"${shot[$i]}\" at ${xlegend[$i]},${ylegend[$i]}" >> $out
  }
  let "i=i+1"
}; done

