#! /bin/csh -f
if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif
if($?GNUPLOT_CMD) then
    set cfilename=${tmpdir}$GNUPLOT_CMD
else
    set cfilename=${tmpdir}gnuplot.cmd
endif
if($1 == "") then
  set filename=${tmpdir}out.ps
else
  set filename=${tmpdir}$1
endif
(echo 'set term postscript' ; echo 'set out "'$filename'"' ;\
 grep -v 'pause 3600' $cfilename ) > ! ${tmpdir}gnuplot_ps.cmd
gnuplot ${tmpdir}gnuplot_ps.cmd
