#! /bin/ksh

#  VERSION : 04.02.2002 14:41

# Plot the data for radiation split on the targets

# First, the target profiles

echo '199 wlld' | b2plot > b2pw.log 2>&1
[ -s ld_tg_o.dat ] && [ -s ld_tg_i.dat ] && plot_set -f trg_split.ps radsplit.prf
ps4_map='1 3 2 4'
[ -s trg_split.ps ] && {
  ps4 trg_split.ps -n $ps4_map
  ps_mac trg_split.ps
}
rm -f ,,*.cmd ,,*.set


# Universal script for b2plot.
# Multiple boxes can be specified in box.b2p - if the first line there starts with #

DATE=20020131

PS=$1
NAME=${0##*/}
[ -n "$PS" ] && echo "$NAME: producing PostScript files ..." || echo "$NAME: producing gmeta files ..."

STEM=${NAME}_PS
LK=rds

[ -n "$PS" ] && {
  [ -d "${STEM}" ] && {
    [ -d "${STEM}.$DATE" ] && {
      rm -rf ${STEM}/* >/dev/null 2>&1; true
    } || {
      mv "${STEM}" "${STEM}.$DATE"; false
    }
  } || mkdir ${STEM}
  [ -d ${STEM}/mono ] || mkdir ${STEM}/mono
  [ -d ${STEM}/color ] || mkdir ${STEM}/color
}

# First, determine the basic variables

unset swbox
[ -s box.${LK} ] && {
  [ -a box.b2p ] && {
    [ -a box.b2p.$$ ] && {
      print -u2 -- "Cannot switch box.b2p: box.b2p.$$ exists"
      exit 4
    }
    mv box.b2p box.b2p.$$
  }
  mv box.${LK} box.b2p && swbox=y
}
. get_parm.bpl
[ -n "$swbox" ] && {
  mv box.b2p box.${LK} && [ -a box.b2p.$$ ] && mv box.b2p.$$ box.b2p
  unset swbox
}

B="'$LL' extl"
BBB="comp"
ST="lbof sep clvl vesl phys 1.2 lbsz"

rm -f gmeta color.${LK} mono.${LK} ${LK}_${L}[cm].ps.legend ${LK}.log b2plot.ps 2>/dev/null
ic=0
im=0
ib=0
echo "$ST $BB" > color.${LK}.h
echo "$ST $BB writ" > mono.${LK}.h

unset ss sf kw
[ -n "${BB[1]}" ] && ss=_b

# Loop over frames specified in box.b2p - or the default one

for bb in " ${BB[@]}"; do {

# Check whether this frame should be plotted in this mode (empty kw means yes)

  [ -n "$ss" ] && {
    let 'ib=ib+1'
    sf="_${SB[$ib]:-${ib}}"
    kw=${KW[$ib]}
    [ -n "$kw" ] && {
      [ -n "$PS" ] && {
        [ "${kw#P}" = "$kw" ] || kw=
        true
      } || [ "${kw#g}" = "$kw" ] || kw=
    }
    [ -z "$kw" ] && {
      print -- "$bb" >> color.${LK}
      print -- "$bb" >> mono.${LK}
    }
  }

  [ -z "$kw" ] && {

# Prepare the 2D plots depending on the frame (samples are below)
 
    let "ic=ic+1"
    echo "$B
      ne -1 10 clvp surf drop" >> color.${LK}
    echo "ne_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

    let "ic=ic+1"
    echo "$B brna 1 zsel pvol
      4 4 clvp surf drop" >> color.${LK}
    echo "rci_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

    let "ic=ic+1"
    echo "$B b2ra pvol abs 0 0 sumz
      -1 10 clvp surf drop" >> color.${LK}
    echo "rad_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

    i=0; for f in ${SPEC[*]}; do {
#      ff=`echo $f | tr [A-Z] [a-z]`
      ff=$f
      let "ii=i+1"

      [ ${SUMZ_1[i]} -eq ${SUMZ_N[i]} ] && {

        let "ic=ic+1"
        echo "$B dab2 $ii zsel
          -1 10 clvp surf drop" >> color.${LK}
        echo "na_${ff}_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

        let "ic=ic+1"
        echo "$B b2ra pvol abs $ii zsel
          -1 10 clvp surf drop " >> color.${LK}
        echo "rd_nt${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

        true
      } || {
# Impurity species

        ((ns=${SUMZ_N[i]}-${SUMZ_1[i]}+1))
        echo "Species ${f} : $ns"

        let "ic=ic+1"
        echo "$B na ${SUMZ_1[i]} ${SUMZ_N[i]} sumz
              -1 10 clvp surf drop" >> color.${LK}
        echo "ni_${ff}${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

        let "ic=ic+1"
        echo "$B b2ra pvol abs $ii zsel
          -1 10 clvp surf drop" >> color.${LK}
        echo "rd_${ff}${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

      }
      i=$ii
    }; done

  }
}; done

# Plots invariant with respect to the bounding box (sample is below)

let "ic=ic+1"
echo "$BBB $B
  ne -1 10 clvp surf drop" >> color.${LK}
echo "ne-c_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

let "ic=ic+1"
echo "$BBB $B brna 1 zsel pvol
  4 4 clvp surf drop" >> color.${LK}
echo "rci-c_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

let "ic=ic+1"
echo "$BBB $B b2ra pvol abs 0 0 sumz
  -1 10 clvp surf drop" >> color.${LK}
echo "rad-c_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

i=0; for f in ${SPEC[*]}; do {
#  ff=`echo $f | tr [A-Z] [a-z]`
  ff=$f
  let "ii=i+1"
  [ ${SUMZ_1[i]} -eq ${SUMZ_N[i]} ] && {

    let "ic=ic+1"
    echo "$BBB $B dab2 $ii zsel
      -1 10 clvp surf drop" >> color.${LK}
    echo "na-c_${ff}_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

    let "ic=ic+1"
    echo "$BBB $B b2ra pvol abs $ii zsel
      -1 10 clvp surf drop " >> color.${LK}
    echo "rd-c_${ff}_${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

    true
  } || {
# Impurity species

    ((ns=${SUMZ_N[i]}-${SUMZ_1[i]}+1))
    echo "Species ${f} : $ns"

    let "ic=ic+1"
    echo "$BBB $B na ${SUMZ_1[i]} ${SUMZ_N[i]} sumz
          -1 10 clvp surf drop" >> color.${LK}
    echo "ni-c_${ff}${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

    let "ic=ic+1"
    echo "$BBB $B b2ra pvol abs $ii zsel
      -1 10 clvp surf drop" >> color.${LK}
    echo "rd-c_${ff}${L}${sf}\t$ic" >> ${LK}_${L}c.ps.legend

  }
  i=$ii
}; done

# Produce the plots from the prepared control files

S=mono
for C in m c; do {
  [ -s ${S}.${LK} ] && {
    cat ${S}.${LK} >> ${S}.${LK}.h
    mv ${S}.${LK}.h ${S}.${LK}
    b2plot < ${S}.${LK} >> ${LK}.log 2>&1
    [ -n "$PS" ] && {
      [ -s gmeta ] && {
        ctrans -d ps.$S -outfile ${STEM}/${S}/${LK}_${L}${C}.ps gmeta
        mv ${LK}_${L}${C}.ps.legend ${STEM}/${S}
        [ -s b2plot.write ] && mv b2plot.write ${STEM}/${S}
        (cd ${STEM}/${S}
          ps_GV ${LK}_${L}${C}.ps && mv ${LK}_${L}${C}_GV.ps ${LK}_${L}${C}.ps && ps_mac ${LK}_${L}${C}.ps
        )
        rm gmeta
      }
    }
    [ -s gmeta ] && mv gmeta gmeta.${LK}.${S}
    true
  } || {
    rm ${S}.${LK}.h 2>/dev/null
  }
  [ -a b2plot.write ] && [ ! -s b2plot.write ] && rm b2plot.write
  S=color
}; done

[ -s gmeta.${LK}.color ] && ln -s gmeta.${LK}.color gmeta

[ -n "$PS" ] && mv trg_split*.ps* ${STEM}/color
