#! /usr/bin/ksh

# Produce the summary plots

#  A. S. Kukushkin version : 29.03.2005 16:54
#  H. D. Pacher: rms modifications 2001.03.13 14:14

vvlist='ns zeff ntot pneu'
vlist='ns'

NS_RANGE=${NS_RANGE:-'0.24:0.48'}
ZEFF_RANGE=${ZEFF_RANGE:-'1.3:2.5'}
NTOT_RANGE=${NTOT_RANGE:-':120'}
PNEU_RANGE=${PNEU_RANGE:-'0:20'}
HE_RANGE=${HE_RANGE:-'0:120'}
D_RANGE=${D_RANGE:-'0:2700'}
PR_RANGE=${PR_RANGE:-'0:10'}
THRPT_RANGE=${THRPT_RANGE:-'0:500'}
COREFLX_RANGE=${COREFLX_RANGE:-'0:'}
MAPY_RANGE=${MAPY_RANGE:-'0:'}

DEF_PRINTER=c

NAME=${0##*/}
Usage="
  $NAME: script for producing the summary plots of the B2 runs.
  Several series of plots, showing the data versus different parameters,
  can be produced. Usage:

$NAME [ <Options> ] [ -t title ] [ -p printer ] [ -y layout ] [ -s 'list1' |  -l 'list1' ] [ list2 ]

  Options:
    -h  help: this screen is printed;
    -ds only the plots with data spread for some points are plotted
    -fl only the particle influx vs. helium neutral pressure is plotted
    -he only the helium concentration vs. particle throughput is plotted
    -ow only the operation window (ns, qpeak, Zeff, cHe, Dcore, Dpump) is plotted
    -pr only the helium enrichment vs. neutral pressure is plotted
    -m  only a map in (ns-Zeff) parameter space is produced;
    -md only a map in (ns-Zeff) space for the dome comparison is produced;
    -i  the (ns-Zeff) map is provided with the point identification labels;
    -is the legend for the (ns-Zeff) map is plotted separately;
    -nohe skip helium concentration and pressure to avoid log(0)
    -c  the legend is cleared before producing the map;
    -n  the plots are not sent to the printer;
    -o  the plots are only sent to the printer;
    -p  the printer <printer> is selected;
    -y  the layout file <layout> is selected;
    -s  only selected data sets are plotted, the rest are omitted;
    -l  only selected data sets are plotted with lines, the rest with points only
    -r  average +/-rms plot (box/cross) rather than average only
    -t  title prefix to be added to every plot in the series

    printer is a valid printer name for the \"print_file\" script.
    list1   is the list of additional keywords to be applied for the data set selection.
            Must appear as one shell argument.
    list2   is the list of keywords to be used as X axis for plotting.
            Must be a subset of \"$vvlist\".

  If selection key (-s or -l) is specified with empty list, then the x axis selection is
  used also for the data.
  If no list2 is specified, then default selection ($vlist) is used.
"

# Parse the parameters

unset MAP_ONLY SEL_STYLE SEL_CRIT MAP_ID NO_PLOT PLOT_ONLY SEP_LEG HE_ONLY CHE_ONLY NO_HE HE_ENRC OW_ONLY DS_ONLY RMS xsuffix TITLEPREF

PRINTER="$DEF_PRINTER"
LAYOUT=layout.sum
FILESSMT="c_he.smt  dt_sprd.smt   he_blnc.smt  he_enrc.smt  ns_qpk.smt  ns_zeff.smt  op_wndw.smt"
SMT="smt"

#hdp put following at end of program if desired
#for f in $FILESRMS; do
#   \rm -f $SOLPSTOP/data/Summary_plots/$f 2>/dev/null
#done

until [ -z "$1" ]; do {
  { case $1 in
    ( -h | -\? )  print "$Usage"; exit;;
    ( -c ) rm -f summary/shot_list 2>/dev/null;;
    ( -ds) DS_ONLY=y;;
    ( -fl) HE_ONLY=y;;
    ( -he) CHE_ONLY=y;;
    ( -ow) OW_ONLY=y;;
    ( -pr) HE_ENRC=y;;
    ( -nohe) NO_HE=-DNo_He;;
    ( -md) MAP_ONLY=d;;
    ( -m ) MAP_ONLY=y;;
    ( -i ) MAP_ID=y;;
    ( -is) MAP_ID=y; SEP_LEG=y;;
    ( -n ) NO_PLOT=y;;
    ( -o ) PLOT_ONLY=y;;
    ( -p ) PRINTER=$2; shift;;
    ( -y ) LAYOUT=$2;  shift;;
    ( -l ) SEL_STYLE=l
           set -A u -- $2
	   SEL_CRIT="${u[*]}"
#	   echo "-l option : $SEL_CRIT"
	   unset u 
           shift;;
    ( -s ) SEL_STYLE=s
           set -A u -- $2
	   SEL_CRIT="${u[*]}"
#	   echo "-s option : $SEL_CRIT" 
	   unset u 
           shift;;
    ( -r ) RMS=y
	   varsuffix="_z"
	   xsuffix="__x"
	   SMT="rms"
	   cat $SOLPSTOP/data/Summary_plots/filelist.smt \
	     | tr "\t" " " | sed s/"\([a-zA-Z0-9]\) "/"\1${varsuffix} "/ > $SOLPSTOP/data/Summary_plots/filelist.rms
	   FILESRMS=
	   for f in $FILESSMT; do
	      frms=`echo "$f" | sed s/"smt$"/"rms"/`
	      FILESRMS="$FILESRMS $frms"
	      cat $SOLPSTOP/data/Summary_plots/$f | awk '{
	       if ($1 ~ "#define" && $2 ~ "XAXIS" ) printf ("%s %s %s%s\n", $1, $2, $3, xsuff)
	       else  print ($0)
	      }' xsuff="$xsuffix" > $SOLPSTOP/data/Summary_plots/$frms
	   done;;
    ( -t ) TITLEPREF="-t $2:_"; shift;;
    ( -* ) print -u2 "$NAME: illegal option $1"; exit 4;;
    ( *  ) break;;
  esac; }
  shift
}; done

#echo "$NAME: parsed. LAYOUT=$LAYOUT, TITLEPREF=${TITLEPREF}="  #!!!

[ -z "$PRINTER" ] && {
  print -u2 "$NAME: no printer specified!!!"
  NO_PRINT=y
}
[ -n "$1" ] && {
  unset vlist
  for i in "$@"; do {
    case " $vvlist " in
      ( *\ $i\ * ) vlist="$vlist $i";;
      ( *        ) print -u2 "$NAME: illegal plotting mode $i"; exit 6;;
    esac
  }; done
#  vlist="$list"
}

#echo "SEL_CRIT : $SEL_CRIT"
#echo "vlist : $vlist"

case "$LAYOUT" in
  ( /*   ) ;;
  ( ./*  ) LAYOUT=$PWD${LAYOUT#.};;
  ( ../* ) LAYOUT=${PWD%/*}${LAYOUT#..};;
  ( *    )
      [ -s "$LAYOUT" ] || {
        [ -s ../"$LAYOUT" ] && LAYOUT="${PWD%/*}/$LAYOUT" || LAYOUT="$SOLPSTOP/data/plot_set/$LAYOUT"
      };;
esac

echo "$NAME: layout file $LAYOUT" #!!!

[ -r "$LAYOUT" ] || {
  ps4_map='1 5 11 19 6 7 8 9 10 13 12 14 29 35 31 33 28 34 30 32 2 3 24 4 22 18 23 15 17 20 16 21 24 25 26 27'
  print -u2 "$NAME: the layout file not found - $LAYOUT"
  unset LAYOUT
}

{ case "$OBJECTCODE" in
  ( linux* )  alias CPP='/usr/bin/cpp -P -C -traditional';;
  (   *    )  alias CPP='/usr/lib/cpp -P';;
esac; }

cd $SOLPSTOP/data/Summary_plots

[ -s OLD_LINK_LIST ] && {

# Link old data files to the current working directory

  for f in `grep -v ^\# OLD_LINK_LIST`; do {
    [ -a summary/$f ] || {
      ln -s $PWD/ALL_DATA/$f summary
      print "linked: $f" 
    }
  }; done
}
#==================================================================================================#
function adjust_color {

# Change yellow to salad-green:

  echo '/^\/LT5/ s/ 1 1 0 DL / 0.5 1 0 DL /
    w
    q' | ed -s $1
}
#==================================================================================================#
function sel_line {
# Make the data set selection if specified
#  echo "Entering sel_line $*"         #!!!
#  echo "SEL_STYLE:$SEL_STYLE:"        #!!!
#  echo "SEL_CRIT:$SEL_CRIT:"          #!!!
  unset GREP_IT LINE_LIS DATA_STYLE
  [ -n "$SEL_STYLE" ] && {
# Selection is required.
# Get the line numbers with the first grep
    N=-n
    for g in $* $SEL_CRIT ; do {
      GREP_IT="$GREP_IT | grep $N @${g}@"
      N=
    }; done
#    echo "GREP_IT:$GREP_IT:"             #!!!

    [ -f filelist.sml ] || ln -sf filelist.${SMT} filelist.sml
#    ls -l filelist.sml     #!!!
    
#    set -x          #!!!
    eval "LINE_TMP=\`cat filelist.sml $GREP_IT | cut -f1 -d':'\`"
#    set +x          #!!!
#    echo "LINE_TMP:$LINE_TMP:"     #!!!
    [ -n "$LINE_TMP" ] && {
      for g in $LINE_TMP; do {
        LINE_LIS="$LINE_LIS -e '${g}s/ @.*@$/ linespoints/'"
      }; done
    }
    [ -n "$LINE_LIS" ] && LINE_LIS="| sed $LINE_LIS"
    [ "$SEL_STYLE" = l ] && {
      LINE_LIS="$LINE_LIS | sed -e 's/ @.*@$/ points/' -e 's/\" *$/\" points/' -e 's/\"$/\" points/'"
      true
    } || {
      LINE_LIS="$LINE_LIS | sed -e '/ linespoints$/!d' | sed -e 's/ linespoints$//'"
    }

#    print -- "LINE_LIS:$LINE_LIS:"        #!!!
#    set -x          #!!!
    eval "cat filelist.sml $LINE_LIS  > filelist.sum"
#    set +x          #!!!
  } || {
# SEL_STYLE not defined - select the whole file removing the labels
#    set -x          #!!!
    eval "cat filelist.sml $LINE_LIS | sed 's/ @.*@$//' > filelist.sum"
#    set +x          #!!!
  }
#  echo "==== filelist.sum:" #!!!
#  cat filelist.sum          #!!!
#  echo "===="               #!!!
#  exit        #!!!
  rm -f filelist.sml
}
#==================================================================================================#
function ns_zeff_map {

  export PLOT_IT_STEM=${1:-$PLOT_IT_STEM}

  echo "Starting series map. PLOT_IT_STEM=$PLOT_IT_STEM: PLOT_ONLY=$PLOT_ONLY: NO_PLOT=$NO_PLOT:"

  [ -z "$PLOT_IT_STEM" ] && {
    print -u2 "$NAME: internal error. PLOT_IT_STEM undefined and ns_zeff_map called without parameter"
    exit 16
  }

#  echo "checking PLOT_ONLY"        #!!!
  [ -z "$PLOT_ONLY" ] && {
#    echo "Empty..."        #!!!
#    DEFINES='-Dns -DXAXIS=ne_s'"${xsuffix}"' -DXLABEL="ne_sep_[1.e20/m**3]" -DXRANGE="xrange=['"${NS_RANGE}]\""
    DEFINES='-Dpneu -DXAXIS=p_neu_PF_av'"${xsuffix}"' -DXLABEL="Neutral_pressure_in_PFR_[Pa]" 
      -DXRANGE="xrange=['"${PNEU_RANGE}]\""' -DYRANGE="yrange=['"${MAPY_RANGE}]\""

#    set -x        #!!!
#    CPP $DEFINES "${PLOT_IT_STEM%%-*}".${SMT} > "$PLOT_IT_STEM".sum 2>/dev/null
    CPP $DEFINES "${PLOT_IT_STEM%%-*}".${SMT} > "$PLOT_IT_STEM".sum
#    set +x        #!!!

#    set -x                    #!!!
    plot_set -k -f summary/"$PLOT_IT_STEM".ps $TITLEPREF "$PLOT_IT_STEM".sum
#    set +x                    #!!!

#    set -x                    #!!!
    adjust_color summary/"$PLOT_IT_STEM".ps
#    set +x                    #!!!

    [ -n "$MAP_ID" ] && {

#  Add the labels identifying the points to the map
#  First, find the location of "Zeff_crs" and "ne_s" columns in the data files

#      echo "Adding legend..."        #!!!
      unset nolegend
#      set -x                  #!!!
      set -A f -- `grep -v -e '^$' -e '^#' -e '^//' -e '^!!' "$PLOT_IT_STEM".sum | head -1`
#      set +x                    #!!!
      [ -z "$f" ] && {
        print -u2 -- "Unexpected error in plotsum: empty $PLOT_IT_STEM.sum - no legend produced!"
        nolegend=y
      } || {
 
#  Create the legend, append it to the plot command file, and redo the plot
# call e.g. plotsum_shot "$col_title_x" "$col_title_y" - produces file with shot numbers in col.1
# x values in column 2, y values in column 3. If  $col_title_x or col_title_y do not exist, file does not exist

#        col_title_x="ne_s"
        col_title_x="p_neu_PF_av"
        col_title_y="qpk_tot"
	plotsum_shot "$col_title_x" "$col_title_y"
        nolegend=
	[ ! -s summary/shot_list ] && nolegend=y
     }
	 
     [ -z "$nolegend" ] && {
	  # call must be plotsum_id 2 3 if x values are in column 2 and y values are in column 3
        plotsum_id 2 3
        [ -z "$SEP_LEG" ] && {
          plotsum_legend
          cat summary/shot_cmd summary/shot_legend "$PLOT_IT_STEM".cmd | gnuplot
          true
        } || {
          plotsum_legend_out
          SEP_LEG=summary/"$PLOT_IT_STEM"_legend_out.ps
          mv summary/shot_legend_out.ps $SEP_LEG
          cat summary/shot_cmd "$PLOT_IT_STEM".cmd | gnuplot
        }
        adjust_color summary/"$PLOT_IT_STEM".ps
      }
    }
  }
#  Plot the map, if ready
#  echo "Before plotting the map"        #!!!
  if [ -s summary/"$PLOT_IT_STEM".ps ]; then
    [ -z "$NO_PLOT" ] && print_file -P$PRINTER summary/"$PLOT_IT_STEM".ps $SEP_LEG &
  fi
#echo "Finished map"        #!!!
}
#==================================================================================================#
[ -n "$HE_ENRC" ] && {
# Plot He enrichment vs. neutral pressure, upstream density, throughput, and number of particles
  print_list="he_enrc4"
  [ -z "$PLOT_ONLY" ] && {
    print "Starting the helium enrichment..."
    export PLOT_IT_STEM=he_enrc
    export STEM="$PLOT_IT_STEM"
    sel_line ns He
#    echo "SEL_STYLE: $SEL_STYLE"

    {
      DEFINES='-DXRANGE="xrange=['"${PR_RANGE}]\" -DXAXIS=p_neu_PF_av'"${xsuffix}"' -DPAGE=pr -DXLABEL=\"Neutral_pressure_[Pa]\""
      CPP $DEFINES ${STEM}.${SMT}
      DEFINES='-DXRANGE="xrange=['"${NS_RANGE}]\" -DXAXIS=ne_s'"${xsuffix}"' -DPAGE=ns -DXLABEL=\"Upstream_density_[1.e20/m**3]\""
      CPP $DEFINES ${STEM}.${SMT} 
      DEFINES='-DXRANGE="xrange=['"${NTOT_RANGE}]\" -DXAXIS=N_e'"${xsuffix}"' -DPAGE=N -DXLABEL=\"Number_of_particles_[1.e20]\""
      CPP $DEFINES ${STEM}.${SMT} 
      DEFINES='-DXRANGE="xrange=['"${THRPT_RANGE}]\" -DXAXIS=DT_throughput'"${xsuffix}"' -DPAGE=thrp -DXLABEL=\"DT_throughput\""
      CPP $DEFINES ${STEM}.${SMT} 
    } > ${PLOT_IT_STEM}.sum  2>/dev/null
    plot_set -k -f summary/${PLOT_IT_STEM}.ps $TITLEPREF ${PLOT_IT_STEM}.sum
    adjust_color summary/${PLOT_IT_STEM}.ps
    ps4 summary/${PLOT_IT_STEM}.ps -n '1 2 3 4'
  }
  [ -z "$NO_PLOT" ] && {
    for f in $print_list; do {
      [ -s "summary/$f.ps" ] && print_file -P$PRINTER "summary/$f.ps" &
    }; done
  }
  exit
}

[ -n "$DS_ONLY" ] && {
# Plot the data spread (oscillations)
  print_list=
  [ -z "$PLOT_ONLY" ] && {

    print "Starting the data spread..."
    [ -s filelist.trc ] || exit
    export PLOT_IT_STEM=dt_sprd
    export STEM="$PLOT_IT_STEM"

    SEL_STYLE=s sel_line sprd
    [ -s filelist.sum ] || exit
    #hop if rms is wanted would have to have new file to replace filelist.tmh 
    # with suffix _z to filenames, so the following if not necessary then
    if [ -z "$RMS" ]; then
	sed 's/$/ @=@/' < filelist.sum > filelist.tmh
    else
	cat filelist.sum | sed 's/$/ @=@/' | sed s/"${varsuffix} "/" "/ > filelist.tmh
    fi
    rm -f filelist.sml 2>/dev/null
    cp filelist.trc filelist.sml
    SEL_STYLE=s sel_line sprd
    [ -s filelist.sum ] || exit
    sed 's/$/ @@/' < filelist.sum >> filelist.tmh
    rm -f filelist.sml 2>/dev/null
    mv filelist.tmh filelist.sml
    SEL_STYLE=l SEL_CRIT= sel_line =
    sed 's/ points/ dots/' < filelist.sum > filelist.tmh
    mv filelist.tmh filelist.sum

    [ -s filelist.sum ] && {
#      DEFINES='-DNSRANGE="xrange=['"${NS_RANGE}]\""' -DTHRANGE="xrange=['"${THRPT_RANGE}]\""' -DZRANGE="xrange=['"${ZEFF_RANGE}]\""' -DCFRANGE="xrange=['"${COREFLX_RANGE}]\""
      DEFINES='-DNSRANGE="xrange=['"${NS_RANGE}]\""' -DTHRANGE="xrange=['"${THRPT_RANGE}]\""' -DZRANGE="yrange=['"${ZEFF_RANGE}]\""' -DCFRANGE="xrange=['"${COREFLX_RANGE}]\""' -DPNRANGE="xrange=['"${PNEU_RANGE}]\""
      # hdp: for data spread want normal runs to use rms box values and data spread cases to use standard
      # i.e. runs to use e.g. ne_s__x, data spread cases to use ne_s. For now, rms has no effect here.
      # in that case would have to have new file to replace filelist.tmh with suffix _z to filenames
      # CPP $DEFINES ${STEM}.${SMT} > ${PLOT_IT_STEM}.sum 2>/dev/null
      CPP $DEFINES ${STEM}.smt > ${PLOT_IT_STEM}.sum 2>/dev/null
      plot_set -k -f summary/${PLOT_IT_STEM}.ps $TITLEPREF ${PLOT_IT_STEM}.sum
      adjust_color summary/${PLOT_IT_STEM}.ps
      ps4 summary/${PLOT_IT_STEM}.ps -n 1 2 3
      print_list="dt_sprd4"
    }
  }
  [ -z "$NO_PLOT" ] && {
    for f in $print_list; do {
      [ -s "summary/$f.ps" ] && print_file -P$PRINTER "summary/$f.ps" &
    }; done
  }
  exit
}

[ -n "$OW_ONLY" ] && {
# Plot the data for operational window
  print_list="op_wndw4"
  [ -z "$PLOT_ONLY" ] && {
    print "Starting the operational window..."
    export PLOT_IT_STEM=op_wndw
    export STEM="$PLOT_IT_STEM"
    SEL_STYLE=s sel_line
#    echo "SEL_STYLE: $SEL_STYLE"

    DEFINES='-DNSRANGE="xrange=['"${NS_RANGE}]\""' -DTHRANGE="xrange=['"${THRPT_RANGE}]\""' -DZRANGE="yrange=['"${ZEFF_RANGE}]\""' -DCFRANGE="xrange=['"${COREFLX_RANGE}]\""' -DPNRANGE="xrange=['"${PNEU_RANGE}]\""
#    set -x
    CPP $DEFINES $NO_HE ${STEM}.${SMT} > ${PLOT_IT_STEM}.sum 2>/dev/null
#    set +x
    plot_set -k -f summary/${PLOT_IT_STEM}.ps $TITLEPREF ${PLOT_IT_STEM}.sum
    adjust_color summary/${PLOT_IT_STEM}.ps
    ps4 summary/${PLOT_IT_STEM}.ps -n 1 2 3 4
  }
  [ -z "$NO_PLOT" ] && {
    for f in $print_list; do {
      [ -s "summary/$f.ps" ] && print_file -P$PRINTER "summary/$f.ps" &
    }; done
  }
  exit
}

[ -n "$CHE_ONLY" ] && {
# Plot CHe vs. throughput
  print_list="c_he"
  [ -z "$PLOT_ONLY" ] && {
    print "Starting the helium concentration..."
    export PLOT_IT_STEM=c_he
    export STEM="$PLOT_IT_STEM"
    SEL_STYLE=s sel_line He
#    echo "SEL_STYLE: $SEL_STYLE"

    DEFINES='-DXRANGE="xrange=['"${THRPT_RANGE}]\""
    CPP $DEFINES ${STEM}.${SMT} > ${PLOT_IT_STEM}.sum 2>/dev/null
    plot_set -k -f summary/${PLOT_IT_STEM}.ps $TITLEPREF ${PLOT_IT_STEM}.sum
    adjust_color summary/${PLOT_IT_STEM}.ps
  }
  [ -z "$NO_PLOT" ] && {
    for f in $print_list; do {
      [ -s "summary/$f.ps" ] && print_file -P$PRINTER "summary/$f.ps" &
    }; done
  }
  exit
}

[ -n "$HE_ONLY" ] && {
  print_list="he_blnc d_blnc"
  [ -z "$PLOT_ONLY" ] && {
    print "Starting the flux balance check..."
    export PLOT_IT_STEM=he_blnc
    export STEM=he_blnc
    sel_line

    DEFINES='-Dhe -DXRANGE="xrange=['"${HE_RANGE}]\""
    CPP $DEFINES ${STEM}.${SMT} > ${PLOT_IT_STEM}.sum 2>/dev/null
    plot_set -k -f summary/${PLOT_IT_STEM}.ps $TITLEPREF ${PLOT_IT_STEM}.sum
    adjust_color summary/${PLOT_IT_STEM}.ps

    export PLOT_IT_STEM=d_blnc
    DEFINES='-Dd -DXRANGE="xrange=['"${D_RANGE}]\""
    CPP $DEFINES ${STEM}.${SMT} > ${PLOT_IT_STEM}.sum 2>/dev/null
    plot_set -k -f summary/${PLOT_IT_STEM}.ps $TITLEPREF ${PLOT_IT_STEM}.sum
    adjust_color summary/${PLOT_IT_STEM}.ps
  }
  [ -z "$NO_PLOT" ] && {
    for f in $print_list; do {
      [ -s "summary/$f.ps" ] && print_file -P$PRINTER "summary/$f.ps" &
    }; done
  }
  exit
}

[ -n "$MAP_ONLY" ] && {
  print "Starting the series map..."
  { case "$MAP_ONLY" in
    ( y ) export PLOT_IT_STEM=series_map;;
    ( d ) export PLOT_IT_STEM=dome_map;;
    ( * ) print -u2 "$NAME: internal error (wrong map specification)"
          exit 16;;
  esac; }

  [ -z "$PLOT_ONLY" ] && {
    [ -s summary/"$PLOT_IT_STEM".ps ] && mv summary/"$PLOT_IT_STEM".ps summary/"$PLOT_IT_STEM".ps~
#    set -x          #!!!
    sel_line
#    set +x          #!!!
  }
  ns_zeff_map
  exit
}

for md in $vlist; do {
  [ -z "$PLOT_ONLY" ] && {
    print "Starting the \"$md\" series..."
    [ -s summary/sum_$md.ps ] && mv summary/sum_$md.ps summary/sum_$md.ps~
  }

  sel_line $md
#  exit

#  [ -n "$SEL_STYLE" ] && ns_zeff_map ns_zeff-$md

  export PLOT_IT_STEM=$md

  [ -z "$PLOT_ONLY" ] && {
    { case $md in
      ( zeff ) DEFINES='-Dzeff -DXAXIS=Zeff_crs'"${xsuffix}"' -DXLABEL=Zeff -DXRANGE="xrange=['"${ZEFF_RANGE}]\"";;
      ( ns   ) DEFINES='-Dns -DXAXIS=ne_s'"${xsuffix}"' -DXLABEL="ne_sep_[1.e20/m**3]" -DXRANGE="xrange=['"${NS_RANGE}]\"";;
      ( ntot ) DEFINES='-Dntot -DXAXIS=N_e'"${xsuffix}"' -DXLABEL="Ne_tot_[1.e20]" -DXRANGE="xrange=['"${NTOT_RANGE}]\"";;
      ( pneu ) DEFINES='-Dpneu -DXAXIS=p_neu_PF_av'"${xsuffix}"' -DXLABEL="Neutral_pressure_in_PFR_[Pa]" -DXRANGE="xrange=['"${PNEU_RANGE}]\"";;
      ( *    ) print "${0##*/}: non-supported mode.  md=$md"; exit 4;;
    esac; }
    DEFINES="$DEFINES $NO_HE"

    CPP $DEFINES template.sum > $md.sum 2>/dev/null

  #  set -x
  #  CPP $DEFINES template.sum > $md.sum
  #  set +x
  #  read u
  #  less $md.sum
  #  read u

    plot_set -k -f summary/sum_$md.ps $TITLEPREF $md.sum
    adjust_color summary/sum_$md.ps
  }

  (cd summary
    if [ -s sum_$md.ps ]; then {
      [ -z "$PLOT_ONLY" ] && {
        [ -n "$LAYOUT" ] && {
          echo "$NAME: before ps4.\nDEFINES=:$DEFINES:\nLAYOUT=:$LAYOUT:"  #!!!
          CPP $DEFINES "$LAYOUT" > layout.$md 2>/dev/null
          ps4_map=`layout.ps4 sum_$md.ps.legend layout.$md`
        }
        ps4 sum_$md.ps -n ${ps4_map}
      }
      [ -z "$NO_PLOT" ] && [ -s sum_${md}4.ps ] && print_file -P$PRINTER sum_${md}4.ps &
    }; fi
  )
}; done
