#! /bin/csh -f

cd ${SOLPSTOP} ; git describe --tags --always | awk '{print "SOLPS-ITER version : ",$1}' > /tmp/SOLPS_versions
cd ${SOLPSTOP}/modules/B2.5 ; git describe --tags --always | awk '{print "B2.5 version : ",$1}' >> /tmp/SOLPS_versions
cd ${SOLPSTOP}/modules/Eirene ; git describe --tags --always | awk '{print "Eirene version : ",$1}' >> /tmp/SOLPS_versions
cd ${SOLPSTOP}/modules/Carre2 ; git describe --tags --always | awk '{print "Carre2 version : ",$1}' >> /tmp/SOLPS_versions
cd ${SOLPSTOP}/modules/DivGeo ; git describe --tags --always | awk '{print "DivGeo version : ",$1}' >> /tmp/SOLPS_versions
cat /tmp/SOLPS_versions
rm /tmp/SOLPS_versions
