#! /bin/csh -f
if ($?LAST10) then
  set FILE=b2.log.last10
else
  set FILE=b2.log
endif
if (-x $SOLPSTOP/bin/$OBJECTCODE/zcat) then
    set ZCAT=$SOLPSTOP/bin/$OBJECTCODE/zcat
else if (-x $SOLPSMASTER/@sys/bin/zcat) then
    set ZCAT=$SOLPSMASTER/@sys/bin/zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT -f $FILE | \
  egrep 'b2bremcore,b2bremsol,b2bremdivin,b2bremdivout|b2radcore,b2radsol,b2raddivin,b2raddivout|recycecore,recycesol,recycedivin,recycedivout|recycicore,recycisol,recycidivin,recycidivout|ITER.*TIME' | \
  awk '/b2bremcore,b2bremsol,b2bremdivin,b2bremdivout/{b2bremcore=$2;b2bremsol=$3;b2bremdivin=$4;b2bremdivout=$5;NC=0}\
       /b2radcore,b2radsol,b2raddivin,b2raddivout/{NC=NC+1;b2radcore[NC]=$2;b2radsol[NC]=$3;b2raddivin[NC]=$4;b2raddivout[NC]=$5}\
       /recycecore,recycesol,recycedivin,recycedivout/{recycecore=$2;recycesol=$3;recycedivin=$4;recycedivout=$5}\
       /recycicore,recycisol,recycidivin,recycidivout/{recycicore=$2;recycisol=$3;recycidivin=$4;recycidivout=$5}\
       /ITER.*TIME/{printf "%s %s %s %s %s %s %s %s %s %s %s %s %s ",$4,b2bremcore,b2bremsol,b2bremdivin,b2bremdivout,recycecore,recycesol,recycedivin,recycedivout,recycicore,recycisol,recycidivin,recycidivout;{for (i=1;i<=NC;i++) {printf "%s %s %s %s ",b2radcore[i],b2radsol[i],b2raddivin[i],b2raddivout[i]}};printf "\n"}' | \
  plot xyplot36 b2bremcore b2bremsol b2bremdivin b2bremdivout recycecore recycesol recycedivin recycedivout recycicore recycisol recycidivin recycidivout \
'b2radcore(LRA)1' 'b2radsol(LRA)1' 'b2raddivin(LRA)1' 'b2raddivout(LRA)1'\
'b2radcore(IRN)1' 'b2radsol(IRN)1' 'b2raddivin(IRN)1' 'b2raddivout(IRN)1'\
'b2radcore(LRA)2' 'b2radsol(LRA)2' 'b2raddivin(LRA)2' 'b2raddivout(LRA)2'\
'b2radcore(IRN)2' 'b2radsol(IRN)2' 'b2raddivin(IRN)2' 'b2raddivout(IRN)2'\
'b2radcore(LRA)3' 'b2radsol(LRA)3' 'b2raddivin(LRA)3' 'b2raddivout(LRA)3'\
'b2radcore(IRN)3' 'b2radsol(IRN)3' 'b2raddivin(IRN)3' 'b2raddivout(IRN)3'\
 "Time" "rad_loss(MW)" $PWD
