#! /bin/csh -f
if ($?LAST10) then
  set FILE=b2.log.last10
else
  set FILE=b2.log
endif
if (-x $SOLPSTOP/bin/$OBJECTCODE/zcat) then
    set ZCAT=$SOLPSTOP/bin/$OBJECTCODE/zcat
else if (-x $SOLPSMASTER/@sys/bin/zcat) then
    set ZCAT=$SOLPSMASTER/@sys/bin/zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT -f $FILE |\
  egrep b2bremcore\|b2radcore\|totadd\|'ITER.*TIME' |\
  awk '/b2bremcore/{radcore=$2}\
        /b2radcore/{radcore+=$2}\
        /totaddee/{add=$2+$3}\
        /TIME/{print $4,-radcore/add}' |\
  xyplot 'radiated fraction in core' 'time' 'frac' $PWD
