#! /bin/csh -f
if ($?LAST10) then
  set FILE=b2.log.last10
else
  set FILE=b2.log
endif
if (-x $SOLPSTOP/bin/$OBJECTCODE/zcat) then
    set ZCAT=$SOLPSTOP/bin/$OBJECTCODE/zcat
else if (-x $SOLPSMASTER/@sys/bin/zcat) then
    set ZCAT=$SOLPSMASTER/@sys/bin/zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT -f $FILE | \
  egrep 'b2bremcore|b2radcore|recycecore|recycicore|ITER.*TIME' | \
  awk '/b2bremcore/{b2bremcore=$2;b2bremsol=$3;b2bremdivin=$4;b2bremdivout=$5;NC=0}\
       /b2radcore/{NC=NC+1;b2radcore[NC]=$2;b2radsol[NC]=$3;b2raddivin[NC]=$4;b2raddivout[NC]=$5}\
       /recycecore/{recycecore=$2;recycesol=$3;recycedivin=$4;recycedivout=$5}\
       /recycicore/{recycicore=$2;recycisol=$3;recycidivin=$4;recycidivout=$5}\
       /ITER.*TIME/{b2radcore[0]=0.0;b2radsol[0]=0.0;b2raddivin[0]=0.0;b2raddivout[0]=0.0;\
                    for (i=1;i<=NC;i++)\
                      {b2radcore[0]+=b2radcore[i];\
                       b2radsol[0]+=b2radsol[i];\
                       b2raddivin[0]+=b2raddivin[i];\
                       b2raddivout[0]+= b2raddivout[i]};\
                    print $4,\
                          b2bremcore+recycecore+recycicore+b2radcore[0],\
                          b2bremsol+recycesol+recycisol+b2radsol[0],\
                          b2bremdivin+recycedivin+recycidivin+b2raddivin[0],\
                          b2bremdivout+recycedivout+recycidivout+b2raddivout[0]}' | \
  plot xyplot4 $1 $2 CORE SOL DIVIN DIVOUT "Time" "rad_loss_sum" $PWD
