#! /bin/csh -f
if ($?LAST10) then
  set FILE=b2.log.last10
else
  set FILE=b2.log
endif
if (-x $SOLPSTOP/bin/$OBJECTCODE/zcat) then
    set ZCAT=$SOLPSTOP/bin/$OBJECTCODE/zcat
else if (-x $SOLPSMASTER/@sys/bin/zcat) then
    set ZCAT=$SOLPSMASTER/@sys/bin/zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT -f $FILE |\
  egrep b2bremcore\|b2rad\|totadd\|'ITER.*TIME' |\
  awk '/b2bremcore/{rad=$2+$3+$4+$5}\
        /b2radcore/{rad+=$2+$3+$4+$5}\
        /totaddee/{add=$2+$3}\
        /TIME/{print $4,-rad/add}' |\
  xyplot 'radiated fraction' 'time' 'frac' $PWD
