#! /usr/bin/ksh

#==============================================================================#
#  Part of B2-Eirene service:                                                  #
#                                                                              #
#  post-processor for calculation of the wall loading                          #
#                                                                              #
#  Author:  A.S.Kukushkin                                                      #
#                                                                              #
#  VERSION : 15.02.2000 17:58
#
# ... not sure that it still works...
#==============================================================================#

[ -r B2SXDR ] || { 
  echo 'No B2SXDR file in this directory - nothing to do!' 
  exit 4 
}

cp=
while true; do {
  case "$1" in
    ( -r )    cp=y;;
    ( -h )    echo "Usage:" `basename $0` '[-r]'; exit;;
    ( -* )    echo "        Non-supported option: $1";;
    ( *  )    break;;
  esac; 
  shift
}; done

[ -a param.dg ] || [ -a *.param.dg ] || cp=y
[ -a struct.dg ] || cp=y
[ -n "$cp" ] && {
  cp $GENERICHOME/rdload/struct.dg .
  set -A u -- *.param.dg
  [ -a "$u" ] && rm -f *.param.dg
  set -A u -- $GENERICHOME/rdload/*.param.dg
  [ -a "$u" ] && {
    cp $GENERICHOME/rdload/*.param.dg . 
    true
  } || cp $GENERICHOME/rdload/param.dg . 
}

s=; ll=
set -A u -- *.param.dg
[ -r "$u" ] && { 
  [ -a param.dg ] && mv param.dg param.dg.b;
  lis=; for f in *.param.dg; do {
    lis="$lis ${f%.param.dg}" 
  }; done
  set a $lis; shift; s=$1; shift; ll="$*" 
}

# echo "s:$s"
# echo "lis:$lis"
# echo "ll:$ll"

[ -n "$s" ] && cp $s.param.dg param.dg
print -- "rdl: block $s" > wlld.log
print -- '111 wlld' | b2plot >> wlld.log 2>&1
rdload >> wlld.log 2>&1
for f in b2radsrc load source struct targ targload wlld 'chrd??' '??_tg_?'; do {
  cp $f.dat $GENERICHOME/rdload
}; done

[ -n "$s" ] && { 
  mv load.dat loaddat.$s; mv targ.dat targdat.$s
  for t in $ll; do {
    cp $t.param.dg param.dg;
    print -- "rdl: block $t" >> wlld.log
    print -- '1 wlld' | b2plot >> wlld.log 2>&1
    rdload >> wlld.log 2>&1
    for f in load targ; do {
         cp $f.dat $GENERICHOME/rdload/$f.$t
    }; done
    mv load.dat loaddat.$t 
    mv targ.dat targdat.$t
  }; done 
}

[ -n "$s" ] && [ -a param.dg.b ] && mv param.dg.b param.dg
