#! /bin/csh -f
awk '/nnreg/{NV=$2;NXY=$3}\
     /^f..reg/{printf "%s",$1; for (i=2;i<=NF;i++) sum[(i-2)%(NXY+1)]+=$i; for (i=0;i<=NXY;i++) {printf " %s",sum[i]; sum[i]=0}; printf "\n"}\
     \!/^f..reg/{print $0}'
