#! /bin/csh -f
touch .read
if ($1 == "") then
  set time=10
else
  set time=$1
endif
while ( { ( timestamp b2.parameters.out .read > /dev/null ) } )
#  echo still sleeping
  sleep $time
end
rm .read
#echo writing done
