#! /bin/csh -f
if (-s b2mn.exe.dir/b2ftrace) then
  set FILE=b2mn.exe.dir/b2ftrace
else
  set FILE=b2ftrace
endif
if (-X zcat) then
  set ZCAT="zcat --force"
else
  set ZCAT="gzip --decompress --force --stdout"
endif
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif
setenv PLOT_FROM_FILE "gnuplot.temp"
$ZCAT $FILE | \
  awk 'BEGIN{ig=0}/data/&&ig==0{ig=1}/data/&&ig==2{printf "\n"}/^[^*]/&&ig>0{ig=2;printf "%s",$0}' | \
  resopt $argv | \
  awk '{print $2,$87,$88,$89,$90,$91,$92,$93}' >! ${tmpdir}PLOT_FROM_FILE
  plot xlyplot7 momtot ee ei en pot kt zt iteration 'norm of residual of non ns equations' $PWD
