#! /bin/tcsh -f

set debug=""
set REDEFINES=""
argloop:
  if ("X${1}X" == "X-nX") then
    set debug="$debug -n"
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
    goto argloop
  endif
  if ("X${1}X" == "X-rX") then
    shift
    set REDEFINES="$REDEFINES $1"
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if (! $?SOLPS_DEBUG) then
      source $SOLPSTOP/SETUP/debug
      set DEBUG_SET=yes
    endif
    if ($1 == "") then
      set debug="$debug TIME=$DBX"
    else
      set next=$1
      set begin_next=`printf '%s' $next | cut -c1`
      if ("X${begin_next}X" == "X-X") then
        set debug="$debug TIME=$DBX"
      else
        set debug="$debug TIME=$1"
        shift
      endif
    endif
    goto argloop
  endif

if ($1 != "") then
  if (-d $1) then
    cd $1
  else if (-f $1) then
    cd `dirname $1`
  else
    echo $1 neither a directory or a file
    exit
  endif
endif
pwd

if (-s b2md.dat) then
  set B2MDDAT=b2md.dat.sav
  mv b2md.dat $B2MDDAT
else if (-s ../baserun/b2md.dat) then
  set B2MDDAT=../baserun/b2md.dat
else if (-s $SOLPSTOP/data.local/mdsplus/b2md.dat) then
  set B2MDDAT=$SOLPSTOP/data.local/mdsplus/b2md.dat
else
  echo 'No b2md.dat found'
  exit
endif

if (! -s shotnumber.history) then
  echo "No shotnumber.history file present !"
  echo "Run save_mds instead"
  exit
endif

foreach i (`cat shotnumber.history | sort -n | uniq`)
  echo Processing $i
  cat $B2MDDAT | sed '/&end/,$d' >! b2md.dat
  echo " overwrite_shotnumber=$i" >> b2md.dat
  echo " &end" >> b2md.dat
  set count=0
  set count_suffix=`echo $count | gawk '{printf "%04i\n",$1}'`
  while (-e b2md.prt.$count_suffix)
    @ count ++  
    set count_suffix=`echo $count | gawk '{printf "%04i\n",$1}'`
  end
  if (-e b2md.prt) mv b2md.prt b2md.prt.$count_suffix
  if (-e b2md.log) mv b2md.log b2md.log.$count_suffix
  if (-e b2fstate.gz) gunzip b2fstate.gz
  if (-e b2fstati.gz) gunzip b2fstati.gz
  if (! -s mesh.extra) ln -s ../mesh.extra .
  if (! -s mesh.extra) then
   (cd .. ; ln -s ../mesh.extra .)
  endif
  if (! -s AMJUEL) ln -s $SOLPSTOP/modules/Eirene/Database/AMJUEL .
  ${MAKE} $debug $REDEFINES -f $SOLPSTOP/runs/Makefile.plot b2md.prt > b2md.log
end

if ($B2MDDAT == b2md.dat.sav) then
  mv b2md.dat.sav b2md.dat
else
  rm b2md.dat
endif

if (-e .resave_mds) rm -f .resave_mds
unsetenv STAND_ALONE
