#! /bin/tcsh -f

set debug=""
argloop:
  if ("X${1}X" == "X-nX") then
    set debug="-n"
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
    goto argloop
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if ($1 == "") then
      set debug="$debug TIME=$DBX"
    else
      set debug="$debug TIME=$1"
    endif
    shift
    goto argloop
  endif

if ($1 != "") then
  if (-d $1) then
    cd $1
  else if (-f $1) then
    cd `dirname $1`
  else
    echo $1 neither a directory or a file
    exit
  endif
endif
pwd

if (-e b2md.dat) then
  set B2MDDAT=b2md.dat.sav
  mv b2md.dat $B2MDDAT
else if (-e ../baserun/b2md.dat) then
  set B2MDDAT=../baserun/b2md.dat
else if (-e $SOLPSTOP/data/mdsplus/b2md.dat) then
  set B2MDDAT=$SOLPSTOP/data/mdsplus/b2md.dat
else
  echo 'No b2md.dat found'
  exit
endif

foreach i (`cat shotnumber.history | sort -n | uniq`)
  echo Processing $i
  cat $B2MDDAT | sed '/&end/,$d' >! b2md.dat
  echo " overwrite_shotnumber=$i" >> b2md.dat
  echo " &end" >> b2md.dat
  set count=0
  set count_suffix=`echo $count | gawk '{printf "%04i\n",$1}'`
  while (-e b2md.prt.$count_suffix)
    @ count ++  
    set count_suffix=`echo $count | gawk '{printf "%04i\n",$1}'`
  end
  if (-e b2md.prt) mv b2md.prt b2md.prt.$count_suffix
  if (-e b2md.log) mv b2md.log b2md.log.$count_suffix
  if (-e b2fstate.gz) gunzip b2fstate.gz
  if (-e b2fstati.gz) gunzip b2fstati.gz
  gmake $debug -f $SOLPSTOP/runs/Makefile.plot b2md.prt > b2md.log
end

if ($B2MDDAT == b2md.dat.sav) then
  mv b2md.dat.sav b2md.dat
else
  rm b2md.dat
endif

if (-e .resave_mds) rm -f .resave_mds
unsetenv STAND_ALONE
