#! /bin/csh -f
if (-e b2mn.exe.dir/b2ftrace) then
  set FILE=b2mn.exe.dir/b2ftrace
else
  set FILE=b2ftrace
endif
if (-x zcat) then
    set ZCAT=zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT $FILE | \
  awk 'BEGIN{ig=0}/data/&&ig==0{ig=1}/data/&&ig==2{printf "\n"}/^[^*]/&&ig>0{ig=2;printf "%s",$0}' | \
  resopt $argv | \
  awk '{print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11}' | \
  plot xlyplot9 `count -p D 0 1` `count -p C 0 6` iteration 'norm of residual of continuity equation' $PWD
