#! /bin/csh -f
if (-e b2mn.exe.dir) then
  set FILE=b2mn.exe.dir/b2ftrace
else
  set FILE=b2ftrace
endif
if (-x zcat) then
    set ZCAT=zcat
else
    set ZCAT="gzip --decompress --force --stdout"
endif
$ZCAT $FILE | \
  awk 'BEGIN{ig=0}/data/&&ig==0{ig=1}/data/&&ig==2{printf "\n"}/^[^*]/&&ig>0{ig=2;printf "%s",$0}' | \
  resopt $argv | \
  awk '{print $2,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24}' | \
  plot xlyplot11 `count -p D 0 1` `count -p O 0 8` iteration 'norm of residual of momentum equation' $PWD
