#! /bin/csh -f
if (-e b2mn.exe.dir/b2ftrace) then
  set FILE=b2mn.exe.dir/b2ftrace
else
  set FILE=b2ftrace
endif
cat $FILE | \
  awk 'BEGIN{ig=0}/data/&&ig==0{ig=1}/data/&&ig==2{printf "\n"}/^[^*]/&&ig>0{ig=2;printf "%s",$0}' | \
  resopt $argv | \
  awk '{print $2,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26}' | \
  plot xlyplot12 `count -p D 0 1` `count -p C 0 6` `count -p He 0 2` iteration 'norm of residual of momentum equation' $PWD
