#! /usr/bin/env csh
set cmd1="cat"
set MOD=0
set cmd2="cat"
set LAST=0
set cmd3="cat"
set AVE=0
while ($#argv > 0)
  switch ("X$1")
  case "X-m":
    set MOD=$2
    shift
    breaksw
  case "X-l":
    set LAST=$2
    shift
    breaksw
  case "X-a":
    set AVE=$2
    shift
    breaksw
  default:
    breaksw
  endsw
  shift
end
if ($MOD > 0) set cmd1="resmod $MOD 0"
if ($LAST > 0) set cmd2="tail -$LAST"
if ($AVE > 0) set cmd3="ave.awk $AVE"
$cmd1 | $cmd2 | $cmd3 | cat - $SOLPSTOP/scripts/blank | sed '$d'
