#! /bin/csh -f
set text=`basename $0`
switch ($text)
  case "resmt_reg":
    set label="total momentum residual"
    breaksw
  case "reshe_reg":
    set label="electron heat residual"
    breaksw
  case "reshi_reg":
    set label="ion heat residual"
    breaksw
  case "respo_reg":
    set label="potential residual"
    breaksw
  case "rdneureg":
    set label="neutral radiation"
    breaksw
  default:
    echo invalid quantity $text
    exit
endsw
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set freg=$nnreg[3]
if ("" == $vreg) set vreg=4
if ("" == $freg) set freg=13
@ vregP = $vreg + 1
if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif
setenv PLOT_FROM_FILE "gnuplot.temp"
pipe_run.log | \
  grep -a "^$text " | \
  awk '{for (i=2;i<=NF;i++) printf "%s ",$i;printf "\n"}' | \
  nl   >! ${tmpdir}PLOT_FROM_FILE
  plot x"$1"yplot$vregP `count 0 $vreg` iter "$label" $PWD
