#! /usr/bin/ksh

#==============================================================================#
#  Part of B2-Eirene service:                                                  #
#                                                                              #
#         replace the symbolic links to a specified directory tree with the    #
#         links to another tree, when the corresponding files exist.           #
# usage:                                                                       #
#         rlndr [-f] fromtree totree < list                                    #
#                                                                              #
#    The totree and fromtree must be the ABSOLUTE path names                   #
#    The list must have a format of ls -l output - that is, the symbolic       #
#    links are shown with ->.                                                  #
#                                                                              #
#  Author:  A.S.Kukushkin                                                      #
#                                                                              #
#  VERSION : 07.05.2001 16:26                                                  #
#==============================================================================#

unset force
[ "$1" = -f ] && {
  force=y
  shift
}
[ $# != 2 ] && { echo Usage: `basename $0` [-f] fromtree totree \< list; exit 2; }

FROM=$1; TO=$2
while true; do
    read NEXTLINE; [ -z "$NEXTLINE" ] && exit
    set / $NEXTLINE; FOUND=''; while true; do
        case /"$3" in
        ( /     )      break;;
        ( '/->' )      FOUND=1; break;;
        ( *     )      shift;;
        esac
    done

# here $2 is the link name, and $4 is the pathname to which the link points

    [ -z "$FOUND" ] || { case "$4" in
        ( $FROM/* )  NEWLINK=$TO${4#$FROM}; FN=$2;
                  [ -L $FN ] && [ -n "$force" ] || [ -a $NEWLINK ] && { rm -f $FN && ln -fs $NEWLINK $FN; true;
                  } || echo "Cannot proceed with $FN: not a link or a link to nothing";;
        ( *        )  ;;
        esac
    }
done
