#! /bin/csh -f
set text=`basename $0`
switch ($text)
  case "rsanareg_region":
    set label="ionization rate"
    breaksw
  case "rsamoreg_region":
    set label="ionization momentum"
    breaksw
  case "rsahireg_region":
    set label="ionization energy"
    breaksw
  case "rranareg_region":
    set label="recombination rate"
    breaksw
  case "rramoreg_region":
    set label="recombination momentum"
    breaksw
  case "rrahireg_region":
    set label="recombination energy"
    breaksw
  case "rcxnareg_region":
    set label="charge exchange rate"
    breaksw
  case "rcxmoreg_region":
    set label="charge exchange momentum"
    breaksw
  case "rcxhireg_region":
    set label="charge exchange energy"
    breaksw
  case "rqahereg_region":
    set label="electron heat loss"
    breaksw
  case "rqradreg_region":
    set label="radiation"
    breaksw
  case "rqbrmreg_region":
    set label="bremsstrahlung"
    breaksw
  case "b2stbr_she_reg_region":
    set label="electron heat loss (-) or source (+) rate from recycling"
    breaksw
  case "b2stbr_shi_reg_region":
    set label="ion heat loss (-) or source (+) rate from recycling"
    breaksw
  case "b2stbr_sne_reg_region":
    set label="electron particle loss (-) or source (+) rate from recycling"
    breaksw
  case "b2stbr_sch_reg_region":
    set label="charge loss (-) or source (+) rate from recycling"
    breaksw
  case "b2stbr_sna_reg_region":
    set label="particle loss (-) or source (+) rate from recycling"
    breaksw
  case "b2stbr_smo_reg_region":
    set label="momentum loss (-) or source (+) rate from recycling"
    breaksw
  case "b2stbc_she_reg_region":
    set label="electron heat loss (-) or source (+) rate from the boundary conditions"
    breaksw
  case "b2stbc_shi_reg_region":
    set label="ion heat loss (-) or source (+) rate from the boundary conditions"
    breaksw
  case "b2stbc_sne_reg_region":
    set label="electron particle loss (-) or source (+) rate from the boundary conditions"
    breaksw
  case "b2stbc_sch_reg_region":
    set label="charge loss (-) or source (+) rate from the boundary conditions"
    breaksw
  case "b2stbc_sna_reg_region":
    set label="particle loss (-) or source (+) rate from the boundary conditions"
    breaksw
  case "b2stbc_smo_reg_region":
    set label="momentum loss (-) or source (+) rate from the boundary conditions"
    breaksw
  case "b2stbm_she_reg_region":
    set label="electron heat loss (-) or source (+) rate from additional sources"
    breaksw
  case "b2stbm_shi_reg_region":
    set label="ion heat loss (-) or source (+) rate from additional sources"
    breaksw
  case "b2stbm_sne_reg_region":
    set label="electron particle loss (-) or source (+) rate from additional sources"
    breaksw
  case "b2stbm_shi_reg_region":
    set label="charge loss (-) or source (+) rate from additional sources"
    breaksw
  case "b2stbm_sna_reg_region":
    set label="particle loss (-) or source (+) rate from additional sources"
    breaksw
  case "b2stbm_smo_reg_region":
    set label="momentum loss (-) or source (+) rate from additional sources"
    breaksw
  case "b2sext_she_reg_region":
    set label="electron heat loss (-) or source (+) rate from external sources"
    breaksw
  case "b2sext_shi_reg_region":
    set label="ion heat loss (-) or source (+) rate from external sources"
    breaksw
  case "b2sext_sne_reg_region":
    set label="electron particle loss (-) or source (+) rate from external sources"
    breaksw
  case "b2sext_shi_reg_region":
    set label="charge loss (-) or source (+) rate from external sources"
    breaksw
  case "b2sext_sna_reg_region":
    set label="particle loss (-) or source (+) rate from external sources"
    breaksw
  case "b2sext_smo_reg_region":
    set label="momentum loss (-) or source (+) rate from external sources"
    breaksw
  case "resco_reg_region":
    set label="continuity residual"
    breaksw
  case "resmo_reg_region":
    set label="momentum residual"
    breaksw
  default:
    echo invalid quantity $text
    exit
endsw
set text=`echo $text | sed 's:_region::'`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set freg=$nnreg[3]
if ("" == $vreg) set vreg=4
if ("" == $freg) set freg=13
@ vregP = $vreg + 1
if ( X$1 =~ X[lLM] ) then
  set log="$1"
  shift
else
  set log=""
endif
if ("X$1" == "X") then
  set species=0
else
  set species=$1
endif
set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-s $solps_fluids) then
  setenv SOLPS_FLUIDS `cat $solps_fluids`
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on $solps_fluids)"
else
  setenv SOLPS_FLUIDS "`get_solps_fluids`"
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on log file)"
endif
set local_fluids=( $SOLPS_FLUIDS )
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif
setenv PLOT_FROM_FILE "gnuplot.temp"
if($species == 0) then
  echo "$label summed over all species"
  pipe_run.log | \
    grep -a "^$text " | \
    awk '{for (j=0;j<='$vreg';j++) {sum[j]=0; for (i=2;i<=NF;i+='$vregP') sum[j]+=$(i+j); printf "%g ",sum[j]};printf "\n"}' | \
    nl >! ${tmpdir}PLOT_FROM_FILE
    plot x"$log"yplot$vregP `count 0 $vreg` iter "$label summed over all species" $PWD
else
  echo "$label for species=$local_fluids[$species]"
  pipe_run.log | \
    grep -a "^$text " | \
    awk '{for (i=0;i<='$vreg';i++) printf "%g ",$(i+2+'$vregP'*('$species'-1));printf "\n"}' | \
    nl >! ${tmpdir}PLOT_FROM_FILE
    plot x"$log"yplot$vregP `count 0 $vreg` iter "$label for species=$local_fluids[$species]" $PWD
endif
