#!/bin/bash

ext=save
SAVE_LAST10=`ls *.last10 2>/dev/null`
SAVE_TRC=`ls -lt trc.* | head -1 | rev | cut -f 1 -d " " | rev`
SAVE_TRG=`ls -lt trg.* | head -1 | rev | cut -f 1 -d " " | rev`
SAVE_FILES="b2fstate b2fplasma b2fparam b2fmovie b2ftrack b2ftrace b2frates b2fpardf b2mn.dat b2.boundary.parameters b2.transport.parameters b2.user.parameters b2.feedback_control.parameters b2.neutrals.parameters b2.numerics.parameters b2.transport.inputfile b2.sources.profile b2.atomic_physics_rescale.parameters input.dat fort.10 fort.11 fort.13 fort.14 fort.15 fort.21 fort.22 fort.31 fort.33 fort.34 fort.35 fort.44 fort.46 b2.feedback_save.parameters b2.wall_save.parameters .VarID $SAVE_TRC $SAVE_TRG trg_sum.dat b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc last_2d_out last_2d_out_f ld_tg_i.dat ld_tg_o.dat ld_tg_iu.dat ld_tg_ou.dat fp_tg_i.dat fp_tg_o.dat fp_tg_iu.dat fp_tg_ou.dat box.b2p run.log.gz $SAVE_LAST10"
SAVE_DIR="tracing b2pl_PS batch_av"

backup=backup
label=`date +"%Y%m%d"`
BK_LAST10=`ls *.last10 2>/dev/null`
BK_TRC=`ls -lt trc.* | head -1 | rev | cut -f 1 -d " " | rev`
BK_TRG=`ls -lt trg.* | head -1 | rev | cut -f 1 -d " " | rev`
BK_FILES="b2fstate b2fplasma b2fparam b2fmovie b2ftrack b2ftrace b2frates b2fpardf b2mn.dat b2.boundary.parameters b2.transport.parameters b2.user.parameters b2.feedback_control.parameters b2.neutrals.parameters b2.numerics.parameters b2.transport.inputfile b2.sources.profile b2.atomic_physics_rescale.parameters input.dat fort.10 fort.11 fort.13 fort.14 fort.15 fort.31 fort.44 fort.46 b2.feedback_save.parameters b2.wall_save.parameters .VarID $BK_TRC $BK_TRG trg_sum.dat last_2d_out last_2d_out_f run.log.gz $BK_LAST10"
BK_MV_FILES="b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc"
BK_MV_DIR="tracing batch_av"

NAME=${0##*/}
[ ! $# -eq 0 ] && arg=$1
case $arg in
  -l)
    echo "saveb2 -l: local backup"
    mode=l
    ;;
  -s)
    echo "saveb2 -s: storing finished run(s)"
    mode=s
    ;;
   *)
    echo "$NAME - used to create local and final backups. "
    echo "USAGE: "
    echo "	saveb2 -l             : backup local files between b2run sessions"
    echo "	saveb2 -s dir_name(s) : store finished runs to dirname(s).$ext"
    exit 1
esac

shift

[ $mode == "l" ] && {

  echo "backup local files to $backup.$label"
  if [ ! -d $backup.$label ]
  then
    mkdir $backup.$label
    for f in $BK_FILES; do {
      [ -f "$f" ] && echo "cp $f $backup.$label/$f" && cp "$f" "$backup.$label/$f"
      if [ ! -s "$backup.$label/$f" ]
      then
        echo "warning: $f either absent or empty"
      fi
    }; done
    for ff in $BK_MV_FILES; do {
      [ -f "$ff" ] && echo "mv $ff $backup.$label/$ff" && mv "$ff" "$backup.$label/$ff"
      if [ ! -s "$backup.$label/$ff" ]
      then
        echo "warning: $ff either absent or empty"
      fi
    }; done
    for fd in $BK_MV_DIR; do {
      [ -d "$fd" ] && [ ! -z "$(ls -A "$fd")" ] && echo "mv $fd $backup.$label/$fd" && mv "$fd" "$backup.$label/$fd"
      if [ ! -d "$backup.$label/$df" ]
      then
        echo "warning: $fd either absent or empty"
      fi
    }; done
  else
    echo "$backup.$label already present, aborting..."
  fi

} || {

[ $mode == "s" ] && {

  [ $# -eq 0 ] && {
    echo "ERROR: No argument provided, nothing to save"
    } || {
    for run in "$@"; do {
      echo "b2save -s $run"
      if [ -d $run ] && [ ! -z "$(ls -A "$run")" ]
      then
        if [ -d "$run.$ext" ]
        then
          echo "rm -rf $run.$ext"
	  rm -rf "$run"."$ext"
        fi
        echo "mkdir $run.$ext"
        mkdir "$run"."$ext"
        for f in $SAVE_FILES; do {
          [ -f "$run/$f" ] && echo "cp -rf $run/$f $run.$ext/$f" && cp -rf "$run"/"$f" "$run"."$ext"/"$f"
          if [ ! -s "$run.$ext/$f" ]
          then
            echo "warning: $f either absent or empty"
          fi
        }; done
        for fd in $SAVE_DIR; do {
          [ -d "$run/$fd" ] && echo "cp -rf $run/$fd $run.$ext/" && cp -rf "$run"/"$fd" "$run"."$ext"/
          if [ ! -d "$run.$ext/$fd" ] && [ -z "$(ls -A "$run.$ext/$fd")" ]
          then
            echo "warning: $fd either absent or empty"
          fi
        }; done
      else
        echo "$run directory does not exist or empty, nothing to do"
      fi
      }; done
    }
  }
}
