#!/bin/bash

ext=save
#In case of save some files (trc, trg and last10) have to be added in the process of backup
SAVE_FILES_BASE="b2fstate b2fplasma b2fparam b2fmovie b2ftrack b2ftrace b2frates b2fpardf b2mn.dat b2.boundary.parameters b2.transport.parameters b2.user.parameters b2.feedback_control.parameters b2.neutrals.parameters b2.numerics.parameters b2.transport.inputfile b2.sources.profile b2.atomic_physics_rescale.parameters b2.feedback_save.parameters b2.wall_save.parameters input.dat eirene.input.json eirene_add_surfaces.input.json eirene_physics_model.input.json eirene_AMData.json user_data.input eirene_input_json.out fort.1 fort.10 fort.11 fort.13 fort.14 fort.15 fort.21 fort.22 fort.31 fort.33 fort.34 fort.35 fort.44 fort.44_aver fort.46 fort.46_aver .VarID trg_sum.dat b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc last_2d_out last_2d_out_f box.b2p run.log.gz dsa dsi dsl dsL dsLP dsr dsR dsRP dstl dsTL dsTLP dstr dsTR dsTRP"
SAVE_DIR="tracing b2pl_PS batch_av"

backup=backup
label=`date +"%Y%m%d"`
BK_LAST10=`ls *.last10 2>/dev/null`
BK_TRC=`ls -lt trc.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
BK_TRG=`ls -lt trg.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
BK_FILES="b2fstate b2fplasma b2fparam b2fmovie b2ftrack b2ftrace b2frates b2fpardf b2mn.dat b2.boundary.parameters b2.transport.parameters b2.user.parameters b2.feedback_control.parameters b2.neutrals.parameters b2.numerics.parameters b2.transport.inputfile b2.sources.profile b2.atomic_physics_rescale.parameters b2.feedback_save.parameters b2.wall_save.parameters input.dat eirene.input.json eirene_add_surfaces.input.json eirene_physics_model.input.json eirene_AMData.json user_data.input eirene_input_json.out fort.1 fort.10 fort.11 fort.13 fort.14 fort.15 fort.31 fort.44 fort.44_aver fort.46 fort.46_aver"
BK_MV_FILES="b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc"
BK_MV_DIR="tracing batch_av"

NAME=${0##*/}
[ ! $# -eq 0 ] && arg=$1
case $arg in
  -l)
    echo "saveb2 -l: local backup"
    mode=l
    ;;
  -s)
    echo "saveb2 -s: storing finished run(s)"
    mode=s
    ;;
   *)
    echo "$NAME - used to create local and final backups. "
    echo "USAGE: "
    echo "	saveb2 -l             : backup local files between b2run sessions"
    echo "	saveb2 -s dir_name(s) : store finished runs to dirname(s).$ext"
    exit 1
esac

shift

[ $mode == "l" ] && {

  echo "backup local files to $backup.$label"
  if [ ! -d $backup.$label ]
  then
    mkdir $backup.$label
    for f in $BK_FILES; do {
      [ -f "$f" ] && echo "cp $f $backup.$label/$f" && cp "$f" "$backup.$label/$f"
      if [ ! -s "$backup.$label/$f" ]
      then
        echo "warning: $f either absent or empty"
      fi
    }; done
    for ff in $BK_MV_FILES; do {
      [ -f "$ff" ] && echo "mv $ff $backup.$label/$ff" && mv "$ff" "$backup.$label/$ff"
      if [ ! -s "$backup.$label/$ff" ]
      then
        echo "warning: $ff either absent or empty"
      fi
    }; done
    for fd in $BK_MV_DIR; do {
      [ -d "$fd" ] && [ ! -z "$(ls -A "$fd")" ] && echo "mv $fd $backup.$label/$fd" && mv "$fd" "$backup.$label/$fd"
      if [ ! -d "$backup.$label/$df" ]
      then
        echo "warning: $fd either absent or empty"
      fi
    }; done
  else
    echo "$backup.$label already present, aborting..."
  fi

} || {

[ $mode == "s" ] && {

  [ $# -eq 0 ] && { 
    echo "ERROR: No argument provided, nothing to save"
    } || {
    for run in "$@"; do { 
      hlp=`echo $run | rev`
      [ "${hlp:0:1}" == "/" ] && run=`echo ${hlp:1} | rev`
      echo "b2save -s $run"
      if [ -d $run ] && [ ! -z "$(ls -A "$run")" ]
      then
        if [ -d "$run.$ext" ]
        then 
          echo "rm -rf $run.$ext"
	  rm -rf "$run"."$ext"
        fi
        echo "mkdir $run.$ext"
        mkdir "$run"."$ext"
	#Add extra files here
	echo "cd $run" && cd $run
        SAVE_LD=`ls ld_tg_* 2>/dev/null`
        SAVE_FP=`ls fp_tg_* 2>/dev/null`
        SAVE_PP=`ls peak_power* 2>/dev/null`
        SAVE_TRC=`ls -lt trc.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
        SAVE_TRG=`ls -lt trg.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
	SAVE_FILES="$SAVE_FILES_BASE $SAVE_LD $SAVE_FP $SAVE_PP $SAVE_TRC $SAVE_TRG"
	echo "cd ../" && cd ../
        for f in $SAVE_FILES; do {
          [ -f "$run/$f" ] && echo "cp -rf $run/$f $run.$ext/$f" && cp -rf "$run"/"$f" "$run"."$ext"/"$f"
          if [ ! -s "$run.$ext/$f" ]
          then
            echo "warning: $f either absent or empty"
          fi
        }; done
        for fd in $SAVE_DIR; do {
          [ -d "$run/$fd" ] && echo "cp -rf $run/$fd $run.$ext/" && cp -rf "$run"/"$fd" "$run"."$ext"/
          if [ ! -d "$run.$ext/$fd" ]
          then
            echo "warning: $fd is absent"
	  else
            if [ -z "$(ls -A "$run.$ext/$fd")" ]
            then
              echo "warning: $fd is empty"
	    fi
          fi
        }; done
      else
        echo "$run directory does not exist or empty, nothing to do"
      fi
      }; done
    }
  }
}
