#! /bin/tcsh -f

set debug=""
argloop:
  if ("X${1}X" == "X-nX") then
    set debug="-n"
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
    goto argloop
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if ($1 == "") then
      set debug="$debug TIME=$DBX"
    else
      set debug="$debug TIME=$1"
    endif
    shift
    goto argloop
  endif

if (-s shotnumber.history) then
  echo "Shotnumber.history already exists in $PWD"
  exit
endif
# fs prefetch -w run.log* b2fstat* b2fplasma fort.44
if (-e b2fstati.gz) gunzip b2fstati.gz
if (-e b2fstate.gz) gunzip b2fstate.gz
if (! -s mesh.extra) ln -s ../mesh.extra .
if (! -s mesh.extra) then
 (cd .. ; ln -s ../mesh.extra .)
endif
if (! -s AMJUEL) ln -s $SOLPSTOP/modules/Eirene/Database/AMJUEL .
gmake $debug -f $SOLPSTOP/runs/Makefile.plot b2md.prt > b2md.log
if (-s shotnumber.history) then
  cat shotnumber.history
  rm -f .save_mds .resave_mds
else
  echo "No shotnumber.history created: save_mds failed. See b2md.log file for details"
endif

unsetenv STAND_ALONE
