#! /bin/tcsh -f
if (-e shotnumber.history) then
  echo "Shotnumber.history already exists in $PWD"
  exit
endif
# fs prefetch -w run.log* b2fstat* b2fplasma fort.44
if (-e b2fstati.gz) gunzip b2fstati.gz
if (-e b2fstate.gz) gunzip b2fstate.gz
if (! -e mesh.extra) ln -s ../mesh.extra .
if (! -e mesh.extra) then
 (cd .. ; ln -s ../mesh.extra .)
endif
gmake -f $SOLPSTOP/runs/Makefile.plot b2md.prt > b2md.log
if (-e shotnumber.history) then
  cat shotnumber.history
else
  echo "No shotnumber.history created: save_mds failed. See b2md.log file for details"
endif
