#! /bin/tcsh -f
set datapath=`echo $PWD/ | sed -e "s|$SOLPSTOP||" -e 's|[^/]*/|../|g' -e 's|$|modules/Eirene/Database|'`
if (! -e ${datapath}/PHOTON) then
  set datapath=`canonical $SOLPSTOP`/modules/Eirene/Database
  if (! -e ${datapath}/PHOTON) then
    set datapath=$SOLPSTOP/modules/Eirene/Database
  endif
endif
if ("X$1X" == "X-rX") then
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/amjuel.tex` AMJUEL        
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/h2vibr.tex` H2VIBR  
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/hydhel.tex` HYDHEL  
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/methane.tex` METHANE
  ln -sf `climb_and_look_for -r modules/Eirene/Database/PHOTON`         
  ln -sf `climb_and_look_for -r modules/Eirene/Database/Surfacedata/SPUTER`        
  ln -sf `climb_and_look_for -r modules/Eirene/Database/Surfacedata/TRIM/trim.dat` fort.21   
  ln -sf `climb_and_look_for -r modules/Eirene/Database/Surfacedata/TRIM/marlow.dat` fort.22
  ln -sf `climb_and_look_for -r modules/Eirene/Database/graphite_ext.dat` graphite_ext.dat
  ln -sf `climb_and_look_for -r modules/Eirene/Database/mo_ext.dat` mo_ext.dat
else
  ln -sf ${datapath}/AMdata/amjuel.tex AMJUEL
  ln -sf ${datapath}/AMdata/h2vibr.tex H2VIBR
  ln -sf ${datapath}/AMdata/hydhel.tex HYDHEL
  ln -sf ${datapath}/AMdata/methane.tex METHANE
  ln -sf ${datapath}/PHOTON
  ln -sf ${datapath}/Surfacedata/SPUTER
  ln -sf ${datapath}/Surfacedata/TRIM/trim.dat fort.21
  ln -sf ${datapath}/Surfacedata/TRIM/marlow.dat fort.22
  ln -sf ${datapath}/graphite_ext.dat .
  ln -sf ${datapath}/mo_ext.dat .
endif

if (! -e input.dat) then
  if (-e ../baserun/input.dat) then
    ln -s ../baserun/input.dat .
  else if (-e input.eir) then
    ln -s input.eir input.dat
    echo "Creating a link between input.eir and input.dat"
  else if (-e ../baserun/input.eir) then
   ln -s ../baserun/input.eir input.dat
   echo "Creating a link between ../baserun/input.eir and input.dat"
  else
    set inputfile=`climb_and_look_for input.dat`
    if (-e $inputfile) then
      ln -s $inputfile .
    else
      set inputfile=`climb_and_look_for input.eir`
      if (-e $inputfile) then
        ln -s $inputfile input.dat
        echo "Creating a link between $inputfile and input.dat"
      else
        echo "Warning: no input.dat found!"
      endif
    endif
  endif
endif
ln -sf input.dat fort.1
if (! -e fort.33) then
  if (-e ../TRIANG/fort.33) then
    ln -s ../TRIANG/fort.33 .
    ln -s ../TRIANG/fort.34 .
    ln -s ../TRIANG/fort.35 .
  else if (-e ../baserun/fort.33) then
    ln -s ../baserun/fort.33 .
    ln -s ../baserun/fort.34 .
    ln -s ../baserun/fort.35 .
  endif
endif
if (! -e mesh.extra) then
  if (-e ../baserun/mesh.extra) then
    ln -s ../baserun/mesh.extra .
  else
    set meshxtra=`climb_and_look_for mesh.extra`
    if (-e $meshxtra) then
      ln -s $meshxtra .
    endif
  endif
endif
if (! -e param.dg) then
  if (-e ../baserun/param.dg) then
    ln -s ../baserun/param.dg .
  else
    set paramdg=`climb_and_look_for param.dg`
    if (-e $paramdg) then
      ln -s $paramdg .
    endif
  endif
endif
if (! -e b2.log) ln -sf run.log b2.log
if (! -e b2.log.gz) ln -sf run.log.gz b2.log.gz
if (! -e tracing) mkdir tracing
