#! /usr/bin/env tcsh

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`

if ($1 == "") then
  if (-e input.dat) then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for QSUB.sge_coupled
    set QSUB=`climb_and_look_for QSUB.sge_coupled`
    if ($QSUB == "//QSUB.sge_coupled") set QSUB=""
  else
    echo Assuming standalone run
    echo No argument is specified. Looking for QSUB.sge
    set QSUB=`climb_and_look_for QSUB.sge`
    if ($QSUB == "//QSUB.sge") set QSUB=""
  endif
else if (-e $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1 
  set QSUB=`climb_and_look_for $1`
  echo Submission file $QSUB is found
  if ($QSUB == "//"$1) set QSUB=""
endif
if($QSUB == "") then
  echo No SGE submission file found. Exiting.
  exit
endif
echo Using submission file template $QSUB

# if ("X$1" == "X-z") then
#  echo run.log will be compressed
#  sed -e 's:#PWD#:'$PWD':g' -e 's:#SOLPSTOP#:'$SOLPSTOP':g' -e 's:#EMAIL#:'$EMAIL':g' < $QSUB-gz > $NAME
#else
  sed -e 's:#PWD#:'$PWD':g' -e 's:#SOLPSTOP#:'$SOLPSTOP':g' -e 's:#EMAIL#:'$EMAIL':g' < $QSUB > $NAME
# endif

update_solps_run_status -n "Submitted at `date`"
qsub -V -S /usr/bin/tcsh $NAME
