#! /usr/bin/env tcsh

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
echo Your email is $EMAIL

set compress=""
if ("X$1X" == "X-zX") then
  set compress="-gz"
  echo run.log will be compressed
  shift
endif

set MPIOPTS=""
if ("X$1X" == "X-mX") then
  shift
  set MPIOPTS="$1"
  echo Using MPI options: $MPIOPTS
  shift
endif

if ($1 == "") then
  if (-e input.dat) then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for QSUB.sge_coupled$compress
    set QSUB=`climb_and_look_for QSUB.sge_coupled$compress`
    if ($QSUB == "//QSUB.sge_coupled$compress") set QSUB=""
  else
    echo Assuming standalone run
    echo No argument is specified. Looking for QSUB.sge$compress
    set QSUB=`climb_and_look_for QSUB.sge$compress`
    if ($QSUB == "//QSUB.sge$compress") set QSUB=""
  endif
else if (-e $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1 
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    set QSUB=""
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No SGE submission file $1 found. Exiting.
  exit
endif
echo Using submission file template $QSUB

sed -e 's:#PWD#:'$PWD':g' -e 's:#SOLPSTOP#:'$SOLPSTOP':g' -e 's:#EMAIL#:'$EMAIL':g' -e "s:#MPIOPTS#:'$MPIOPTS':g" < $QSUB > $NAME

update_solps_run_status -n "Submitted at `date`"
qsub -V -S /usr/bin/tcsh $NAME
