#! /usr/bin/env tcsh

cd $SOLPSTOP
echo "Switching to SOLPS-ITER develop branch"
git fetch --prune
git checkout develop && echo "Checked out SOLPS-ITER develop branch" || goto branch
git pull && goto b25 || goto local

b25:
  cp .gitmodules_develop .gitmodules
  git submodule update
  echo "Updating B2.5"
  cd $SOLPSTOP/modules/B2.5
  git fetch --prune
  git checkout develop && echo "Checked out B2.5 develop branch" || goto branch
  git pull && goto Eirene || goto local

Eirene:
  echo "Updating Eirene"
  cd $SOLPSTOP/modules/Eirene
  git fetch --prune
  git checkout develop && echo "Checked out Eirene develop branch" || goto branch
  git pull && goto Carre || goto local

Carre:
  echo "Updating Carre"
  cd $SOLPSTOP/modules/Carre
  git fetch --prune
  git checkout develop && echo "Checked out Carre develop branch" || goto branch
  git pull && goto DivGeo || goto local

DivGeo:
  echo "Updating DivGeo"
  cd $SOLPSTOP/modules/DivGeo
  git fetch --prune
  git checkout develop && echo "Checked out DivGeo develop branch" || goto branch
  git pull && goto ADAS || goto local

ADAS:
  echo "Updating ADAS"
  cd $SOLPSTOP/modules/adas
  git fetch --prune
  git checkout develop && echo "Checked out ADAS develop branch" || goto branch
  git pull && goto compile || goto local

branch:
  echo "You are not on the main development branch."

local:
  echo "You have local files under version control which"
  echo "would cause a conflict during the update."
  echo "Please modify, delete, rename, stash these files or"
  echo "commit them to a local branch before proceeding with the update."
  exit

compile:
  cd $SOLPSTOP
  rehash
  ${MAKE} VERSION
  ${MAKE} listobj listobj_debug
  ${MAKE} depend depend_debug
  ${MAKE} tags
  ${MAKE} solps



