#! /usr/bin/env tcsh

cd $SOLPSTOP
echo "Switching to SOLPS-ITER WG-relese branch"
git fetch --prune
git checkout feature/wg-release && echo "Checked out SOLPS-ITER WG-release branch" || goto branch
git pull && goto b25 || goto local

b25:
  git submodule update
  echo "Updating B2.5"
  cd $SOLPSTOP/modules/B2.5
  git fetch --prune
  git checkout feature/wg-release && echo "Checked out B2.5 WG-release branch" || goto branch
  git pull && goto Eirene || goto local

Eirene:
  echo "Updating Eirene"
  cd $SOLPSTOP/modules/Eirene
  git fetch --prune
  git checkout feature/wg-release && echo "Checked out Eirene WG-release branch" || goto branch
  git pull && goto compile || goto local

branch:
  echo "You are not on the WG-release branch."

local:
  echo "You have local files under version control which"
  echo "would cause a conflict during the update."
  echo "Please modify, delete, rename, stash these files or"
  echo "commit them to a local branch before proceeding with the update."
  exit

compile:
  cd $SOLPSTOP
  rehash
  ${MAKE} VERSION
  ${MAKE} listobj listobj_debug
  ${MAKE} depend depend_debug
  ${MAKE} tags
  ${MAKE} solps MAKE_OPTIONS=-j8

