#! /usr/bin/env tcsh

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
set PROCS=1
echo Your email is $EMAIL

set compress=""
set MPIOPTS=""

set solpstop=`climb_and_look_for SOLPSTOP`
if (-s $solpstop) then
  setenv SOLPSTOP "`cat $solpstop`"
else
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
endif

argloop:
  if ("X$1X" == "X-zX") then
    set compress="-gz"
    echo run.log will be compressed
    shift
    goto argloop
  endif
  if ("X$1X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set MPIOPTS="$1"
    echo Using MPI options: $MPIOPTS
    set PROCS=`echo $MPIOPTS | awk.transpose | grep -A 1 "\-np" | tail -n 1`
    echo Asking for $PROCS processors
    shift
    goto argloop
  endif

if ($1 == "") then
  if (-s input.dat) then
    echo Assuming run with Eirene
    echo No argument is specified. Looking for SBATCH.spbstu_coupled$compress
    set QSUB=`climb_and_look_for SBATCH.spbstu_coupled$compress`
    if ($QSUB == "//SBATCH.spbstu_coupled$compress") then
      if (-s $SOLPSTOP/runs/SBATCH.spbstu_coupled$compress) then
        set QSUB="$SOLPSTOP/runs/SBATCH.spbstu_coupled$compress"
      else
        set QSUB=""
      endif
    endif
  else
    echo Assuming standalone run
    echo No argument is specified. Looking for SBATCH.spbstu$compress
    set QSUB=`climb_and_look_for SBATCH.spbstu$compress`
    if ($QSUB == "//SBATCH.spbstu$compress") then
      if (-s $SOLPSTOP/runs/SBATCH.spbstu$compress) then
        set QSUB="$SOLPSTOP/runs/SBATCH.spbstu$compress"
      else
        set QSUB=""
      endif
    endif
  endif
else if (-s $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1 
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    if (-s $SOLPSTOP/runs/$1) then
      set QSUB="$SOLPSTOP/runs/$1"
    else
      set QSUB=""
    endif
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No SPBSTU submission file $1 found. Exiting.
  exit
endif
echo Using submission file template $QSUB

sed -e 's:#PWD#:'$PWD':g' -e 's:#SOLPSTOP#:'$SOLPSTOP':g' -e 's:#EMAIL#:'$EMAIL':g' -e "s:#MPIOPTS#:'$MPIOPTS':g" -e "s:#PROCS#:'$PROCS':g" < $QSUB > $NAME

set msg="Submitted at `date`"
update_solps_run_status -n ${msg}
if ($?SOLPS_GUI_IP) then
  echo ${USER} ${PWD} ${msg} | nc -u -v -w 0 ${SOLPS_GUI_IP} ${SOLPS_GUI_PORT}
endif
echo sbatch $NAME
echo $NAME
sbatch $NAME

rm -f $NAME

