#! /bin/csh -f
if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif
pipe_run.log | \
  egrep -a tchee\|tphye\|thvpe\|trese\|trfle | \
  awk '{print $2}' | \
  paste - - - - - | \
  nl >! ${tmpdir}PLOT_FROM_FILE
  x"$1"yplot5 tphye tchee thvpe trese trfle
