#! /bin/csh -f
set solps_fluids=`climb_and_look_for SOLPS_FLUIDS`
if (-e $solps_fluids) then
  setenv SOLPS_FLUIDS `cat $solps_fluids`
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on $solps_fluids)"
else
  setenv SOLPS_FLUIDS "`get_solps_fluids`"
  echo Set SOLPS_FLUIDS to $SOLPS_FLUIDS "(based on log file)"
endif
set nplts=`echo $SOLPS_FLUIDS | wc -w`
@ nplts += 1
if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif
setenv PLOT_FROM_FILE "gnuplot.temp"
pipe_run.log | \
  grep -a trese | \
  sed 's:trese::' | \
  nl >! ${tmpdir}PLOT_FROM_FILE
  plot x"$1"yplot$nplts SUM $SOLPS_FLUIDS iter "Radiation Enhanced Sublimation Energy" $PWD
