#! /usr/bin/env tcsh

setenv GNUPLOT_POSTSCRIPT_OPTIONS 'color solid'
setenv PRINT_PLOT resrest.ps ; resrest
setenv PRINT_PLOT resco.ps ; resco
setenv PRINT_PLOT resmo.ps ; resmo
setenv PRINT_PLOT rqahereg.ps ; rqahereg
setenv PRINT_PLOT energy_analysis.ps ; energy_analysis
setenv PRINT_PLOT density.ps ; density l
2d_profiles
2d_plots
last10
