#! /bin/tcsh -f

###                save important files as a single tar file                ###

mkdir $USER.work.$$
mv b2.*.parameters b2.*.inputfile b2.*.profile input.dat b2mn.dat b2fgmtry b2fpardf b2fstati b2frates b2mn.prt b2fparam b2fstate b2ftrace b2fplasma *.nc fort.15 fort.3[01] fort.3[3-5] fort.44 run.log ds* output.* $USER.work.$$/
set DATESTAMP=`datestamp`
(cd $USER.work.$$ ; tar cvf ../$DATESTAMP.tar .)
mv $USER.work.$$/* .
rmdir $USER.work.$$
tar tvf $DATESTAMP.tar >& $DATESTAMP.tar.toc
gzip -9 $DATESTAMP.tar
