#! /bin/ksh

#==============================================================================#
#  Part of B2-Eirene service:                                                  #
#                                                                              #
#  creates plots of the run history, using VarID file for the run              #
#  identification, and invokes GhostView to show them on the screen            #
#                                                                              #
#  Author:  A.S.Kukushkin                                                      #
#                                                                              #
#  VERSION : 08.07.99 23:23
#==============================================================================#

scriptname=`basename $0`
scriptdir=`dirname $0`

noview=
while true; do
  case "$1" in
    ( -*) case "$1" in
            ( -n)   noview=y;;
            ( * )   echo "Non-supported option: $1";;
          esac; shift;;
    ( * ) break;;
  esac
done

[ -s B2STIME ] || [ -s b2time.nc ] && {
  (cd time_dep && rm -f *.ps ??3d? traces gnuplot.cmd last_2d_out LOCK) > /dev/null 2>&1
  [ -s VarID ] && I=`cat VarID` || I=`basename \`pwd\``
  time_dep/document "$I" $*
}

[ -s time_dep/tmp2d.ps ] && { \
#  put pages in order 4 by 4 according to pages_tmp2d
    if [ -r time_dep/pages_tmp2d ] ; then
      ps4 time_dep/tmp2d.ps time_dep/pages_tmp2d
    else
      ps4 time_dep/tmp2d.ps ${scriptdir}/pages_tmp2d
    fi
}

unset L2D_PROC
if [ -s time_dep/traces ]; then
  last_2d &
  L2D_PROC=$!
fi

if [ -z "$noview" ]; then
    [ -s time_dep/tmp2d4.ps ] && file=time_dep/tmp2d4.ps || file=time_dep/tmp2d.ps
    ghostview $GV_OPT $file &
    setnice 0 $!
fi
[ -n "$L2D_PROC" ] && ps -p $L2D_PROC > /dev/null 2>&1 && wait $L2D_PROC
