#! /usr/bin/env tcsh

if($1 == "") then
  if (-s b2.neutrals.parameters) then
    set count = `egrep -i 'NSTRAI *=' b2.neutrals.parameters | tail -1 | sed -e 's/NSTRAI//' | sed -e 's/nstrai//' | sed -e 's/=//' | sed -e 's/,//'`
  else if (-s $SOLPSTOP/modules/B2.5/src/include.local/DIMENSIONS.F) then
    set count = `egrep 'DEF_NSTRA' $SOLPSTOP/modules/B2.5/src/include.local/DIMENSIONS.F | tail -1 | sed -e 's/^#define DEF_NSTRA//'`
  else
    set count = `egrep 'DEF_NSTRA' $SOLPSTOP/modules/B2.5/src/include/DIMENSIONS.F | tail -1 | sed -e 's/^#define DEF_NSTRA//'`
  endif
  if (-s fort.1) then
    set count = `echo $count 1 | awk '{print $1+$2}'`
  endif   
#  set count=20
else
  set count=$1
endif
echo Found $count strata
pipe_run.log | \
  grep -a "tflux:" | \
  awk '{for (i=2;i<=NF;i++) printf " %s",$i;printf "\n"}' | \
  nl | \
  plot xlyplot"$count" `count 1 $count` "iteration number" "tflux (#/s)" $PWD
