#! /usr/bin/ksh

#  VERSION : 23.01.2005 18:10

NAME=${0##*/}

ps_p="${PS_P--p}"

[ -r /tmp/NO_TRC ] && exit 1
[ -r .NO_TRC ] && exit 1

[ -s .trc_running ] && {
    ps $ps_p `cat .trc_running` >/dev/null && {
    print -u2 'trc is already running here!!!'; exit 32;
  }
} || {
  [ -r .trc_running ] && {
    print -u2 'trc is already running here!!!'; exit 32;
  }
}
print $$ > .trc_running

# Parse the parameters

# option  variable      function
#   -n      view        do not show the plot (batch mode)
#   -p      tmdp        do not run time_dep (plot only)
#   -t      tmdp        do not produce "tmp3d.ps" (debugging mode)

unset view tmdp trco
while true; do
  case "$1" in
    ( -n  )   view=$1;;
    ( -p  )   trco=$1;;
    ( -t  )   tmdp=$1;;
    ( -*  )   print -u2 -- "Non-supported option $1";;
    ( *   )   break;;
  esac; shift
done

D=
if [ -n "$view" ]; then
# Batch mode. Start a daemon monitoring the appearance of /tmp/suspend flag
  (
    while true; do
        [ -f /tmp/suspend ] && break
        sleep 10
    done
    > .NO_TRC
    sleep 10
    rm -f .trc_running
    crack $$
  )&
  D=$!
fi

# clean up the directory

rm -f trc.ps trc.err 2>/dev/null

# run td in the data mode in order to have the traces file

PROC_LIS='PROC_3D L2D_PROC PROC_ps4'
unset td_ID $PROC_LIS
[ -z "$trco" ] && time_dep/document -d data > td.log

# Create truncated files for the residuals and sources

unset NL RMLIS
[ -s RES ] && [ -r RES ] && {
  set -A l -- `grep -v \# RES | head -1`
  NL=${l[1]}
  unset l
}
NL="${NL:=200}"
set -- $NL 300 $NL

[ -s "$SOLPSTOP/bin/$OBJECTCODE/nl" ] && nl="$SOLPSTOP/bin/$OBJECTCODE/nl" || nl=nl

for f in residuals sources test; do {
  f1="tracing/$f.trc"
  f2="tracing/$f.tmp"
  RMLIS="$RMLIS $f2"
#  (grep '^#' $f1 | tail -1 | sed -e 's/#/#iit /'; grep -v '^#' $f1 | nl | tail -$1) > $f2
  (grep '^#' $f1 | tail -1 | sed -e 's/#/#iit /'; grep -v '^#' $f1 | $nl | tail -$1) > $f2
  shift
}; done

[ -f .NO_TRC ] && {
  \rm -f .trc_running
  exit
}

# Extract the average values from the tracing files

if [ -s time_dep/traces ]; then
  [ ! -d last_2dir ] && mkdir last_2dir
  ( last_2d > last_2d.log 2>&1
    cd last_2dir
    rm -f var_out powers_out temp[01]_out 2>/dev/null
  ) &
  L2D_PROC=$!
fi

export PLOT_IT_STEM=trc
[ ! -s VarID ] && v="$PWD" || v=`cat VarID | tr _/ '  '`
[ -f .NO_TRC ] && {
  \rm -f .trc_running
  exit
}
TRC=trc
#Check whether this is a limiter case
. get_parm.bpl
[ "$NXC_I" -eq 0 ] && [ "$NXC_O" -gt "$NX" ] && [ "$NNISO" -eq 2 ] && TRC=trc_lim

echo "=== $NAME: before plot_set. PLOT_IT_STEM=$PLOT_IT_STEM, TRC=$TRC, v=$v ===" #!!!
plot_set -f $PLOT_IT_STEM.ps -s -t "$v" $TRC.cms
[ -s $PLOT_IT_STEM.ps ] || {
  print -u2 "$NAME: bad PS file. Re-creating $PLOT_IT_STEM.cmd"
  rm $PLOT_IT_STEM.cmd
  plot_set -f $PLOT_IT_STEM.ps -t "$v" $TRC.cms
}
# Plot testing data for particle balance
PB=part_blnc
PBH="$SOLPSTOP/data/plot_set/$PB.hed"
PBT="$SOLPSTOP/data/plot_set/$PB.tpl"
[ -s "$PBH" ] && [ -s "$PBT" ] && {
  export NSPEC SPEC
  (cat "$PBH"
    i=0; until [ $i -eq "$NSPEC" ]; do {
      s=`echo ${SPEC[i]} | sed 's/_//g'`
      sed "s/%%/$s/g" < "$PBT"
      let "i=i+1"
    }; done
  ) > $PB.cms
  plot_set -t "$v" $PB.cms
} || {
  echo "Some of $PBH $PBT not found - no particle balance tracing"
}

[ -n "$RMLIS" ] && \rm -f $RMLIS

[ -f .NO_TRC ] && {
  \rm -f .trc_running
  exit
}
if [ -z "$view" ] ; then
  ghostview $GV_OPT $PLOT_IT_STEM.ps &
  setnice 0 $!
fi

# put pages in order 4 by 4 according to layout.trc

#echo "=== $NAME: before layout.ps4. PLOT_IT_STEM=$PLOT_IT_STEM, v=$v ==="

ps4_map=`layout.ps4 $PLOT_IT_STEM.ps.legend layout.$TRC`
ps4 $PLOT_IT_STEM.ps -n $ps4_map &
PROC_ps4=$!

set -A td_ID -- `tail -1 td.log`
td_ID[1]="${td_ID[1]}$trco"
if [ -n "${td_ID[1]}" ]; then
  print "$NAME: wrong format of document output. No 3D plots created."
else
  echo "=== $NAME: tmdp= $tmdp ==="
  if [ -z "$tmdp" ]; then
    ( cd time_dep
      sed "s:LABEL:$v:g" gnuplot_3d_timetraces > gnuplot_3d_timetraces.$td_ID
      gnuplot gnuplot_3d_timetraces.$td_ID
    ) >> td.log 2>&1 &
    PROC_3D=$!
  fi
fi

#echo "=== $NAME: after td. PROC_3D=$PROC_3D, L2D_PROC=$L2D_PROC ==="

# wait until the background jobs are over

for pp in $PROC_LIS; do
  eval "p=\$$pp"
  [ -n "$p" ] && wait $p
done
rm time_dep/gnuplot_[23]d_timetraces.$td_ID 2>/dev/null
\rm -f .trc_running 2>/dev/null

# kill the daemon, if started

[ -n "$D" ] && kill $D
