#! /usr/bin/ksh

#  VERSION : 21.01.2002 21:12

# Prepares tracing data to plot on the summary plots - indication of the data spread.
# If the third non-comment line in the "RES" file is not empty, then the first value from there
# is used to determine the time range of the data selected. It can be
#   (integer) the number of last lines in the *.trc files, or
#   (positive real) the starting time [ms], or
#   (negative real) the time span [ms] from the last line.
# If started in the "tracing" directory, the script uses the data from there, otherwise from "traces_all"
 

NAME=${0##*/}
CHECK_LIST='traces user.trc blnn.trc blne.trc integral.trc sepdata.trc'
regular='traces'
seldom='seldom.trc'

[ "$1" = '-b' ] && view=n || view=

export PLOT_IT_STEM=trcpp
SEL_FILE=$SOLPSTOP/data/plot_set/trcpp.stc
SEL_SLDM=$SOLPSTOP/data/plot_set/trcpp-s.stc

[ -s "$SEL_FILE" ] || {
  print -u2 -- "$NAME: the data selection control file not found: $SEL_FILE"
  exit 4
}

D=${PWD##*/}
unset RMTR

{ case "$D" in
  ( traces_all ) ;;
  (tracing )  ln -sf ../time_dep/traces .; RMTR=traces;;
  ( * ) cd traces_all || {
      print -u2 -- "$NAME: unable to switch to traces_all"
      exit 4
    };;
esac; }

# Check the data files

for f in $CHECK_LIST; do {
  [ ! -s $f ] && {
    print -u2 -- "$NAME: file $f not found"
    exit 4
  }
}; done

# Check for the data range to plot - the 3rd line in the "RES" file

unset RES t 
[ -s RES ] && [ -r RES ] && RES=RES || {
  [ -s ../RES ] && [ -r ../RES ] && RES=../RES
}

[ -n "$RES" ] && {
  set -A RES -- `grep -v \# $RES | tail -n +3 | head -1`
  [ -n "$RES" ] && {

# Determine the starting time

    [ "${RES#*.}" = "${RES}" ] && {
# Integer - the number of lines
      ((i=l+1))
      set -A t -- `grep -v \# $regular | tail -$i`
      true
    } || {
      set -A t -- `print -- ${RES} | awk '{print 0.001*$l}'`
      [ "${t#-}" = "$t" ] || {
# Negative - the time span from the end
        t=`echo $t \`tail -1 $regular\` | awk '{print $1+$2}'`
      }
      u=`grep -v \# $regular | wc -l`
      RES=`grep -v \# $regular | awk "{if(\\$1>$t) {print $u-NR; exit}}"`
    }
    u=`grep -v \# $seldom | wc -l`
    RES[1]=`grep -v \# $seldom | awk "{if(\\$1>$t) {print $u-NR; exit}}"`
  }
}

print -- "lines, starting time : ${RES[0]} : ${RES[1]} : $t :"

# Compose the case label

LL="$PWD"
[ -s VarID ] && {
  LL=`cat VarID | tr _ ' '`
} || {
  [ -s ../VarID ] && {
    LL=`cat ../VarID | tr _ ' '`
  } || {
    [ -s ../../VarID ] && {
      LL=`cat ../../VarID | tr _ ' '`
    }
  }
}

# Check the number of lines in traces and *.trc: 
# at some point, the very first line has been removed from *.trc files

[ -a traces.tmp ] && { 
  \rm -f traces.tmp || {
    print -u2 -- "$NAME: unable to remove \"traces.tmp\""
    [ -n "$RMTR" ] && \rm -f $RMTR
    exit 4
  }
}
count_s=`grep -v '^#' traces | wc -l`
count_c=`grep -v '^#' user.trc | wc -l`

[ "$count_s" -eq "$count_c" ] && {
# Apparently, old-style files
  ln -s traces traces.tmp
  RMTR="$RMTR traces.tmp"
  true
} || { 
  [ "$count_s" -gt "$count_c" ] && {
# Probably, the new-style files. Remove the first data line and all the lines with repeating time from traces
    (grep '^#' traces; grep -v '^#' traces | tail -n +2 | awk 'BEGIN{t=-1}; {if(t!=$1) print; t=$1}') > traces.tmp
    RMTR="$RMTR traces.tmp"
    count_s=`grep -v '^#' traces.tmp | wc -l`
  }
}
[ "$count_s" -eq "$count_c" ] || {
    print -u2 "$NAME: different number of lines in traces and user.trc ($count_s:$count_c)- cannot proceed"
    [ -n "$RMTR" ] && rm -f $RMTR
    exit 16
}



# Select the data

sltbcl -o trcpp.dat -i user.trc time -f "$SEL_FILE"
rc=$?
\rm -f ,stc.*
[ "$rc" -ne 0 ] && exit 16

[ -n "$RES" ] && (grep \# trcpp.dat; grep -v \# trcpp.dat | tail -$RES) > trcpp.$$.tmp && mv trcpp.$$.tmp trcpp.dat

# Produce the plots

plot_set -f $PLOT_IT_STEM.ps -t "$LL " $PLOT_IT_STEM.cms > $PLOT_IT_STEM.log 2>&1
[ -z "$view" ] && ghostview $GV_OPT $PLOT_IT_STEM.ps &
[ -s $PLOT_IT_STEM.ps ] && {

  LAYOUT=layout.trcpp

  echo "$NAME: layout file - $LAYOUT"
  
  ps4_map=`layout.ps4 $PLOT_IT_STEM.ps.legend $LAYOUT`
  ps4 $PLOT_IT_STEM.ps -n $ps4_map && [ -s ${PLOT_IT_STEM}4.ps ] && {
#    print_file -Pc ${PLOT_IT_STEM}4.ps
  }
}

# Make a shortened data file

unset SLD_EXT
[ -s "$SEL_SLDM" ] && {
  sltbcl -o seldom.tmp -i seldom.trc time -f "$SEL_SLDM"
  rc=$?
  \rm -f ,stc.*
  [ "$rc" -ne 0 ] && exit 16
  [ -n "${RES[1]}" ] && (grep \# seldom.tmp; grep -v \# seldom.tmp | tail -${RES[1]}) > trcpp.$$.tmp && mv trcpp.$$.tmp seldom.tmp
  [ -s "$SEL_SLDM" ] && {
    exec 3<seldom.tmp 4<trcpp.dat 5>trcpp.sld.dat
    print -u5 -- `grep \# trcpp.dat | tail -1`
    while read -u3 s; do {
      [ -n "$s" ] && [ "${s#\#}" = "$s" ] && {
        set -- $s
        ss=$1
        [ -n "$ss" ] && {
          while { read -u4 u && [ ! "${u#\#}" = "$u" ]; }; do :; done
          set -- $u
          [ "$1" = "$ss" ] && {
            print -u5 -- $u
            true
          } || {
            set -- `print -- $ss $u | awk '{ print $1-$2 }'`
            [ "${1#-}" = "$1" ] && {
              while read -u4 u; do {
                set -- `print -- $ss $u | awk '{ print $2-$1 }'`
                [ "${1#-}" = "$1" ] && {
                  print -u5 -- $u
                  true
                  break
                }
              }; done
            } || {
              SLD_EXT="$SLD_EXT $ss"
            }
          }
        }
      }
    }; done
    [ -n "$SLD_EXT" ] && {
      print -u2 -- "seldom outside full:\n$SLD_EXT\n  ==> no trcpp_sel"
    } || {
      sltbcl -o trcpp.sel.dat -f $SEL_SLDM || exit 16
      [ -n "${RES[1]}" ] && (grep \# trcpp.sel.dat; grep -v \# trcpp.sel.dat | tail -${RES[1]}) > trcpp.$$.tmp && mv trcpp.$$.tmp trcpp.sel.dat
      tail -n +2 trcpp.sel.dat | paste trcpp.sld.dat - > trcpp_sel.dat
      mv trcpp.dat trcpp.dat~ && cp trcpp_sel.dat trcpp.dat && {
        plot_set -f ${PLOT_IT_STEM}.sel.ps -t "$LL " $PLOT_IT_STEM.cms > $PLOT_IT_STEM.sel.log 2>&1
        [ -z "$view" ] && ghostview $GV_OPT $PLOT_IT_STEM.sel.ps &
        [ -s $PLOT_IT_STEM.sel.ps ] && {

          LAYOUT=layout.trcpp

          echo "$NAME: layout file - $LAYOUT"

          ps4_map=`layout.ps4 $PLOT_IT_STEM.sel.ps.legend $LAYOUT`
          ps4 $PLOT_IT_STEM.sel.ps -n $ps4_map && [ -s ${PLOT_IT_STEM}.sel4.ps ] && {
#            print_file -Pc ${PLOT_IT_STEM}.sel4.ps
          }
        }
        mv trcpp.dat~ trcpp.dat
      }
      \rm -f trcpp.sel.dat
    }
    \rm -f trcpp.sld.dat
  }
  \rm -f seldom.tmp $RMTR
}
true
