# Data for triangular mesh for Eirene
# version : 17.02.2015

[ "$SOLPS_CENTRAL" = 'yes' ] && DEVICE=$DEVICE/$USER
# the directory where the grid is located
[ -z "$TRIADIR" ] && TRIADIR=$SOLPSTOP/modules/Triang/triangles/$DEVICE

# the directory where the templates are located
[ -z "$CNVTRIOUT" ] && CNVTRIOUT=$SOLPSTOP/modules/DivGeo/device/$DEVICE

# the file stem
[ -z "$TRIASTEM" ] && TRIASTEM=$DEVICE.tria

# grid file extensions and fortran units to link them
TRIATRI='nodes elemente neighbor'
TRIAEXT='nodes cells    links'
TRIAFTN='33    34       35'

# files containing the Eirene results related to the triangular mesh
TRIARES='fort.13'
