#! /usr/bin/env ksh

#  VERSION : 18.10.2016 21:48

. functions.ksh

# specify the viewer for PostScript files

GV="gv $GV_OPT"
case "$(uname -s)" in
    Darwin*)
        GV="gs $GV_OPT"
        ;;
esac

SOLPSTOP=`determine_SOLPSTOP`

[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
}

TRIADIR_back=$TRIADIR
TRIASTEM_back=$TRIASTEM

. triang.conf

set -A f -- $TRIATRI
gkseps=gli.eps
eirinp=triang.eir
triahed=triang.hed
[ "$COMPILER" = 'HP' ] && {
  tripuin=ftn48
  tripbin=ftn30
  tripout=ftn78
} || {
  tripuin=fort.48
  tripbin=fort.30
  tripout=fort.78
}
b2agout=b2fgmtry
b2aiout=b2fstati
b2ahout=b2fpardf
b2arout=b2frates
b2usout=triangle.neighbors
b2usinp=b2us.dat
triplog=triainp.log
triain=tria.in
trialog=tria.log
trianodes=tria.${f[0]}
triacells=tria.${f[1]}
trialinks=tria.${f[2]}
triaeps=tria.eps
triglog=triageom.log
trignodes=triageom.${f[0]}
trigcells=triageom.${f[1]}
triglinks=triageom.${f[2]}
trigeps=triageom.eps
b2usnodes=triangle.coordinates
b2uscells=triangle.elements
b2uslinks=triangle.neighbors
STRDAT=structures.dat
FRNDAT=frontier.dat
TRNDAT=triangles.dat
CURDAT=curtrngl.dat
PLTINF=triplt.dat
TRIPLT=tria

LEN=3   # minimum width of the serial number field in the filenames
POS=1   # serial number field position in the filenames (counted from the right, starting with 0)
unset f

triaoutlist="$trianodes $triacells $trialinks"
trigoutlist="$trignodes $trigcells $triglinks"
[ "$COMPILER" = 'HP' ] && {
triglnklist="ftn33 ftn34 ftn35"
} || {
triglnklist="fort.33 fort.34 fort.35"
}
b2usoutlist="$b2usnodes $b2uscells $b2uslinks"
b2uslnklist=$triglnklist

NAME=`basename $0`
stty erase ^H

Help="
Uinp    (u) run uinp to produce the input files for the initial short run of Eirene;
        (U) run uinp -l to make first the necessary links to the DG output (run first the 
            lns command from the DG environment to link the DG output to the standard place);
B2a*    (b) run b2ag, b2ai, b2ah and b2ar to produce the B2.5 input files;
triaiNp (n) run triainp to produce the geometry data / contours for tria;
Tria    (t) run tria to generate the triangular mesh outside the regular B2.5 grid;
b2us    (g) run b2us to complete plasma Grid triangulation;
Plot    (p) produce PostScript plots of the structures and triangular mesh using gnuplot;
View    (v) view the PostScript output from tria (v) or triageom (V);
Store   (s) store the combined mesh, giving it a serial number and linking to fort.3[345];
Convert (c) convert the triangular (c) or combined (C) mesh into a DG template;
List    (l) list the meshes present in the archive;
Remove  (r) remove the specified meshes from the archive;
reMap   (m) run b2yt to remap the B2.5 data on a new grid and to produce a new $b2agout file (TBD!);
trAp    (a) set a trap in tria for debugging purposes;
Inquire (i) inquire about a reference point in the triangulation;
Quit    (q) quit.

Options C, l, r can contain an argument separated by \"-\". This argument for C is the serial
number of the mesh to be converted, and for the l and r options, it is a space-separated list 
of numbers to be processed."

Usage="
$NAME: an interactive script to produce a combined triangular mesh for EIRENE.

It should be run in the working directory where the case,
for which the mesh is being produced, will be run. 
The directory should be set up so that the b2ag, b2yt and eirobjx codes can be run there.
The following steps are foreseen in $NAME:
$Help"

[ "$1" = -h ] && { print -- "$Usage"; exit; }

# wd: not required if determined by PATH
#location="$SOLPSTOP/scripts"
#[ -s B2E.version ] && {
#  set -A u -- `cat B2E.version`
#  location="${SOLPSTOP%/*}/$u/scripts"
#}

toolchain=${HOST_NAME}.${COMPILER}
[ "${SOLPS_MPI}" = '' ] && {
  eirchain=${HOST_NAME}.${COMPILER}
} || {
  eirchain=${HOST_NAME}.${COMPILER}.mpi
}  
[ "${USE_IMPGYRO}" = '' ] || {
  eirchain=$eirchain.ig
}
[ "${SOLPS_DEBUG}" = '' ] || {
  eirchain=$eirchain.debug
  toolchain=$toolchain.debug
}

TRIA="${SOLPSTOP}/modules/Triang/builds/$toolchain/tria"
TRIAGEOM="${SOLPSTOP}/modules/Triang/builds/$toolchain/triageom"
TRIAINP="${SOLPSTOP}/modules/Triang/builds/$toolchain/triainp"
TRIAINQ="${SOLPSTOP}/modules/Triang/builds/$toolchain/triainq"

q=U
griddir=${CARRE_GRIDDIR-$SOLPSTOP/modules/Carre2/meshes/${DEVICE-iter}}
[ -s dg.dgo ] && {
  modelname=`lln dg.dgo`
  [ -s $modelname ] && {
    dgname=`basename $modelname`
    carre_stem=`echo $dgname | sed -e 's|\.dgo||' `
  } || {
    print -u2 -- "No valid DG model found. Limited capabilities available only"
  }
} || {
  print -u2 -- "No valid dg.dgo file found. Did you run lns first?"
}
[ -d $griddir ] && {
  n=`ls -1 $griddir | grep -E "$carre_stem.v[0-9][0-9][0-9].geo" | wc -l`
  set -- $griddir/$carre_stem.v[0-9][0-9][0-9].geo
  [ n -gt 0 ] && {
    n=`ls $griddir/$carre_stem.v[0-9][0-9][0-9].geo | tail -1`
    n=${n#*/$carre_stem.v}
    n=${n%.geo}
  } || {
    n=000
  }
  carrename=$carre_stem.v$n.geo
  [ -s $griddir/$carre_stem.v$n/carre.out ] && {
    ln -sf $griddir/$carre_stem.v$n/carre.out uinput.crr
  } || {
    [ -s carre.out ] && {
      ln -sf carre.out uinput.crr
    } || {
      print -u2 -- "No valid carre.out file found. Did you run Carre first?"
      q=q
    }
  }
} || {
  print -u2 -n -- "The directory $griddir does not exist. Create it? (y/n)"
  while true; do {
    read u
    { case $u in
       ( y|Y ) mkdir -p "$griddir" || {
               print -u2 -- "Unable to create the directory. Check the permissions in ${griddir}%/*"
               break 2
               }; break;;
       ( n|N ) break 2;;
       (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
    esac; }
  }; done
  n=000
  carrename=$carre_stem.v$n.geo
  [ -s $griddir/$carre_stem.v$n/carre.out ] && {
    ln -sf $griddir/$carre_stem.v$n/carre.out uinput.crr
  } || {
    [ -s carre.out ] && {
      ln -sf carre.out uinput.crr
    } || {
      print -u2 -- "No valid carre.out file found. Did you run Carre first?"
      q=q
    }
  }
}

templatedir=$SOLPSTOP/modules/DivGeo/device/${DEVICE-iter}/templates

e=
[ -x "$TRIA" ] || {
  print -u2 -- "$NAME: $TRIA not found. Check run environment settings"
  e=y
}
[ -x "$TRIAGEOM" ] || {
  print -u2 -- "$NAME: $TRIAGEOM not found. Check run environment settings"
  e=y
}
[ -x "$TRIAINQ" ] || {
  print -u2 -- "$NAME: $TRIAINQ not found. Check run environment settings"
  e=y
}
[ -x "$TRIAINP" ] || {
  print -u2 -- "$NAME: $TRIAINP not found. Check run environment settings"
  e=y
}
[ -n "$e" ] && exit 4

[ -L uinput.dg ] && [ -L uinput.trg ] && [ -L uinput.crr ] && q=u

export GRSOFT_DEVICE='62'
export PLOT_IT_STEM='tria'

# N is the serial number of the current mesh. It is assigned when the mesh is stored.
N=

while true; do {
  print -u2 -n -- "Help, Uinp, B2ag, triaiNp, Tria, b2us (G), Plot, View, Store, Convert, List, Remove, reMap, Inquire, Quit ? ($q)"
  while true; do {
    read u
    extra="${u#*-}"
    [ "$u" = "$extra" ] && extra= || u="${u%%-*}"
    { case "${u:-$q}" in
      ( h|H )                                               # help:
            echo "$Help"; break;;
      (  u  )                                               # run uinp to produce the input for Eirene:
            [ -r $eirinp ] && rm $eirinp
            uinp
            [ -r b2.neutrals.parameters_hybrid.stencil ] && {
              mv b2.neutrals.parameters_hybrid.stencil b2.neutrals.parameters_hybrid.stencil.tmp
              sed -e 's:NEUTRALS_HYBRID:NEUTRALS:g' < b2.neutrals.parameters_hybrid.stencil.tmp > b2.neutrals.parameters_hybrid.stencil
              rm b2.neutrals.parameters_hybrid.stencil.tmp
            }
            N=
            [ -r $b2agout ] && [ b2ag.dat -nt structure.dat ] && {
              [ -r $eirinp ] && q=n || q=q
            } || {
              [ -r b2ag.dat ] && {
                ln -sf $griddir/$carre_stem.v$n.geo .
                /bin/echo -e "The last grid found is : $carrename"
                echo -e "'b2agfs_geometry'\t'$carrename'" >> b2ag.dat
              }
              [ $eirinp -nt dg.dgo ] && q=b || q=q
            }
            break;;  
      (  U  )                                               # run uinp to produce the input for Eirene:
            [ -r $eirinp ] && rm $eirinp
            uinp -l
            [ -r b2.neutrals.parameters_hybrid.stencil ] && {
              mv b2.neutrals.parameters_hybrid.stencil b2.neutrals.parameters_hybrid.stencil.tmp
              sed -e 's:NEUTRALS_HYBRID:NEUTRALS:g' < b2.neutrals.parameters_hybrid.stencil.tmp > b2.neutrals.parameters_hybrid.stencil
              rm b2.neutrals.parameters_hybrid.stencil.tmp
            }
            [ -L uinput.dg ] && {
              TRIADIR=$TRIADIR_back
              TRIASTEM=$TRIASTEM_back
              . triang.conf
            }
            N=
            [ -r $b2agout ] && [ b2ag.dat -nt structure.dat ] && {
              [ -r $eirinp ] && q=n || q=q
            } || {
              [ -r b2ag.dat ] && {
                ln -sf $griddir/$carre_stem.v$n.geo .
                /bin/echo -e "The last grid found is : $carrename"
                echo -e "'b2agfs_geometry'\t'$carrename'" >> b2ag.dat
              }
              [ $eirinp -nt dg.dgo ] && q=b || q=q
            }
            break;;  
      ( b|B )                                               # run b2ag/i/h to produce fort.30 file and b2 input files
            print -u2 -- "Command line: ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ag.prt > b2ag.log"
            [ -r b2ag.prt ] && rm b2ag.prt
            [ -r $b2agout ] && rm $b2agout
            ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ag.prt > b2ag.log
            [ -s $b2agout ] && {
              [ -d b2ag.exe.dir ] && rmdir b2ag.exe.dir
              print -u2 -- "Produced $b2agout file"
            } || {
              print -u2 -- "Could not produce the $b2agout file"
              print -u2 -- "    ==> Check b2ag.log file or provide separately"
              q=u
              break
            }
            print -u2 -- "Command line: ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ai.prt > b2ai.log"
            [ -r b2ai.prt ] && rm b2ai.prt
            [ -r $b2aiout ] && rm $b2aiout
            ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ai.prt > b2ai.log
            [ -s $b2aiout ] && {
              [ -d b2ai.exe.dir ] && rmdir b2ai.exe.dir
              print -u2 -- "Produced $b2aiout file"
            } || {
              print -u2 -- "Could not produce the $b2aiout file"
              print -u2 -- "    ==> Check b2ai.log file or provide separately"
              q=u
              break
            }
            print -u2 -- "Command line: ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ah.prt > b2ah.log"
            [ ! -r b2ah.dat ] && {
              [ -r b2ah.dat.stencil ] && {
               ln -sf b2ah.dat.stencil b2ah.dat
              } || {
                print -u2 -- "Could not find b2ah.dat(.stencil) file"
                print -u2 -- "    ==> Check b2ah.log file or provide separately"
                q=u
                break
              }
            }
            [ -r b2ah.prt ] && rm b2ah.prt
            [ -r $b2ahout ] && rm $b2ahout
            ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ah.prt > b2ah.log
            [ -s $b2ahout ] && {
              [ -d b2ah.exe.dir ] && rmdir b2ah.exe.dir
              print -u2 -- "Produced $b2ahout file"
            } || {
              print -u2 -- "Could not produce the $b2ahout file"
              print -u2 -- "    ==> Check b2ah.log file or provide separately"
              q=u
              break
            }
            print -u2 -- "Command line: ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ar.prt > b2ar.log"
            [ -r b2ar.prt ] && rm b2ar.prt
            [ -r $b2arout ] && rm $b2arout
            ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ar.prt > b2ar.log
            [ -s $b2arout ] && {
              [ -d b2ar.exe.dir ] && rmdir b2ar.exe.dir
              print -u2 -- "Produced $b2arout file"
              q=n
            } || {
              print -u2 -- "Could not produce the $b2arout file"
              print -u2 -- "    ==> Check b2ar.log file or provide separately"
              q=u
            }
            break;;
      ( n|N )                                               # run TRIAINP to make input file for TRIA:
            [ -r $tripbin ] && {
              [ -r $tripuin ] && {
                N=
                print -u2 -- "Starting triainp"
                print -u2 -- "Command line: $TRIAINP > $triplog"
                [ -r $tripout ] && rm $tripout
                "$TRIAINP" > "$triplog"
                [ -s "$tripout" ] && [ -r "$tripout" ] && {
                  [ -s "$triahed" ] && [ -r "$triahed" ] && {
                    (cat "$triahed"; tail --lines=+2 "$tripout") > "$triain"
                  } || {
                    cp "$tripout" "$triain"
                    print -u2 -- "No $triahed file found, using default provided by TRIAINP instead"
                  }
                  q=t
                  true
                } || {
                  print -u2 -- "No valid $tripout file created ==> Check $triplog"
                  q=u
                }
              } || {
                print -u2 -- "No $tripuin - run uinp first"
                q=u
                [ -L uinput.dg ] && [ -L uinput.trg ] && q=u
              }
              true
            } || {
              print -u2 -- "No $tripbin - run b2ag first"
              q=b
              [ -s b2mn.dat ] && [ -r b2mn.dat ] && q=m
            }
            break;;
      ( t|T )                                               # run TRIA to make triangular mesh for the void regions:
            [ -r "$triain" ] && [ -s "$triain" ] && {
              N=
              print -u2 -- "Starting a TRIA run."
              print -u2 -- "Command line: $TRIA > $trialog"
              print -u2 -- "If it continues more than a couple of minutes, kill with Ctrl-C"
              print -u2 -- "and check the output - probably, the polygon sides are wrong"
              print -u2 -- "In that case, consider re-running DG and asking for larger triangles"
              "$TRIA" > $trialog
              [ -s "$gkseps" ] && [ -r "$gkseps" ] && mv "$gkseps" "$triaeps"
              check_files $triaoutlist && q=g || {
                print -u2 -- "Not all output files, $triaoutlist, are produced"
                print -u2 -- "    ==> Check $trialog"
                print -u2 -- "For extended cases without void regions, proceed with (f)"
                q=p
              }
              q=g
              true
            } || {
              print -u2 -- "No valid $triain file found. Probably, some of the previous steps forgotten?"
              q=u
            } 
            break;;
      ( g|G )                                               # run b2us to triangulate unstructured plasma Grid and build combined mesh
            print -u2 -- "Command line: ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2us.prt > b2us.log"
            [ -r $b2usinp ] && {
              [ -r b2mn.dat ] && {
                mv b2mn.dat b2mn.dat.triang_backup 
              }
              ln -s $b2usinp b2mn.dat
            } || {
              print -u2 -- "Could not find the $b2usinp file"
              print -u2 -- "    ==> Rerun uinp or provide separately"
              q=u
              break
            }
            [ ! -r b2.boundary.parameters ] && {
              [ -r b2.boundary.parameters.stencil ] && {
               ln -sf b2.boundary.parameters.stencil b2.boundary.parameters
              } || {
                print -u2 -- "Could not find b2.boundary.parameters(.stencil) file"
                print -u2 -- "    ==> Rerun uinp or provide separately"
                [ -r b2mn.dat.triang_backup ] && {
                  rm b2mn.dat
                  mv b2mn.dat.triang_backup b2mn.dat
                }
                q=u
                break
              }
            }
            [ ! -r b2.neutrals.parameters ] && {
              [ -r b2.neutrals.parameters.stencil ] && {
               ln -sf b2.neutrals.parameters.stencil b2.neutrals.parameters
              } || {
                print -u2 -- "Could not find b2.neutrals.parameters(.stencil) file"
                print -u2 -- "    ==> Rerun uinp or provide separately"
                [ -r b2mn.dat.triang_backup ] && {
                  rm b2mn.dat
                  mv b2mn.dat.triang_backup b2mn.dat
                }
                q=u
                break
              }
            }
            [ -r b2fgmtry ] || {
              print -u2 -- "Could not find b2fgmtry file"
              print -u2 -- "    ==> Rerun B2a* or provide separately"
              [ -r b2mn.dat.triang_backup ] && {
                rm b2mn.dat
                mv b2mn.dat.triang_backup b2mn.dat
              }
              q=b
              break
            }
            [ -r b2fstati ]  || {
              print -u2 -- "Could not find b2fstati file"
              print -u2 -- "    ==> Rerun B2a* or provide separately"
              [ -r b2mn.dat.triang_backup ] && {
                rm b2mn.dat
                mv b2mn.dat.triang_backup b2mn.dat
              }
              q=b
              break
            }
            check_files $triaoutlist && {
              ln -sf $trianodes fort.33
              ln -sf $triacells fort.34
              ln -sf $trialinks fort.35
            } || {
              print -u2 -- "Did not find void triangulation files"
              print -u2 -- "    ==> only creating triangulation plasma region"
            }
            [ -r input.eir ] && {
              ln -sf input.eir input.dat
            } || {
              print -u2 -- "Could not find input.eir file"
              print -u2 -- "    ==> Rerun Uinp or provide separately"
              q=u
              break
            }
            [ -r b2us.prt ] && rm b2us.prt
            [ -r $b2usout ] && rm $b2usout
            ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2us.prt > b2us.log
            [ -r $b2usout ] && {
              [ -d b2us.exe.dir ] && rmdir b2us.exe.dir
              [ -r b2mn.dat.triang_backup ] && {
                rm b2mn.dat
                mv b2mn.dat.triang_backup b2mn.dat
              }
              check_files $b2usoutlist && {
                  q=s
                  set -A L -- $b2uslnklist
                  ln -sf $b2usnodes ${L[0]}
                  ln -sf $b2uscells ${L[1]}
                  ln -sf $b2uslinks ${L[2]}
                  [ -r input.dat.us    ] && {
                    rm input.dat
                    mv input.dat.us input.dat
                  }
                } || {
                  print -u2 -- "Not all output files, $b2usoutlist, are produced"
                  print -u2 -- "    ==> Check b2us.log"
                  q=u
                  break
                }
              print -u2 -- "Produced $b2usout file"
              q=s
            } || {
              print -u2 -- "Could not produce the $b2usout file"
              print -u2 -- "    ==> Check b2us.log file or provide separately"
              [ -r b2mn.dat.triang_backup ] && {
                rm b2mn.dat
                mv b2mn.dat.triang_backup b2mn.dat
              }
              q=u
            }
            break;;
      ( s|S )                                             # assign a serial number and store the mesh:
            check_files $trigoutlist || check_files $b2usoutlist && q=c || {
              print -u2 -- "Not all output files, $b2usoutlist, are produced"
              print -u2 -- "Probably, some of the previous steps forgotten?"
              q=g
              break
            }
            [ -d "$TRIADIR" ] || {
              print -u2 -n -- "The directory $TRIADIR does not exist. Create it? (y/n) "
              while true; do {
                read u
                { case $u in
                  ( y|Y ) mkdir -p "$TRIADIR" || {
                          print -u2 -- "Unable to create the directory. Check the permissions in ${TRIADIR}%/*"
                          break 2
                          }; break;;
                  ( n|N ) q=q; break 2;;
                  (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                esac; }
              }; done
            }
            N=
            for x in $B2USEXT; do {
              n=`get_serial_number -d "$TRIADIR" -p "$TRIASTEM.*.$x" -s $POS -l $LEN` || {
                print -u2 -- "$NAME: error $? reported from get_serial_number:"
                print -u2 -- "get_serial_number -d \"$TRIADIR\" -p \"$TRIASTEM.*.$x\" -s $POS -l $LEN n"
                q=q
                break 2
              }
              [ -z "$N" ] && N=$n || { [ "$N" -lt "$n" ] && N=$n; }
            }; done
            for x in $B2USEXT; do {
              while [ -e "$TRIADIR/$TRIASTEM.$N.$x" ]; do {
                ((n+=1))
                while [ $LEN -gt ${#n} ]; do n="0$n"; done
                print -u2 -- "Had to change the found number to $n"
                [ -z "$N" ] && N=$n || { [ "$N" -lt "$n" ] && N=$n; }
              }; done 
            }; done
            print -u2 -- "The serial number selected for the mesh is $N"
            set -A X -- $TRIAFTN
            set -A f -- $b2usoutlist
            i=0
            for x in $B2USEXT; do {
              mv ${f[i]} "$TRIADIR/$TRIASTEM.$N.${x}" && ln -sf "$TRIADIR/$TRIASTEM.$N.${x}" fort.${X[i]} || {
                print -u2 -- "$NAME: error while moving files."
                print -u2 -- "$f $TRIADIR/$TRIASTEM.$N.${x[i]} fort.${X[i]}"
                q=q
                break 2
              }
              ((i+=1))
            }; done
            unset f X
            q=c
            break;;
      (  c  )                                               # convert the TRIA result to template:
            check_files $triaoutlist && {
              [ -z "$N" ] && stem="template.a" || stem="template.a$N"
              set -A f -- $triaoutlist
              i=0
              for x in $TRIATRI; do {
                ln -sf ${f[i]} $stem.$x || {
                  print -u2 -- "Unable to link ${f[i]} to $stem.$x ==> check the file permissions"
                  q=q
                  break 2
                }
                ((i+=1))
              }; done
              [ -d "$CNVTRIOUT" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            mkdir -p $CNVTRIOUT/templates 
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              [ -d "$CNVTRIOUT/templates" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT/templates does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT/templates" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              print -u2 -- "Command line: cnvtria $stem"
              cnvtria $stem || {
                print -u2 -- "Error $? reported from cnvtria"
                q=g
                break
              }
              ln -sf $templatedir/$stem.tria $stem.tria.ogr
              print -- "... converted into a template $stem.tria"
              for x in $TRIATRI; do {
                rm -f $stem.$x
              }; done
              q=C
              true
            } || {
              print -u2 -- "Not all the files in $triaoutlist are present ==> run TRIA first?"
              q=t
            }
            unset f 
            break;;
      (  C  )                                               # convert the TRIAGEOM / B2US result to template:
            [ X"$extra" = X ] && NN="$N" || set -A NN -- $extra
            [ -z "$NN" ] && {
              check_files $b2usoutlist && {
                stem="template.g"
                set -A f -- $b2usoutlist
                true
              } || {
                print -u2 -- "Not all the files in $b2usoutlist are present ==> run B2US first?"
                q=g
              }
              true
              } || {
                while [ $LEN -gt ${#NN} ]; do NN="0$NN"; done
                stem="template.g$NN"
                list=
                for x in $B2USEXT; do list="$list $TRIADIR/$TRIASTEM.$NN.$x"; done
                check_files $list && set -A f -- $list || {
                  print -u2 -- "Not all the files $TRIASTEM.$NN.{$B2USEXT} are present in $TRIADIR"
                  q=l
                  break
                }
              }
              i=0
              for x in $B2USEXT; do {
                ln -sf ${f[i]} $stem.$x || {
                  print -u2 -- "Unable to link ${f[i]} to $stem.$x ==> check the file permissions"
                  q=q
                  break 2
                }
                ((i+=1))
              }; done
              [ -d "$CNVTRIOUT" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            mkdir -p $CNVTRIOUT/templates 
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              [ -d "$CNVTRIOUT/templates" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT/templates does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT/templates" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              cnvtria $stem || {
                print -u2 -- "Error $? reported from cnvtria"
                break
              }
              ln -sf $templatedir/$stem.tria $stem.tria.ogr
              print -- "... converted into a template $stem.tria"
              for x in $TRIATRI; do {
                rm -f $stem.$x
              }; done
              q=q
              true
            unset f 
            break;;
      ( p|P )                                               # plot the TRIA output:
            e=
            [ -s "$STRDAT" ] && [ -s "$TRIPLT.ps" ] && [ "$STRDAT" -nt "$TRIPLT.ps" ] && e=y
            [ -s "$PLTINF" ] && [ -s "$TRIPLT.ps" ] && [ "$PLTINF" -nt "$TRIPLT.ps" ] && e=y
            [ -s "$STRDAT" ] && [ ! -s "$TRIPLT.ps" ] && e=y
            [ -n "$e" ] && {
              s="size=0.5"
              [ -s "$PLTINF" ] && {
                s=`cat "$PLTINF"`
                print -u2 -- "        the $PLTINF file is used for the axis limits"
              }
              ( print -- "!! $TRIPLT.ps title=\" \" xlabel=\" \"\n"
                print -- "// \"struct\" title=\"Structures as input\" $s"
                print -- "$STRDAT   x   y    \" \"    lines"
                print -- "$STRDAT   xo  yo   \" \"    lines"
                print -- "$STRDAT   xs  ys   \" \"    points\n"
                print -- "// \"full\" title=\"Full plot\" $s"
                print -- "$STRDAT   x   y    \" \"    lines"
                [ -s "$TRNDAT" ] && [ ! $STRDAT -nt $TRNDAT ] && print -- "$TRNDAT   x   y    \" \"    lines"
                [ -s "$FRNDAT" ] && [ ! $STRDAT -nt $FRNDAT ] && print -- "$FRNDAT   x   y    \" \"    lines"
                [ -s "$CURDAT" ] && [ ! $STRDAT -nt $CURDAT ] && {
                  print -- "$CURDAT   x   y    \" \"    lines"
                  print -- "$CURDAT   xc  yc   \" \"    points"
                }
              ) > $TRIPLT.cms
              plot_set $TRIPLT.cms
              [ -s "$TRIPLT.ps" ] && {
                $GV $TRIPLT.ps &
                q=t
              } || {
                print -u2 -- "No $TRIPLT.ps file to plot"
                q=q
              }
              true
            } || {
              print -u2 -- "The plots were created after the last call to tria - no reason to do it again."
              print -u2 -- "Check the files $STRDAT and $TRIPLT.ps"
              q=t
            }; unset e; break;;
      (  v  )                                               # view graphical output of TRIA:
            [ -r "$triaeps" ] && {
              $GV $triaeps &
              q=q
              true
            } || {
              print -u2 -- "No $triaeps file found - run TRIA first"
              q=t
            }; break;;
      (  V  )                                               # view graphical output of TRIA:
            [ -r "$trigeps" ] && {
              $GV $trigeps &
              true
              q=q
            } || {
              print -u2 -- "No $trigeps file found - run TRIAGEOM first or use \"v\" to see the TRIA output"
              q=v
            }; break;;
      ( l|L )                                               # list:
            e=
            for n in $extra; do {
              while [ "$LEN" -gt ${#n} ]; do n="0$n"; done
              e="$e $n"
            }; done
            excom=`comma_separate ${e# }`
            tricom=`comma_separate $B2USEXT`
            L="${excom:=*}"
            listi=`ls $TRIADIR/$TRIASTEM.$L.$tricom | sed -e '1,$s,^.*/,,' -e '1,$s/\./ /g' | awk '{print $3}' | sort -u`
            listo=
            for n in $listi; do {
              check_files $TRIADIR/$TRIASTEM.$n.$tricom && l=${n}_ || l=${n}\*
              listo="$listo $l"
            }; done
            m=8
            w=
            [ -z "$COLUMNS" ] && c=8 || { ((c=($COLUMNS-$m)/($LEN+4))); [ "$c" -lt 1 ] && c=1; w="-w $COLUMNS"; }
            for n in $listo; do echo "$n" | tr _ \ ; done | pr -T $w --columns=$c -o $m
            q=q
            break;;
      ( r|R )                                               # remove:
            [ -z "$extra" ] && {
              print -u2 -- "Input the mesh number(s) to be removed (space separated)"
              read extra
              [ X$extra = X ] && break
            }
            e=
            for n in $extra; do {
              while [ $LEN -gt ${#n} ]; do n="0$n"; done
              e="$e $n"
            }; done
            excom=`comma_separate ${e# }`
            tricom=`comma_separate $B2USEXT`
            [ -z "$CNVTRIOUT" ] && { 
              CNVTRIOUT=$SOLPSTOP/modules/DivGeo/device/$DEVICE
            }
            [ -d $CNVTRIOUT/templates ] && CNVTRIOUT=$CNVTRIOUT/templates
            tmplcom=
            [ -d $CNVTRIOUT ] && tmplcom=$CNVTRIOUT/template.[ag]$excom.tria
            ls -l $TRIADIR/$TRIASTEM.$excom.$tricom $tmplcom
            print -n -u2 -- "Are you sure you want to remove all these files? (y/n): "
            while true; do {
              read u
              { case $u in
                ( y|Y ) rm -f $TRIADIR/$TRIASTEM.$excom.$tricom $tmplcom
                        break;;
                ( n|N ) q=q; break 2;;
                (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
              esac; }
            }; done
            q=l
            break;;
      ( m|M )                                               # remap using b2yt:
            print -u2 -- "Option is not realised yet. Please produce the $b2agout file separately"; break
            ####
            break;;
      ( a|A  )                                               # Trap for tria:
            l=
            print -u2 -- "Enter the number of steps to be made in tria (integer to set or ENTER to remove) : \c"
            read l
            [ -z "$l" ] && {
              rm -f $TRIPLT.dbg && print -u2 -- "     trap is removed"
            } || { 
              echo $l > $TRIPLT.dbg && print -u2 -- "     trap is set at step $l"
            }
            q=t
            break;;
      ( i|I )                                               # inquire:
            check_files $triglnklist && q=q || {
              print -u2 -- "Not all output files, $triglnklist, are produced"
              print -u2 -- "Probably, some of the previous steps forgotten?"
              q=g
              break
            }
            while { print -u2 -- "Enter the coordinates of the reference point [mm] or the cell number to investigate (<Return> to end)"; read u; [ -n "$u" ]; }; do {
              echo "$u" | $TRIAINQ
            }; done
            q=i
            break;;
      ( q|Q )                                               # quit:
            break 2;;
      (  *  )
            echo 'Illegal response.'
            echo 'Please use letters capitalized in the list or press ENTER for default'
            q=h
            continue;;
     esac; }
  }; done
}; done
stty sane

