#! /usr/bin/ksh

#  VERSION : 25.07.2008 

. functions.ksh

# specify the viewer for PostScript files

GV="gv $GV_OPT"

[ -L uinput.dg ] && {
  e=`lln -e uinput.dg`
  e=${e%/*}
  e=${e##*/}
  [ "$e" = "$DEVICE" ] || {
    export DEVICE=${e}
    print -u2 -- "      temporarily changed DEVICE to $DEVICE according to the 'uinput.dg' link"
  }
}

TRIADIR_back=$TRIADIR
TRIASTEM_back=$TRIASTEM

. triang.conf

set -A f -- $TRIATRI
gkseps=gli.eps
eirinp=triang.eir
eirhed=triang.hed
eirout=fort.78
eirlog=eirtria.log
triain=tria.in
trialog=tria.log
trianodes=tria.${f[0]}
triacells=tria.${f[1]}
trialinks=tria.${f[2]}
triaeps=tria.eps
triglog=triageom.log
trignodes=triageom.${f[0]}
trigcells=triageom.${f[1]}
triglinks=triageom.${f[2]}
trigeps=triageom.eps
STRDAT=structures.dat
FRNDAT=frontier.dat
TRNDAT=triangles.dat
CURDAT=curtrngl.dat
PLTINF=triplt.dat
TRIPLT=tria

LEN=3   # minimum width of the serial number field in the filenames
POS=1   # serial number field position in the filenames (counted from the right, starting with 0)
unset f

triaoutlist="$trianodes $triacells $trialinks"
trigoutlist="$trignodes $trigcells $triglinks"

NAME=`basename $0`
stty erase ^H

Help="
Uinp    (u) run uinp to produce the input files for the initial short run of Eirene;
        (U) run uinp -l to make first the necessary links to the DG output (run first the 
            lns command from the DG environment to link the DG output to the standard place);
Eirene  (e) run eirobjx to produce the geometry data for tria;
Tria    (t) run tria to generate the triangular mesh outside the regular B2.5 grid;
triaGeom(g) run triageom to combine the triangular mesh with the regular B2.5 grid;
Plot    (p) produce PostScript plots of the structures and triangular mesh using gnuplot;
View    (v) view the PostScript output from tria (v) or triageom (V);
Store   (s) store the combined mesh, giving it a serial number and linking to fort.3[345];
Convert (c) convert the triangular (c) or combined (C) mesh into a DG template;
List    (l) list the meshes present in the archive;
Remove  (r) remove the specified meshes from the archive;
B2ag    (b) run b2ag to produce the fort.30 file;
reMap   (m) run b2yt to remap the B2.5 data on a new grid and to produce a new fort.30 file (TBD!);
trAp    (a) set a trap in tria for debugging purposes;
Quit    (q) quit.

Options C, l, r can contain an argument separated by \"-\". This argument for C is the serial
number of the mesh to be converted, and for the l and r options, it is a space-separated list 
of numbers to be processed."

Usage="
$NAME: an interactive script to produce a combined triangular mesh for EIRENE.

It should be run in the working directory where the case,
for which the mesh is being produced, will be run. 
The directory should be set up so that the b2ag, b2yt and eirobjx codes can be run there.
The following steps are foreseen in $NAME:
$Help"

[ "$1" = -h ] && { print -- "$Usage"; exit; }

# wd: not required if determined by PATH
#location="$SOLPSTOP/bin"
#[ -s B2E.version ] && {
#  set -A u -- `cat B2E.version`
#  location="${SOLPSTOP%/*}/$u/bin"
#}

TRIA="tria"
TRIAGEOM="triageom"

e=
[ -x "$TRIA" ] || {
  print -u2 -- "$NAME: $TRIA not found. Check B2E.version setting"
  e=y
}
[ -x "$TRIAGEOM" ] || {
  print -u2 -- "$NAME: $TRIAGEOM not found. Check B2E.version setting"
  e=y
}
[ -n "$e" ] && exit 4

q=U
[ -L uinput.dg ] && [ -L uinput.trg ] && q=u


export GRSOFT_DEVICE='62'

# N is the serial number of the current mesh. It is assigned when the mesh is stored.
N=

while true; do {
  print -u2 -n -- "Help, Uinp, B2ag, reMap, Eirene, Tria, triaGeom, Plot, View, Store, Convert, List, Remove, Quit ? ($q)"
  while true; do {
    read u
    extra="${u#*-}"
    [ "$u" = "$extra" ] && extra= || u="${u%%-*}"
    { case "${u:-$q}" in
      ( h|H )                                               # help:
            echo "$Help"; break;;
      ( u   )                                               # run uinp to produce the input for Eirene:
            uinp
            N=
            [ -r fort.30 ] && q=e || q=b
            break;;  
      ( U   )                                               # run uinp to produce the input for Eirene:
            uinp -l
            [ -L uinput.dg ] && {
              e=`lln -e uinput.dg`
              e=${e%/*}
              e=${e##*/}
              [ "$e" = "$DEVICE" ] || {
                export DEVICE=${e}
                print -u2 -- "      temporarily changed DEVICE to $DEVICE"
                TRIADIR=$TRIADIR_back
                TRIASTEM=$TRIASTEM_back
                . triang.conf
              }
            }
            N=
            [ -r fort.30 ] && q=e || q=b
            break;;  
      ( b|B )                                               # run b2ag to produce fort.30 file:
            print -u2 -- "Command line: echo f30 | gmake -f ${SOLPSTOP}/runs/Makefile b2ag.prt > b2ag.log"
            [ -r b2ag.prt ] && rm b2ag.prt
            gmake -f ${SOLPSTOP}/runs/Makefile b2ag.prt > b2ag.log
            [ -r fort.30 ] && {
              rmdir b2ag.exe.dir
              print -u2 -- "Produced fort.30 file"
              q=e
            } || {
              print -u2 -- "Could not produce the fort.30 file. Please provide separately"
              q=u
            }
            break;;
      ( e|E )                                               # run EIRENE to make input file for TRIA:
            [ -r AMJUEL ] || {
              setup_baserun_eirene_links
            } 
            [ -r fort.30 ] && {
              [ -r $eirinp ] && {
                N=
                print -u2 -- "Starting Eirene - may take a while..."
                print -u2 -- "Command line: eirobjx < triang.eir > $eirlog"
                ln -sf "$eirinp" fort.1
                eirobjx < triang.eir > "$eirlog"
                rm fort.1
                [ -s "$eirout" ] && [ -r "$eirout" ] && {
                  (cat "$eirhed"; tail --lines=+2  "$eirout") > "$triain" && q=t || {
                    print -u2 -- "Something is wrong with $eirout ==> Check $eirlog"
                    q=u
                  }
                  true
                } || {
                  print -u2 -- "No valid $eirout file created ==> Check $eirlog"
                  q=u
                }
              } || {
                print -u2 -- "No $eirinp - run uinp first"
                q=i
                [ -L uinput.dg ] && [ -L uinput.trg ] && q=u
              }
              true
            } || {
              print -u2 -- "No fort.30 - run b2ag or b2plot first"
              q=b
              [ -s b2mn.dat ] && [ -r b2mn.dat ] && q=m
            }
            break;;
      ( t|T )                                               # run TRIA to make triangular mesh:
            [ -r "$triain" ] && [ -s "$triain" ] && {
              N=
              print -u2 -- "Starting a TRIA run."
              print -u2 -- "If it continues more than a couple of minutes, kill with Ctrl-C"
              print -u2 -- "and check the output - probably, the polygon sides are wrong"
              print -u2 -- "In that case, consider re-running DG and asking for larger triangles"
              "$TRIA" > $trialog
              [ -s "$gkseps" ] && [ -r "$gkseps" ] && mv "$gkseps" "$triaeps"
              check_files $triaoutlist && q=g || {
                print -u2 -- "Not all output files, $triaoutlist, are produced"
                print -u2 -- "    ==> Check $trialog"
                q=u 
              }
              true
            } || {
              print -u2 -- "No valid $triain file found. Probably, some of the previous steps forgotten?"
              q=u
            } 
            break;;
      ( g|G )                                               # run TRIAGEOM to make combined mesh:  
            [ -r fort.30 ] && [ -s fort.30 ] && {
              check_files $triaoutlist && {
                N=
                print -u2 -- "Starting a TRIAGEOM run"
                "$TRIAGEOM" > $triglog
                [ -s "$gkseps" ] && [ -r "$gkseps" ] && mv "$gkseps" "$trigeps"
                check_files $trigoutlist && q=s || {
                  print -u2 -- "Not all output files, $trigoutlist, are produced"
                  print -u2 -- "    ==> Check $triglog"
                  q=u
                }
                true
              } || {
                print -u2 -- "Not all valid input files, $triaoutlist, are present"
                print -u2 -- "Probably, some of the previous steps forgotten?"
                q=t 
              }
              true
            } || {
              print -u2 -- "No valid fort.30 file is found. Run b2ag or b2plot first"
              q=b
            }
            break;;
      ( s|S )                                             # assign a serial number and store the mesh:
            check_files $trigoutlist && q=c || {
              print -u2 -- "Not all output files, $trigoutlist, are produced"
              print -u2 -- "Probably, some of the previous steps forgotten?"
              q=g
              break
            }
            [ -d "$TRIADIR" ] || {
              print -u2 -n -- "The directory $TRIADIR does not exist. Create it? (y/n) "
              while true; do {
                read u
                { case $u in
                  ( y|Y ) mkdir -p "$TRIADIR" || {
                          print -u2 -- "Unable to create the directory. Check the permissions in ${TRIADIR}%/*"
                          break 2
                          }; break;;
                  ( n|N ) q=q; break 2;;
                  (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                esac; }
              }; done
            }
            N=
            for x in $TRIAEXT; do {
              n=`get_serial_number -d "$TRIADIR" -p "$TRIASTEM.*.$x" -s $POS -l $LEN` || {
                print -u2 -- "$NAME: error $? reported from get_serial_number:"
                print -u2 -- "get_serial_number -d \"$TRIADIR\" -p \"$TRIASTEM.*.$x\" -s $POS -l $LEN n"
                q=q
                break 2
              }
              [ -z "$N" ] && N=$n || { [ "$N" -lt "$n" ] && N=$n; }
            }; done
            for x in $TRIAEXT; do {
              while [ -e "$TRIADIR/$TRIASTEM.$N.$x" ]; do {
                ((n+=1))
                while [ $LEN -gt ${#n} ]; do n="0$n"; done
                print -u2 -- "Had to change the found number to $n"
                [ -z "$N" ] && N=$n || { [ "$N" -lt "$n" ] && N=$n; }
              }; done 
            }; done
            print -u2 -- "The serial number selected for the mesh is $N"
            set -A X -- $TRIAFTN
            set -A f -- $trigoutlist
            i=0
            for x in $TRIAEXT; do {
              mv ${f[i]} "$TRIADIR/$TRIASTEM.$N.${x}" && ln -sf "$TRIADIR/$TRIASTEM.$N.${x}" fort.${X[i]} || {
                print -u2 -- "$NAME: error while moving files."
                print -u2 -- "$f $TRIADIR/$TRIASTEM.$N.${x[i]} fort.${X[i]}"
                q=q
                break 2
              }
              ((i+=1))
            }; done
            unset f X
            q=c 
            break;;
      (  c  )                                               # convert the TRIA result to template:
            check_files $triaoutlist && {
              [ -z "$N" ] && stem="%a%" || stem="%a$N"
              set -A f -- $triaoutlist
              i=0
              for x in $TRIATRI; do {
                ln -sf ${f[i]} $stem.$x || {
                  print -u2 -- "Unable to link ${f[i]} to $stem.$x ==> check the file permissions"
                  break 2
                }
                ((i+=1))
              }; done
              [ -d "$CNVTRIOUT" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            break 2
                            };
                            mkdir -p $CNVTRIOUT/templates 
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              [ -d "$CNVTRIOUT/templates" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT/templates does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT/templates" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            break 2
                            };
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              cnvtria $stem || {
                print -u2 -- "Error $? reported from cnvtria"
                break
              }
              print -- "... converted into a template $stem.tria"
              for x in $TRIATRI; do {
                rm -f $stem.$x
              }; done
              q=g
              true
            } || {
              print -u2 -- "Not all the files in $triaoutlist are present ==> run TRIA first?"
              q=t
            }
            unset f 
            break;;
      (  C  )                                               # convert the TRIAGEOM result to template:
            [ X"$extra" = X ] && NN="$N" || set -A NN -- $extra
            [ -z "$NN" ] && {
              check_files $trigoutlist && {
                stem="%g%"
                set -A f -- $trigoutlist
                true
              } || {
                print -u2 -- "Not all the files in $trigoutlist are present ==> run TRIAGEOM first?"
                q=g
              }
              true
              } || {
                while [ $LEN -gt ${#NN} ]; do NN="0$NN"; done
                stem="%g$NN"
                list=
                for x in $TRIAEXT; do list="$list $TRIADIR/$TRIASTEM.$NN.$x"; done
                check_files $list && set -A f -- $list || {
                  print -u2 -- "Not all the files $TRIASTEM.$NN.{$TRIAEXT} are present in $TRIADIR"
                  q=l
                  break
                }
              }
              i=0
              for x in $TRIATRI; do {
                ln -sf ${f[i]} $stem.$x || {
                  print -u2 -- "Unable to link ${f[i]} to $stem.$x ==> check the file permissions"
                  break 2
                }
                ((i+=1))
              }; done
              [ -d "$CNVTRIOUT" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            break 2
                            };
                            mkdir -p $CNVTRIOUT/templates 
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              [ -d "$CNVTRIOUT/templates" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT/templates does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT/templates" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            break 2
                            };
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              cnvtria $stem || {
                print -u2 -- "Error $? reported from cnvtria"
                break
              }
              print -- "... converted into a template $stem.tria"
              for x in $TRIATRI; do {
                rm -f $stem.$x
              }; done
              q=g
              true
            unset f 
            break;;
      ( p|P )                                               # plot the TRIA output:
            e=
            [ -s "$STRDAT" ] && [ -s "$TRIPLT.ps" ] && [ "$STRDAT" -nt "$TRIPLT.ps" ] && e=y
            [ -s "$PLTINF" ] && [ -s "$TRIPLT.ps" ] && [ "$PLTINF" -nt "$TRIPLT.ps" ] && e=y
            [ -s "$STRDAT" ] && [ ! -s "$TRIPLT.ps" ] && e=y
            [ -n "$e" ] && {
              s="size=0.5"
              [ -s "$PLTINF" ] && {
                s=`cat "$PLTINF"`
                print -u2 -- "        the $PLTINF file is used for the axis limits"
              }
              ( print -- "!! $TRIPLT.ps title=\" \" xlabel=\" \"\n"
                print -- "// \"struct\" title=\"Structures as input\" $s"
                print -- "$STRDAT   x   y    \" \"    lines"
                print -- "$STRDAT   xo  yo   \" \"    lines"
                print -- "$STRDAT   xs  ys   \" \"    points\n"
                print -- "// \"full\" title=\"Full plot\" $s"
                print -- "$STRDAT   x   y    \" \"    lines"
                [ -s "$TRNDAT" ] && [ ! $STRDAT -nt $TRNDAT ] && print -- "$TRNDAT   x   y    \" \"    lines"
                [ -s "$FRNDAT" ] && [ ! $STRDAT -nt $FRNDAT ] && print -- "$FRNDAT   x   y    \" \"    lines"
                [ -s "$CURDAT" ] && [ ! $STRDAT -nt $CURDAT ] && {
                  print -- "$CURDAT   x   y    \" \"    lines"
                  print -- "$CURDAT   xc  yc   \" \"    points"
                }
              ) > $TRIPLT.cms
              plot_set $TRIPLT.cms
              [ -s "$TRIPLT.ps" ] && {
                $GV $TRIPLT.ps& 
              } || {
                print -u2 -- "No $TRIPLT.ps file to plot"
              }
              true
            } || {
              print -u2 -- "The plots were created after the last call to tria - no reason to do it again."
              print -u2 -- "Check the files $STRDAT and $TRIPLT.ps"
            }; unset e; break;;
      (  v  )                                               # view graphical output of TRIA:
            [ -r  "$triaeps" ] && {
              $GV $triaeps &
              true
            } || {
              print -u2 -- "No $triaeps file found - run TRIA first"
              q=t
            }; break;;
      (  V  )                                               # view graphical output of TRIA:
            [ -r  "$trigeps" ] && {
              $GV $trigeps &
              true
            } || {
              print -u2 -- "No $trigeps file found - run TRIAGEOM first or use \"v\" to see the TRIA output"
              q=v
            }; break;;
      ( l|L )                                               # list:
            e=
            for n in $extra; do {
              while [ "$LEN" -gt ${#n} ]; do n="0$n"; done
              e="$e $n"
            }; done
            excom=`comma_separate ${e# }`
            tricom=`comma_separate $TRIAEXT`
            L="${excom:=*}"
            listi=`ls $TRIADIR/$TRIASTEM.$L.$tricom | sed -e '1,$s,^.*/,,' -e '1,$s/\./ /g' | awk '{print $3}' | sort -u`
            listo=
            for n in $listi; do {
              check_files $TRIADIR/$TRIASTEM.$n.$tricom && l=${n}_ || l=${n}\*
              listo="$listo $l"
            }; done
            m=8
            w=
            [ -z "$COLUMNS" ] && c=8 || { ((c=($COLUMNS-$m)/($LEN+4))); [ "$c" -lt 1 ] && c=1; w="-w $COLUMNS"; }
            for n in $listo; do echo "$n" | tr _ \ ; done | pr -T $w --columns=$c -o $m
            break;;
      ( r|R )                                               # remove:
            [ -z "$extra" ] && {
              print -u2 -- "Input the mesh number(s) to be removed (space separated)"
              read extra
              [ X$extra = X ] && break
            }
            e=
            for n in $extra; do {
              while [ $LEN -gt ${#n} ]; do n="0$n"; done
              e="$e $n"
            }; done
            excom=`comma_separate ${e# }`
            tricom=`comma_separate $TRIAEXT`
            [ -z "$CNVTRIOUT" ] && { 
              CNVTRIOUT=$SOLPSTOP/data/DivGeo/dg/class/$DEVICE
            }
            [ -d $CNVTRIOUT/templates ] && CNVTRIOUT=$CNVTRIOUT/templates
            tmplcom=
            [ -d $CNVTRIOUT ] && tmplcom=$CNVTRIOUT/%[ag]$excom.tria
            ls -l $TRIADIR/$TRIASTEM.$excom.$tricom $tmplcom
            print -n -u2 -- "Are you sure you want to remove all these files? (y/n): "
            while true; do {
              read u
              { case $u in
                ( y|Y ) rm -f $TRIADIR/$TRIASTEM.$excom.$tricom $tmplcom
                         break;;
                ( n|N ) q=q; break 2;;
                (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
              esac; }
            }; done
            break;;
      ( m|M )                                               # remap using b2yt:
            print -u2 -- "Option is not realised yet. Please produce the fort.30 file separately"; break
            ####
            break;;
      ( a|A  )                                               # Trap for tria:
            l=
            print -u2 -- "Enter the number of steps to be made in tria (integer to set or ENTER to remove) : \c"
            read l
            [ -z "$l" ] && {
              rm -f $TRIPLT.dbg && print -u2 -- "     trap is removed"
            } || { 
              echo $l > $TRIPLT.dbg && print -u2 -- "     trap is set at step $l"
            }
            q=t
            break;;
      ( q|Q )                                               # quit:
            break 2;;
      (  *  )
            echo 'Illegal response.'
            echo 'Please use letters capitalized in the list or press ENTER for default'
            continue;;
     esac; }
  }; done
}; done
