# Data for triangular mesh for Eirene
# version : 17.02.2015

# the file stem
[ -z "$TRIASTEM" ] && TRIASTEM=$DEVICE.tria

print -- "DEVICE $DEVICE $DEVICE_SAVE"
[ "$SOLPS_CENTRAL" = 'yes' ] && {
  [ -z "$DEVICE_SAVE" ] && export DEVICE_SAVE=$DEVICE
  DEVICE=$DEVICE_SAVE/$USER
}
print -- "DEVICE $DEVICE $DEVICE_SAVE"
# the directory where the grid is located
[ -z "$TRIADIR" ] && TRIADIR=$SOLPSTOP/modules/Triang/triangles/$DEVICE

# the directory where the templates are located
[ -z "$CNVTRIOUT" ] && CNVTRIOUT=$SOLPSTOP/modules/DivGeo/device/$DEVICE

# grid file extensions and fortran units to link them
TRIATRI='nodes elemente neighbor'
TRIAEXT='nodes cells    links'
B2USEXT='coordinates elements neighbors'
TRIAFTN='33    34       35'

# files containing the Eirene results related to the triangular mesh
[ "$COMPILER" = 'HP' ] && {
  TRIARES='ftn13'
} || {
  TRIARES='fort.13'
}
