#! /usr/bin/env ksh

#  VERSION : 18.10.2016 21:48

. functions.ksh

# specify the viewer for PostScript files

GV="gv $GV_OPT"
case "$(uname -s)" in
    Darwin*)
        GV="gs $GV_OPT"
        ;;
esac

SOLPSTOP=`determine_SOLPSTOP`

[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
}

TRIADIR_back=$TRIADIR
TRIASTEM_back=$TRIASTEM

. triang.conf

set -A f -- $TRIATRI
gkseps=gli.eps
eirinp=triang.eir
eirhed=triang.hed
[ "$COMPILER" = 'HP' ] && {
  b2agout=ftn30
  eirout=ftn78
  eirlink=ftn1
} || {
  b2agout=fort.30
  eirout=fort.78
  eirlink=fort.1
}
eirlog=eirtria.log
triain=tria.in
trialog=tria.log
trianodes=tria.${f[0]}
triacells=tria.${f[1]}
trialinks=tria.${f[2]}
triaeps=tria.eps
triglog=triageom.log
trignodes=triageom.${f[0]}
trigcells=triageom.${f[1]}
triglinks=triageom.${f[2]}
trigeps=triageom.eps
STRDAT=structures.dat
FRNDAT=frontier.dat
TRNDAT=triangles.dat
CURDAT=curtrngl.dat
PLTINF=triplt.dat
TRIPLT=tria

LEN=3   # minimum width of the serial number field in the filenames
POS=1   # serial number field position in the filenames (counted from the right, starting with 0)
unset f

triaoutlist="$trianodes $triacells $trialinks"
trigoutlist="$trignodes $trigcells $triglinks"
[ "$COMPILER" = 'HP' ] && {
triglnklist="ftn33 ftn34 ftn35"
} || {
triglnklist="fort.33 fort.34 fort.35"
}

NAME=`basename $0`
stty erase ^H

Help="
Uinp    (u) run uinp to produce the input files for the initial short run of Eirene;
        (U) run uinp -l to make first the necessary links to the DG output (run first the 
            lns command from the DG environment to link the DG output to the standard place);
B2ag    (b) run b2ag to produce the $b2agout file;
Eirene  (e) run eirobjx to produce the geometry data for tria;
Tria    (t) run tria to generate the triangular mesh outside the regular B2.5 grid;
triaGeom(g) run triageom to combine the triangular mesh with the regular B2.5 grid;
Plot    (p) produce PostScript plots of the structures and triangular mesh using gnuplot;
View    (v) view the PostScript output from tria (v) or triageom (V);
Store   (s) store the combined mesh, giving it a serial number and linking to fort.3[345];
Convert (c) convert the triangular (c) or combined (C) mesh into a DG template;
List    (l) list the meshes present in the archive;
Remove  (r) remove the specified meshes from the archive;
reMap   (m) run b2yt to remap the B2.5 data on a new grid and to produce a new $b2agout file (TBD!);
trAp    (a) set a trap in tria for debugging purposes;
Inquire (i) inquire about a reference point in the triangulation;
Quit    (q) quit.

Options C, l, r can contain an argument separated by \"-\". This argument for C is the serial
number of the mesh to be converted, and for the l and r options, it is a space-separated list 
of numbers to be processed."

Usage="
$NAME: an interactive script to produce a combined triangular mesh for EIRENE.

It should be run in the working directory where the case,
for which the mesh is being produced, will be run. 
The directory should be set up so that the b2ag, b2yt and eirobjx codes can be run there.
The following steps are foreseen in $NAME:
$Help"

[ "$1" = -h ] && { print -- "$Usage"; exit; }

# wd: not required if determined by PATH
#location="$SOLPSTOP/scripts"
#[ -s B2E.version ] && {
#  set -A u -- `cat B2E.version`
#  location="${SOLPSTOP%/*}/$u/scripts"
#}

toolchain=${HOST_NAME}.${COMPILER}
[ "${SOLPS_MPI}" = '' ] && {
  eirchain=${HOST_NAME}.${COMPILER}
} || {
  eirchain=${HOST_NAME}.${COMPILER}.mpi
}  
[ "${USE_IMPGYRO}" = '' ] || {
  eirchain=$eirchain.ig
}
[ "${SOLPS_DEBUG}" = '' ] || {
  eirchain=$eirchain.debug
  toolchain=$toolchain.debug
}

TRIA="${SOLPSTOP}/modules/Triang/builds/$toolchain/tria"
TRIAGEOM="${SOLPSTOP}/modules/Triang/builds/$toolchain/triageom"
TRIAINQ="${SOLPSTOP}/modules/Triang/builds/$toolchain/triainq"
EIRENE="${SOLPSTOP}/modules/Eirene/builds/standalone.$eirchain/eirobjx"

griddir=${CARRE_GRIDDIR-$SOLPSTOP/modules/Carre/meshes/${DEVICE-iter}}
[ -s dg.dgo ] && {
  modelname=`lln dg.dgo`
  [ -s $modelname ] && {
    dgname=`basename $modelname`
    carre_stem=`echo $dgname | sed -e 's|\.dgo||' `
  } || {
    print -u2 -- "No valid DG model found. Limited capabilities available only"
  }
} || {
  print -u2 -- "No valid dg.dgo file found. Did you run lns first?"
}
[ -d $griddir ] && {
  n=`ls -1 $griddir | grep -E "$carre_stem.v[0-9][0-9][0-9].geo" | wc -l`
  set -- $griddir/$carre_stem.v[0-9][0-9][0-9].geo
  [ n -gt 0 ] && {
    n=`ls $griddir/$carre_stem.v[0-9][0-9][0-9].geo | tail -1`
    n=${n#*/$carre_stem.v}
    n=${n%.geo}
  } || {
    n=000
  }
  carrename=$carre_stem.v$n.geo
} || {
  print -u2 -n -- "The directory $griddir does not exist. Create it? (y/n)"
  while true; do {
    read u
    { case $u in
       ( y|Y ) mkdir -p "$griddir" || {
               print -u2 -- "Unable to create the directory. Check the permissions in ${griddir}%/*"
               break 2
               }; break;;
       ( n|N ) break 2;;
       (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
    esac; }
  }; done
  n=000
  carrename=$carre_stem.v$n.geo
}

templatedir=$SOLPSTOP/modules/DivGeo/device/${DEVICE-iter}/templates

e=
[ -x "$TRIA" ] || {
  print -u2 -- "$NAME: $TRIA not found. Check run environment settings"
  e=y
}
[ -x "$TRIAGEOM" ] || {
  print -u2 -- "$NAME: $TRIAGEOM not found. Check run environment settings"
  e=y
}
[ -x "$TRIAINQ" ] || {
  print -u2 -- "$NAME: $TRIAINQ not found. Check run environment settings"
  e=y
}
[ -x "$EIRENE" ] || {
  print -u2 -- "$NAME: $EIRENE not found. Check run environment settings"
  e=y
}
[ -n "$e" ] && exit 4

q=U
[ -L uinput.dg ] && [ -L uinput.trg ] && q=u


export GRSOFT_DEVICE='62'
export PLOT_IT_STEM='tria'

# N is the serial number of the current mesh. It is assigned when the mesh is stored.
N=

while true; do {
  print -u2 -n -- "Help, Uinp, B2ag, Eirene, Tria, triaGeom, Plot, View, Store, Convert, List, Remove, reMap, Inquire, Quit ? ($q)"
  while true; do {
    read u
    extra="${u#*-}"
    [ "$u" = "$extra" ] && extra= || u="${u%%-*}"
    { case "${u:-$q}" in
      ( h|H )                                               # help:
            echo "$Help"; break;;
      (  u  )                                               # run uinp to produce the input for Eirene:
            [ -r $eirinp ] && rm $eirinp
            uinp
            N=
            [ -r $b2agout ] && [ b2ag.dat -nt structure.dat ] && {
              [ -r $eirinp ] && q=e || q=q
            } || {
              [ -r b2ag.dat ] && {
                ln -sf $griddir/$carre_stem.v$n.geo .
                /bin/echo -e "The last grid found is : $carrename"
                echo -e "'b2agfs_geometry'\t'$carrename'" >> b2ag.dat
              }
              [ $eirinp -nt dg.dgo ] && q=b || q=q
            }
            break;;  
      (  U  )                                               # run uinp to produce the input for Eirene:
            [ -r $eirinp ] && rm $eirinp
            uinp -l
            [ -L uinput.dg ] && {
              TRIADIR=$TRIADIR_back
              TRIASTEM=$TRIASTEM_back
              . triang.conf
            }
            N=
            [ -r $b2agout ] && [ b2ag.dat -nt structure.dat ] && {
              [ -r $eirinp ] && q=e || q=q
            } || {
              [ -r b2ag.dat ] && {
                ln -sf $griddir/$carre_stem.v$n.geo .
                /bin/echo -e "The last grid found is : $carrename"
                echo -e "'b2agfs_geometry'\t'$carrename'" >> b2ag.dat
              }
              [ $eirinp -nt dg.dgo ] && q=b || q=q
            }
            break;;  
      ( b|B )                                               # run b2ag to produce fort.30 file:
            [ -r b2fplasma ] && {
              print -u2 -- "Command line: echo f30 | b2plot > b2pl.log"
              [ -r $b2agout ] && rm $b2agout
              echo f30 | b2plot > b2pl.log
              [ -r b2pl.exe.dir/$b2agout ] && {
                mv b2pl.exe.dir/$b2agout .
                rmdir b2pl.exe.dir
                print -u2 -- "Produced $b2agout file"
                q=e
              } || {
                print -u2 -- "Could not produce the $b2agout file"
                print -u2 -- "    ==> Check b2pl.log file or provide separately"
                q=u
              }
            } || {
              print -u2 -- "Command line: ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ag.prt > b2ag.log"
              [ -r b2ag.prt ] && rm b2ag.prt
              [ -r $b2agout ] && rm $b2agout
              ${MAKE} -f ${SOLPSTOP}/runs/Makefile b2ag.prt > b2ag.log
              [ -r $b2agout ] && {
                [ -d b2ag.exe.dir ] && rmdir b2ag.exe.dir
                print -u2 -- "Produced $b2agout file"
                q=e
              } || {
                print -u2 -- "Could not produce the $b2agout file"
                print -u2 -- "    ==> Check b2ag.log file or provide separately"
                q=u
              }
            }
            break;;
      ( e|E )                                               # run EIRENE to make input file for TRIA:
            [ -r AMJUEL ] || {
              setup_baserun_eirene_links ; rm b2.log b2.log.gz ; rmdir tracing batch_av run_av
            } 
            [ -r $b2agout ] && {
              [ -r $eirinp ] && {
                N=
                print -u2 -- "Starting Eirene - may take a while..."
                print -u2 -- "Command line: $EIRENE > $eirlog"
                [ -r $eirout ] && rm $eirout
                ln -sf "$eirinp" "$eirlink"
                $EIRENE > "$eirlog"
                rm $eirlink fort.85
                [ -s "$eirout" ] && [ -r "$eirout" ] && {
                  [ -s "$eirhed" ] && [ -r "$eirhed" ] && {
                    (cat "$eirhed"; tail --lines=+2 "$eirout") > "$triain"
                  } || {
                    cp "$eirout" "$triain"
                    print -u2 -- "No $eirhed file found, using default provided by Eirene instead"
                  }
                  q=t
                  true
                } || {
                  print -u2 -- "No valid $eirout file created ==> Check $eirlog"
                  q=u
                }
              } || {
                print -u2 -- "No $eirinp - run uinp first"
                q=u
                [ -L uinput.dg ] && [ -L uinput.trg ] && q=u
              }
              true
            } || {
              print -u2 -- "No $b2agout - run b2ag or b2plot first"
              q=b
              [ -s b2mn.dat ] && [ -r b2mn.dat ] && q=m
            }
            break;;
      ( t|T )                                               # run TRIA to make triangular mesh:
            [ -r "$triain" ] && [ -s "$triain" ] && {
              N=
              print -u2 -- "Starting a TRIA run."
              print -u2 -- "Command line: $TRIA > $trialog"
              print -u2 -- "If it continues more than a couple of minutes, kill with Ctrl-C"
              print -u2 -- "and check the output - probably, the polygon sides are wrong"
              print -u2 -- "In that case, consider re-running DG and asking for larger triangles"
              "$TRIA" > $trialog
              [ -s "$gkseps" ] && [ -r "$gkseps" ] && mv "$gkseps" "$triaeps"
              check_files $triaoutlist && q=g || {
                print -u2 -- "Not all output files, $triaoutlist, are produced"
                print -u2 -- "    ==> Check $trialog"
                q=p
              }
              true
            } || {
              print -u2 -- "No valid $triain file found. Probably, some of the previous steps forgotten?"
              q=u
            } 
            break;;
      ( g|G )                                               # run TRIAGEOM to make combined mesh:  
            [ -r $b2agout ] && [ -s $b2agout ] && {
              check_files $triaoutlist && {
                N=
                print -u2 -- "Starting a TRIAGEOM run"
                print -u2 -- "Command line: $TRIAGEOM > $triglog"
                "$TRIAGEOM" > $triglog
                [ -s "$gkseps" ] && [ -r "$gkseps" ] && mv "$gkseps" "$trigeps"
                check_files $trigoutlist && {
                  q=s
                  set -A L -- $triglnklist
                  ln -sf $trignodes ${L[0]}
                  ln -sf $trigcells ${L[1]}
                  ln -sf $triglinks ${L[2]}
                } || {
                  print -u2 -- "Not all output files, $trigoutlist, are produced"
                  print -u2 -- "    ==> Check $triglog"
                  q=u
                }
                true
              } || {
                print -u2 -- "Not all valid input files, $triaoutlist, are present"
                print -u2 -- "Probably, some of the previous steps forgotten?"
                q=t 
              }
              true
            } || {
              print -u2 -- "No valid $b2agout file is found. Run b2ag or b2plot first"
              q=b
            }
            break;;
      ( s|S )                                             # assign a serial number and store the mesh:
            check_files $trigoutlist && q=c || {
              print -u2 -- "Not all output files, $trigoutlist, are produced"
              print -u2 -- "Probably, some of the previous steps forgotten?"
              q=g
              break
            }
            [ -d "$TRIADIR" ] || {
              print -u2 -n -- "The directory $TRIADIR does not exist. Create it? (y/n) "
              while true; do {
                read u
                { case $u in
                  ( y|Y ) mkdir -p "$TRIADIR" || {
                          print -u2 -- "Unable to create the directory. Check the permissions in ${TRIADIR}%/*"
                          break 2
                          }; break;;
                  ( n|N ) q=q; break 2;;
                  (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                esac; }
              }; done
            }
            N=
            for x in $TRIAEXT; do {
              n=`get_serial_number -d "$TRIADIR" -p "$TRIASTEM.*.$x" -s $POS -l $LEN` || {
                print -u2 -- "$NAME: error $? reported from get_serial_number:"
                print -u2 -- "get_serial_number -d \"$TRIADIR\" -p \"$TRIASTEM.*.$x\" -s $POS -l $LEN n"
                q=q
                break 2
              }
              [ -z "$N" ] && N=$n || { [ "$N" -lt "$n" ] && N=$n; }
            }; done
            for x in $TRIAEXT; do {
              while [ -e "$TRIADIR/$TRIASTEM.$N.$x" ]; do {
                ((n+=1))
                while [ $LEN -gt ${#n} ]; do n="0$n"; done
                print -u2 -- "Had to change the found number to $n"
                [ -z "$N" ] && N=$n || { [ "$N" -lt "$n" ] && N=$n; }
              }; done 
            }; done
            print -u2 -- "The serial number selected for the mesh is $N"
            set -A X -- $TRIAFTN
            set -A f -- $trigoutlist
            i=0
            for x in $TRIAEXT; do {
              mv ${f[i]} "$TRIADIR/$TRIASTEM.$N.${x}" && ln -sf "$TRIADIR/$TRIASTEM.$N.${x}" fort.${X[i]} || {
                print -u2 -- "$NAME: error while moving files."
                print -u2 -- "$f $TRIADIR/$TRIASTEM.$N.${x[i]} fort.${X[i]}"
                q=q
                break 2
              }
              ((i+=1))
            }; done
            unset f X
            q=c 
            break;;
      (  c  )                                               # convert the TRIA result to template:
            check_files $triaoutlist && {
              [ -z "$N" ] && stem="template.a" || stem="template.a$N"
              set -A f -- $triaoutlist
              i=0
              for x in $TRIATRI; do {
                ln -sf ${f[i]} $stem.$x || {
                  print -u2 -- "Unable to link ${f[i]} to $stem.$x ==> check the file permissions"
                  q=q
                  break 2
                }
                ((i+=1))
              }; done
              [ -d "$CNVTRIOUT" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            mkdir -p $CNVTRIOUT/templates 
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              [ -d "$CNVTRIOUT/templates" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT/templates does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT/templates" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              print -u2 -- "Command line: cnvtria $stem"
              cnvtria $stem || {
                print -u2 -- "Error $? reported from cnvtria"
                q=g
                break
              }
              ln -sf $templatedir/$stem.tria $stem.tria.ogr
              print -- "... converted into a template $stem.tria"
              for x in $TRIATRI; do {
                rm -f $stem.$x
              }; done
              q=C
              true
            } || {
              print -u2 -- "Not all the files in $triaoutlist are present ==> run TRIA first?"
              q=t
            }
            unset f 
            break;;
      (  C  )                                               # convert the TRIAGEOM result to template:
            [ X"$extra" = X ] && NN="$N" || set -A NN -- $extra
            [ -z "$NN" ] && {
              check_files $trigoutlist && {
                stem="template.g"
                set -A f -- $trigoutlist
                true
              } || {
                print -u2 -- "Not all the files in $trigoutlist are present ==> run TRIAGEOM first?"
                q=g
              }
              true
              } || {
                while [ $LEN -gt ${#NN} ]; do NN="0$NN"; done
                stem="template.g$NN"
                list=
                for x in $TRIAEXT; do list="$list $TRIADIR/$TRIASTEM.$NN.$x"; done
                check_files $list && set -A f -- $list || {
                  print -u2 -- "Not all the files $TRIASTEM.$NN.{$TRIAEXT} are present in $TRIADIR"
                  q=l
                  break
                }
              }
              i=0
              for x in $TRIATRI; do {
                ln -sf ${f[i]} $stem.$x || {
                  print -u2 -- "Unable to link ${f[i]} to $stem.$x ==> check the file permissions"
                  q=q
                  break 2
                }
                ((i+=1))
              }; done
              [ -d "$CNVTRIOUT" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            mkdir -p $CNVTRIOUT/templates 
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              [ -d "$CNVTRIOUT/templates" ] || {
                print -u2 -n -- "The directory $CNVTRIOUT/templates does not exist. Create it? (y/n) "
                while true; do {
                  read u
                  { case $u in
                    ( y|Y ) mkdir -p "$CNVTRIOUT/templates" || {
                            print -u2 -- "Unable to create the directory. Check the permissions in ${CNVDIR}%/*"
                            q=q
                            break 2
                            };
                            break;;
                    ( n|N ) q=q; break 2;;
                    (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
                  esac; }
                }; done
              }
              cnvtria $stem || {
                print -u2 -- "Error $? reported from cnvtria"
                break
              }
              ln -sf $templatedir/$stem.tria $stem.tria.ogr
              print -- "... converted into a template $stem.tria"
              for x in $TRIATRI; do {
                rm -f $stem.$x
              }; done
              q=q
              true
            unset f 
            break;;
      ( p|P )                                               # plot the TRIA output:
            e=
            [ -s "$STRDAT" ] && [ -s "$TRIPLT.ps" ] && [ "$STRDAT" -nt "$TRIPLT.ps" ] && e=y
            [ -s "$PLTINF" ] && [ -s "$TRIPLT.ps" ] && [ "$PLTINF" -nt "$TRIPLT.ps" ] && e=y
            [ -s "$STRDAT" ] && [ ! -s "$TRIPLT.ps" ] && e=y
            [ -n "$e" ] && {
              s="size=0.5"
              [ -s "$PLTINF" ] && {
                s=`cat "$PLTINF"`
                print -u2 -- "        the $PLTINF file is used for the axis limits"
              }
              ( print -- "!! $TRIPLT.ps title=\" \" xlabel=\" \"\n"
                print -- "// \"struct\" title=\"Structures as input\" $s"
                print -- "$STRDAT   x   y    \" \"    lines"
                print -- "$STRDAT   xo  yo   \" \"    lines"
                print -- "$STRDAT   xs  ys   \" \"    points\n"
                print -- "// \"full\" title=\"Full plot\" $s"
                print -- "$STRDAT   x   y    \" \"    lines"
                [ -s "$TRNDAT" ] && [ ! $STRDAT -nt $TRNDAT ] && print -- "$TRNDAT   x   y    \" \"    lines"
                [ -s "$FRNDAT" ] && [ ! $STRDAT -nt $FRNDAT ] && print -- "$FRNDAT   x   y    \" \"    lines"
                [ -s "$CURDAT" ] && [ ! $STRDAT -nt $CURDAT ] && {
                  print -- "$CURDAT   x   y    \" \"    lines"
                  print -- "$CURDAT   xc  yc   \" \"    points"
                }
              ) > $TRIPLT.cms
              plot_set $TRIPLT.cms
              [ -s "$TRIPLT.ps" ] && {
                $GV $TRIPLT.ps &
                q=t
              } || {
                print -u2 -- "No $TRIPLT.ps file to plot"
                q=q
              }
              true
            } || {
              print -u2 -- "The plots were created after the last call to tria - no reason to do it again."
              print -u2 -- "Check the files $STRDAT and $TRIPLT.ps"
              q=t
            }; unset e; break;;
      (  v  )                                               # view graphical output of TRIA:
            [ -r "$triaeps" ] && {
              $GV $triaeps &
              q=q
              true
            } || {
              print -u2 -- "No $triaeps file found - run TRIA first"
              q=t
            }; break;;
      (  V  )                                               # view graphical output of TRIA:
            [ -r "$trigeps" ] && {
              $GV $trigeps &
              true
              q=q
            } || {
              print -u2 -- "No $trigeps file found - run TRIAGEOM first or use \"v\" to see the TRIA output"
              q=v
            }; break;;
      ( l|L )                                               # list:
            e=
            for n in $extra; do {
              while [ "$LEN" -gt ${#n} ]; do n="0$n"; done
              e="$e $n"
            }; done
            excom=`comma_separate ${e# }`
            tricom=`comma_separate $TRIAEXT`
            L="${excom:=*}"
            listi=`ls $TRIADIR/$TRIASTEM.$L.$tricom | sed -e '1,$s,^.*/,,' -e '1,$s/\./ /g' | awk '{print $3}' | sort -u`
            listo=
            for n in $listi; do {
              check_files $TRIADIR/$TRIASTEM.$n.$tricom && l=${n}_ || l=${n}\*
              listo="$listo $l"
            }; done
            m=8
            w=
            [ -z "$COLUMNS" ] && c=8 || { ((c=($COLUMNS-$m)/($LEN+4))); [ "$c" -lt 1 ] && c=1; w="-w $COLUMNS"; }
            for n in $listo; do echo "$n" | tr _ \ ; done | pr -T $w --columns=$c -o $m
            q=q
            break;;
      ( r|R )                                               # remove:
            [ -z "$extra" ] && {
              print -u2 -- "Input the mesh number(s) to be removed (space separated)"
              read extra
              [ X$extra = X ] && break
            }
            e=
            for n in $extra; do {
              while [ $LEN -gt ${#n} ]; do n="0$n"; done
              e="$e $n"
            }; done
            excom=`comma_separate ${e# }`
            tricom=`comma_separate $TRIAEXT`
            [ -z "$CNVTRIOUT" ] && { 
              CNVTRIOUT=$SOLPSTOP/modules/DivGeo/device/$DEVICE
            }
            [ -d $CNVTRIOUT/templates ] && CNVTRIOUT=$CNVTRIOUT/templates
            tmplcom=
            [ -d $CNVTRIOUT ] && tmplcom=$CNVTRIOUT/template.[ag]$excom.tria
            ls -l $TRIADIR/$TRIASTEM.$excom.$tricom $tmplcom
            print -n -u2 -- "Are you sure you want to remove all these files? (y/n): "
            while true; do {
              read u
              { case $u in
                ( y|Y ) rm -f $TRIADIR/$TRIASTEM.$excom.$tricom $tmplcom
                        break;;
                ( n|N ) q=q; break 2;;
                (  *  ) print -u2 -n -- "Please answer with either y or n: ";;
              esac; }
            }; done
            q=l
            break;;
      ( m|M )                                               # remap using b2yt:
            print -u2 -- "Option is not realised yet. Please produce the $b2agout file separately"; break
            ####
            break;;
      ( a|A  )                                               # Trap for tria:
            l=
            print -u2 -- "Enter the number of steps to be made in tria (integer to set or ENTER to remove) : \c"
            read l
            [ -z "$l" ] && {
              rm -f $TRIPLT.dbg && print -u2 -- "     trap is removed"
            } || { 
              echo $l > $TRIPLT.dbg && print -u2 -- "     trap is set at step $l"
            }
            q=t
            break;;
      ( i|I )                                               # inquire:
            check_files $triglnklist && q=q || {
              print -u2 -- "Not all output files, $triglnklist, are produced"
              print -u2 -- "Probably, some of the previous steps forgotten?"
              q=g
              break
            }
            while { print -u2 -- "Enter the coordinates of the reference point [mm] or the cell number to investigate (<Return> to end)"; read u; [ -n "$u" ]; }; do {
              echo "$u" | $TRIAINQ
            }; done
            q=i
            break;;
      ( q|Q )                                               # quit:
            break 2;;
      (  *  )
            echo 'Illegal response.'
            echo 'Please use letters capitalized in the list or press ENTER for default'
            q=h
            continue;;
     esac; }
  }; done
}; done
stty sane

