#! /bin/tcsh -f

if ("X-nX" == "X${1}X") then
  touch .status.history
  [ -e .status ] && cat .status >> .status.history
  echo '####' >> .status.history
  cp /dev/null .status
  shift
endif

echo $argv >! .current_status
cat .current_status >>! .status

if ($?SOLPS_GUI_IP && $?SOLPS_GUI_PORT) then
  set cmd = "echo ${USER} ${PWD} ${argv}"
  set cmd = "${cmd} > /dev/udp/${SOLPS_GUI_IP}/${SOLPS_GUI_PORT}"
  bash --norc --noprofile -c "${cmd}"
endif
