#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg | cut -d ' ' -f 1`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG=4
@ NREGP = $NREG + 1
if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif
setenv PLOT_FROM_FILE "gnuplot.temp"
pipe_run.log | \
  egrep -a '^b2vis' | \
  awk '/b2vis/{for (i=2;i<=NF;i++) printf "%s ",$i;printf "\n"}' | \
  nl >! ${tmpdir}PLOT_FROM_FILE
  plot x"$1"yplot$NREGP `count 0 $NREG` iter "Viscous heating (W)" $PWD
