#! /bin/csh -f
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
set vreg=$nnreg[2]
set freg=$nnreg[3]
if ("" == $vreg) set vreg=4
if ("" == $freg) set freg=13
@ vregP = $vreg + 1
if($?GNUPLOT_TMP) then
    set tmpdir="$GNUPLOT_TMP/"
else
    set tmpdir=""
endif
setenv PLOT_FROM_FILE "gnuplot.temp"
pipe_run.log | \
  egrep -a nereg\|ne2reg\|tallies | \
  awk '/nereg/{for (i=2;i<=NF;i++)ne[i]=$i}\
       /ne2reg/{for (i=2;i<=NF;i++) printf "%s ",$i/ne[i];printf "\n"}'| \
  nl >! ${tmpdir}PLOT_FROM_FILE
  plot x"$1"yplot$vregP `count 0 $vreg` iter "ave zeff" $PWD
