'${HOST} ${PWD} `date` T=${TIME}' extl glob
a4p 2 2 page
comp
feex sumy 19 f.x drop feex 1 nreg 2 nreg m+ m* sumy 19 f.x drop
feey sumx 57 f.y drop feey 1 nreg 2 nreg m+ m* sumx 57 f.y drop
feix sumy 19 f.x drop feix 1 nreg 2 nreg m+ m* sumy 19 f.x drop
feiy sumx 57 f.y drop feiy 1 nreg 2 nreg m+ m* sumx 57 f.y drop
fnix sumy 19 f.x drop fnix 1 nreg 2 nreg m+ m* sumy 19 f.x drop
fniy sumx 57 f.y drop fniy 1 nreg 2 nreg m+ m* sumx 57 f.y drop
phys
fniy 0.0 fmin 0.0 fmax 57 f.y drop
ni 0.0 fmin 0.0 fmax 57 f.y drop
feey 0.0 fmin 0.0 fmax 57 f.y drop
te 0.0 fmin 0.0 fmax 57 f.y drop
feiy 0.0 fmin 0.0 fmax 57 f.y drop
ti 0.0 fmin 0.0 fmax 57 f.y drop
