'${HOST} ${PWD} `date` T=${TIME}' extl glob
a4p 2 2 page
comp
fhex sumy 19 f.x drop fhex 1 nreg 2 nreg m+ m* sumy 19 f.x drop
fhey sumx 57 f.y drop fhey 1 nreg 2 nreg m+ m* sumx 57 f.y drop
fhix sumy 19 f.x drop fhix 1 nreg 2 nreg m+ m* sumy 19 f.x drop
fhiy sumx 57 f.y drop fhiy 1 nreg 2 nreg m+ m* sumx 57 f.y drop
fnax sumy 19 f.x drop fnax 1 nreg 2 nreg m+ m* sumy 19 f.x drop
fnay sumx 57 f.y drop fnay 1 nreg 2 nreg m+ m* sumx 57 f.y drop
phys
fnay 0.0 fmin 0.0 fmax 57 f.y drop
na 0.0 fmin 0.0 fmax 57 f.y drop
fhey 0.0 fmin 0.0 fmax 57 f.y drop
te 0.0 fmin 0.0 fmax 57 f.y drop
fhiy 0.0 fmin 0.0 fmax 57 f.y drop
ti 0.0 fmin 0.0 fmax 57 f.y drop
